### ISSUE TITLE
Object return null if row not exist

### ISSUE THREAD

**Issue by thiagofernando** [sequelize/sequelize#6600] opened 2016-09-15 13:33 UTC
## What you are doing?
If the line does not exist, the return generated object is null, even if there is data in the general assembly.

```js
return ProgramaModel.findAll(
            {
                where: {
                    'tipo_id': tipoPrograma
                },
                attributes: [],
                 include: [{
                     model: ProjetoModel, as : 'projetos',
                     attributes: ['id'],
                     include: [{
                         model: EAPModel,
                         attributes: ['id'],
                         include: [{
                             model: TarefaEAPModel,
                             attributes: ['tarefa_id'],
                             where: {'tarefa_id' : {$in : [1082, 2437, 4179, 7312]} },
                             include: [
                                 {
                                     model: TarefaProjetoModel,
                                     attributes : [
                                         [sequelize.fn('SUM', sequelize.fn('IF', sequelize.literal(' `projetos.EAP.TarefaEAPs.TarefaProjeto`.`DT_FIM_TRF_PROJ` IS NULL'), 0, 1)), 'quantidadeConclusao'] ,
                                         [sequelize.fn('SUM', sequelize.fn('IF', sequelize.literal(' `projetos.EAP.TarefaEAPs.TarefaProjeto`.`DT_INC_TRF_PROJ` IS NULL'), 0, 1)), 'quantidadeInicio'],
                                         [sequelize.fn('COUNT', '*'),  'total']
                                     ],
                                     where: {$and: [['`projetos`.`CD_PROJ` = `projetos.EAP.TarefaEAPs.TarefaProjeto`.`CD_PROJ`']]
                                    },
                                    required: false
                                 },
                                {
                                    model: TarefaModel, as: 'tarefa',
                                    attributes: ['nome']
                                }
                            ]
                         }]
                    }]
                 }],
                group: ['projetos.EAP.TarefaEAPs.CD_TRF'],
                order: ['projetos.EAP.TarefaEAPs.SEQ_TRF_EAP']
            });
```
id |projetos.id |projetos.EAP.id |projetos.EAP.TarefaEAPs.id |projetos.EAP.TarefaEAPs.tarefa_id |projetos.EAP.TarefaEAPs.TarefaProjeto.id |projetos.EAP.TarefaEAPs.TarefaProjeto.quantidadeConclusao |projetos.EAP.TarefaEAPs.TarefaProjeto.quantidadeInicio |projetos.EAP.TarefaEAPs.TarefaProjeto.total |projetos.EAP.TarefaEAPs.tarefa.id |projetos.EAP.TarefaEAPs.tarefa.nome |
---|------------|----------------|---------------------------|----------------------------------|-----------------------------------------|----------------------------------------------------------|-------------------------------------------------------|--------------------------------------------|----------------------------------|------------------------------------|
39 |18602       |168             |79831                      |2437                              |                                         |343                                                       |644                                                    |10030                                       |2437                              |Estudo Preliminar                   |
39 |18602       |168             |79846                      |4179                              |1574188                                  |938                                                       |1062                                                   |10030                                       |4179                              |Projeto Executivo                   |
39 |18602       |168             |79848                      |1082                              |                                         |3755                                                      |6669                                                   |20060                                       |1082                              |OBRA                                |
39 |18602       |168             |79856                      |7312                              |                                         |381                                                       |1113                                                   |10030                                       |7312                              |Entrega da Obra                     |

## What do you expect to happen?

Columns projetos.EAP.TarefaEAPs.TarefaProjeto.quantidadeConclusao,  	projetos.EAP.TarefaEAPs.TarefaProjeto.quantidadeInicio and 	projetos.EAP.TarefaEAPs.TarefaProjeto.total must be returned

## What is actually happening?
This is the actual return (TarefaProjeto: null)
```
projetos [{
    projetos: [[{
        id: 18602,
        EAP: {
            id: 168,
            TarefaEAPs: [[{
                tarefa_id: 2437,
                TarefaProjeto: null,
                tarefa: {nome: 'Estudo Preliminar'}
            }], [tarefa_id
:
4179,
    TarefaProjeto
:
{
    quantidadeConclusao: 938,
        quantidadeInicio
:
    1062,
        total
:
    10030
}
,
tarefa: {
    nome: 'Projeto Executivo'
}
}],
[{
    tarefa_id: 1082,
    TarefaProjeto: null,
    tarefa: {nome: 'OBRA'}
}], [{
    tarefa_id: 7312,
    TarefaProjeto: null,
    tarefa: {nome: 'Entrega da Obra'}
}]
] } }] ] } ]
```

__Dialect:__ mysql 
__Database version:__ 5.6
__Sequelize version:__ 3.23.4

**Comment by janmeier** [comment] 2016-09-15 13:42
Are you sure this is the smallest possible example :)? Also, its really hard to reason about an example in spanish (at least for me).

Please provide a complete [SSCCE](HTTP://SSCCE.ORG/), with model definiotions and associations

**Comment by felixfbecker** [comment] 2016-09-15 13:55
It is expected behavior that `null` is returned if the row of the model you queried does not exist. It is possible to attach additional data to the instance, but to _only_ get additional columns totally independent from an instance doesn't make sense if you call the method on the model. That's what raw queries are for imo

**Comment by thiagofernando** [comment] 2016-09-22 12:13
The problem is that : basically when I realize a count with a left join to a record that would not exist in the table that you are getting the count for the consultation, should receive the count back, but as the record of this table is null, the count it is not returned.

**Comment by janmeier** [comment] 2016-10-27 13:34
Still not sure what the issue is, and no [SSCCE](HTTP://SSCCE.ORG/) provided, closing

**Closed by janmeier** 2016-10-27 13:34 UTC
