### ISSUE TITLE
defaultScope breaks association fetching

### ISSUE THREAD

**Issue by parkroolucas** [sequelize/sequelize#9736] opened 2018-07-29 08:06 UTC
## What are you doing?

```js
const Questions = sequelize.define(
  "question",
  {
    id: {
      allowNull: false,
      autoIncrement: true,
      primaryKey: true,
      type: DataTypes.INTEGER.UNSIGNED
    },
    submittedAt: {
      allowNull: true,
      type: DataTypes.DATE
    }
  },
  {
    defaultScope: {
      attributes: { exclude: ["deletedAt"] }
    }
  }
);

Questions.associate = models => {
  Questions.belongsTo(models.Exam); // examId
  Questions.belongsTo(models.User, { as: "createdBy" }); // createdById
}
```

## What do you expect to happen?
I expect `Questions.findOne` to return a model that includes the `examId` and `createdById` values; however, these are both `undefined`, and the query itself does not include the selection of `examId` nor `createdById`.

I've taken a look into the Sequelize source, and I've isolated the issue (I think). If I take the source code above and remove the `defaultScope` from `options`, i.e. this section of code:

```js
defaultScope: {
  attributes: { exclude: ["deletedAt"] }
}
```

This is because of this section of code inside of the `static init` method in the `Model` class:

```js
if (_.isPlainObject(this._scope)) {
  this._conformOptions(this._scope, this);
}
```

The above bit of code does not run if `defaultScope` is set.

Then I am able to access the values of `examId` and `createdById`, which seems like weird behavior to me.

I'm using Sequelize v4.19.0.

**Comment by sushantdhiman** [comment] 2018-07-30 15:23
Looks like a version of https://github.com/sequelize/sequelize/issues/6245, This PR https://github.com/sequelize/sequelize/pull/9735 should fix this issue. It will be merged soon and available in next `v5-beta`

Closing as duplicate of https://github.com/sequelize/sequelize/issues/6245 , Please follow the issue template next time

**Closed by sushantdhiman** 2018-07-30 15:23 UTC
