### ISSUE TITLE
Cannot create table with `enum` field when using explicit schema.

### ISSUE THREAD

**Issue by realyze** [sequelize/sequelize#3605] opened 2015-04-27 01:20 UTC
Here's my (simplified) table schema:

```javascript
const Participation = sequelize.define('Participation', {
    lastUpdated: {
      type: DataTypes.DATE,
      defaultValue: DataTypes.NOW,
      allowNull: false
    },
    status: {
      type: DataTypes.ENUM('invited', 'started', 'completed'),
      allowNull: false
    }
  }, {
    underscored: true,

    timestamps: true,
    updatedAt: false,
    createdAt: 'created',

    freezeTableName: true,
    tableName: 'participation',
    schema: 'ah_api'
}}
```

When I (force) sync it, it throws:
```
SequelizeDatabaseError : no schema has been selected to create in SequelizeDatabaseError: no schema has been selected to create in
    at [object Object].module.exports.Query.formatError (/Users/realyze/code/pureprofile/warp/deployment/apps/account-holder-api/node_modules/hapi-sequelized/node_modules/sequelize/lib/dialects/postgres/query.js:421:16)
    at [object Object].<anonymous> (/Users/realyze/code/pureprofile/warp/deployment/apps/account-holder-api/node_modules/hapi-sequelized/node_modules/sequelize/lib/dialects/postgres/query.js:108:21)
    at [object Object].emit (events.js:107:17)
    at [object Object].Query.handleError (/Users/realyze/code/pureprofile/warp/deployment/apps/account-holder-api/node_modules/pg/lib/query.js:99:8)
    at [object Object].<anonymous> (/Users/realyze/code/pureprofile/warp/deployment/apps/account-holder-api/node_modules/pg/lib/client.js:166:26)
    at [object Object].emit (events.js:107:17)
    at Socket.<anonymous> (/Users/realyze/code/pureprofile/warp/deployment/apps/account-holder-api/node_modules/pg/lib/connection.js:109:12)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:529:20)
```

The raw SQL that fails is: 
```SQL
CREATE TYPE "enum_ah_api_ah_api.participation_status" AS ENUM('invited', 'started', 'completed');
```

**Comment by vascofg** [comment] 2015-05-02 14:39
+1

**Comment by skarbovskiy** [comment] 2015-06-16 10:06
+1

**Comment by janmeier** [comment] 2015-06-28 14:54
Closing as duplicate of https://github.com/sequelize/sequelize/issues/3171

**Closed by janmeier** 2015-06-28 14:54 UTC
Labels: bug, postgres
