### ISSUE TITLE
postgres .save() not able to detect change in JSON fields

### ISSUE THREAD

**Issue by calvintwr** [sequelize/sequelize#2862] opened 2015-01-08 13:01 UTC
When changing the dao, suppose the dao has a json field called "data":
    
    return dao.data // {"a": "b"}

After adding attributes to the dao:

    dao.data.c = "d";
    return dao.data // {"a": "b", "c": "d"}

Calling .save() on the dao will not save the new "c" attribute.

Looking into:
https://github.com/sequelize/sequelize/blob/master/lib/instance.js#L377

    Instance.prototype.changed = function(key) {
        if (key) {
            if (this.Model._isDateAttribute(key) && this._previousDataValues[key] && this.dataValues[key]) {
                return this._previousDataValues[key].valueOf() !== this.dataValues[key].valueOf();
            }
            return this._previousDataValues[key] !== this.dataValues[key];  // <-- this returns false because the internals of the json isn't compared.
        }
        var changed = Object.keys(this.dataValues).filter(function(key) {
            return this.changed(key);
        }.bind(this));

        return changed.length ? changed : false;
    };

Nonetheless, one possible way is to compare the JSONs:

    _isJSONAttribute = function(key) {
      return typeof key === "object";
    }

    Instance.prototype.changed = function(key) {
        if (key) {
            if (this.Model._isDateAttribute(key) && this._previousDataValues[key] && this.dataValues[key]) {
                return this._previousDataValues[key].valueOf() !== this.dataValues[key].valueOf();
            }
            //stringify and compare
            if (this.Model._isJSONAttribute(key) && this._previousDataValues[key] && this.dataValues[key]) {
                return JSON.stringify(this._previousDataValues[key]) !== JSON.stringify(this.dataValues[key]);
            }
            return this._previousDataValues[key] !== this.dataValues[key];
        }
        var changed = Object.keys(this.dataValues).filter(function(key) {
            return this.changed(key);
        }.bind(this));

        return changed.length ? changed : false;
    };

**Comment by mickhansen** [comment] 2015-01-08 13:04
https://github.com/sequelize/sequelize/blob/master/lib/model.js#L341

PR welcome @calvintwr :)

**Comment by janmeier** [comment] 2015-01-08 14:52
I would use `isEqual` to do a deep comparison of the two objects, but other than that looks good https://lodash.com/docs#isEqual

**Comment by mickhansen** [comment] 2015-01-08 14:57
@janmeier i actually asked @calvintwr to do some benchmarks on what is faster.

**Comment by mickhansen** [comment] 2015-01-08 14:58
But given lodash's reputation they might be the fastest :)

**Comment by mickhansen** [comment] 2015-01-08 15:39
#2863

**Comment by YouriT** [comment] 2015-01-09 10:48
In the end, for now until the PR is released, the only way is to create a new object and just set it to the object ?

**Comment by mickhansen** [comment] 2015-01-09 10:58
@YouriT or use `fields: instance.changed().concat['jsonField']`

**Comment by calvintwr** [comment] 2015-01-10 15:28
@mickhansen @janmeier 
1)http://jsperf.com/comparing-j/3

Lodash performs slightly slower than the function that I consolidated. I haven't really examined the internals of #isEqual to see how we can optimise it for our use case. Nonetheless we should keep in mind that performance varies depending on the type of JSON we compare. It will be difficult to accurately gauge performance because it is not possible to reflect JSON changes in real life. The tests is more of a reference to feel the kind of overheads we are faced with.

2) There can be a valid assumption that most .save() calls does not involve changes to any JSON objects. Hence, this is where the deep compares performs the slowest because every branch in the JSON is scanned (as opposed to where there are changes, especially to the outer branches, where comparison can be "returned" early). Also, under this assumption, overheads for cloning the JSON largely wasted.

3) I propose we do something like:

    dao.data.newBranch = "new data";

    dao.save({
        haveChangedJSON: [ "data"]
    }); // at the save call, we pass in an array of fields that are JSONs and have been changed. This way, we don't clone nor compare.

4) The clone and deep compare is not difficult to add. Should we provide and option to toggle it on, where everything will be magic, or off, where we will need to use the method i mentioned in (3).

**Comment by mickhansen** [comment] 2015-01-10 15:40
@calvintwr 3) can already be solved by me previous comment.

We do need a real solution for this, and i think it's changed to checks on set and requiring people to do `set('data.newBranch')`, and if they don't want to do that they can use `fields: (instance.changed() || []).concat(['jsonField'])`

**Comment by calvintwr** [comment] 2015-01-10 16:14
@mickhansen

Correct me if i understand you wrongly.

Are you suggesting this:

    dao.data.newBranch = "new data"; // standard js append attribute
    dao.set('data.newBranch'); // triggering a "changed" state on data.newBranch
    dao.save(); // when looking into the JSON field "data", it will know that "data.newBranch" needs to be inserted/persisted to the database.

Or you are actually proposing:

    dao.set('data.newBranch', 'new data');

Which I wouldn't prefer like how you mentioned we should keep data access and setting the way JSON is meant for.

And in the first case, really why not pass the JSON fields like i mentioned:

    dao.save({
        haveChangedJSON: ["data"]
    });

Cause regardless changes were made to `data.newBranch` or `data.oldBranch.newBranch`, the whole chunk of `data` JSON gets saved into the db anyway right?

Or unless JSONB + plv8 in future will allow changes to single/nested key values and therefore we should prepare for it?

**Comment by mickhansen** [comment] 2015-01-10 16:21
I'm proposing `dao.set('data.newBranch', 'new data');`. It's that or deep equal checks in changed.

In any case `dao.save({haveChangedJSON: ["data"]});` is a no-need since `fields: (instance.changed() || []).concat(['jsonField'])`

I'm not certain about atomic updates in JSONB structures, you might need a postgres function for it (don't think there's an operator)

**Comment by calvintwr** [comment] 2015-01-10 16:26
The case for `dao.save({haveChangedJSON: ["jsonField1", "jsonField2"]})` is because `fields: (instance.changed() || []).concat(['jsonField'])` is not really idiomatic.

If we already have `fields: (instance.changed() || []).concat(['jsonField'])` we don't need `.set`.

deep equal checks are expensive IMO, and the reasons are as mentioned before. but nonetheless, I don't think it's difficult to add. Just a matter of whether we want it to default `ON` or `OFF`.

**Comment by mickhansen** [comment] 2015-01-10 16:30
We need `set` if we want an out of the box sane and atomic solution, which we do :)
`haveChangedJSON` just seems so ugly to me.

But a solution could also a be a mix of the `changed()` on `set` rewrite, the `set` to take nested change, and then allow users to do something like `changed(field, true)` aswell if they want to manipulate the JSON data the "normal" way.

**Comment by BridgeAR** [comment] 2015-04-27 18:47
This should be fixed in version 2.1 130cd9a00f2b1c3d7b3a093532e5eb5335e31a23
Ping @mickhansen

**Closed** 2015-04-28 06:24 UTC
Labels: bug

**Comment by calvintwr** [comment] 2015-04-29 05:49
Whats the way to amend JSON fields?

Looking through the code I believe this works:

    instance.setDataValue('json_field', { foo: 'bar' });

But i'm not entirely sure how you would set a nested field. Currently I'm doing this:

    instance.json_field.foo = 'barbar';
    instance.changed('json_field', true);

@BridgeAR @mickhansen

**Comment by mickhansen** [comment] 2015-04-29 07:54
@calvintwr Use `instance.set('nested.key.thingie', value);` or change it directly and call `changed(field, true)` as you suggest.

**Comment by calvintwr** [comment] 2015-04-29 10:34
@mickhansen roger that thanks!

**Comment by alexturek** [comment] 2015-06-03 20:31
@mickhansen This seems to be an issue again, and I can't find an open issue referencing it. I'm fine creating a new one if you want.

What I'm seeing is that, on hash `cc8687539fe96f7f64887a04ddf5d48f159f5e92`, version `3.1.1': '2015-05-26T11:34:46.172Z` (from `npm show sequelize`) I have to call
```
this.jsonField.pop()
this.changed('jsonField', true);
```

Or is this intended behavior?

**Comment by calvintwr** [comment] 2015-06-04 01:53
Sequelize detects changes by making a copy of the data and stores it as `_previousDataValues`. Arrays and JSON objects are not cloned when doing it. So there is no way of "diffing" it with the original values to find changes.

What you mentioned is one of the methods. Which is to explicitly mark a field to have changed.

The other way is to do `instance.set('JSONField', 'someValue')

It depends on what you like. I generally find it more convenient to just use normal assignment `instance.JSONField.someData = myData`, then mark it as changed `instance.changed('JSONField').

Or you can also use `instance.save({fields:['JSONField']})`. This would however require you to explicitly name all other fields that you have changed as it skips the "diffing" mechanism.

**Comment by alexturek** [comment] 2015-06-04 04:22
Ok thanks for the explanation. I just wasn't sure if that was intended
behavior given this and the other related issues.

Thanks for maintaining this library, it's awesome!

**Comment by calvintwr** [comment] 2015-06-04 04:47
Yea I think it's the intended behavior unless @mickhansen have adopted deep cloning and deep comparison. Which even if there is I wouldn't use cause it's too resource intensive.

No worries. I'm not a maintainer lol. But yea they are awesome.

**Comment by mickhansen** [comment] 2015-06-04 07:41
We refactored to set `changed` on `set`, so either you use `set()` to set the JSON value or you manipulate directly and use `.changed(field)`

**Comment by alexturek** [comment] 2015-06-04 16:40
@mickhansen Got it. Just curious, do you personally use `.set()` everywhere, or just for JSON fields, or do you use `.changed` ?

**Comment by mickhansen** [comment] 2015-06-05 09:26
@alexturek Well i generally use `update()` for pure crud stuff, but that uses `set` internally. I haven't done much with JSON yet but the stuff i have done has been acheived with `set` using a nested key.

**Comment by twler** [comment] 2015-06-23 18:33
I'm on 3.0 and still experiencing this issue.

    # instance.myfield is originally { foo: 'bar' }
    instance.myfield = {}
    instance.set('myfield', {})
    instance.changed('myfield')
    instance.save()
    # instance.myfield is still { foo: 'bar' }

**Comment by calvintwr** [comment] 2015-06-28 05:49
@mickhansen reading through this:

https://github.com/sequelize/sequelize/blob/master/lib/instance.js#L249

I don't think `.set()` is refactored to set `.changed()` on JSON fields.

I have experimented with it and the same problem exists. Using 3.3.2.

**Comment by mickhansen** [comment] 2015-06-28 08:00
@calvintwr Hmm no the code might not account for someone reusing the object.

```
var obj = instance.get('obj');
obj.prop = val;
instance.set('obj', obj);
```

Will likely not trigger changed no.

**Comment by calvintwr** [comment] 2015-06-28 09:08
@mickhansen may not be. Cause it did something like this:

    req.user.set('dataMeta.profileChangeLimits.' + field, changeLimits - 1);

The field is `dataMeta`, which is a JSON field. `changeLimits` and `field` are just `number` and `string` types.

**Comment by janmeier** [comment] 2015-06-28 10:27
@mickhansen I dont remember the reasoning for not just using _.isEqual to check equality :)? It should work for both simple and complex objects

**Comment by calvintwr** [comment] 2015-06-28 11:20
It's probably because to use _.isEqual, you need to first deep clone the JSON. It's going to take a hit on performance and really not worth the cost-benefit.

I'm very happy using .changed().

**Comment by mickhansen** [comment] 2015-07-01 07:03
@janmeier Pretty expensive.

`req.user.set('dataMeta.profileChangeLimits.' + field, changeLimits - 1);` should work.

**Comment by curiousdannii** [comment] 2015-07-24 02:07
Can I request this be documented somewhere in addition to Instance.set()? I don't normally use .set() and even if I did I wouldn't have thought to look there for an explanation of how to set JSON properties.

**Comment by janmeier** [comment] 2015-07-24 07:47
@curiousdannii Documentation PRs are very welcome :)

**Comment by GregorioF2** [comment] 2018-10-30 14:54
@calvintwr You are like a god to me now. Thanks a lot!
