### ISSUE TITLE
TimeoutError: unknown timed out - Not recovering

### ISSUE THREAD

**Issue by Niffy** [sequelize/sequelize#10013] opened 2018-10-10 13:43 UTC
## What are you doing?
A worker is consuming messages from a queue and inserting them into the database. But when the DB is unavailable it is not reconnecting when it is available. Instead a server restart is required. 
The following code running locally against a postgres instance which I stop and start, produces an "TimeoutError: unknown timed out" and does not recover, indicating sequelize is not recovering at all when these errors occur.

```js
// "pg@7.5.0"
// "pg-hstore@2.3.2"
// "sequelize@4.39.0"

const Sequelize = require('sequelize')
const config = {
  logging: console.log,
  username: 'user',
  password: undefined,
  host: 'localhost',
  port: 5433,
  database: 'test_db',
  dialect: 'postgres',
  replication: {
    read: {
      username: 'user',
      password: undefined,
      host: 'localhost',
      port: 5433,
      database: 'test_db'
    },
    write: {
      username: 'user',
      password: undefined,
      host: 'localhost',
      port: 5433,
      database: 'test_db'
    }
  },
  retry: {
    match: [
      /SequelizeConnectionError/,
      /SequelizeConnectionRefusedError/,
      /SequelizeHostNotFoundError/,
      /SequelizeHostNotReachableError/,
      /SequelizeInvalidConnectionError/,
      /SequelizeConnectionTimedOutError/,
      /TimeoutError/
    ],
    max: 10,
    timeout: 10000,
    retry: 100
  }
}

const sequelize = new Sequelize(config)
const user = sequelize.define('test', {someField: Sequelize.STRING})

function createUser(cb) {
  return new Promise((resolve, reject) => {
    user.create({someField: 'aa'})
    .then(() => { 
      setTimeout(resolve, 2000)
    })
    .catch((err) => {console.error('err', err); resolve()})
  })
}

async function loop () {
  while(true) {
    await createUser()
  }
}

sequelize.authenticate()
.then( () => {
  sequelize.sync({force: false})
  loop()
  console.log(`PostgreSQL: Connected to main database`)
})
.catch((err) => {
  console.error('PostgreSQL: Error connecting', err)
})
```

## What do you expect to happen?
When the DB is not available it should attempt to reconnect when certain errors occur, such "TimeoutError: ResourceRequest timed out" or "TimeoutError: unknown timed out"

## What is actually happening?
When the following errors is hit, no reconnecting occurs, a server restart is required.

```js
TimeoutError: unknown timed out
    at Function.SubError [as TimeoutError] (/Users/paulrobinson/workspace/akero/modules/akero-tracking-sql-models/node_modules/bluebird/js/release/errors.js:10:49)
    at Timeout._onTimeout (/Users/paulrobinson/workspace/akero/modules/akero-tracking-sql-models/node_modules/retry-as-promised/index.js:35:24)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)

{ TimeoutError: ResourceRequest timed out
at ResourceRequest._fireTimeout (/var/app/current/node_modules/generic-pool/lib/ResourceRequest.js:62:17)
at Timeout.bound [as _onTimeout] (/var/app/current/node_modules/generic-pool/lib/ResourceRequest.js:8:15)
at ontimeout (timers.js:488:11)
at tryOnTimeout (timers.js:323:5)
at Timer.listOnTimeout (timers.js:283:5) name: 'TimeoutError' }
```
__Dialect:__ postgres
__Database version:__ 9.6
__Sequelize version:__ 4.39.0
__Tested with latest release:__ Yes

This is quite annoying, I wish it would just try and recover, or at least have the option of failover to another host for writing. It's even more annoying I can only have one host to write to, but I can read from many.  This is causing us issues in production.

**Comment by sushantdhiman** [comment] 2018-10-11 04:44
Increase `pool.acquire` timeout which is only `10 sec` by default

**Comment by sushantdhiman** [comment] 2018-10-11 04:45
Duplicate of https://github.com/sequelize/sequelize/issues/9541

**Closed by sushantdhiman** 2018-10-11 04:45 UTC
