### ISSUE TITLE
bulkCreate can't do "upsert" logic with postgres, even though normal "upsert" is supported by postgres?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [sequelize/sequelize#4324] opened 2015-08-14 02:14 UTC
How come bulkCreate can't use "upsert" logic with postgres? The normal "upsert" command supports Postgres.

**Comment by janmeier** [comment] 2015-08-14 06:49
Do you mean upsert as in `ON DUPLICATE KEY UPDATE `? That feature only exists in postgres 9.5, which isn't officially released yet. 

Right now single row upsert is handled using a function which catches the unique constraint error. It's not pretty :-). We're definitely going to switch to the new syntax once it's released officially, but not before we can test it on Travis

**Comment by GeoffreyPlitt** [comment] 2015-08-14 20:46
Here's what I'm currently doing:

```javascript
// True if the model has a non-autogenerated primary key
const has_actual_primary_key = (model) => {
  const attrs = Object.keys(model.attributes)
  const pk_fields = attrs.filter( (x) => {
    return model.attributes[x].primaryKey && !model.attributes[x]._autoGenerated
  })
  return pk_fields.length>0
}

// Uses true "upsert" if the model has a primary key, otherwise findOrCreate().
const bulk_upsert = (model, rows) => {
  return Promise.all(rows.map( (row) => {
    if(has_actual_primary_key(model)) {
      return model.upsert(row)
    } else {
      return model.findOrCreate({
        where: row,
        defaults: row
      })
    }
  }))
}

module.exports = bulk_upsert
```

**Comment by janmeier** [comment] 2015-08-14 21:08
Yeah, something along those lines is probably your best bet for now

**Comment by janmeier** [comment] 2015-08-17 19:52
Closing, works as intended until postgres 9.5 is out

**Comment by diosney** [comment] 2016-02-29 16:18
It seems that Postgres 9.5.1 is already out, maybe you can reopen the issue now?

**Comment by mickhansen** [comment] 2016-02-29 16:36
@diosney Is it on travis yet?

**Comment by diosney** [comment] 2016-02-29 17:10
It seems that not yet (latest version they have in the docs are 9.4.1) :(

I will leave here the links for future reference:

https://docs.travis-ci.com/user/using-postgresql/
https://github.com/travis-ci/travis-ci/issues/4264

**Comment by prasadbhosale** [comment] 2016-05-02 07:34
Postgres 9.5 is already out . You can reopen this issue now ?

**Comment by janmeier** [comment] 2016-05-02 07:36
but its not yet easily available on travis https://github.com/travis-ci/travis-ci/issues/4264

**Comment by bbnnt** [comment] 2016-08-13 09:04
It is now available; isn't it ?

**Comment by andrewgbliss** [comment] 2016-08-16 22:41
+1

**Comment by charlesdeuter** [comment] 2016-12-22 18:27
+1

**Comment by trjstewart** [comment] 2017-01-16 04:11
+1

**Comment by prasadbhosale** [comment] 2017-01-31 07:18
+1

**Comment by lironess** [comment] 2017-03-16 10:06
+1

**Comment by jtbh89** [comment] 2017-03-28 21:31
+1

**Comment by gmunhoz** [comment] 2017-03-31 01:49
+1

**Comment by illumimari** [comment] 2017-04-14 20:29
+1

**Comment by ayazmaroof** [comment] 2017-05-11 09:09
+1

**Comment by viktorchukhantsev** [comment] 2017-06-28 11:54
+1

**Comment by parthgandhi7** [comment] 2017-07-14 06:13
+1

**Comment by NotAmaan** [comment] 2017-08-05 13:02
I guess stop commenting "+1" and use reactions instead and avoid useless comments? But yeah would be great to have this feature.

**Comment by vinhboy** [comment] 2017-09-01 19:35
Just gonna leave this link here in case anyone wants to know if there is any update on this issue

https://github.com/sequelize/sequelize/pull/6325

**Comment by lironess** [comment] 2017-12-10 20:37
comment for getting out of "stale"

**Comment by jameskennethrobinson** [comment] 2017-12-19 18:21
Would love to see this feature!

**Comment by master-atul** [comment] 2018-02-04 19:16
👍  Need it !

**Comment by petersg83** [comment] 2018-03-07 18:17
Almost 3 years now it is open ?...

**Comment by rahulverma** [comment] 2018-03-16 11:08
I `hacked` the insert query generated and added `ON CONFLICT` at the end. 

```
/**
 * Postgres bulk Upsert
 * Hacked from the insert query generated by Sequelize
 * https://www.postgresql.org/docs/10/static/sql-insert.html
 *
 * @param {string} clientId - client id of the database
 * @param {Sequelize.Model} Model - Model to do bulk upsert on
 * @param {any[]} values - bulk values for model
 * @param {string} constraint - constraint name or primary key to check
 * @param {string[]} fieldsToSet - fields to set on conflict
 *
 */
export function bulkUpsert (clientId: string,
                            Model: Sequelize.Model<any, any>,
                            values: any[],
                            constraint: string,
                            fieldsToSet: string[]) {
  const model: any = Model;

  // Map attributes to fields for serial identification
  const fieldMappedAttributes: any = {};
  for (const attr of keys(model.tableAttributes)) {
    fieldMappedAttributes[model.rawAttributes[attr].field || attr] = model.rawAttributes[attr];
  }

  const instance = getPgInstance(clientId);
  const queryGererator = instance.getQueryInterface().QueryGenerator;
  let bulkQuery = queryGererator.bulkInsertQuery(
    Model.getTableName(),
    values,
    {},
    fieldMappedAttributes,
  );

  bulkQuery = bulkQuery.replace(/;\s*$/, '');

  const sets = fieldsToSet.map(f => ` ${f} = EXCLUDED.${f} `).join(',');
  const bulkUpsertQuery = upsertCompiled({bulkQuery, constraint, sets});
  instance.query(bulkUpsertQuery);
}
```

you probably should be careful with this!

**Comment by flashpointsrl** [comment] 2018-11-17 10:30
> // True if the model has a non-autogenerated primary key const has_actual_primary_key = (model) => 

If the model has an autogenerated primary key is still possible to do something to update the existent items?

thank you

cld

**Comment by EdoardoPaluan** [comment] 2019-01-12 22:14
Any updates on this? Would love to get an affectedRows output on bulkCreate :)

**Comment by imShara** [comment] 2019-01-17 13:03
`ON CONFLICT UPDATE` is supported in postgres long time ago. Why not to support in sequelize?

**Comment by mickhansen** [comment] 2019-01-17 13:07
@imShara The reason, as for most things, is *time*. Maintainers have limited time and no one has taken the time to contribute.

**Comment by lpedromachado** [comment] 2019-04-05 16:40
> Here's what I'm currently doing:
> 
> ```js
> // True if the model has a non-autogenerated primary key
> const has_actual_primary_key = (model) => {
>   const attrs = Object.keys(model.attributes)
>   const pk_fields = attrs.filter( (x) => {
>     return model.attributes[x].primaryKey && !model.attributes[x]._autoGenerated
>   })
>   return pk_fields.length>0
> }
> 
> // Uses true "upsert" if the model has a primary key, otherwise findOrCreate().
> const bulk_upsert = (model, rows) => {
>   return Promise.all(rows.map( (row) => {
>     if(has_actual_primary_key(model)) {
>       return model.upsert(row)
>     } else {
>       return model.findOrCreate({
>         where: row,
>         defaults: row
>       })
>     }
>   }))
> }
> 
> module.exports = bulk_upsert
> ```

If I use an array of `upsert`'s instead of a single `bulkCreate`, I get a
```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```
My table has 113 thousand rows. 

Another problem is that I need to insert/update in bulk because some rows have foreign keys to other rows that are to be inserted but are not in the DB yet. If I use `upsert`, I get a `SequelizeForeignKeyConstraintError`.

I don't know what to do. :(

**Comment by gabrielmsdiniz** [comment] 2019-06-19 19:14
+1

**Comment by sushantdhiman** [comment] 2019-07-27 05:50
Fixed https://github.com/sequelize/sequelize/pull/11163

**Closed by sushantdhiman** 2019-07-27 05:50 UTC
Labels: dialect: postgres, type: feature
