### ISSUE TITLE
Have validator return all ValidationErrorItems at once instead of only one

### ISSUE THREAD

**Issue by pruhstal** [sequelize/sequelize#8236] opened 2017-08-31 16:10 UTC
## What you are doing?
Creating a user that fails more than one validation.

```js
try {
      const user = await User.create({
        email: email,
        username: username.toLowerCase(),
        salt: salt,
        password: hash,
      });

      return req.login(user, err => {
        if (!err) {
          return res.status(200).send(getUserProps(user));
        }

        return res.status(500).send({
          message: 'Auth error',
        });
      });
    } catch (err) {
      let errors = {};
      err.errors.forEach((error) => {
        errors[error.path] = {
          value: error.value,
          errors: [error.message]
        }
      });

      return res.status(500).send({
        errors: errors
      });
    }
```

## What do you expect to happen?
 Instead of having the validator return one ValidationErrorItem error at a time, I'd like an array of all validation errors.

## What is actually happening?
Validator is only returning one ValidationErrorItem error at a time, when in reality, when it's failing more than a single validation.

__Database version:__ postgres
__Sequelize version:__ 4.8.0

**Comment by pruhstal** [comment] 2017-12-06 09:06
Is this at all possible?

**Comment by dantot** [comment] 2018-10-23 18:48
I'm having the same problem, did you solve it?

**Comment by bradhaydon** [comment] 2018-10-28 17:02
I would also like to know if you were able to resolve this

**Comment by sushantdhiman** [comment] 2018-10-29 06:35
Duplicate of https://github.com/sequelize/sequelize/issues/9249

**Closed** 2018-10-29 08:36 UTC
