### ISSUE TITLE
Feature: custom dialect support

### ISSUE THREAD

**Issue by callmehiphop** [sequelize/sequelize#6986] opened 2016-12-14 18:52 UTC
Hello!

I'm looking to use sequelize with a custom dialect that is currently unsupported. I took a look through the code base and I *think* it would be pretty easy to support custom dialects by modifying/creating an option to accept a module and then making the `AbstractDialect` class its own module.

Would you accept a PR to implement this feature? Thanks!

**Comment by felixfbecker** [comment] 2016-12-14 19:10
Duplicate of #6285

**Closed by felixfbecker** 2016-12-14 19:10 UTC

**Comment by callmehiphop** [comment] 2016-12-14 19:11
@felixfbecker Ah, sorry I missed that one!

**Comment by callmehiphop** [comment] 2016-12-14 19:43
So if moving the `AbstractDialect` to a separate module is a concern, could it just be exported? My end goal is to allow a dialect to be configured at runtime.

```js
import { AbstractDialect } from 'sequelize'

class CustomDialect extends AbstractDialect {
 // ..stuff!
}

export default CustomDialect
```

Then in my project something like..

```js
import Sequelize from 'sequelize'
import CustomDialect from 'custom-dialect'

const sequelize = new Sequelize({
 dialect: CustomDialect
});
```

**Comment by felixfbecker** [comment] 2016-12-14 19:55
Why not add the dialect with a PR?

**Comment by callmehiphop** [comment] 2016-12-14 20:02
I think if you let users have control in their own applications, you would be opening up the library to an infinite amount of dialects without adding the burden of support and maintenance.

**Comment by mattbrunetti** [comment] 2017-04-19 12:35
@felixfbecker I believe this to be a subtly distinct issue from #6285. That issue suggests extracting the core/supported dialects from the main package. This issue suggests supporting use of third-party dialects, regardless of where the core/supported dialects reside. 

I personally don't care so much if I can `npm install` this package without the dialects I won't use, but I want to be able to `npm install` this package (exact; not a fork) and a new experimental dialect, particularly DB2. See issue #6263. 

I think it would be easier for people in the community to create share and collaborate on such new dialects if it could be done separately from this repo.

For example, there is a [sails-db2](https://github.com/IbuildingsItaly/sails-db2) which is not an [officially supported sails adapter](http://sailsjs.com/documentation/concepts/extending-sails/adapters/available-adapters) and probably isn't serious and/or mature enough to become officially supported (the core maintainers would probably receive a lot of issues they don't want to deal with), but it's a starting point for those needing something like it.

**Comment by Crusader4Christ** [comment] 2017-08-03 08:06
@felixfbecker Moreover - now I work with sails & sequelize, and I want to extend Sequelize query generator with additional options, so I need to make a class inherited from dialects/mysql/QueryGenerator and force sequelize use it. I hope I can monkeypath sequelize instance now, but provide dialect in config it is better.

**Comment by leafoflegend** [comment] 2019-03-21 12:49
I wanted to bump on this, my company has a proprietary DB with sqllite syntax, and I (we) love Sequelize. It would be great if I had some way to configure sequelize to use a custom dialect, and it doesnt seem like all too much overhead.

**Comment by spearmootz** [comment] 2020-06-16 17:55
bump, i also want to interface with odbc, syntax almost matches that of mysql with minor things, i was able to make a utility to hook up to odbc, but now i am left with the incomatibilities of the the sql syntax of the proprietary tool that i cant deal with without changing the dialect, but i would like to extend it and provide a path to it like the module.


lol, im on V4 because V5 nor V6 support getters and setters typescripts (for example, if i wanted to use moment instead of Date, or if i wanted to treat a certain field as a number but it is in fact stored as a string)
