### ISSUE TITLE
Sequelize sum function always rounding to 4 decimal point

### ISSUE THREAD

**Issue by billyadelphia** [sequelize/sequelize#11752] opened 2019-12-16 03:57 UTC
## Issue Description

like the title. I'm using `DataTypes.DECIMAL(36, 18),` as the dataType

### What was unclear/insufficient/not covered in the documentation

I could find any documentation why sum function always rounding to 4 decimal point.

### Additional context
Add any other context or screenshots about the issue here.

### Is this issue dialect-specific?

- [x] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by billyadelphia** [comment] 2019-12-16 04:51
I have testing using raw query instead of sum function with sequelize model. It return with full value instead of rounded.

```
let query = sequelize.query('select SUM(value) from transactions type = "deposit"');
{ 'SUM(value)': '6870098.867600000001175427' }
```

**Comment by jy95** [comment] 2019-12-21 01:03
It seems to be [documented](https://sequelize.org/v5/class/lib/model.js~Model.html#static-method-aggregate) : 

![image](https://user-images.githubusercontent.com/9306961/71300540-0d188a00-2396-11ea-8f0d-b052ad3d30e1.png)

![image](https://user-images.githubusercontent.com/9306961/71300532-feca6e00-2395-11ea-89d3-9eb755ac2b36.png)

**Comment by billyadelphia** [comment] 2019-12-21 05:03
@jy95 so you mean I have to change dataType from decimal to string for this kind of case ?
Well, I haven't thought about that. I'll try then.

**Comment by papb** [comment] 2020-01-16 18:03
@billyadelphia did you figure it out?

**Comment by Ms1709** [comment] 2020-05-31 03:19
You can use like this 
 [sequelize.fn('ROUND', sequelize.fn('SUM', sequelize.col('col')),2), 'col']
col: is table column name 
2: after decimal how much precision you need

**Comment by kingjerod** [comment] 2021-03-26 22:20
If the column is DataTypes.DECIMAL(36, 18) shouldn't it be returned as a string? The column itself will come back as a string, why wouldn't the sum?

As a work around, you can do this:
```
sum("amount", {where: {id: 1}, dataType: "string"});
```
And it will come back as a string.

**Comment by kingjerod** [comment] 2021-11-20 05:03
Not stale.

**Comment by WikiRik** [comment] 2021-11-22 16:28
Hi @kingjerod
Can you explain to me what the issue is that you want solved?

**Comment by kingjerod** [comment] 2021-11-22 18:15
When you have a column defined as a decimal in Sequelize, it is returned from basic queries as a string (unlimited precision) which is correct. When you use that column with the `SUM` function, it rounds the result to 4 decimal places. 

Ideally Sequelize should see that the column type being summed is a decimal, and not perform any sort of rounding or `parseFloat` on it. It should return the value as a string to maintain precision.

**Comment by WikiRik** [comment] 2021-11-22 18:52
Allowing Sequelize to see the dataType of the column and using that in the SUM would be great and sounds like a valid feature request to me. I think it would be nice if you could make a new feature request for that [here](https://github.com/sequelize/sequelize/issues/new?assignees=&labels=&template=feature_request.md&title=)

Since it's currently documented that the default fallback is a float and that there is a valid workaround I will close this issue.

**Closed by WikiRik** 2021-11-22 18:52 UTC
Labels: existing workaround
