### ISSUE TITLE
Different results on timestamp attributes on loading eagerly

### ISSUE THREAD

**Issue by soletan** [sequelize/sequelize#4259] opened 2015-08-04 22:14 UTC
I'm using sequelize 3.5.1 wih sqlite. When querying a model eagerly implicit timestamps of associated instances differ from implicit timestamp of basically queried model in terms of value type/format.

I've tested behaviour using this script:

```javascript
var db   = require( "sequelize" ),
    path = require( "path" );

var link = new db( "default", null, null, {
	dialect: "sqlite",
	storage: path.join( __dirname, "test.sqlite" )
} );

var A = link.define( "A", {
	id:   {
		type:          db.INTEGER,
		primaryKey:    true,
		autoIncrement: true
	},
	name: {
		type: db.STRING
	}
} );

var B = link.define( "B", {
	id:    {
		type:          db.INTEGER,
		primaryKey:    true,
		autoIncrement: true
	},
	value: {
		type: db.STRING
	}
} );

A.belongsTo( B );
B.hasMany( A );

link.sync()
	.then( function() {
		return A.create( { name: "test" } );
	} )
	.then( function( newA ) {
		return B.create( { value: "5" } )
			.then( function( newB ) {
				newA.setB( newB );
			} );
	} )
	.then( function() {
		return A.findOne( { include: [ B ] } )
	} )
	.then( function( match ) {
		console.dir( match.get( { plain: true } ) );
	} );
```

Running it on command line results in this output:

```
Executing (default): CREATE TABLE IF NOT EXISTS `Bs` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `value` VARCHAR(255), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
Executing (default): PRAGMA INDEX_LIST(`Bs`)
Executing (default): CREATE TABLE IF NOT EXISTS `As` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `name` VARCHAR(255), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `BId` INTEGER REFERENCES `Bs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE);
Executing (default): PRAGMA INDEX_LIST(`As`)
Executing (default): INSERT INTO `As` (`id`,`name`,`updatedAt`,`createdAt`) VALUES (NULL,'test','2015-08-04 22:02:30.149 +00:00','2015-08-04 22:02:30.149 +00:00');
Executing (default): INSERT INTO `Bs` (`id`,`value`,`updatedAt`,`createdAt`) VALUES (NULL,'5','2015-08-04 22:02:30.177 +00:00','2015-08-04 22:02:30.177 +00:00');
Executing (default): SELECT `A`.`id`, `A`.`name`, `A`.`createdAt`, `A`.`updatedAt`, `A`.`BId`, `B`.`id` AS `B.id`, `B`.`value` AS `B.value`, `B`.`createdAt` AS `B.createdAt`, `B`.`updatedAt` AS `B.updatedAt` FROM `As` AS `A` LEFT OUTER JOIN `Bs` AS `B` ON `A`.`BId` = `B`.`id` LIMIT 1;
Executing (default): UPDATE `As` SET `BId`=1,`updatedAt`='2015-08-04 22:02:30.207 +00:00' WHERE `id` = 1
{ id: 1,
  name: 'test',
  createdAt: Wed Aug 05 2015 00:02:30 GMT+0200 (Mitteleuropäische Sommerzeit),
  updatedAt: Wed Aug 05 2015 00:02:30 GMT+0200 (Mitteleuropäische Sommerzeit),
  BId: 1,
  B: 
   { id: 1,
     value: '5',
     createdAt: '2015-08-04 22:02:30.177 +00:00',
     updatedAt: '2015-08-04 22:02:30.177 +00:00' } }
```

Difference is clearly visible on comparing delivered timestamps on createdAt and updatedAt: on basic model values are instances of Date. In associated model they preformatted strings. This is clearly different from what is documented to be expected [here](http://sequelize.readthedocs.org/en/latest/docs/models-usage/#eager-loading).

My actual problem is: trying to parse the latter with `new Date( match.B.createdAt )` results in invalid date. If I want to post-process those information I have to parse those latter timestamps manually. What a mess ...

**Comment by janmeier** [comment] 2015-08-05 18:27
Duplicate of https://github.com/sequelize/sequelize/issues/2644, will be fixed by https://github.com/sequelize/sequelize/pull/4186

**Closed by janmeier** 2015-08-05 18:27 UTC
