### ISSUE TITLE
Column comments

### ISSUE THREAD

**Issue by coolicer** [sequelize/sequelize#3553] opened 2015-04-18 01:37 UTC
as I define a modle, when I can `sync()` in node, a table has generated ,but comments are lost in table's comments field.
```js
var Foo = sequelize.define('Foo', {
 // Comments can be specified for each field for MySQL and PG
 hasComment: { type: Sequelize.INTEGER, comment: "I'm a comment!" },
})
```

**Comment by janmeier** [comment] 2015-04-24 09:10
Hmm, we have https://github.com/sequelize/sequelize/pull/3263 to fix this, but not sure if we actually want to @mickhansen 

As you mention, comments were giving a bit of trouble due to the way we generate attributes (convert to sql -> then create table query) where comments might end up in the wrong place if the attribute also have foreign keys / indexes.

We'd probably want to support column comments, but it would be a lot easier to do after the create table logic is refactored

**Comment by jduckworth** [comment] 2015-08-03 01:07
Just wondering if anyone has a solution to this yet. Adding the `comment` parameter when I define a model doesn't seem to have any effect in the PostgreSQL database.

For example, the following code generates no comment on the `added_by` column of the `camp` table:
```
var Camp = sequelize.define('Camp', {
		id: {
			type: dataTypes.UUID,
			primaryKey: true
		},
		name: {
			type: dataTypes.STRING,
			allowNull: false
		},
		description: {
			type: dataTypes.STRING(1000),
			comment: 'The short description for the camp'
		},
		addedBy: {
			type: dataTypes.STRING(20),
			field: 'added_by',
			comment: 'The user who added the camp to the database'
		}

	}, {
		classMethods: {
			associate: function (models) {

				Camp.belongsToMany(models.Trailhead, {
					onDelete: 'CASCADE',
					through: 'trailhead_camp'
				});

				Camp.hasMany(models.ClassGroup, {
					onDelete: 'CASCADE'
				})

				// Camp.hasMany(models.Picture);

			}
		}
	});
```

Thanks!

**Comment by janmeier** [comment] 2015-08-03 07:16
@jduckworth No work is being done on this at the moment. As noted in https://github.com/sequelize/sequelize/pull/3263 they were originally removed because they caused more trouble than it was worth during query generation.

It might be possible to implement now, since quite some things have been refactored

**Comment by janmeier** [comment] 2016-04-26 11:02
Closed, duplicate of https://github.com/sequelize/sequelize/issues/4386 (which has more comments)

**Closed by janmeier** 2016-04-26 11:02 UTC
Labels: feature
