### ISSUE TITLE
Replace bluebird with async/await

### ISSUE THREAD

**Issue by remcohaszing** [sequelize/sequelize#11576] opened 2019-10-18 12:02 UTC
## Issue Description

Sequelize depends on bluebird a lot. This obscures stack traces and negatively impacts readability of the Sequelize code base itself.

I believe it should be possible to replace all of bluebird with async/await syntax and maybe some utility libraries such as [p-waterfall](https://www.npmjs.com/package/p-waterfall) and friends.

The goal would be to lose bluebird as a dependency.

### Additional context

Async/await has been supported since NodeJS 7.9. NodeJS 8 is already about to be end of life, so it’s safe to assume this doesn’t break compatibility.

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.
- [x] Maybe, I’m willing to give it a try if the Sequelize team would allow it.

**Comment by papb** [comment] 2019-10-18 12:27
Hello, thanks for the idea, I am also a big fan of [sindresorhus/promise-fun](https://github.com/sindresorhus/promise-fun).

This is a duplicate of #8315 though.

**Closed by papb** 2019-10-18 12:27 UTC
