### ISSUE TITLE
Model options.charset is overwritten by default options

### ISSUE THREAD

**Issue by rohitsud** [sequelize/sequelize#12273] opened 2020-05-18 20:04 UTC
https://github.com/sequelize/sequelize/blob/8a1429d6044123bba3a3f312b2e0c74b0c829990/lib/model.js#L1271

If I create any model with 
`charset: 'utf8mb4',
collate: 'utf8mb4_general_ci'`

sequelize translates it to this for mysql

`CREATE TABLE IF NOT EXISTS `tablename` ... ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8mb4_general_ci;`

On stepping through the code, it seems that the issue is here where we don't use the model's charset but the default charset.

**Comment by sushantdhiman** [comment] 2020-05-19 04:44
Sequelize requires you to file new issues with a specific [issue template](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com).

**Comment by rohitsud** [comment] 2020-05-19 05:38
Issue Description
What are you doing?

Here is the link to the SSCCE for this issue: LINK-HERE

```
const options = { charset = 'utf8' };
const s = new Sequelize(databaseName, username, password, options);
s.define('myModel', {
        field: {
            primaryKey: true,
            type: DataTypes.STRING(20)
        }
    , {
        charset: 'utf8mb4',
        collate: 'utf8mb4_general_ci',
    });
s.sync();
```

What do you expect to happen?

A table called myModel is created with  charset: 'utf8mb4', collate: 'utf8mb4_general_ci'

What is actually happening?

SQL error due to incorrect charset

CREATE TABLE IF NOT EXISTS myModel ... ENGINE=InnoDB DEFAULT **CHARSET=utf8** COLLATE utf8mb4_general_ci;

Output here

https://github.com/sequelize/sequelize/blob/8a1429d6044123bba3a3f312b2e0c74b0c829990/lib/model.js#L1271

This line overwrites the charset specified for the model with the previous charset Sequelize was initialized with

Add any other context or screenshots about the feature request here.
Environment

    Sequelize version: 4.44.3
    Node.js version: 8.9.14
    Operating System: OSX Catalina
    If TypeScript related: TypeScript version: NA

Issue Template Checklist
How does this problem relate to dialects?

    I think this problem happens only for the following dialect(s): mysql

Would you be willing to resolve this issue by submitting a Pull Request?

    No, I don't have the time, although I believe I could do it if I had the time...

**Comment by rohitsud** [comment] 2020-05-19 15:47
@sushantdhiman Added information as per template

**Comment by sushantdhiman** [comment] 2020-05-20 04:47
I can confirm this bug on `master`. I have noticed you are using `4.44.3`, if this bug is fixed, it wont be released for v4/v3 branches as they are deprecated.

```js
const Sequelize = require("./index");                                  
const sequelize = require("./test/support").createSequelizeInstance({                                  
  charset: "utf8",                                  
});                                  
                                  
const Model = Sequelize.Model;                                  
                                  
(async () => {                                  
  const User = sequelize.define(                                  
    "User",                                  
    {                                  
      name: Sequelize.STRING,                                  
    },                                  
    {                                  
      charset: "utf8mb4",                                  
      collate: "utf8mb4_general_ci",                                  
    }                                  
  );                                  
                                  
  await sequelize.sync({                                  
    force: true,                                  
  });                                  
})();
```

```sql
DatabaseError [SequelizeDatabaseError]: COLLATION 'utf8mb4_general_ci' is not valid for CHARACTER SET 'utf8'
    at Query.formatError (/var/projects/oss/sequelize/lib/dialects/mysql/query.js:239:16)
    at Query.handler [as onResult] (/var/projects/oss/sequelize/lib/dialects/mysql/query.js:50:23)
    at Query.execute (/var/projects/oss/sequelize/node_modules/mysql2/lib/commands/command.js:30:14)
    at Connection.handlePacket (/var/projects/oss/sequelize/node_modules/mysql2/lib/connection.js:408:32)
    at PacketParser.onPacket (/var/projects/oss/sequelize/node_modules/mysql2/lib/connection.js:70:12)
    at PacketParser.executeStart (/var/projects/oss/sequelize/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/var/projects/oss/sequelize/node_modules/mysql2/lib/connection.js:77:25)
    at Socket.emit (events.js:311:20)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11) {
  name: 'SequelizeDatabaseError',
  parent: Error: COLLATION 'utf8mb4_general_ci' is not valid for CHARACTER SET 'utf8'
      at Packet.asError (/var/projects/oss/sequelize/node_modules/mysql2/lib/packets/packet.js:708:17)
      at Query.execute (/var/projects/oss/sequelize/node_modules/mysql2/lib/commands/command.js:28:26)
      at Connection.handlePacket (/var/projects/oss/sequelize/node_modules/mysql2/lib/connection.js:408:32)
      at PacketParser.onPacket (/var/projects/oss/sequelize/node_modules/mysql2/lib/connection.js:70:12)
      at PacketParser.executeStart (/var/projects/oss/sequelize/node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.<anonymous> (/var/projects/oss/sequelize/node_modules/mysql2/lib/connection.js:77:25)
      at Socket.emit (events.js:311:20)
      at addChunk (_stream_readable.js:294:12)
      at readableAddChunk (_stream_readable.js:275:11)
      at Socket.Readable.push (_stream_readable.js:209:10) {
    code: 'ER_COLLATION_CHARSET_MISMATCH',
    errno: 1253,
    sqlState: '42000',
    sqlMessage: "COLLATION 'utf8mb4_general_ci' is not valid for CHARACTER SET 'utf8'",
    sql: 'CREATE TABLE IF NOT EXISTS `Users` (`id` INTEGER NOT NULL auto_increment , `name` VARCHAR(255), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8mb4_general_ci;',
    parameters: undefined
  },
  original: Error: COLLATION 'utf8mb4_general_ci' is not valid for CHARACTER SET 'utf8'
      at Packet.asError (/var/projects/oss/sequelize/node_modules/mysql2/lib/packets/packet.js:708:17)
      at Query.execute (/var/projects/oss/sequelize/node_modules/mysql2/lib/commands/command.js:28:26)
      at Connection.handlePacket (/var/projects/oss/sequelize/node_modules/mysql2/lib/connection.js:408:32)
      at PacketParser.onPacket (/var/projects/oss/sequelize/node_modules/mysql2/lib/connection.js:70:12)
      at PacketParser.executeStart (/var/projects/oss/sequelize/node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.<anonymous> (/var/projects/oss/sequelize/node_modules/mysql2/lib/connection.js:77:25)
      at Socket.emit (events.js:311:20)
      at addChunk (_stream_readable.js:294:12)
      at readableAddChunk (_stream_readable.js:275:11)
      at Socket.Readable.push (_stream_readable.js:209:10) {
    code: 'ER_COLLATION_CHARSET_MISMATCH',
    errno: 1253,
    sqlState: '42000',
    sqlMessage: "COLLATION 'utf8mb4_general_ci' is not valid for CHARACTER SET 'utf8'",
    sql: 'CREATE TABLE IF NOT EXISTS `Users` (`id` INTEGER NOT NULL auto_increment , `name` VARCHAR(255), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8mb4_general_ci;',
    parameters: undefined
  },
  sql: 'CREATE TABLE IF NOT EXISTS `Users` (`id` INTEGER NOT NULL auto_increment , `name` VARCHAR(255), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8mb4_general_ci;',
  parameters: undefined
}
```

**Comment by nassimmoussa** [comment] 2020-06-29 13:48
I would like to have a go on this.

**Comment by mearns** [comment] 2020-10-01 13:06
Is this issue still open? I see a lot of commits referencing it.

**Comment by LouiZibdawi** [comment] 2020-10-16 09:13
Any news on this?

**Comment by Edu93Jer** [comment] 2020-12-04 01:39
Is this still open?

**Comment by iengonline** [comment] 2021-05-21 17:31
Is this still open?

**Comment by rohitsud** [comment] 2021-11-02 17:41
Still an issue

**Comment by chetvishal** [comment] 2022-10-08 10:48
is this still an issue?

**Comment by fzn0x** [comment] 2022-10-08 11:20
> is this still an issue?

There's no default charset are set.

Set it through Sequelize constructor:
```js
const sequelize = new Sequelize('database', 'username', 'password', {
  define: {
    charset: 'utf8',
    collate: 'utf8_general_ci', 
  },
});
```

Define per model:
```js
sequelize.define('songs', {
  stringField: DataTypes.STRING,
}, {
  charset: 'utf8',
  collate: 'utf8_unicode_ci'
});
```

If you choose to define per model just empty the define options in Sequelize constructor.

**Comment by fzn0x** [comment] 2022-10-08 11:21
> Still an issue

What version of Sequelize do you use, create a simple [SSCCE](https://github.com/sequelize/sequelize-sscce) to reproduce this issue may help the issue is fixed faster.

**Comment by frostzt** [comment] 2022-10-09 06:34
@fzn0x I'll start looking into it, will try to reproduce and will raise a pr if this is an issue!

**Comment by fzn0x** [comment] 2022-10-09 07:57
> @fzn0x I'll start looking into it, will try to reproduce and will raise a pr if this is an issue!

That's would be nice, thank you!

**Comment by WikiRik** [comment] 2022-10-09 08:12
It seems charset is only tested/supported for snowflake https://github.com/sequelize/sequelize/blob/main/test/unit/query-generator/create-database-query.test.ts

But maybe other dialects also support it as well?

**Comment by fzn0x** [comment] 2022-10-09 08:15
> It seems charset is only tested/supported for snowflake https://github.com/sequelize/sequelize/blob/main/test/unit/query-generator/create-database-query.test.ts
> 
> But maybe other dialects also support it as well?

AFAIK This should applied to other dialects as well (but the tests is missing?) https://github.com/sequelize/sequelize/blob/dc7654191dc5a01e627e98eb7751c0e361b67603/src/sequelize.js#L487

**Comment by frostzt** [comment] 2022-10-09 09:33
@fzn0x @WikiRik seems like the query is indeed being generated properly for v6 or 7

```typescript
const sequelize = createSequelize6Instance({
    logQueryParameters: true,
    benchmark: true,
    define: {
      // For less clutter in the SSCCE
      timestamps: false,
    },
    logging: console.log,
});

class Foo extends Model {}

Foo.init({
    name: DataTypes.TEXT,
}, {
    charset: "utf8mb4",
    collate: "utf8mb4_general_ci",
    sequelize,
    modelName: 'Foo',
});
```

This seems to generate what the `charset` was provided.

```sql
CREATE TABLE IF NOT EXISTS `Foos` (`id` INTEGER NOT NULL auto_increment , `name` TEXT, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_general_ci
```

**Comment by ephys** [comment] 2022-10-09 09:45
@frostzt Try setting the charset option in `createSequelize6Instance`. It's supposed to be used as the default if nothing is provided in Model but it's possible it's always overwriting it

**Comment by frostzt** [comment] 2022-10-09 10:25
@ephys as you mentioned this is invalid

```js
const sequelize = createSequelize6Instance({
  charset: 'utf8mb4'
});
```

Passing charset by default into the `createSequelize6Instance` also generates the same query:

```sql
CREATE TABLE IF NOT EXISTS `Foos` (`id` INTEGER NOT NULL auto_increment , `name` TEXT, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_general_ci
```

This is what I had now:

```js
const sequelize = createSequelize7Instance({
    logQueryParameters: true,
    benchmark: true,
    define: {
      charset: "utf8mb4",
      collate: "utf8mb4_general_ci",
      // For less clutter in the SSCCE
      timestamps: false,
    },
    logging: console.log,
});
```

**Comment by ephys** [comment] 2022-10-09 10:45
Sorry to ask this, I'd run it myself but I'm not on my work machine, could you check this to make sure before we close this issue?

```ts
const sequelize = createSequelize7Instance({
  logQueryParameters: true,
  benchmark: true,
  define: {
    charset: "utf8",
    // For less clutter in the SSCCE
    timestamps: false,
  },
  logging: console.log,
});

const User = sequelize.define('User', {}, {
  charset: "utf8mb4", 
});

await User.sync({ force: true });
```

If it logs `utf8mb4` in the query, we can consider this issue resolved :)

**Comment by frostzt** [comment] 2022-10-09 10:59
@ephys Indeed I do think we can close this. This is the query it generates.

```sql
CREATE TABLE IF NOT EXISTS `Users` (`id` INTEGER NOT NULL auto_increment , PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

It always takes the `charset` from the defined model.

**Comment by ephys** [comment] 2022-10-09 11:01
Amazing, thank you! :)

**Comment by WikiRik** [comment] 2022-10-09 11:02
Did we find additional tests for this? Or maybe we should write some new unit tests?

**Closed by ephys** 2022-10-09 11:01 UTC
Labels: type: bug, good first issue

**Comment by ephys** [comment] 2022-10-09 11:11
I don't think we have a test specific to charset but we do have a test that checks that `define` in the sequelize options is used as the default value for `sequelize.define` and `Model.init`. I don't think there ever was a bug here as much as an option was set in the wrong place
