### ISSUE TITLE
How to eliminate the "id" field on table creation and select?  Postgres

### ISSUE THREAD

**Issue by awesomehimanshu** [sequelize/sequelize#7945] opened 2017-07-13 12:07 UTC
when i am creating any table by sequlizer it is adding id with it . I want to to be removed.

/*global sequelize Sequelize */
module.exports = (function () {
    'use strict';
    var blurbs = sequelize.define('blurb', {
        blurb_id: {
            type: Sequelize.INTEGER
        },
        update_date: {
            type: Sequelize.DATE
        }
    },
            {
        freezeTableName: true,
        schema: 'mobile_blurb',// don't add the timestamp attributes (updatedAt, createdAt)
        timestamps: false
      //  ,id: false
    });

// // force: true will drop the table if it already exists
    blurbs.sync({force: false}).then(function () {
        // Table created
        return true;
    });
    return blurbs;
}());

**The query is generated is this .

 CREATE TABLE IF NOT EXISTS "mobile_blurb"."blurb" ("id"   S
ERIAL , "blurb_id" INTEGER, "update_date" TIMESTAMP WITH TIME ZONE, PRIMARY KEY
("id"));

I don't need "id" field.**

**Comment by ox** [comment] 2017-07-13 17:10
You can remove the attribute by calling:

```js
blurbs.removeAttribute('id');
```

Right after you have defined `blurb`.

**Comment by awesomehimanshu** [comment] 2017-09-12 06:05
The solution worked.

**Comment by scucchiero** [comment] 2019-11-08 19:59
Any fancier solution so far?

**Comment by papb** [comment] 2020-01-15 00:42
Duplicate of #3142

**Closed by papb** 2020-01-15 00:42 UTC
