### ISSUE TITLE
Model.bulkCreate upsertKeys issue related to multiple unique fields

### ISSUE THREAD

**Issue by 4zuko** [sequelize/sequelize#12515] opened 2020-07-16 11:01 UTC
## Issue Description

Model.bulkCreate fails if the model has multiple unique fields.

### What are you doing?

Hi. My Model has the following fields: **id** (primaryKey), **uuid** (unique key), **parentUuid** (unique key), and **data**.
I want to execute bulk **update** using `Model.bulkCreate([...], { updateOnDuplicate: ['data'] })` and the following error occurs:
```
TypeError: options.upsertKeys.map is not a function at SQLiteQueryGenerator.bulkInsertQuery
```

https://github.com/sequelize/sequelize/blob/b0d4f06ea8a089a569f18f53b5958aa0cf82e671/src/dialects/abstract/query-generator.js#L194

The issue related to multiple unique keys occurs in the snippet shown below:
https://github.com/sequelize/sequelize/blob/b0d4f06ea8a089a569f18f53b5958aa0cf82e671/src/model.js#L2811-L2818

Once it's executed the value assigned to `options.upsertKeys` is not array anymore. It becomes a string value. **String.map()** fails.

### What is actually happening?

```
TypeError: options.upsertKeys.map is not a function at SQLiteQueryGenerator.bulkInsertQuery
```

### Environment

- Sequelize version: **CLI: 6.2.0**, **ORM: 6.3.3**
- Node.js version: **12.17.0**, 
- Operating System: **macOS Catalina v10.15.5**

**Comment by brianschardt** [comment] 2020-07-16 22:22
This PR will solve your problem lets encourage them to get it in 
https://github.com/prototype-two/sequelize/tree/unique-index-upsert

**Comment by almgwary** [comment] 2020-12-30 02:05
any updates on this ?

**Comment by azoreG** [comment] 2021-02-16 04:19
I had the same problem :(

**Comment by Aleksey-Danchin** [comment] 2021-02-24 15:12
The problem is actual! Details:

```
root@54537b9e143e:/app# npm view sequelize

sequelize@6.5.0 | MIT | deps: 13 | versions: 526
Multi dialect ORM for Node.JS
https://sequelize.org/

keywords: mysql, mariadb, sqlite, postgresql, postgres, mssql, orm, nodejs, object relational mapper

dist
.tarball: https://registry.npmjs.org/sequelize/-/sequelize-6.5.0.tgz
.shasum: c968a03f6fbbcda40717f73edb39fadf27b85e96
.integrity: sha512-owBt8fnzVy8E1OvyCyfCdVk7OOLyPVrBCMEf+CvRReC5oCyo+UqeXCtwaex9L6LM9ifZ1i3TG3sFeM5MgLK0CQ==
.unpackedSize: 1.1 MB

dependencies:
debug: ^4.1.1             inflection: 1.12.0        moment-timezone: ^0.5.31  retry-as-promised: ^3.2.0 sequelize-pool: ^6.0.0    uuid: ^8.1.0              wkx: ^0.5.0               
dottie: ^2.0.0            lodash: ^4.17.20          moment: ^2.26.0           semver: ^7.3.2            toposort-class: ^1.0.1    validator: ^10.11.0       

maintainers:
- janaameier <janzeh@gmail.com>
- durango <me@danieldurante.com>
- mickhansen <mick.kasper.hansen@gmail.com>
- sdepold <sascha@depold.com>
- felixfbecker <felix.b@outlook.com>
- sushantdhiman <sushantdhiman@outlook.com>
- eseliger <erikseliger@me.com>
- papb <papb1996@gmail.com>

dist-tags:
latest: 6.5.0  v4: 4.44.4     v5: 5.22.3     

published 4 weeks ago by papb <papb1996@gmail.com>
```

Use `bulkCreate` from multi update:

```js
await Block.bulkCreate(
    course.blocks.map((block) => {
        block.order = args.data.blocks.find(
            (x) => x.blockId === block.id
        ).order;

        return block.dataValues;
    }),
    {
        updateOnDuplicate: ["id", "order"],
        transaction,
    }
);
```

```js
await Lesson.bulkCreate(
    lessons.map((lesson) => {
        const { blockId, order } = args.data.lessons.find(
            (x) => x.lessonId === lesson.id
        );

        Object.assign(lesson, { blockId, order });

        return lesson.dataValues;
    }),
    {
        updateOnDuplicate: ["id", "order", "blockId"],
        transaction,
    }
);
```

**Comment by halaelsaka2** [comment] 2021-11-02 10:38
this problem still occur with me ,any updates?

**Comment by lukasver** [comment] 2021-11-11 22:14
Having the same issue with multiple unique fields on the same table and trying to upsert values with bulk create. Got this error:
`/node_modules/sequelize/lib/model.js:2698:52)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at Function.bulkCreate (/node_modules/sequelize/lib/model.js:2824:12)","type":"Error","msg":"options.upsertKeys.map is not a function"}`

**Comment by creativefctr** [comment] 2021-12-28 11:44
This is a bad one. @WikiRik any news on a fix? What about the PR by: @brianschardt

**Comment by WikiRik** [comment] 2021-12-28 12:09
Interesting that this still occurs, @brianschardt made a PR [#12516](https://github.com/sequelize/sequelize/pull/12516) which was merged as https://github.com/sequelize/sequelize/pull/13345 in v6.6.4. See also [this test in v6.12.3](https://github.com/sequelize/sequelize/blob/v6.12.3/test/integration/model/bulk-create.test.js#L650-L710)

@creativefctr  Can you confim that this is not fixed yet in v6.12.3 and provide an alternative test for your usecase?

**Comment by creativefctr** [comment] 2021-12-28 16:13
@WikiRik sorry, my bad. I did know this was fixed because it was open. After an update the issue was resolved.

**Comment by WikiRik** [comment] 2021-12-28 16:41
No worries, thanks for informing me this was still open. Seeing that it is indeed resolved I'll close this issue.

**Closed by WikiRik** 2021-12-28 16:41 UTC
Labels: type: bug
