### ISSUE TITLE
SELECT field AS field: woefully long queries

### ISSUE THREAD

**Issue by heisian** [sequelize/sequelize#9315] opened 2018-04-17 00:17 UTC
## What are you doing?
Using Sequelize as normal.

## What do you expect to happen?
I don't expect Sequelize to create a gigantic useless query full of useless `AS` statements:
```SQL
SELECT "Identity"."id", 
       "Identity"."user_id", 
       "Identity"."primary", 
       "Identity"."birth_name_first", 
       "Identity"."birth_name_middle", 
       "Identity"."birth_name_last", 
       "Identity"."birth_date", 
       "Identity"."birth_gender", 
       "Identity"."birth_country", 
       "Identity"."created_at", 
       "Identity"."updated_at", 
       "Identity"."deleted_at", 
       "PhoneNumbers"."id"               AS "PhoneNumbers.id", 
       "PhoneNumbers"."identity_id"      AS "PhoneNumbers.identity_id", 
       "PhoneNumbers"."number"           AS "PhoneNumbers.number", 
       "PhoneNumbers"."verified"         AS "PhoneNumbers.verified", 
       "addresses"."id"                  AS "Addresses.id", 
       "addresses"."identity_id"         AS "Addresses.identity_id", 
       "addresses"."type"                AS "Addresses.type", 
       "addresses"."street1"             AS "Addresses.street1", 
       "addresses"."street2"             AS "Addresses.street2", 
       "addresses"."locality"            AS "Addresses.locality", 
       "addresses"."region"              AS "Addresses.region", 
       "addresses"."postal_code"         AS "Addresses.postal_code", 
       "addresses"."country"             AS "Addresses.country", 
       "SSN"."id"                        AS "SSN.id", 
       "SSN"."identity_id"               AS "SSN.identity_id", 
       "SSN"."encrypted_value"           AS "SSN.encrypted_value", 
       "SSN"."transunion_attempts"       AS "SSN.transunion_attempts", 
       "SSN"."transunion_risk_group"     AS "SSN.transunion_risk_group", 
       "SSN"."transunion_details"        AS "SSN.transunion_details", 
       "SSN"."transunion_report"         AS "SSN.transunion_report", 
       "SSN"."lexis_nexis_attempts"      AS "SSN.lexis_nexis_attempts", 
       "SSN"."lexis_nexis_prefill"       AS "SSN.lexis_nexis_prefill", 
       "SSN"."lexis_nexis_report"        AS "SSN.lexis_nexis_report", 
       "SSN"."created_at"                AS "SSN.created_at", 
       "SSN"."updated_at"                AS "SSN.updated_at", 
       "SSN"."deleted_at"                AS "SSN.deleted_at", 
       "User"."id"                       AS "User.id", 
       "User"."lead_id"                  AS "User.lead_id", 
       "User"."password"                 AS "User.password", 
       "User"."password_change_required" AS "User.password_change_required", 
       "User"."client_data"              AS "User.client_data", 
       "User"."object_id"                AS "User.object_id", 
       "User"."lead_object_id"           AS "User.lead_object_id", 
       "User"."referrer_object_id"       AS "User.referrer_object_id", 
       "User"."created_at"               AS "User.created_at", 
       "User"."updated_at"               AS "User.updated_at", 
       "User"."deleted_at"               AS "User.deleted_at" 
FROM   "identities" AS "Identity" 
       LEFT OUTER JOIN "phone_numbers" AS "PhoneNumbers" 
                    ON "Identity"."id" = "PhoneNumbers"."identity_id" 
       LEFT OUTER JOIN "addresses" AS "Addresses" 
                    ON "Identity"."id" = "addresses"."identity_id" 
       LEFT OUTER JOIN "ssns" AS "SSN" 
                    ON "Identity"."id" = "SSN"."identity_id" 
                       AND ( ( 
       "SSN"."deleted_at" > '2018-04-17 00:11:53.739 +00:00' 
        OR "SSN"."deleted_at" IS NULL ) 
                             AND ( "SSN"."deleted_at" > 
                                   '2018-04-17 00:11:53.680 +00:00' 
                                    OR "SSN"."deleted_at" IS NULL ) ) 
       LEFT OUTER JOIN "users" AS "User" 
                    ON "Identity"."user_id" = "User"."id" 
                       AND ( ( 
       "User"."deleted_at" > '2018-04-17 00:11:53.739 +00:00' 
        OR "User"."deleted_at" IS NULL ) 
                             AND ( "User"."deleted_at" > 
                                   '2018-04-17 00:11:53.680 +00:00' 
                                    OR "User"."deleted_at" IS NULL ) ) 
WHERE  ( ( "Identity"."deleted_at" > '2018-04-17 00:11:53.739 +00:00' 
            OR "Identity"."deleted_at" IS NULL ) 
         AND "Identity"."id" = 526 ); 
```

## What is actually happening?
Sequelize is creating gigantic queries full of useless `AS` statements. It's not even using its own aliases in the `JOIN` statements: `OR "User"."deleted_at" IS NULL`

__Dialect:__ postgres
__Dialect version:__ 10.1
__Database version:__ 10.1
__Sequelize version:__ 4.37.6
__Tested with latest release:__ Yes

**Comment by sushantdhiman** [comment] 2018-04-17 03:47
I think you created a similar issue before, as before duplicate of https://github.com/sequelize/sequelize/issues/5708

**Closed by sushantdhiman** 2018-04-17 03:47 UTC
