### ISSUE TITLE
does support postgresql ltree ?

### ISSUE THREAD

**Issue by qianfangyuan** [sequelize/sequelize#10278] opened 2018-12-18 04:31 UTC
postgresql have value type ltree ?
https://www.postgresql.org/docs/current/ltree.html

does support postgresql ltree ?

**Comment by nithishjv** [comment] 2019-09-19 12:11
Has there been any momentum on this? Do we have a workaround to use ltree with Sequelize?

**Comment by papb** [comment] 2019-09-26 02:05
@nithishjv Not that I know of. Also, it would be great if you (or someone else) could open a new issue about this, filling our feature request template, since this issue is too far from our current feature request standards. If you do, I will close this one as a duplicate of the new one. Thanks!

**Comment by papb** [comment] 2019-11-01 14:18
Duplicate of #11629

**Closed by papb** 2019-11-01 14:18 UTC
Labels: type: feature
