### ISSUE TITLE
setAssocations w/ contextual through

### ISSUE THREAD

**Issue by xizhao** [sequelize/sequelize#4835] opened 2015-11-10 21:03 UTC
for .belongsToMany setAssociations(), it makes sense to be able to specify the fields of the through table on each individual association.  i.e.:

```javascript
reader.setBooks([{
  book: { id: 3 },
  through: {
    hasRead: true // can be contextual to the book instance
  }
}, ..., ..., ...], options)
```

**Comment by mickhansen** [comment] 2015-11-10 21:06
Think there's a discussion for this elsewhere already, can't find it atm though.

/cc @janmeier

**Comment by RyanThomas73** [comment] 2016-05-22 21:11
@janmeier You're book.[name of through table] = { ... } example only works if book is an instance of a db model. Is there no way to set the fields of the through table per association when setting via an array of ids?

e.g.
reader.setBooks([bookids], [{hasRead: true}, {hasRead: false}]);

**Comment by sushantdhiman** [comment] 2016-07-21 11:10
Duplicate of #4597

**Closed by sushantdhiman** 2016-07-21 11:10 UTC
