### ISSUE TITLE
sync() with new alter method fails with dataType enum

### ISSUE THREAD

**Issue by skn3** [sequelize/sequelize#7649] opened 2017-05-17 16:02 UTC
## What you are doing?

```js
'use strict';

const Sequelize = require('sequelize');

//first connect to the database
const database = new Sequelize('database', 'user', 'password', {
    dialect: 'postgres',
    host: '127.0.0.1',
    port: 5432,

    pool: {
        max: 5,
        min: 0,
        idle: 10000
    },
});

return database.authenticate()
.then(() => {
    //success connecting,
    console.log('database connected');
    return database;
})
.then(database => {
    const containerModel = database.define('TestContainer', {
        option: {
            type: Sequelize.DataTypes.ENUM('enum1', 'enum2', 'enum3'),
            defaultValue: 'enum1',
            allowNull: false
        },
    });

    return database.sync({
        alter: true,
        force: false,
    });
})
.catch(err => {
    //failed to connect
    console.error(err);
    process.exit(1);
});
```

## What do you expect to happen?
Being able to run the example multiple times without fail

## What is actually happening?
On second run, an error occurs:

> SequelizeDatabaseError: type "enum_TestContainer_option" already exists

__Dialect:__ postgres
__Database version:__ 9.6.2
__Sequelize version:__ git master

**Comment by skn3** [comment] 2017-07-09 18:55
#7606

**Comment by GrigoryGraborenko** [comment] 2017-07-21 08:43
This can be fixed by changing line 783 in query-generator from:
let sql = 'CREATE TYPE ' + enumName + ' AS ' + values + ';';
To:
let sql = 'DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = \'enum_' + tableName + '_' + attr + '\') THEN CREATE TYPE ' + enumName + ' AS ' + values + '; END IF; END$$;'

I've never contributed to OSS before, so I don't feel that confident about creating a push request. I can figure it out and create one if you think this solution is acceptable. I worry that I wasn't able to use the enumName as generated a few lines up - postgres throws an error if I don't recreate the name without the namespace. Should I also then refactor the pgEnumName function to pull from a new, third function that returns a pure name without the namespace for commonality?

**Comment by techsin** [comment] 2017-11-10 06:07
I've this exact issue

**Comment by Jadex1** [comment] 2017-12-03 22:18
I'm getting this issue for my tests, not sure what's causing it.

**Comment by Vincz** [comment] 2018-02-08 00:26
Getting the same issue. Enum don't work with sync alter.

**Comment by Vardiak** [comment] 2018-03-10 23:14
This error is still occurring with latest version, any idea ?

**Comment by papigers** [comment] 2018-08-30 08:02
Bump? I'm getting the same

**Comment by IgorSzymanski** [comment] 2018-09-14 11:02
v. 4.38.1
There error is still there in `alter: true` mode. `force: true` does the trick in development, but no data is persisted for obvious reasons.

**Comment by ekatzenstein** [comment] 2018-09-16 02:55
Yes, this is still an issue.

**Comment by NVIERAINFO** [comment] 2019-03-08 07:22
So how to maintain alters, is there any workaround? Kindly let us know.

**Comment by thesciz** [comment] 2019-05-28 18:36
Bump. Still having a similar issue.

**Comment by ZTAP0011** [comment] 2019-05-29 09:16
Did anyone find the solution for the issue? I am also facing the same issue.

**Comment by radcapitalist** [comment] 2019-05-29 10:25
Yes, but you may not like it:  Don’t use sync with alter, use migrations instead. Sync with alter is no good in production anyway; might as well get good at migrations early on.

I told you youmay not like it :-).

Eric

**Comment by papb** [comment] 2019-08-17 03:55
Can someone confirm this is still happening? I was thinking that perhaps #11249 might have fixed this...

**Comment by rike422** [comment] 2019-10-17 15:21
Hi @papb 

I still have a problem. versoin "5.19.8"

```
Executing (default): ALTER TABLE "providers" ALTER COLUMN "name" SET NOT NULL;ALTER TABLE "providers" ALTER COLUMN "name" DROP DEFAULT;CREATE TYPE "public"."enum_providers_name" AS ENUM('type1');ALTER TABLE "providers" ALTER COLUMN "name" TYPE "public"."enum_providers_name" USING ("name"::"public"."enum_providers_name");

 ERROR  type "enum_providers_name" already exists                                                                           

  at Query.formatError (node_modules/sequelize/lib/dialects/postgres/query.js:366:16)
  at node_modules/sequelize/lib/dialects/postgres/query.js:72:18
  From previous event:
  at Query.run (node_modules/sequelize/lib/dialects/postgres/query.js:64:23)
  at node_modules/sequelize/lib/sequelize.js:645:29

```

**Comment by syy1125** [comment] 2020-01-07 01:51
I encountered this problem as well.
From what I can tell, line 292 on `lib/dialects/postgres/query-generator.js` (in `changeColumnQuery` function) is most likely the offending line.
```
if (attributes[attributeName].startsWith('ENUM(')) {
  /* THIS LINE */ attrSql += this.pgEnum(tableName, attributeName, attributes[attributeName]);
  definition = definition.replace(/^ENUM\(.+\)/, this.pgEnumName(tableName, attributeName, { schema: false }));
  definition += ` USING (${this.quoteIdentifier(attributeName)}::${this.pgEnumName(tableName, attributeName)})`;
}
```
It's a blind call to `pgEnum` (which generates a `CREATE TYPE ... AS ENUM(...)` statement), without checking if the type's name has already been taken.

Unfortunately, I don't know sequelize internals or postgres well enough to suggest changes or come up with a workaround.

**Comment by bwoodlt** [comment] 2020-01-28 09:16
Still experiencing this issue... any thoughts?

**Comment by sturdynut** [comment] 2020-01-30 17:38
I have an open PR that has changes related to this.  I can try to fix there, but just waiting on some feedback before I put more time into https://github.com/sequelize/sequelize/pull/11514

**Comment by bodolawale** [comment] 2020-02-19 21:31
Can someone help with this issue?
It has been years now

**Comment by aristov** [comment] 2020-03-05 18:00
> @GrigoryGraborenko:
>
> This can be fixed by changing line 783 in query-generator from:
> let sql = 'CREATE TYPE ' + enumName + ' AS ' + values + ';';
> To:
> let sql = 'DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'enum_' + tableName + '_' + attr + '') THEN CREATE TYPE ' + enumName + ' AS ' + values + '; END IF; END$$;'

This https://github.com/sequelize/sequelize/issues/7649#issuecomment-316942602 helps.
I use this workaround while a new patch version containing the fix is in progress:
```js
// pgEnum-fix.js

const PostgresQueryGenerator = require('sequelize/lib/dialects/postgres/query-generator')

PostgresQueryGenerator.prototype.pgEnum = function(tableName, attr, dataType, options) {
  const enumName = this.pgEnumName(tableName, attr, options);
  let values;

  if (dataType.values) {
    values = `ENUM(${dataType.values.map(value => this.escape(value)).join(', ')})`;
  } else {
    values = dataType.toString().match(/^ENUM\(.+\)/)[0];
  }

  let sql = `DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'enum_${ tableName }_${ attr }') THEN CREATE TYPE ${ enumName } AS ${ values }; END IF; END$$;`;
  if (!!options && options.force === true) {
    sql = this.pgEnumDrop(tableName, attr) + sql;
  }
  return sql;
}
```

Require this script before the first Sequelize require statement:

```js
require('./pgEnum-fix')
const sequelize = require('sequelize')
```

**Comment by MichaelLeeHobbs** [comment] 2020-05-18 15:19
I used @aristov pgEnum-fix.js but had to add ```module.exports = ()=> PostgresQueryGenerator``` at the end to fix an issue as shown below. 

/usr/src/app/node_modules/sequelize/lib/sequelize.js:489
       this.importCache[importPath] = defineCall(this, DataTypes);
                                      ^
TypeError: defineCall is not a function
     at Sequelize.import (/usr/src/app/node_modules/sequelize/lib/sequelize.js:489:38)

**Comment by zephyrosjyd** [comment] 2020-07-22 04:31
I used @aristov pgEnum-fix.js and @MichaelLeeHobbs comments.
```javascript
/* eslint-disable func-names */
/* eslint-disable no-restricted-syntax */
/* eslint-disable guard-for-in */
const PostgresQueryGenerator = require('sequelize/lib/dialects/postgres/query-generator');

PostgresQueryGenerator.prototype.pgEnum = function (tableName, attr, dataType, options) {
  const enumName = this.pgEnumName(tableName, attr, options);
  let values;

  if (dataType.values) {
    values = `ENUM(${dataType.values.map((value) => this.escape(value)).join(', ')})`;
  } else {
    // eslint-disable-next-line prefer-destructuring
    values = dataType.toString().match(/^ENUM\(.+\)/)[0];
  }

  let sql = `DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'enum_${tableName}_${attr}') THEN CREATE TYPE ${enumName} AS ${values}; END IF; END$$;`;
  if (!!options && options.force === true) {
    sql = this.pgEnumDrop(tableName, attr) + sql;
  }
  return sql;
};

PostgresQueryGenerator.prototype.changeColumnQuery = function (tableName, attributes) {
  const query = (subQuery) => `ALTER TABLE ${this.quoteTable(tableName)} ALTER COLUMN ${subQuery};`;
  const sql = [];
  for (const attributeName in attributes) {
    let definition = this.dataTypeMapping(tableName, attributeName, attributes[attributeName]);
    let attrSql = '';

    if (definition.includes('NOT NULL')) {
      attrSql += query(`${this.quoteIdentifier(attributeName)} SET NOT NULL`);

      definition = definition.replace('NOT NULL', '').trim();
    } else if (!definition.includes('REFERENCES')) {
      attrSql += query(`${this.quoteIdentifier(attributeName)} DROP NOT NULL`);
    }

    if (definition.includes('DEFAULT')) {
      attrSql += query(`${this.quoteIdentifier(attributeName)} SET DEFAULT ${definition.match(/DEFAULT ([^;]+)/)[1]}`);

      definition = definition.replace(/(DEFAULT[^;]+)/, '').trim();
    } else if (!definition.includes('REFERENCES')) {
      attrSql += query(`${this.quoteIdentifier(attributeName)} DROP DEFAULT`);
    }

    if (attributes[attributeName].startsWith('ENUM(')) {
      attrSql += this.pgEnum(tableName, attributeName, attributes[attributeName]);
      definition = definition.replace(/^ENUM\(.+\)/, this.pgEnumName(tableName, attributeName, { schema: false }));
      // definition += ` USING (${this.quoteIdentifier(attributeName)}::${this.pgEnumName(tableName, attributeName)})`;
    }

    if (definition.match(/UNIQUE;*$/)) {
      definition = definition.replace(/UNIQUE;*$/, '');
      attrSql += query(`ADD UNIQUE (${this.quoteIdentifier(attributeName)})`).replace('ALTER COLUMN', '');
    }

    if (definition.includes('REFERENCES')) {
      definition = definition.replace(/.+?(?=REFERENCES)/, '');
      attrSql += query(`ADD FOREIGN KEY (${this.quoteIdentifier(attributeName)}) ${definition}`).replace('ALTER COLUMN', '');
    } else {
      attrSql += query(`${this.quoteIdentifier(attributeName)} TYPE ${definition}`);
    }

    sql.push(attrSql);
  }

  return sql.join('');
};

module.exports = () => PostgresQueryGenerator;
```
This is my temporary solution for `ENUM` and `USING` errors.

**Comment by cskiwi** [comment] 2020-12-06 10:05
Small change to @zephyrosjyd version:

```javascript
let sql = `DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'enum_${tableName}_${attr}') THEN CREATE TYPE ${enumName} AS ${values}; END IF; END$$;`;
```

should be:

```javascript
let sql = `DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'enum_${tableName.tableName}_${attr}') THEN CREATE TYPE ${enumName} AS ${values}; END IF; END$$;`;
```
This is needed when using multiple schemas

**Comment by omsi96** [comment] 2021-01-19 22:37
This is still an issue and we need a proper fix for this

**Comment by achempak** [comment] 2021-01-25 04:44
I'm also dealing with this issue. 

Also, I had to change @aristov version:
`let sql = `DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'enum_${ tableName }_${ attr }') THEN CREATE TYPE ${ enumName } AS ${ values }; END IF; END$$;`;`

Was changed to this: 
`let sql = `DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'enum_${ tableName.tableName }_${ attr }') THEN CREATE TYPE ${ enumName } AS ${ values }; END IF; END$$;`;`

**Comment by changesbyjames** [comment] 2021-03-02 16:43
Just confirming that this is still an issue. I'm opting to not use enums for now and enforce restrictions outside of the database, which isn't ideal.

**Comment by Dammmien** [comment] 2021-03-15 21:10
That's still an issue on my side too

**Comment by dalisoft** [comment] 2021-03-26 20:25
I have same issue, not solution found yet

**Comment by yassernascimento** [comment] 2021-03-30 07:42
this is happening even using the force: true flag

**Comment by charan1973** [comment] 2021-04-30 05:43
Hey, is this issue fixed yet? Because there seems to be no comments after March. @skn3

**Comment by GabrielRatener** [comment] 2021-06-22 19:04
Why isn't this being fixed?

**Comment by jaimindevstree** [comment] 2021-08-28 10:48
The issue still not fixed.

**Comment by jscul** [comment] 2021-09-01 19:30
My current development environment can't persist data. I need to use `force: true` and `alter: false` for every deploy. I set it up so it seeds data every single deployment but this is a huge annoyance in the development process. I guess this is why people say not to use ORMs.

**Comment by ArsiGondal** [comment] 2021-09-10 12:15
I still have this issue

**Comment by alphaFaiz** [comment] 2021-09-15 03:38
still have this issue

**Comment by muhammadshumas** [comment] 2021-10-12 15:23
still facing this issue

**Comment by wesww** [comment] 2021-10-21 20:11
If anyone is still facing this issue, here's the workaround I'm using.

Instead of doing this:
```
option: {
  type: Sequelize.DataTypes.ENUM('enum1', 'enum2', 'enum3'),
  allowNull: false  
  defaultValue: 'enum1',
},
```

```
  type: {
    type: Sequelize.DataTypes.STRING,
    allowNull: false,
    defaultValue: 'enum1',
    validate: {
      customValidator: (value) => {
        const enums = ['enum1', 'enum2', 'enum3']
        if (!enums.includes(value)) {
          throw new Error('not a valid option')
        }
      }
    },
  },
```
There you have it, all the enum validation of DataTypes.ENUM, without the sync problem.

Note: If anybody is motivated to test out this workaround for high-volume queries, please share back whether it has any measurable performance implications.

**Comment by eliezra236** [comment] 2021-12-17 11:11
> If anyone is still facing this issue, here's the workaround I'm using.
> 
> Instead of doing this:
> 
> ```
> option: {
>   type: Sequelize.DataTypes.ENUM('enum1', 'enum2', 'enum3'),
>   allowNull: false  
>   defaultValue: 'enum1',
> },
> ```
> 
> I instead do this:
> 
> ```
>   type: {
>     type: Sequelize.DataTypes.STRING,
>     allowNull: false,
>     defaultValue: 'enum1',
>     validate: {
>       customValidator: (value) => {
>         const enums = ['enum1', 'enum2', 'enum3']
>         if (!enums.includes(value)) {
>           throw new Error('not a valid option')
>         }
>       }
>     },
>   },
> ```
> 
> There you have it, all the enum validation of DataTypes.ENUM, without the sync problem. 😄
> 
> Note: If anybody is motivated to test out this workaround for high-volume queries, please share back whether it has any measurable performance implications.

Thanks,
But then it wouldn't define it as Enum on the postgres DB, will it have any performence / issues because of that?

And the problem isn't fixed yet, on version 6.11

**Comment by soyIsaacDev** [comment] 2022-03-22 19:06
The issue is still in lates version (6.17.0) using alter: true;
force: true does the trick in development.

**Comment by AndrewSerra** [comment] 2022-04-02 18:36
I'm getting the same problem even if force is true.

**Comment by mordonez-me** [comment] 2022-06-18 10:02
5 years and the same issue? Is there a plan to fix this? let us know please so we can workaround or wait.

**Comment by CrafterSvK** [comment] 2022-06-18 10:28
This thing happens also in 7.0.0-alpha.14.

**Comment by ephys** [comment] 2022-06-19 09:24
Unfortunately we have to prioritize what we work on, and `sync({alter:true})` is low on my list because I consider it to be a flawed approach to migrations (not because it has bugs, but because it's never going to be able to reliably migrate a schema). I prefer pointing people to [this resource](https://github.com/MRVMV/sequelize-mig) instead.

That being said we always prioritize PRs over our own code, so if someone is willing to work on this we will review and merge the PR

**Comment by CrafterSvK** [comment] 2022-06-19 13:16
It really does not work even without the `alter: true`. When creating new tables, it still does create enums multiple times resulting in incomplete table and errors.

**Comment by geekchiq** [comment] 2022-08-18 08:50
The issue is still in lates version (6.21.1) using alter: true.

**Comment by DN92** [comment] 2022-08-31 21:53
Exists Still

**Comment by ephys** [comment] 2022-09-17 12:05
This is being worked on in https://github.com/sequelize/sequelize/pull/14687

**Comment by BaptisteMartinet** [comment] 2022-12-29 15:39
Encountered this issue today. I'm not able to sync postgreSQL because of enums.

**Comment by aristov** [comment] 2023-02-27 12:01
One more attempt for v6 about this: https://github.com/sequelize/sequelize/pull/15718

**Comment by aristov** [comment] 2023-03-05 10:49
🎉

**Comment by ephys** [comment] 2023-03-07 08:14
Reopening because we still need to merge https://github.com/sequelize/sequelize/pull/15718 for v6 :)

**Closed** 2023-03-07 08:16 UTC
Labels: type: bug, dialect: postgres

**Comment by DN92** [comment] 2023-03-11 02:30
someone confirm this is fixed before i drop my db (again)
