### ISSUE TITLE
How to customize the "join on" attributes

### ISSUE THREAD

**Issue by TivonJJ** [sequelize/sequelize#3658] opened 2015-05-06 01:49 UTC
```javascript
var user = sequelize.define("user",{
    id:{type:Sequelize.UUIDV4, defaultValue: Sequelize.UUIDV4},
    name:{type:Sequelize.STRING(50)},
    cardNo:{type:Sequelize.STRING(100)}
});

var card = sequelize.define("user",{
    id:{type:Sequelize.UUIDV4, defaultValue: Sequelize.UUIDV4},
    no:{type:Sequelize.STRING(100)},
    validDate:{type:Sequelize.DATE}
});

user.hasOne(card,{as:'card',foreignKey:'no'});

user.findAll({
    include:{model:card,as:'card'}
});
```
There is no primary key and foreign key！

generated SQL：
```sql
SELECT `user`.`id`, `user`.`name`, `user`.`cardNo`, `user`.`createdAt`, `user`.`updatedAt`, `card`.`id` AS `card.id`, `card`.`no` AS `card.no`, `card`.`validDate` AS `card.validDate`, `card`.`createdAt` AS `card.createdAt`, `card`.`updatedAt` AS `card.updatedAt` 
FROM `users` AS `user` 
LEFT OUTER JOIN `users` AS `card` ON `user`.`id` = `card`.`no`;
```
but i want
```sql
SELECT `user`.`id`, `user`.`name`, `user`.`cardNo`, `user`.`createdAt`, `user`.`updatedAt`, `card`.`id` AS `card.id`, `card`.`no` AS `card.no`, `card`.`validDate` AS `card.validDate`, `card`.`createdAt` AS `card.createdAt`, `card`.`updatedAt` AS `card.updatedAt` 
FROM `users` AS `user` 
LEFT OUTER JOIN `users` AS `card` ON `user`.`cardNo` = `card`.`no`;
```
``ON `user`.`cardNo` = `card`.`no```  do not use 'user.id'

**Comment by janmeier** [comment] 2015-05-06 05:10
Associations with non-primary keys are not currently supported

**Comment by mickhansen** [comment] 2015-05-06 06:40
Duplicate of https://github.com/sequelize/sequelize/issues/3561

**Closed by mickhansen** 2015-05-06 06:40 UTC
Labels: feature
