### ISSUE TITLE
Error when creating non-association constraint on table in different schema

### ISSUE THREAD

**Issue by Askelkana** [sequelize/sequelize#5049] opened 2015-12-15 16:56 UTC
Dialect: mysql

When specifying a foreign key constraint that references a table in another schema, the correct format is:

FOREIGN KEY (\`tableId\`) REFERENCES __Schema.Table__ (\`id\`) ON DELETE CASCADE ON UPDATE CASCADE

whereas what is generated is:

FOREIGN KEY (\`tableId\`) REFERENCES __\`Table\`__ (\`id\`) ON DELETE CASCADE ON UPDATE CASCADE

(the difference is (a) the absence of the Schema name and (b) the presence of the tick marks)

This results even if specifying the model in the reference map, i.e.

    references: { model: Schema.Table }

I have played around with other documented variations of the "references" option, but all produce this latter result, which fails to factor in the schema, and adds the tick marks which need to be removed.

Unless, of course, there exists a correct way to specify this relationship, that I'm missing...

**Comment by mickhansen** [comment] 2015-12-15 18:35
Related to but not a duplicate of: https://github.com/sequelize/sequelize/issues/5047

**Comment by mickhansen** [comment] 2015-12-15 18:35
Have you tried with `references: { model: Model.schema('schema') }`?

**Comment by Askelkana** [comment] 2015-12-15 18:52
Now I have, thanks to your suggestion. Still no joy.

**Comment by mickhansen** [comment] 2015-12-15 18:57
Alright, definitely a bug then.

**Comment by Askelkana** [comment] 2015-12-15 22:02
If you could give some pointers, I could perhaps create a pull request?

**Comment by Askelkana** [comment] 2015-12-15 23:30
Ok, some progress: by adding a 'schema' option when defining a Model, the schema appears in the association, and no `references` map is required. The sole problem now is that the quotes are not correct, i.e. we get

    `Schema.Table`

when we should be getting:

    `Schema`.`Table`

The `quoteTable` method is not being used, although the logic seems to be just what is wanted. I'm still digging to see where the string is constructed. Once found, the fix should be straightforward.

**Comment by mickhansen** [comment] 2015-12-16 08:04
MySQL does not have real schema support IIRC.

**Comment by Askelkana** [comment] 2015-12-16 08:19
But what does that mean? MySQL supports references like `Schema`.`Table`, which is what is wanted in this particular situation.

What do you suggest as a solution, then?

**Comment by mickhansen** [comment] 2015-12-16 08:33
I don't believe it does, mysql does not have schemas (it does support SOME cross database querying, but not quite the same), sequelize has some pseudo schema support.

I'm not sure exactly what you are attempting to do here?

**Comment by Askelkana** [comment] 2015-12-16 08:33
The offending code segment is thus:

      if (this._dialect.supports.schemas) {
        if (param.schema) {
          table += this.quoteIdentifier(param.schema) + '.';
        }

        table += this.quoteIdentifier(param.tableName);
      } else {
        if (param.schema) {
          table += param.schema + (param.delimiter || '.');
        }

        table += param.tableName;
        table = this.quoteIdentifier(table);
      }

Without schema support, the else-branch is taken, rendering the incorrect \`Schema.Table\` result. Is it simply so that this rendering is invalid? Why is the schema property sought for even when schema support is not present? The logic is not self-explanatory here.

**Comment by mickhansen** [comment] 2015-12-16 08:37
We implement pseudo schemas via prefixes for MySQL. A choice made back when we figured every dialect should support the same features.

**Comment by janmeier** [comment] 2015-12-16 08:39
Perhaps there is a bit of confusion here - in mysql `CREATE SCHEMA` actually maps to `CREATE DATABASE` http://dev.mysql.com/doc/refman/5.7/en/create-database.html, whereas in poistgres, schema and database are two diferent things. Therefore we decided to implement pseudo-schemas in mysql as mick mentioned, by simply prefixing the tablename

**Comment by Askelkana** [comment] 2015-12-16 08:40
I have no beef with that whatsoever. Can you recall why the else-branch referenced above renders what it does? I mean, in what dialect is \`Schema.Table\` correct?

I agree that the schema-database misnomer is more than frustrating in MySql.

**Comment by janmeier** [comment] 2015-12-16 08:41
Its correct in mysql, because its a pseudo schema

**Comment by Askelkana** [comment] 2015-12-16 08:41
I see that the schema support is a side-issue to the issue at hand (incorrect rendering of the prefix). Can I get your thoughts on that?

**Comment by Askelkana** [comment] 2015-12-16 08:42
What do you mean by psuedo-schema? It is not correct, because it generates an error.

**Comment by mickhansen** [comment] 2015-12-16 08:44
pseudo-schema means that mysql does not have proper schema support so we simply prepend table names so you can have different tables in the same database (but prefixed).
However the constraints query does not have the prefix correctly it seems.

As to whether or not MySQL should have real database/schema support, we'd definitely welcome that, i don't know if MySQL supports the same things as PG/MSSQL in terms of cross schema joins etc though.

**Comment by janmeier** [comment] 2015-12-16 08:44
```
`Schema`.`Table`
```
is incorrect in mysql, because it would reference the `schema` database. If you add a schema in sequelize, its prefixed to the table name. Which error does it generate?

**Comment by Askelkana** [comment] 2015-12-16 08:44
`\`Schema.Table\`` is incorrect format in MySql. It should be either
    Schema.Table
or
    \`Schema\`.\`Table\`

**Comment by mickhansen** [comment] 2015-12-16 08:45
```
`Schema.Table`
```
is actually correct, it's simply a single table with with a name consiting of two parts and a dot.

**Comment by Askelkana** [comment] 2015-12-16 08:48
Are we talking about two separate things here?

In my scenario, I have two schema/databases. I want to reference one from the other. In normal MySql parlance, that is written as

    Schema.Table

or

    `Schema`.`Table`

as I have stated. The format

    `Schema.Table`

does not go through.

I am not using table prefixes. I am using standard MySql schemas.

**Comment by Askelkana** [comment] 2015-12-16 08:49
and when I say schema, I'm talking about what is generated by the following:

    create database `myDatabase`;

**Comment by janmeier** [comment] 2015-12-16 08:50
In that case yes - sequelize schemas are schemas, not databases. In the case of postgres we use native schema support, and in the case of mysql, we emulate schemas by prefixing the table name

**Comment by mickhansen** [comment] 2015-12-16 08:50
And as mentioned a few times, Sequelize does not support MySQL schemas, it uses prefixes for pseudo schema support.

As you mentioned things break down when setting schema support to true, so the mysql schema support is likely not up to par with PG.

Now i have no ideas what the limitations of cross-db stuff is in MySQL (are cross-db joins allowed?).
But we could definitely look at providing real schema support for MySQL in the next major.

**Comment by Askelkana** [comment] 2015-12-16 08:51
yes, cross-dbs associations are not a problem, as long as the grants are in place.

**Comment by janmeier** [comment] 2015-12-16 08:51
See https://github.com/sequelize/sequelize/issues/3023

**Closed** 2015-12-16 08:53 UTC
Labels: bug

**Comment by Askelkana** [comment] 2015-12-16 08:55
Well, hey. This issue seems to be a duplicate of #3023. I'll go ahead and close this. Thanks for the support!
