### ISSUE TITLE
bulkCreate doesn't support 'includes'

### ISSUE THREAD

**Issue by antony** [sequelize/sequelize#10172] opened 2018-11-17 09:53 UTC
## What are you doing?

One might assume that bulkCreate would take the same attributes as create, after reading the docs. There is no reason that I can discern that 'include' wouldn't work.

This is probably a docs issue, or a validation enhancement than strictly a bug.

```js
Product.bulkCreate(productList, {
            include: {
              model: [ Tag ],
              as: 'tags'
            }
          })
```

## What do you expect to happen?
I wanted tags to be created with each of my products.

## What is actually happening?
The includes was simply ignored, without warning.

_Output, either JSON or SQL_
```sql
INSERT INTO `product` (`product_id`,`title`,`status`,`add_timestamp`) VALUES (1,'Product Name','ok','2018-11-17 09:45:00'),(2,'Other product name','ok','2018-11-17 09:45:00')
```

__Dialect:__ mysql
__Sequelize version:__ 4.38.0

**Comment by sushantdhiman** [comment] 2018-11-17 13:30
Duplicate of https://github.com/sequelize/sequelize/issues/3277

**Closed by sushantdhiman** 2018-11-17 13:30 UTC

**Comment by antony** [comment] 2018-11-17 15:55
@sushantdhiman good spot - ta!
