### ISSUE TITLE
dataTypes.ENUM crash

### ISSUE THREAD

**Issue by 11000100111000** [sequelize/sequelize#8209] opened 2017-08-27 13:38 UTC
## What you are doing?

Trying to create a model utilizing an enumeration with the following code
```js
export default function (sequelize, dataTypes) {
    let User = sequelize.define<UserInstance, UserAttributes>("User", {
        type: {type: dataTypes.ENUM("customer", "administrator"), allowNull: false},
    }, {
        indexes: [],
        classMethods: {},
        timestamps: false
    });

    return User;
}

```

## What do you expect to happen?
I expect the sync function to not crash while creating the database entries.
## What is actually happening?
>Unhandled rejection TypeError: Cannot read property '0' of undefined
    at query.catch.then.then.queryResult (node_modules\sequelize\lib\dialects\postgres\query.js:115:25)

The issue gets resolved after modifying line 115 of "sequelize\lib\dialects\postgres\query.js"
from
```js
if (rows[0] && rows[0].sequelize_caught_exception !== undefined) {
```
to
```js
if (rows && rows[0] && rows[0].sequelize_caught_exception !== undefined) {
```
Dialect: postgres 
Database version: 9.6.4
Sequelize version:4.7.5

**Comment by dancrumb** [comment] 2017-08-27 14:35
This is a duplicate of #8203 

For now, rollback your `pg` module to `6.4.2` and you'll be fine.

**Comment by holmberd** [comment] 2017-09-02 16:40
Please pin a note at the top of the readme stating that Sequelize is currently incompatible with pg - v7.0 to avoid duplicate issues.

**Comment by dancrumb** [comment] 2017-12-11 20:40
This should not be closed - as far as I can tell it has not been addressed.

**Comment by sushantdhiman** [comment] 2018-01-20 06:58
With `pg@7` any query using multiple statements is still not supported. Moving to main issue https://github.com/sequelize/sequelize/issues/8043

**Closed by sushantdhiman** 2018-01-20 06:58 UTC
