### ISSUE TITLE
Creating an array of enums with default value is failing

### ISSUE THREAD

**Issue by UdiBen** [sequelize/sequelize#17087] opened 2024-02-13 08:47 UTC
## Bug Description

I have the following migration:
```
const vals = ['a', 'b'];
module.exports = {
    up: async (queryInterface, Sequelize) => {
        await queryInterface.createTable('test', {
            field: { type: Sequelize.ARRAY(Sequelize.ENUM(vals)), allowNull: false, defaultValue: [] },
        });
    },
    down: async (queryInterface) => {}
}
```
Running this migration is failing with the following error:
ERROR: Cannot read properties of undefined (reading 'getTableName')

If I change the Array type to STRING, or remove the defaultValue - the migration passes.

### What do you expect to happen?

I expect the table to be created 

### What is actually happening?

ERROR: Cannot read properties of undefined (reading 'getTableName')

### Environment

*Indicate your interest in the resolution of this issue by adding the 👍 reaction. Comments such as "+1" will be removed.*

**Comment by WikiRik** [comment] 2024-02-13 08:50
Duplicate of https://github.com/sequelize/sequelize/issues/11285

**Closed by WikiRik** 2024-02-13 08:50 UTC
Labels: type: bug, pending-approval
