### ISSUE TITLE
Bulk update updatedAt

### ISSUE THREAD

**Issue by binarymee** [sequelize/sequelize#11340] opened 2019-08-20 13:37 UTC
I am trying to set updatedAt manually for bulkRecords, since I am relying on it to show some information.

```
await MyModel.update({
  updatedAt: new Date(),
}, {
  where: {
    id: [1,2,3,4,5],
  },
});
```
The expectation is, it will update updatedAt for all the records that match the condition. But it is not happening.

On debugging I found this line
https://github.com/sequelize/sequelize/blob/master/lib/model.js#L3207-L3212
If there are no other field changes and the value array has only updatedAt it will be ignored.

So I don't think there is a way to do now. Is there any reason for not handling this?

**Comment by papb** [comment] 2019-08-21 01:51
Duplicate of #11183

**Closed by papb** 2019-08-21 01:51 UTC
