### ISSUE TITLE
sqlite3: modifying existing table's column overwrites constraint settings, and does not allow adding unique constraint to multiple columns using queryInterface.changeColumn

### ISSUE THREAD

**Issue by dyc3** [sequelize/sequelize#12415] opened 2020-06-23 21:56 UTC
### What are you doing?

**Here is the link to the SSCCE for this issue:** https://github.com/papb/sequelize-sscce/pull/86

I have a preexisting table that I'm modifying with migrations. When the table was initially created, it had unique constraints on 2 different columns. After the first migration, neither of the columns had the unique constraint applied. After the second migration, only 1 of the columns had the unique constraint.

### What do you expect to happen?

changeColumn should merge new settings into existing settings for the table. More than 1 unique constraint should be allowed to exist.

### What is actually happening?

See SSCCE

### Additional context

I have been debugging this for 3 days and my morale is very low. :(

### Environment

- Sequelize version: 5.21.4
- Node.js version: v10.15.3
- Operating System: Ubuntu 18.04

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [x] I think this problem happens only for the following dialect(s): sqlite3
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment] 2020-06-24 04:51
Duplicate of https://github.com/sequelize/sequelize/issues/7078

**Closed by sushantdhiman** 2020-06-24 04:51 UTC

**Comment by sushantdhiman** [comment] 2020-06-24 04:56
Thanks for good SSCCE. If you want to fix this, you can start by looking at 

1. [`QueryInterface.changeColumn`](https://github.com/sequelize/sequelize/blob/663261bf0ee122ba7581ea9df5cba141435395fc/lib/dialects/sqlite/query-interface.js#L38), See if `describeQuery` is returning constraints properly.
2. [`removeColumnQuery`](https://github.com/sequelize/sequelize/blob/663261bf0ee122ba7581ea9df5cba141435395fc/lib/dialects/sqlite/query-generator.js#L347) could be the issue
3. You can add tests [here](https://github.com/sequelize/sequelize/blob/master/test/integration/query-interface/changeColumn.test.js)
