### ISSUE TITLE
Postgres: Schema does not default to the current schema when using queryInterface methods like addColumn, removeColumn, sequelize.query, etc, 

### ISSUE THREAD

**Issue by OmarDer** [sequelize/sequelize#11742] opened 2019-12-12 13:41 UTC
### What are you doing?

I want to store all of my tables in custom DB schema. I am using **Postgres** database and I have set this configuration:
```
config: {
     database: 'mydb',
     username: 'username',
     password: 'password',
     dialect: 'postgres',
     host: 'host',
     port: 'port',
     migrationStorageTableName: 'TableMeta',
     seederStorage: 'sequelize',
     seederStorageTableName: 'TableData',
     migrationStorageTableSchema: 'custom',
     seederStorageTableSchema: 'custom',
     schema: 'custom',
     searchPath: 'custom',
     dialectOptions: {
        prependSearchPath: true
     }
}
```
While running migrations 'custom' schema is used only when creating a table and table is created under this 'custom' schema.

```
queryInterface.createTable('MyTable', {
  id: {
    allowNull: false,
    primaryKey: true,
    type: Sequelize.INTEGER
  },
  name: {
    allowNull: false,
    type: Sequelize.STRING
  }
})
```
However, when I use methods like **_'addColumn', 'removeColumn'_** or even use **_raw_** queries it looks like this 'custom' schema is not read from my config and it always searches for tables in the 'public' schema, which causes errors. 

Is there any way to read the schema from config instead of passing it explicitly on each call of these methods (**_addColumn_**, **_removeColumn_**, **_raw_** query,... )

```
queryInterface.addColumn(
      'MyTable',
      'newColumn',
      { type: Sequelize.BOOLEAN }
    );
```

### What do you expect to happen?

I expect that all methods will read schema from config.

### What is actually happening?
```
ERROR: relation "public.MyTable" does not exist
```

### Environment

- Sequelize version: 5.18.4
- Node.js version: 10

**Comment by papb** [comment] 2020-01-16 05:17
Looks like a duplicate of #11634 

If I'm mistaken let me know and I will reopen this

**Closed by papb** 2020-01-16 05:17 UTC

**Comment by miketeix** [comment] 2020-02-06 21:32
👍 same here

**Comment by PanopticaRising** [comment] 2021-05-19 18:35
This PR should address this by shortcutting the missing `options` in addColumn, etc.

https://github.com/sequelize/sequelize/pull/13045

**Comment by hrabizadeh-acceptto** [comment] 2023-02-23 20:09
> Just a quick note. I spent ages looking for how to specify the schema in an addColumn migration. This issue was the closest that I came to it, but the PR above (at the time of writing) has not been merged.
> 
> I took a look at the source code and found that instead of using the documented syntax of:
> 
> ```js
> await queryInterface.addColumn('nameOfAnExistingTable', 'nameOfTheNewAttribute', DataTypes.STRING);
> ```
> 
> there is an alternative syntax that allows for specifying the schema as follows:
> 
> ```js
> await queryInterface.addColumn(
>     { tableName: 'nameOfAnExistingTable', schema: 'nameOfSchema' },
>     'nameOfTheNewAttribute',
>     DataTypes.STRING
>   );
> ```
> 
> I have implemented this in my migration and it works fine, and also for removeColumn.
> 
> The above examples are taken from the file ``sequelize\types\test\query-interface.ts```
> 
> It should be noted that here I am referring to version 6.7.0. Upgrading to v6 caused some problems (e.g. the import method has gone), but actually easily fixed.
> 
> I hope this saves someone some time.

It seems these approach is not working for all `queryInterfaces` for example I try to fix the `relation "xxx" does not exist in the following query interface and it didn't work:

`return queryInterface.bulkDelete(
      "tablename",
      {},
      { truncate: true },
    { tableName: 'tablename', schema: process.env.DEFAULT_DB_SCHEMA });`

**Comment by ephys** [comment] 2023-03-02 21:21
In `bulkDelete`, the first parameter is the table, not the fourth. The fourth parameter is an optional model

```ts
return queryInterface.bulkDelete(
  { tableName: 'tablename', schema: process.env.DEFAULT_DB_SCHEMA }, 
  {}, 
  { truncate: true },
);
```
