### ISSUE TITLE
set methods for associations (bool option to delete if you want)

### ISSUE THREAD

**Issue by bloodhawk** [sequelize/sequelize#4275] opened 2015-08-06 22:05 UTC
I notice with the set methods for associations it does not delete old rows. It sets the rows foreign key to null and creates a new one. This is desirable in some cases, but in others you simply want the old rows to delete. Would it be easy to add an option into the set methods to accommodate that?

**Comment by janmeier** [comment] 2015-08-07 07:28
Duplicate of https://github.com/sequelize/sequelize/issues/3298

**Closed by janmeier** 2015-08-07 07:28 UTC
