### ISSUE TITLE
MSSQL. Error saving number value bigger than 2147483647

### ISSUE THREAD

**Issue by bparan** [sequelize/sequelize#11245] opened 2019-07-29 15:10 UTC
## What are you doing?

I'm trying to store a number that is bigger than 2147483647 as value of a column with BIGINT type.

```js
const sequelize = new Sequelize('sequelize_test', 'user', 'user', {
    host: 'localhost',
    dialect: 'mssql'
});

const User = sequelize.define('user', {
    business_id: {type: Sequelize.BIGINT, allowNull: false}
}, {
    freezeTableName: true,
    timestamps: false
});


await User.create({
    business_id: 2147483647 // Max value for Integer type
});

await User.create({
    business_id: 2147483648 // Max value for Integer type + 1. SequelizeDatabaseError: Validation failed for parameter '0'. Value must be between -2147483648 and 2147483647.
});

```
**To Reproduce**
1. Define a model with BIGINT type in database.
2. Use `Model.create` with a number bigger than 2147483647.
3. See error `SequelizeDatabaseError: Validation failed for parameter '0'. Value must be between -2147483648 and 2147483647.`

## What do you expect to happen?
JavaScript supports 64 bit numbers and I'd expect to save number that are bigger than 2147483647.

## What is actually happening?
I see an error `SequelizeDatabaseError: Validation failed for parameter '0'. Value must be between -2147483648 and 2147483647.`

## Environment
Dialect:
- [ ] mysql
- [ ] postgres
- [ ] sqlite
- [x] mssql
- [ ] any
Dialect **library** version: tedious 6.0.0
Database version: SQL Server 2017, 14.0.1000.169
Sequelize version: 5.9.1
Node Version: 10.13.0
OS: Windows 10
If TypeScript related: TypeScript version: XXX
Tested with latest release:
- [x] No
- [ ] Yes, specify that version: 

A simple project to demonstrate the issue https://github.com/bparan/mssql-bigint-sequelize.

**Comment by papb** [comment] 2019-07-29 15:58
Thank you very much for the detailed, reproducible issue!

Can you please test this with another dialect? This is important to know whether the problem is dialect-specific or not.

You can instantiate an in-memory SQLite instance very easily:

1. `npm install sqlite3`
2. `new Sequelize('sqlite::memory:')`

You can instantiate a local postgres instance very easily:

1. Run a local postgres
    * On windows: [PostgreSQLPortable_10.4.1.zip](https://github.com/garethflowers/postgresql-portable/releases/download/v10.4.1/PostgreSQLPortable_10.4.1.zip) (no need to install, just unzip and run)
        * Run the `.exe` and then `CREATE DATABASE testdb;` (don't close the `.exe`)
    * On linux (with docker): `docker pull postgres && docker run --rm --name pg -d -p 5432:5432 postgres`
        * Run `docker exec -t pg psql -U postgres -c 'CREATE DATABASE testdb;'`
2. `new Sequelize('postgres://postgres@localhost:5432/testdb')`

**Comment by bparan** [comment] 2019-07-29 16:47
Thanks for simple instructions for Sqlite and Postgres. 
Both dialects store a number bigger than 2147483647 without any issues.

I fixed this issue for mssql dialect by changing file lib/dialects/mssql/query.js, function `getSQLTypeFromJsType.` however I'm not sure that it's a good fix for the issue.

```
--- a/lib/dialects/mssql/query.js
+++ b/lib/dialects/mssql/query.js
@@ -19,7 +19,11 @@ class Query extends AbstractQuery {
     paramType.type = TYPES.NVarChar;
     if (typeof value === 'number') {
       if (Number.isInteger(value)) {
-        paramType.type = TYPES.Int;
+        if (value >= -2147483648 && value <= 2147483647) {
+          paramType.type = TYPES.Int;
+        } else {
+          paramType.type = TYPES.BigInt;
+        }
       } else {
         paramType.type = TYPES.Numeric;
         //Default to a reasonable numeric precision/scale pending more sophisticated logic
```

**Comment by papb** [comment] 2019-07-29 18:09
I think that fix is fine, if you add a test case to prevent regressions. Would you be willing to submit a PR?

**Comment by bparan** [comment] 2019-07-30 15:33
Submitted PR for this issue.

**Comment by sushantdhiman** [comment] 2019-07-30 16:52
Fixed by https://github.com/sequelize/sequelize/pull/11252

**Closed by sushantdhiman** 2019-07-30 16:52 UTC
Labels: dialect: mssql, status: wip, type: bug
