### ISSUE TITLE
Sequelize 2.0.0-rc4+ consumes field definitions

### ISSUE THREAD

**Issue by hacker112** [sequelize/sequelize#2851] opened 2015-01-07 09:26 UTC
After upgrading from 2.0.0-rc3, the definition of fields are modified so that the same instance of an object can not used to define a field.

See this example:
https://www.dropbox.com/s/ky7rerubc8i6pzj/consumed_fields.png?dl=0

My current workaround:
https://www.dropbox.com/s/f387659vbvdpvm4/Skärmklipp%202015-01-07%2010.16.26.png?dl=0

**Comment by mickhansen** [comment] 2015-01-08 18:19
Meh, can't use `_.cloneDeep` for this.

**Comment by mickhansen** [comment] 2015-01-10 14:37
Duplicate of #2771, closing this.

**Closed by mickhansen** 2015-01-10 14:37 UTC
Labels: bug
