### ISSUE TITLE
Bug or issue in transaction working

### ISSUE THREAD

**Issue by pavhov93** [sequelize/sequelize#9005] opened 2018-02-06 10:29 UTC
## What are you doing?
Hello, I'm open transaction for update, delete and bulk Create 

```js
const transaction = Core.models.seq.transaction({
	autocommit: true
});


product = await query(
	productData,
	{where, returning: true, individualHooks: true, transaction},
	'update'
);

await query(
	{
		where: {
			productId: where.product_id
		}
	},
	{returning: true, transaction},
	'destroy',
	'productDescription'
);

productDescription = await query(
	productDescription,
	{returning: true, transaction},
	'bulkCreate',
	'productDescription'
);
```

## What do you expect to happen?
I expect to complete transaction

## What is actually happening?

 UnhandledRejection: Cannot read property 'query' of undefined TypeError: Cannot read property 'query' of undefined
    at parameters.length.Promise (/path/to/Projects/Core/node_modules/sequelize/lib/dialects/postgres/query.js:65:54)
    at Query.run (/path/to/Projects/Core/node_modules/sequelize/lib/dialects/postgres/query.js:65:9)
    at Promise.try.then.connection (/path/to/Projects/Core/node_modules/sequelize/lib/sequelize.js:558:20)
From previous event:
    at retryParameters (/path/to/Projects/Core/node_modules/sequelize/lib/sequelize.js:555:8)
    at /path/to/Projects/Core/node_modules/retry-as-promised/index.js:39:21
    at retryAsPromised (/path/to/Projects/Core/node_modules/retry-as-promised/index.js:29:10)
    at Sequelize.query (/path/to/Projects/Core/node_modules/sequelize/lib/sequelize.js:454:12)
    at QueryInterface.select (/path/to/Projects/Core/node_modules/sequelize/lib/query-interface.js:1099:27)
    at Promise.try.then.then.then (/path/to/Projects/Core/node_modules/sequelize/lib/model.js:1598:34)
From previous event:
    at Function.findAll (/path/to/Projects/Core/node_modules/sequelize/lib/model.js:1595:8)
    at Promise.try.then.then (/path/to/Projects/Core/node_modules/sequelize/lib/model.js:2734:21)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Function.update (/path/to/Projects/Core/node_modules/sequelize/lib/model.js:2729:8)
    at query (/path/to/Projects/dashboard/modules/Catalog/Products/models/Products.js:2213:24)
    at update (/path/to/Projects/dashboard/modules/Catalog/Products/models/Products.js:1119:18)
    at <anonymous> 
  dashboard [ 'TypeError: Cannot read property \'uuid\' of undefined',
  dashboard   '    at Query.run (/path/to/Projects/Core/node_modules/sequelize/lib/dialects/postgres/query.js:74:55)',
  dashboard   '    at Promise.try.then.connection (/path/to/Projects/Core/node_modules/sequelize/lib/sequelize.js:558:20)',
  dashboard   'From previous event:',
  dashboard   '    at retryParameters (/path/to/Projects/Core/node_modules/sequelize/lib/sequelize.js:555:8)',
  dashboard   '    at /path/to/Projects/Core/node_modules/retry-as-promised/index.js:39:21',
  dashboard   '    at retryAsPromised (/path/to/Projects/Core/node_modules/retry-as-promised/index.js:29:10)',
  dashboard   '    at Sequelize.query (/path/to/Projects/Core/node_modules/sequelize/lib/sequelize.js:454:12)',
  dashboard   '    at QueryInterface.select (/path/to/Projects/Core/node_modules/sequelize/lib/query-interface.js:1099:27)',
  dashboard   '    at Promise.try.then.then.then (/path/to/Projects/Core/node_modules/sequelize/lib/model.js:1598:34)',
  dashboard   'From previous event:',
  dashboard   '    at Function.findAll (/path/to/Projects/Core/node_modules/sequelize/lib/model.js:1595:8)',
  dashboard   '    at Promise.try.then.then (/path/to/Projects/Core/node_modules/sequelize/lib/model.js:2734:21)',
  dashboard   '    at runCallback (timers.js:789:20)',
  dashboard   '    at tryOnImmediate (timers.js:751:5)',
  dashboard   '    at processImmediate [as _immediateCallback] (timers.js:722:5)',
  dashboard   'From previous event:',
  dashboard   '    at Function.update (/path/to/Projects/Core/node_modules/sequelize/lib/model.js:2729:8)',
  dashboard   '    at query (/path/to/Projects/dashboard/modules/Catalog/Products/models/Products.js:2213:24)',
  dashboard   '    at update (/path/to/Projects/dashboard/modules/Catalog/Products/models/Products.js:1119:18)',
  dashboard   '    at <anonymous>' ]  +3s

__Dialect:__ postgres
__Dialect version:__ ^7.4.1
__Database version:__ 10
__Sequelize version:__ ^4.32.7

**Comment by sushantdhiman** [comment] 2018-02-09 05:40
Duplicate of https://github.com/sequelize/sequelize/issues/8087

**Closed by sushantdhiman** 2018-02-09 05:40 UTC
