### ISSUE TITLE
Getting associations correct with underscored

### ISSUE THREAD

**Issue by Znarkus** [sequelize/sequelize#3260] opened 2015-03-03 15:39 UTC
Hi! Below is test code to replicate one of my issues. I'm having problems wrapping my head around how to get Sequelize to fully work with underscored names.

```javascript
var Sequelize = require('sequelize');
var sequelize = new Sequelize('mysql://root@127.0.0.1/test', {
    define: {
        freezeTableName: true,
        underscoredAll: true,
        underscored: true,
        createdAt: 'created_date',
        updatedAt: 'updated_date',
        deletedAt: 'deleted_date'
    }
});

var Person = sequelize.define('person', {
    first_name: Sequelize.STRING,
    last_name: Sequelize.STRING
});

var Job = sequelize.define('job', {
    title: Sequelize.STRING,
    description: Sequelize.STRING
});

Job.belongsTo(Person, { as: 'ResponsiblePerson' });

sequelize
    .sync({ force: true })
    .then(function() {
        return [
            Person.create({ first_name: 'Markus', last_name: 'Hedlund' }),
            Job.create({ title: 'Job', description: 'Description' })
        ];
    })
    .spread(function(person, job) {
        return job.setResponsiblePerson(person);
    })
    .then(function(job) {
        return Job.find({where: {id: job.id}, include: [{all: true, nested: true}]});
    })
    .then(function(job) {
        console.log(job.toJSON());
    });
```

This outputs:

```
{ id: 1,
  title: 'Job',
  description: 'Description',
  created_date: Tue Mar 03 2015 16:26:16 GMT+0100 (CET),
  updated_date: Tue Mar 03 2015 16:26:16 GMT+0100 (CET),
  responsible_person_id: 1,
  ResponsiblePerson: 
   { id: 1,
     first_name: 'Markus',
     last_name: 'Hedlund',
     created_date: Tue Mar 03 2015 16:26:16 GMT+0100 (CET),
     updated_date: Tue Mar 03 2015 16:26:16 GMT+0100 (CET) } }
```

I want `ResponsiblePerson` to be `responsible_person`. Is this possible? Thank you.

**Comment by mickhansen** [comment] 2015-03-03 18:08
You'd have to use `Job.belongsTo(Person, { as: 'responsible_person' }); `

**Comment by Znarkus** [comment] 2015-03-03 19:03
@mickhansen Thank you for the quick response. The problem with that is, it creates the function `setResponsible_person()` instead of `setResponsiblePerson()`.

**Comment by mickhansen** [comment] 2015-03-03 19:16
@Znarkus yes that is generally the tradeoff im afraid, although generally people prefer camel cased in their JSON so it usually works out.

**Comment by Znarkus** [comment] 2015-03-04 08:09
@mickhansen Would it not be possible to add `Utils._.camelizeIf(singular, this.target.options.underscored);` to this code in `node_modules/sequelize/lib/associations/belongs-to.js`:

```javascript
    // Get singular name, trying to uppercase the first letter, unless the model forbids it
    var singular = Utils.uppercaseFirst(this.options.name.singular);

    this.accessors = {
      get: 'get' + singular,
      set: 'set' + singular,
      create: 'create' + singular
    };
```

**Comment by janmeier** [comment] 2015-03-04 08:29
@Znarkus We had that at one point as far as I remember but it was recently removed. 

We try to permute the `as` part as little as possible to allow the user to specfiy what they want. I see the reasoning in your case, but we try to change `as` as little as possible in order to be predictable

**Comment by janmeier** [comment] 2015-03-24 14:44
Not a bug or feature request, closing

As mentioned, we try to refraing from changing the name as much as possible.

You could do `Job.Instance.prototype.setResponsible_person = .. ` etc. I realize this is not ideal but the behaviour in core won't change

**Closed by janmeier** 2015-03-24 14:44 UTC

**Comment by Znarkus** [comment] 2015-04-20 08:55
Is there anyway to see what association setter functions are available on a model?

**Comment by janmeier** [comment] 2015-04-20 11:07
The association adds the functions to `Model.Instance.prototype`

**Comment by diosney** [comment] 2015-09-25 18:18
+1 to the OP question.

Related https://github.com/sequelize/sequelize/issues/4570
