### ISSUE TITLE
Updating an Array field with the same data will show up as changed in Sequelize

### ISSUE THREAD

**Issue by gb-jlofton** [sequelize/sequelize#10007] opened 2018-10-08 18:59 UTC
## What are you doing?

I'm updating a pre existing record that has an array field.

The issue I have encountered is that doing an update on a record with fields that are array datatypes or JSON datatypes, it will show that the Array or JSON fields have been changed even if the current and previous values are the same. This seems to be the case for any array format or JSON format, arrays of strings/arrays/objects.

This could be any field that is of Array datatype, for this example I'm looking at the selected_indications field on this Study model.
```js
let Study = sequelize.define("Study", {
    ...
    selected_indications: {
      type: DataTypes.ARRAY(DataTypes.STRING),
      allowNull: true
    },
    ...
```

## What do you expect to happen?
When updating a record that has an Array datatype field with the previous data being the same as the current data I would expect there to not be a change listed for that field.

## What is actually happening?
When updating a record that has an Array datatype field with the previous data being the same as the current data I'm seeing a change listed for that field.

Using the sequelize built in methods looking at an instance of the study object in an audit the _changed shows that the selected_indications field has changed.
![screen shot 2018-10-08 at 11 35 07 am](https://user-images.githubusercontent.com/33907277/46627711-29f9d200-caf0-11e8-8597-6d60983334ee.png)

But looking at the current and previous values, they are both the same so I would expect this field to not show as changed like other data types in Sequelize.
![screen shot 2018-10-08 at 11 35 40 am](https://user-images.githubusercontent.com/33907277/46627712-29f9d200-caf0-11e8-9005-553939949096.png)
![screen shot 2018-10-08 at 11 36 00 am](https://user-images.githubusercontent.com/33907277/46627713-29f9d200-caf0-11e8-87c8-f37cfc196263.png)

__Dialect:__ postgres
__Dialect version:__ XXX
__Database version:__ 10.1
__Sequelize version:__ 4.39
__Tested with latest release:__ Yes

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment] 2018-10-10 05:08
Duplicate of https://github.com/sequelize/sequelize/issues/9880

Some related issues and discussions

- https://github.com/sequelize/sequelize/issues/8916
- https://github.com/sequelize/sequelize/pull/6505

**Closed by sushantdhiman** 2018-10-10 05:09 UTC
