### ISSUE TITLE
"Cannot read property 'options' of undefined" error in _paranoidClause when update query has include option

### ISSUE THREAD

**Issue by hallvors** [sequelize/sequelize#9755] opened 2018-08-02 08:20 UTC
## What are you doing?

```js
  var models = {foo: sequelize.define('foo', {
    state: {
      type: Sequelize.STRING,
      defaultValue: 'bad',
      validate: {
        isIn: [[
          'bad',
          'ok'
        ]]
      }
    }
  }),
  bar: sequelize.define('bar', {
    fooId: Sequelize.INTEGER
  })
};

models.bar.belongsTo(models.foo);
models.foo.hasMany(models.bar, {foreignKey: 'fooId'})

models.foo.update({state: 'ok'}, {where: {id: req.params.id}, returning: true, include: [models.bar]}
```

## What do you expect to happen?
Data of foo and bar returned from the completed update query.

## What is actually happening?
An error is thrown inside sequelize code. Seems using include in an update query runs into some code that wasn't tested with this pattern?

```
Unhandled rejection TypeError: Cannot read property 'options' of undefined
    at Function._paranoidClause (./node_modules/sequelize/lib/model.js:72:16)
    at Function._paranoidClause (./node_modules/sequelize/lib/model.js:60:14)
    at Function.update (./node_modules/sequelize/lib/model.js:2679:20)
```

__Dialect:__ postgres
__Sequelize version:__ 
├─ sequelize-cli@4.0.0
└─ sequelize@4.38.0
__Tested with latest release:__ Yes

**Comment by sushantdhiman** [comment] 2018-08-10 04:41
Duplicate of #9516

**Closed by sushantdhiman** 2018-08-10 04:41 UTC
