### ISSUE TITLE
beforeCreate not called before value validation

### ISSUE THREAD

**Issue by ahsan98** [sequelize/sequelize#12362] opened 2020-06-10 04:48 UTC
### What are you doing?
I am trying to generate a non null value in beforeCreate.

```js
const QueueItem = sequelize.define('QueueItem', {
    id: {
      type: DataTypes.BIGINT,
      allowNull: false,
      primaryKey: true,
      autoIncrement: true,
    },
    ref: {
      type: DataTypes.INTEGER,
      allowNull: false
    }
  },
  {
    tableName: 'queue_item',
    underscored: true,
  });

QueueItem.belongsTo(models.Store, {
  onDelete: 'CASCADE',
  foreignKey: {
    allowNull: false
  },
}),
QueueItem.belongsTo(models.User, {
   onDelete: 'CASCADE',
   foreignKey: {
     allowNull: false
    },
})
QueueItem.belongsTo(models.AgentSession, {
  onDelete: 'SET NULL',
  foreignKey: {
     name: 'serverId',
      allowNull: true,
   },
    as: 'server'
})
```
I have defined a beforeCreate hook to auto calculate ref
```js
QueueItem.beforeCreate((item, options) => {
    return new Promise(async (resolve, reject) => {
      const store = await sequelize.models.Store.findOne({ where: { id: item.StoreId } });
      const openStatus = await store.isOpen(true);
      if (!item.ref) {
        const lastItem = await QueueItem.findOne({ where: { createdAt: { [Op.gte]: openStatus.lastOpenTime } }, order: [['ref', 'DESC']] });
        
        item.ref = lastItem ? (lastItem.ref + 1) : 1;
      }

      resolve()
    });
```

When trying to create object as:
```js
QueueItem.create(data).then(() => console.log('item created'))
```
However I get an exception that ref cannot be null

### What do you expect to happen?

The queueItem should have been created successfully as ref is being defined in hook

### What is actually happening?

Sequelize raised an exception stating
```
QueueItem.ref cannot be null
```
If I remove allowNull: false from the ref column it works as expected and a value for ref is appropriately generated.

### Environment

- Sequelize version: 5.21.7
- Node.js version: 12.6.0
- Operating System: MacOS Catalina 10.15.4
- If TypeScript related: Not typescript related

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment] 2020-06-11 05:56
This is correct behavior, validation occur before `beforeCreate` hooks. You can check order of hooks [here](https://sequelize.org/master/manual/hooks.html)

**Comment by sushantdhiman** [comment] 2020-06-11 05:57
Duplicate of https://github.com/sequelize/sequelize/issues/5490

**Closed by sushantdhiman** 2020-06-11 05:56 UTC
