### ISSUE TITLE
beforeValidate Hook Does Not Allow Modification of DataValues

### ISSUE THREAD

**Issue by corim707** [sequelize/sequelize#9930] opened 2018-09-17 18:23 UTC
## What are you doing?
Updating a field as part of the beforeValidate hook per http://docs.sequelizejs.com/manual/tutorial/hooks.html#declaring-hooks

```js
const User = sequelize.define('user', {
	userId: { field: 'user_id', type: Sequelize.INTEGER, primaryKey: true, autoIncrement: true },
	userName: { field: 'user_name', type: Sequelize.STRING },
	lastValidatedDate: { field: 'last_validated_date', type: Sequelize.DATE}
},
{
	createdAt: 'created_at',
	updatedAt: 'updated_at'
});

User.hook('beforeValidate', function(user, options) {
	user.lastValidatedDate = new Date();
});

const newUser = new User({ userName: 'someGuy'} );
await newUser.save();
assert.ok( newUser.lastValidatedDate );

const userFromDatabase = await User.findOne({ where: { userName: 'someGuy' } });
assert.ok( userFromDatabase.lastValidatedDate );
const lastValidatedDate = userFromDatabase.lastValidatedDate;

userFromDatabase.userName = 'changedUserName';
await userFromDatabase.save();
const updatedLastValidatedDate = userFromDatabase.lastValidatedDate;
assert.notStrictEqual( updatedLastValidatedDate.getTime(), lastValidatedDate.getTime() );

const postChange = await await User.findOne({ where: { userName: 'changedUserName' } });
assert.strictEqual( lastValidatedDate.getTime(), postChange.lastValidatedDate.getTime() ); //Should not be equal to the original date
assert.notStrictEqual( updatedLastValidatedDate.getTime(), postChange.lastValidatedDate.getTime() ); //Should be equal
```

## What do you expect to happen?
_I wanted lastValidatedDate to update per http://docs.sequelizejs.com/manual/tutorial/hooks.html#declaring-hooks_

## What is actually happening?
_lastValidatedDate does not update_

_Output, either JSON or SQL_
Executing (default): INSERT INTO "users" ("user_id","user_name","last_validated_date","created_at","updated_at") VALUES (DEFAULT,'someGuy','2018-09-17 18:15:47.776 +00:00','2018-09-17 18:15:47.773 +00:00','2018-09-17 18:15:47.773 +00:00') RETURNING *;
Executing (default): SELECT "user_id" AS "userId", "user_name" AS "userName", "last_validated_date" AS "lastValidatedDate", "created_at", "updated_at" FROM "users" AS "user" WHERE "user"."user_name" = 'someGuy' LIMIT 1;
Executing (default): UPDATE "users" SET "user_name"='changedUserName',"updated_at"='2018-09-17 18:15:47.838 +00:00' WHERE "user_id" = 3
Executing (default): SELECT "user_id" AS "userId", "user_name" AS "userName", "last_validated_date" AS "lastValidatedDate", "created_at", "updated_at" FROM "users" AS "user" WHERE "user"."user_name" = 'changedUserName' LIMIT 1;

__Dialect:__ postgres
__Dialect version:__ 6.1.0
__Database version:__ 9.5
__Sequelize version:__ 4.38.1
__Tested with latest release:__ Yes (If yes, specify that version)

**Comment by sushantdhiman** [comment] 2018-09-18 06:45
Duplicate of https://github.com/sequelize/sequelize/issues/8586

**Closed by sushantdhiman** 2018-09-18 06:45 UTC
