### ISSUE TITLE
Support for Deno

### ISSUE THREAD

**Issue by hashemisa** [sequelize/sequelize#13176] opened 2021-04-08 08:45 UTC
#This issue is relevant to Sequelize as a whole.

#Deno is a simple, modern and secure runtime for JavaScript and TypeScript that uses V8 and is built in Rust.

##Ships only a single executable file
Deni v1.8.3 released:
https://github.com/denoland/deno/releases

##Announcing the Deno Company | Ryan Dahl

https://deno.com/blog/the-deno-company

##Example:

Few existing web frameworks supporting Deno are:

https://deno.land/x/typeorm@v0.2.23-rc10/docs/sequelize-migration.md

**Comment by Keimeno** [comment] 2021-04-08 09:26
Duplicate of https://github.com/sequelize/sequelize/issues/12836

**Closed** 2021-06-15 10:02 UTC
