### ISSUE TITLE
any way to define custom error message for composite unique?

### ISSUE THREAD

**Issue by guoerwei** [sequelize/sequelize#11164] opened 2019-07-08 10:59 UTC
**Is your feature request related to a problem? Please describe.**

```javascript
class FolderFilesModel extends Sequelize.Model{}
FolderFilesModel.init(
  {
    folderName: {
      type: Sequelize.STRING,
      allowNull: false
    },
    fileName: {
      type: Sequelize.INTEGER.UNSINGED,
      allowNull: false
    },
    testUniqueKey: {
      type: Sequelize.STRING,
      allowNull: false,
      unique: {
        name: 'u_uk',
        msg: 'custom error message works fine here, but i want the composite one'
      }
    },
    // ...other fields
  },
  {
    sequelize: instance,
    modelName: "folder_file",
    indexes: [
      {
        name: 'u_folder_file',
        unique: true,
        fields: ['folderName', 'fileName'],
        msg: 'can i define custom error message here or somewhere'
      }
    ]
  }
);
```

any way to define custom error message for composite unique?

**Comment by papb** [comment] 2019-08-22 00:23
Duplicate of #7395

**Closed by papb** 2019-08-22 00:23 UTC
Labels: question, status: awaiting investigation, type: docs
