### ISSUE TITLE
Promise warnings (postgres)

### ISSUE THREAD

**Issue by AlexNasonov** [sequelize/sequelize#5100] opened 2015-12-24 12:56 UTC
There are still some `Warning: a promise was created in a handler but was not returned from it`.
For example, I get one in `model.findById(id)` using postgres:
```
Warning: a promise was created in a handler but was not returned from it
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Model.findAll (d:\Users\Alexey\Documents\#Development\marvin\node_modules\sequelize\lib\model.js:1329:18)
    at Model.findOne (d:\Users\Alexey\Documents\#Development\marvin\node_modules\sequelize\lib\model.js:1490:34)
    at Model.findById (d:\Users\Alexey\Documents\#Development\marvin\node_modules\sequelize\lib\model.js:1459:34)
    at d:\Users\Alexey\Documents\#Development\marvin\routes\auth.js:14:10
```

**Comment by silentcoast** [comment] 2015-12-24 21:15
I dont think this is directly related to postgres as I am also getting this with MySQL when trying to save. The closest version without the issue is 3.13.0.

**Comment by maleeb** [comment] 2015-12-26 11:42
a bluebird bug?
https://github.com/petkaantonov/bluebird/issues/846
https://github.com/angular-fullstack/generator-angular-fullstack/issues/1507

I updatet bluebird to 3.1.1 but have the same issue.

**Comment by mickhansen** [comment] 2015-12-27 07:44
@maleeb Likely not a bluebird error. Either issues with sequelize internals or user implemented code.

**Comment by oherman1** [comment] 2016-01-03 18:43
getting the same error when calling findOrCreate with MySQL

**Comment by fredericlefeurmou** [comment] 2016-01-04 18:07
Same error with findById using Postgres

**Comment by ilaif** [comment] 2016-01-06 23:17
getting the same error when calling findAll with MySQL

**Comment by macneib** [comment] 2016-01-12 04:54
an error?  or warning?  I'm just seeing a warning.

**Comment by ebrian** [comment] 2016-01-15 01:04
They are warnings and many of them don't appear to be accurate. I can reproduce it on a simple `findOne` which I'm positive isn't missing a return value.

Unless I don't understand the error.

In any case, it's terrorizing my logs and I must downgrade for now.

**Comment by mickhansen** [comment] 2016-01-15 06:31
/cc @ebrian 
A temporary workaround using a `BLUEBIRD_WARNINGS = 0` env var should also disable these warnings.

**Comment by ebrian** [comment] 2016-01-15 06:33
:+1: @mickhansen That's good to know, thanks.

**Comment by jocull** [comment] 2016-02-04 17:00
Happening for me as well. MySQL using Sequelize 3.18.0

```
Warning: a promise was created in a handler but was not returned from it
    at Model.findAll (/home/jocull/Documents/Projects/eventlink-api/node_modules/sequelize/lib/model.js:1341:18)
    at Model.findOne (/home/jocull/Documents/Projects/eventlink-api/node_modules/sequelize/lib/model.js:1502:34)
    at Model.findById (/home/jocull/Documents/Projects/eventlink-api/node_modules/sequelize/lib/model.js:1471:34)
```

**Comment by matomesc** [comment] 2016-02-05 02:54
Getting this as well with MySQL and Sequelize 3.19.1 when loading an associated model (has one) using `User.getProfile()`.

```
Warning: a promise was created in a handler but was not returned from it
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Model.findAll (/app/server/node_modules/sequelize/lib/model.js:1345:18)
    at Model.findOne (/app/server/node_modules/sequelize/lib/model.js:1505:34)
    at instancePrototype.(anonymous function) [as getProfile] (/app/server/node_modules/sequelize/lib/associations/has-one.js:166:18)
    <app stack>
```

**Comment by denisazevedo** [comment] 2016-04-16 16:34
This issue was discussed here too: https://github.com/sequelize/sequelize/issues/4883

Although there is no concrete answer there, this thread provides a workaround for this warning.

**Comment by janmeier** [comment] 2016-04-16 18:16
Closing this issue as we haven't seen any code to reproduce the issue - and without that it's hard to do anything about. Personally I haven't seen the error for quite some time in my code

**Closed by janmeier** 2016-04-16 18:16 UTC
