### ISSUE TITLE
upsert generates incorrect SQL when using a SQL literal as a default value

### ISSUE THREAD

**Issue by btmorex** [sequelize/sequelize#7631] opened 2017-05-12 21:27 UTC
## What you are doing?

I'm trying to use upsert with a SQL literal as a default value. Here's the model:

```js
module.exports = function (sequelize, DataTypes) {
  const Statistics = sequelize.define('Statistics', {
    date: {
      type: DataTypes.DATEONLY,
      defaultValue: sequelize.literal('CURRENT_DATE'),
      //defaultValue: DataTypes.NOW,
      allowNull: false,
      unique: 'uniqueDateTrack',
    },
    num_comments: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },
    num_downloads: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },
    num_plays: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },
    num_likes: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },
    num_reposts: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },
  }, {
    classMethods: {
      associate: function (db) {
        Statistics.belongsTo(db.Track, {
          onDelete: 'CASCADE',
          foreignKey: {
            allowNull: false,
            unique: 'uniqueDateTrack',
          },
        });
      },
    },
    freezeTableName: true,
    tableName: 'statistics',
    timestamps: false,
    underscored: true,
  });
  return Statistics;
};
```

The generated upsert looks like:

```sql
CREATE OR REPLACE FUNCTION pg_temp.sequelize_upsert() RETURNS integer AS $func$ BEGIN INSERT INTO "statistics" ("date","num_comments","num_downloads","num_plays","num_likes","num_reposts","track_id") VALUES (CURRENT_DATE,25,0,21337,926,165,295971540); RETURN 1; EXCEPTION WHEN unique_violation THEN UPDATE "statistics" SET "num_comments"=25,"num_downloads"=0,"num_plays"=21337,"num_likes"=926,"num_reposts"=165,"track_id"=295971540 WHERE ("id" IS NULL OR (CURRENT_DATE AND "track_id" = 295971540)); RETURN 2; END; $func$ LANGUAGE plpgsql; SELECT * FROM pg_temp.sequelize_upsert();
```

Notice that in the UPDATE section CURRENT_DATE is bare. It should be "date" = CURRENT_DATE. I get the following error when the unique constraint fails:

```
SequelizeBaseError: argument of AND must be type boolean, not type date
    at Query.formatError (/home/avery/dev/insight/node_modules/sequelize/lib/dialects/postgres/query.js:357:14)
    at Query.<anonymous> (/home/avery/dev/insight/node_modules/sequelize/lib/dialects/postgres/query.js:88:19)
    at emitOne (events.js:96:13)
    at Query.emit (events.js:191:7)
    at Query.handleError (/home/avery/dev/insight/node_modules/pg/lib/query.js:143:8)
    at Connection.<anonymous> (/home/avery/dev/insight/node_modules/pg/lib/client.js:180:26)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/home/avery/dev/insight/node_modules/pg/lib/connection.js:136:12)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:561:20)
```

__Dialect:__ postgres
__Database version:__ 9.6.2
__Sequelize version:__ 3.30.4

**Comment by ccemeraldeyes** [comment] 2019-09-04 19:12
This is still an issue as of version 5.18.0

**Comment by ccemeraldeyes** [comment] 2019-09-04 19:13
'UPDATE "candidate_applications" SET "user_id"=\'some-uuid\',"updated_at"=\'2019-09-04 19:03:07.718 +00:00\' WHERE (uuid_generate_v4() OR "user_id" = \'some-uuid\')',

**Comment by papb** [comment] 2019-09-05 12:32
Duplicate of #10710

**Closed by papb** 2019-09-05 12:32 UTC
