### ISSUE TITLE
large nesting returns wrong or partial data

### ISSUE THREAD

**Issue by sklyarov-ivan** [sequelize/sequelize#3257] opened 2015-03-03 06:12 UTC
version sequelize 2.0.3
 request like
````
    models.Customer.find({
        include: [{
          model:models.Offer,
          include: [{
            model:models.Product,
            include: [{
              model: models.Properties,
              include: [{
                model: models.PropertySegments
              }]
            }]
          }]
        }
          ],
        where:{user_id: params.id, criteria::params.criteria}
      })
````
relation OneToMany between each entity.

it returns nested objects with cut keys on lowest level
i.e.
````
 [{
    name_category_i: 'something'
}]
````
instead of
````
 [{
    name_category_independent: 'something'
}]
````
Also on lowest level returns only first element of set i.e. array with only 1 object instead of group of objects.

**Comment by mickhansen** [comment] 2015-03-03 08:33
Appears to be a duplicate of https://github.com/sequelize/sequelize/issues/2084 - otherwise let me know.

**Closed** 2015-03-03 08:41 UTC
