### ISSUE TITLE
Postgres raw queries fail when using IN operator with an array

### ISSUE THREAD

**Issue by keithrz** [sequelize/sequelize#4301] opened 2015-08-11 18:20 UTC
From issue #1436 

Here is a mocha-style test case:

```
'use strict';

var sequelize = require('sequelize');
var connString = 'postgresql://user:pass@host:port/dbname';

describe('Testing sequelize issue # 1436', function() {

    it('cannot take an array as a bind variable in a raw postgres query', function (done) {

        var queryText = 'SELECT foo_id from schema.table_of_foos ' +
            'where foo_id in (:fooIds)';

        var queryValues = {
            fooIds: [1, 2, 3, 4]
        };

        var seqDb = new sequelize(connString, {
            dialect: 'postgres',
            keepDefaultTimezone: true,
            logging: false
        });

        seqDb.query(queryText, null, {raw: true, replacements: queryValues})
            .then(function (result) {
                console.dir(result);
                done();
            },
            function (error) {
                console.error(error);
                done();
            });

    });
});
```
That produces an error like this:
```
{ [SequelizeDatabaseError: operator does not exist: integer = integer[]]
  name: 'SequelizeDatabaseError',
  message: 'operator does not exist: integer = integer[]',
  parent: 
   { [error: operator does not exist: integer = integer[]]
     name: 'error',
     length: 238,
     severity: 'ERROR',
     code: '42883',
     detail: undefined,
     hint: 'No operator matches the given name and argument type(s). You may need to add explicit type casts.',
     position: undefined,
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     file: '/path/to/src/pg/src/backend/parser/parse_oper.c',
     line: '814',
     routine: 'op_error',
     sql: 'SELECT foo_id from schema.table_of_foos where foo_id in (ARRAY[1,2,3,4])' },
  original: 
   { [error: operator does not exist: integer = integer[]]
     name: 'error',
     length: 238,
     severity: 'ERROR',
     code: '42883',
     detail: undefined,
     hint: 'No operator matches the given name and argument type(s). You may need to add explicit type casts.',
     position: undefined,
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     file: '/path/to/src/pg/src/backend/parser/parse_oper.c',
     line: '814',
     routine: 'op_error',
     sql: 'SELECT foo_id from schema.table_of_foos where foo_id in (ARRAY[1,2,3,4])' },
  sql: 'SELECT foo_id from schema.table_of_foos where foo_id in (ARRAY[1,2,3,4])' }
```

**Comment by sushantdhiman** [comment] 2016-06-17 09:51
@mickhansen @janmeier Duplicate of #3769

**Closed** 2016-06-17 14:15 UTC
Labels: bug
