### ISSUE TITLE
Remove ID for legacy databases.

### ISSUE THREAD

**Issue by yan-foto** [sequelize/sequelize#4032] opened 2015-06-29 16:43 UTC
I use sequelize with a legacy database, where none of the tables has the column `id` or any other column as the primary key. Since sequelize assumes by default that each table has a primary key called `id` and requests this column in all select queries, I have to explicitly remove it using `model.removeAttribute('id')`.

Are there any reasons why `id` cannot be removed just like `timestamps` using the config object? And if not, should I send a pull request to implement this feature?

**Comment by janmeier** [comment] 2015-06-29 17:04
Duplicate of https://github.com/sequelize/sequelize/issues/3142

Well, a lot of stuff would not work without a primary key - How can we do an update query, when we don't know what uniquely identifies the row?

You are welcome to take a stab at it, since this has been requested multiple times before, I just think the result would be a very crippled ORM :)

**Closed by janmeier** 2015-06-29 17:04 UTC

**Comment by yan-foto** [comment] 2015-06-30 07:27
@janmeier it would have been a very crippled ORM if we were to remove support for primary keys altogether :) But I absolutely see your point. Not knowing what you're doing would break the whole thing!
