### ISSUE TITLE
Validation for JSONB?

### ISSUE THREAD

**Issue by leemalmac** [sequelize/sequelize#5908] opened 2016-05-17 15:39 UTC
Is there a way to validate json, add required fields, datatypes?
If it is not implemented in Sequelize, can I add this as a plugin/ hook? I've googled for plugins, but have not found any valueable info.

I've seen similar issue which had been opened a year ago and still open.

__Dialect:__ postgres / 
__Database version:__ 9.5
__Sequelize version:__ latest

**Comment by janmeier** [comment] 2016-05-17 15:40
Duplicate of https://github.com/sequelize/sequelize/issues/3698

When an issue is still open, please direct your comments there instead of posting a new one. Maintainers are subscribed to all comments, so we will still see your comments on open issues

**Comment by janmeier** [comment] 2016-05-17 15:41
As for how to write plugins, see https://github.com/sequelize/sequelize/wiki/Add-ons-&-Plugins

**Closed by janmeier** 2016-05-17 15:40 UTC

**Comment by leemalmac** [comment] 2016-05-17 15:42
Got it, thanks!
