### ISSUE TITLE
Where statements involving joined tables

### ISSUE THREAD

**Issue by YP28** [sequelize/sequelize#4248] opened 2015-08-03 09:26 UTC
I'm not sure whether this is just not documented or not implemented at all, so my apologies if I'm missing something.

I think it should be able to create where statements involving joined tables on the main query when including nested models.

Example:
```javascript
Project.findAll({
    where: {
        active: true,
        $User: { 
            createdAt: {
                $gt: (new Date() - (3600 * 1000)
            }
        }
    },
    include: [
        User
    ]
}).then(function (projects) {
    console.log(projects);
});
```
Would output something like:
```
...WHERE Project.active = true AND User.createdAt > '0000-00-00 00:00:00';
```

The only thing close to this at this moment (unless I'm mistaken), is this:
```javascript
Project.findAll({
    where: {
        active: true
    },
    include: [
        { model: User, where: { createdAt: { $gt: (new Date() - (3600 * 1000) } } }
    ]
}).then(function (projects) {
    console.log(projects);
});
```
Outputs something like this:
```
... INNER JOIN Users as User on User.ProjectId=Project.id AND (User.createdAt > '0000-00-00 00:00:00')
WHERE Project.active = true;
```
But the queries are different and result in different returned rows.

(I'm having trouble with this in a more complex query and I tried to explain it in a simple way)

**Comment by YP28** [comment] 2015-08-03 14:11
Apparently, this was already discussed in #3095, and unfortunately, no one is working on it at the moment.

**Comment by janmeier** [comment] 2015-08-04 11:54
Closed, duplicate of https://github.com/sequelize/sequelize/issues/3095

**Comment by janmeier** [comment] 2015-08-04 11:54
@YP28 You are welcome to chime in on https://github.com/sequelize/sequelize/issues/3095 with API suggestions to resurrect the discussion :)

**Closed by janmeier** 2015-08-04 11:54 UTC
