### ISSUE TITLE
long identifiers are being truncated by Postgres

### ISSUE THREAD

**Issue by alekbarszczewski** [sequelize/sequelize#3209] opened 2015-02-24 08:18 UTC
```
"Category.CategoryAssociations.Post.Series.SeriesTranslations.slug" will be truncated to "Category.CategoryAssociations.Post.Series.SeriesTranslations.sl"
```

When identifier (`AS "{identifier}"`) is longer than 63 characters then it is truncated by Postgres and Sequelize does not "see" returned column values (for example. `sl` instead of `slug` like in example above). It would be nice if Sequelize could do something about it (mask/shorten identifiers if they are too long?). Or at least print some warning/error, because it is hard to find whats wrong.

Note that it is possible to increase 63 chars limit but it requires recompiling Postgres source so 99% DBs is just limited to 63 chars...

**Comment by mickhansen** [comment] 2015-02-24 08:47
Duplicate of https://github.com/sequelize/sequelize/issues/2084

**Closed by mickhansen** 2015-02-24 08:47 UTC
