### ISSUE TITLE
How to count where column is 1?

### ISSUE THREAD

**Issue by mllumiquinga194** [sequelize/sequelize#11309] opened 2019-08-12 03:49 UTC
to enter context. I have my table `'user_companies'` and the table `'user_company_views'`. In the table `'user_company_views'` I keep a record of each user that has seen that company.
To list a company, I want to check all existing records in `'user_company_views'` and get the statistics.
Within the table `'user_company_views'` I have the shares and likes columns, where the times that the user has shared my company and if he has marked my company as a favorite are recorded.
The statistic consists in adding the `'shares'` of all the records that my company has in `'user_company_views'` and in that same way counting all the `likes` that are (1 or true).
I am doing this with sequelize in this way.
   ```
 async searchAll(counter, pages, offset, limit) {
        const result = await this.repository.findAll({
            offset,
            limit,
            include: [
                {
                    model: UserCompanyViews,
                    attributes: [
                        [Sequelize.fn('SUM', Sequelize.col('userCompanyViews.user_company_share')), 'shares'],
                        [Sequelize.fn('COUNT', (Sequelize.where(Sequelize.col('userCompanyViews.user_company_like'), true))), 'likes']
                    ],
                    required: true
                },
            ],
            raw: true,
        });
```

But the result is not as expected since it counts all the likes and shares of all companies. Could you help me?

**Comment by papb** [comment] 2019-08-12 23:58
Can you please post:

1. What SQL query was generated by sequelize
2. What SQL query were you trying to get

**Comment by mllumiquinga194** [comment] 2019-08-13 00:10
I try to get this query

```
SELECT uc.id AS companyId,
(
	SELECT COALESCE(SUM(ucv.user_company_share),0) 
	FROM user_company_views ucv
	WHERE ucv.user_company_id = uc.id
) AS shares,
(
	SELECT COUNT(ucv.user_company_like)
	FROM user_company_views ucv
    WHERE ucv.user_company_id = uc.id AND ucv.user_company_like = true
) AS likes

FROM user_companies uc;
```

![image](https://user-images.githubusercontent.com/12899361/62906566-3d438280-bd3d-11e9-98d6-e50cff586079.png)

**Comment by papb** [comment] 2019-08-13 01:45
@mllumiquinga194 Thanks - can you post what SQL query was generated by sequelize?

**Comment by mllumiquinga194** [comment] 2019-08-13 02:01
![image](https://user-images.githubusercontent.com/12899361/62909826-2fe1c480-bd4c-11e9-8a62-6c474e5e40e6.png)

This is the generated query and in the image you can see the execution of that query in mysql.
```
  SELECT `UserCompanies`.*, `userCompanyViews`.`id` AS `userCompanyViews.id`, 
  SUM(`userCompanyViews`.`user_company_share`) AS `userCompanyViews.shares`, 
  COUNT(`userCompanyViews`.`user_company_like` = 1) AS `userCompanyViews.likes` 
  FROM (SELECT `UserCompanies`.`id` 
  FROM `user_companies` AS `UserCompanies` 
  WHERE ( SELECT `user_company_id` 
  FROM `user_company_views` AS `userCompanyViews` 
  WHERE (`userCompanyViews`.`user_company_id` = `UserCompanies`.`id` 
  AND `userCompanyViews`.`user_company_id` = `UserCompanies`.`id`) LIMIT 1 ) IS NOT NULL LIMIT 5, 5) 
  AS `UserCompanies` 
  INNER JOIN `user_company_views` AS `userCompanyViews` 
  ON `UserCompanies`.`id` = `userCompanyViews`.`user_company_id` 
  AND `userCompanyViews`.`user_company_id` = `UserCompanies`.`id`;
```

both the sum and the count is wrong. My intention is to generate the result of the image above .. Sorry if my English is bad, I do not speak English, I use GoogleTraductor

**Comment by papb** [comment] 2019-08-13 02:12
I see... I don't have time to help right now though... Could you please try [StackOverflow](https://stackoverflow.com/) instead (using the [sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js))? If you do, please post a link for it here.

I will close this for now because the issue tracker isn't really a place to be asking questions like this, as our contribution guidelines say. Sorry, good luck!

**Closed by papb** 2019-08-13 02:12 UTC
Labels: question, status: awaiting response

**Comment by mllumiquinga194** [comment] 2019-08-17 02:16
You asked me so many questions, I thought you would help me.
Now if I have a problem it can be a mistake in sequelize.

**Comment by papb** [comment] 2019-08-17 02:19
@mllumiquinga194 Can you provide a SSCCE/MCVE/reprex for your situation?

**Comment by mllumiquinga194** [comment] 2019-08-17 02:20
```
        const result = await this._productsServices.findAll({
            include: [
                {
                    attributes: [],
                    required: true,
                    model: UserCompanies,
                    include: [
                        {
                            attributes: [],
                            required: true,
                            model: Users,
                            include: [
                                {
                                    attributes: [],
                                    model: PlanTransactions,
                                    where: {
                                        planTransactionsActive: 1
                                    },
                                    include: [
                                        {
                                            attributes: [],
                                            model: Plans,
                                            where: {
                                                planProductsServicesSales: 1,
                                            },
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
            ],
        });
```

This query works perfectly for me, but when adding limit and offset and the query is damaged, I would like to know why this happens. It's strange, I just add limit and offset and my query stops working. What happens? something is wrong with sequelize .. can you help me?

**Comment by papb** [comment] 2019-08-17 02:24
You have posted a code snippet that shows the problem but is not entirely self-contained (i.e. I can't just copy-paste it and run it). Please provide a [SSCCE](http://sscce.org/) (also known as [MCVE/reprex](https://stackoverflow.com/help/minimal-reproducible-example)).

**Comment by mllumiquinga194** [comment] 2019-08-17 02:36
```
        const result = await this._productsServices.findAll({
            include: [
                {
                    attributes: [],
                    required: true,
                    model: UserCompanies,
                    include: [
                        {
                            attributes: [],
                            required: true,
                            model: Users,
                            include: [
                                {
                                    attributes: [],
                                    model: PlanTransactions,
                                    where: {
                                        planTransactionsActive: 1
                                    },
                                    include: [
                                        {
                                            attributes: [],
                                            model: Plans,
                                            where: {
                                                planProductsServicesSales: 1,
                                            },
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
            ],
            subQuery: false,
            limit, offset
        });
```

READY :+1:

**Comment by papb** [comment] 2019-08-17 02:56
Hello, that is not an SSCCE.
