### ISSUE TITLE
DataTypes.NOW cannot be set as defaultValue

### ISSUE THREAD

**Issue by marswong** [sequelize/sequelize#9363] opened 2018-04-27 02:21 UTC
## What are you doing?

define a model and set a model's `defaultValue` to `DataTypes.NOW`

```js
module.exports = (sequelize, DataTypes) => {
  const User = sequelize.define('User', {
    create_time: {
      type: DataTypes.DATE,
      allowNull: false,
      defaultValue: DataTypes.NOW,
    },
  }, {
    tableName: 'users',
    timestamps: false,
  });

  return User;
};
```

## What do you expect to happen?

the `defaultValue` should be set

## What is actually happening?

the `create_time` column has no `defaultValue`

```sql
Executing (default): CREATE TABLE IF NOT EXISTS `users` (`create_time` DATETIME NOT NULL) ENGINE=InnoDB;
```

__Dialect:__ mysql
__Dialect version:__ 1.5.3
__Database version:__ 5.7.21
__Sequelize version:__ 4.37.6
__Tested with latest release:__ 5.0.0-beta.3

**Comment by mrfoe7** [comment] 2018-04-29 19:50
@marswong man, use type _timestamps_.
**example:** const User = sequelize.define('User', {
    create_time: {
      type: "TIMESTAMP",
      allowNull: false,
    },
  }

**Comment by SimonSchick** [comment] 2018-04-29 20:01
@mrfoe7 no, just use `createdAt: 'create_time'` in `sequelize.define` to override the column name.

**Comment by mrfoe7** [comment] 2018-04-29 20:39
@SimonSchick i used my version and this variant is working on production without someone problems. But i don't known why, it is correctly 😄

**Comment by marswong** [comment] 2018-04-30 05:34
@SimonSchick @mrfoe7 thank you all:) both of your solutions can work fine. but were they just the tricks, or could we call it a **sequelize convention**? 'cause the problem is `sequelize` provides a `NOW` function for `CURRENT_TIMESTAMP`, right? but it cannot work at all.

**Comment by mrfoe7** [comment] 2018-05-01 11:00
@marswong If i am correct understood your question, it is not tricks:) I think, **sequilize** don't support native types someone of DBMS. http://docs.sequelizejs.com/manual/tutorial/models-definition.html
P.S. If you want find answer for you question, read code **sequelize**.

**Comment by marswong** [comment] 2018-05-01 11:46
@mrfoe7 
> I think, **sequilize** don't support native types someone of DBMS.

excuse me, i don't get your point. there is nothing to do with the **native types** of **DBMS**. `DataTypes.NOW` is used to generate `CURRENT_TIMESTAMP` and concated to be a raw sql. the [Model definition](http://docs.sequelizejs.com/manual/tutorial/models-definition.html) doc doesn't indicate `DataTypes.NOW`.

of course i did check the source code, or i wouldn't open this issue. the [toDefaultValue](https://github.com/sequelize/sequelize/blob/2752bf7a07013699dd4058581aef77c3d270df35/lib/utils.js#L302) is used to transform `defaultValue` and it seems the test case does'nt cover this situation.

**Comment by sushantdhiman** [comment] 2018-05-02 04:29
Due to some cross database limitations that I am not aware of `DataTypes.NOW` is not set as default value in actual column definition.

But regardless Sequelize will automatically populate current time for `NOW`

```js
const User = sequelize.define('User', {
  createTime: {
    type: Sequelize.DATE,
    allowNull: false,
    defaultValue: Sequelize.NOW
  },
}, {
  tableName: 'users',
  timestamps: false
});

User
  .sync({ force: true })
  .then(() => User.create({}))
  .then(user => console.log(user.toJSON()));

Executing (default): DROP TABLE IF EXISTS `users`;
Executing (default): CREATE TABLE IF NOT EXISTS `users` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `createTime` DATETIME NOT NULL);
Executing (default): PRAGMA INDEX_LIST(`users`)
Executing (default): INSERT INTO `users` (`id`,`createTime`) VALUES (NULL,'2018-05-02 04:17:49.871 +00:00');
{ createTime: 2018-05-02T04:17:49.871Z, id: 1 }

``` 

So as long as you are only using Sequelize for these operations it should pose no problem.

On other hand If you want to ensure default value at database level then `NOW` is indeed lacking in that regard. It should ideally be setting default value to current timestamp in column definition

Duplicate of https://github.com/sequelize/sequelize/issues/7603

**Closed by sushantdhiman** 2018-05-02 04:29 UTC
