### ISSUE TITLE
Accessing properties directly when querying with aggregation returns undefined

### ISSUE THREAD

**Issue by younowidan** [sequelize/sequelize#8118] opened 2017-08-14 15:50 UTC
## What you are doing?
When querying a table and using either `sequelize.literal` or `sequelize.fn` with aggregation the results properties are only accessible through `instance.get('field')` and when trying to access them directly `instance.field` the result is `undefined` this in contradiction to the docs [here](http://docs.sequelizejs.com/class/lib/model.js~Model.html) which describe how result instance properties can be accessed. When reading regular properties e.g. not using `sequelize.literal` or `sequelize.fn` it's working fine.

```js
UserCoins.findById(1234, {
   attributes: [
      'user_id',
      [sequelize.fn('SUM', sequelize.col('coins')), 'sum_coins'],
    ],
    group: ['user_id'],
}).then((result) => {
   console.log(result.user_id); // 1234
   console.log(result.sum_coins); // undefined
   console.log(result.get('sum_coins')); // 712371
});
```

## What do you expect to happen?
To be able to access 'sum_coins' directly -> `result.sum_coins` but that's returning `undefined` where `result.get('sum_coins')` is working

## What is actually happening?
`result.sum_coins` is `undefined`

__Dialect:__ mysql
__Database version:__ 5.6.10
__Sequelize version:__ 4.4.3

**Comment by ph55** [comment] 2018-10-25 15:13
Why closed, is it expected behaviour ?

**Comment by Aligertor** [comment] 2019-02-06 17:10
This Issue is still an issue.
There are Usecases where it is big pain to deal with this.

For example: I dont access the fields myself but pass the result of the query to some third party library that creates an API response automatically. In such a case i have to iterate over the result and "fix" every row before i can pass it.

**Comment by Aligertor** [comment] 2019-02-06 17:21
found a solution that works for me:
i added the raw option so i get plain objects
see: http://docs.sequelizejs.com/class/lib/model.js~Model.html#static-method-findAll

**Comment by ratulSharker** [comment] 2020-01-15 06:29
I am also facing this issue. Example query

```
FloorPlanTableModel.findOne({
		attributes: [
			[Sequelize.fn("MAX", Sequelize.literal("LENGTH(`svgId`)")), "maxLengthSVGId"]
		]
	})
.then(result => {
    console.log(result.maxLengthSVGId); // undefined.
})
```
Putting the `raw: true` option in the solves this issue (as @Aligertor mentioned). Is this the proper way to access values ?

**Comment by papb** [comment] 2020-01-19 19:20
Hi @ratulSharker can you try `result.get('maxLengthSVGId')` instead of `result.maxLengthSVGId`?

**Comment by papb** [comment] 2020-01-19 19:23
This looks very similar to #10699, I will close this one to keep track of everything in a single place (#10699)

**Closed by papb** 2020-01-19 19:23 UTC

**Comment by viraths** [comment] 2023-07-20 08:09
You have to use following to access the properties

`result.dataValues.sum_coins `
