### ISSUE TITLE
DatabaseError.stack property is missing message

### ISSUE THREAD

**Issue by mdouglass** [sequelize/sequelize#14408] opened 2022-04-17 20:15 UTC
## Issue Creation Checklist

- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

### SSCCE

**Here is the link to the SSCCE for this issue:** https://github.com/mdouglass/sequelize-sscce-error-stack

Note, I've demonstrated with sqlite in the sscce because the sscce infrastructure for MySQL does not work on an M1 Mac (`ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries`). But our actual problem is with MySQL.

### What do you expect to happen?

The DatabaseError.stack property has its first line as just `Error` rather than the JavaScript standard of `$error: $message`, e.g. `DatabaseError: SQLITE_ERROR: cannot start a transaction within a transaction`.

Actual:
```
Error
    at Database.<anonymous> (/Users/matthew/projects/sequelize-sscce-error-stack/node_modules/sequelize/src/dialects/sqlite/query.js:227:27)
    at /Users/matthew/projects/sequelize-sscce-error-stack/node_modules/sequelize/src/dialects/sqlite/query.js:225:50
    at new Promise (<anonymous>)
    at Query.run (/Users/matthew/projects/sequelize-sscce-error-stack/node_modules/sequelize/src/dialects/sqlite/query.js:225:12)
    at /Users/matthew/projects/sequelize-sscce-error-stack/node_modules/sequelize/src/sequelize.js:643:28
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SQLiteQueryInterface.startTransaction (/Users/matthew/projects/sequelize-sscce-error-stack/node_modules/sequelize/src/dialects/abstract/query-interface.js:1228:12)
    at async Transaction.begin (/Users/matthew/projects/sequelize-sscce-error-stack/node_modules/sequelize/src/transaction.js:154:7)
    at async Transaction.prepareEnvironment (/Users/matthew/projects/sequelize-sscce-error-stack/node_modules/sequelize/src/transaction.js:124:7)
    at async /Users/matthew/projects/sequelize-sscce-error-stack/node_modules/sequelize/src/sequelize.js:1112:9
```

Expected:
```
DatabaseError: SQLITE_ERROR: cannot start a transaction within a transaction
    at Database.<anonymous> (/Users/matthew/projects/sequelize-sscce-error-stack/node_modules/sequelize/src/dialects/sqlite/query.js:227:27)
    at /Users/matthew/projects/sequelize-sscce-error-stack/node_modules/sequelize/src/dialects/sqlite/query.js:225:50
    at new Promise (<anonymous>)
    at Query.run (/Users/matthew/projects/sequelize-sscce-error-stack/node_modules/sequelize/src/dialects/sqlite/query.js:225:12)
    at /Users/matthew/projects/sequelize-sscce-error-stack/node_modules/sequelize/src/sequelize.js:643:28
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SQLiteQueryInterface.startTransaction (/Users/matthew/projects/sequelize-sscce-error-stack/node_modules/sequelize/src/dialects/abstract/query-interface.js:1228:12)
    at async Transaction.begin (/Users/matthew/projects/sequelize-sscce-error-stack/node_modules/sequelize/src/transaction.js:154:7)
    at async Transaction.prepareEnvironment (/Users/matthew/projects/sequelize-sscce-error-stack/node_modules/sequelize/src/transaction.js:124:7)
    at async /Users/matthew/projects/sequelize-sscce-error-stack/node_modules/sequelize/src/sequelize.js:1112:9
```

### Additional context

This breaks our logging systems as unhandled errors log the `stack` property and no longer contain useful information describing the error.

### Environment
- Sequelize version: 6.19.0
- Node.js version: 16.31.1
- If TypeScript related: TypeScript version: 4.5.4 (but not TypeScript-related)
- Database & Version: MySQL 8.0.28 (but not MySQL-related)
- Connector library & Version: mysql2@2.3.3

## Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [X] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

The issue is caused in `DatabaseError` when it overwrites the `stack` property with the one provided in the `options.stack` parameter: https://github.com/sequelize/sequelize/blob/3f58554672c724d9e3dbd45264a16048ba847777/src/errors/database-error.ts#L42

The passed-in stack was created without a message eg. https://github.com/sequelize/sequelize/blob/3f58554672c724d9e3dbd45264a16048ba847777/src/dialects/mysql/query.js#L49

This pattern/issue repeats everywhere `options.stack` is passed to `DatabaseError`

**Comment by ephys** [comment] 2022-04-28 10:34
Sounds like this was caused by https://github.com/sequelize/sequelize/pull/13347

**Comment by mdouglass** [comment] 2022-05-13 01:50
Go away stale bot

**Comment by WikiRik** [comment] 2022-08-19 10:12
I'll close this issue, this bug will be tracked further in #14807

**Closed by WikiRik** 2022-08-19 10:12 UTC
Labels: type: bug
