### ISSUE TITLE
Help with a Maria DB/Sequelize API Issue.

### ISSUE THREAD

**Issue by Bloodmaster132** [sequelize/sequelize#14460] opened 2022-04-27 16:54 UTC
```
[    if (user.seller_id) {
      // User is a seller
      const sellerQuery = await Sellers.findAll({
        include: [
          { model: Cookies, as: 'cookies' },
          { model: Proxies, as: 'proxies' },
          { model: Limiteds, as: 'limiteds' },
          {
            model: Transactions,
            as: 'transactions',
            include: [{ model: User, as: 'buyer' }],
          },
        ],
        where: {
          id: user.seller_id,
        },
      });
      seller = sellerQuery[0];
    }](url)
```

This currently pulls all things in my Database with the seller_id and I need to exclude the reset_code from the Users Table. How would I do this?

**Comment by Bloodmaster132** [comment] 2022-04-27 16:59
I need to exclude 
`"reset_code":null,`

**Comment by ephys** [comment] 2022-04-27 19:39
Duplicate of https://github.com/sequelize/sequelize/issues/14341

**Closed by ephys** 2022-04-27 19:39 UTC
