### ISSUE TITLE
When soft deleting (paranoid: true) a table row, ON DELETE SET NULL does not operate correctly

### ISSUE THREAD

**Issue by craig-gordon** [sequelize/sequelize#10324] opened 2019-01-06 08:14 UTC
## What are you doing?
I imagine this issue has been addressed before but I could not find anything through extensive searching about paranoid delete set null specifically (I found some things about paranoid delete cascade but it was unclear to me if this is a planned feature or not.)

When paranoid is set to true, the foreign key in a child table's row is left untouched when the parent table's corresponding row is (soft) deleted. I will note, though, that the child table's eagerly loaded associations no longer feature the parent table row's data.

```js
const database = new Sequelize(/* options */, {
  define: {
    paranoid: true
  },
  /* other parameters */
});

const Player = database.define('player', {
  name: Sequelize.STRING
});

const User = database.define('user', {
  username: Sequelize.STRING
  password: Sequelize.STRING
});

User.belongsTo(Player);
Player.hasOne(User);
```

```js
let player, user;

Player.create({
  id: 1,
  name: 'Bob'
})
  .then(playerInstance => {
    player = playerInstance.get();
    return User.create({
      username: 'bobtheblob',
      password: 123
      playerId: player.id
    });
  })
  .then(userInstance => {
    user = userInstance.get();
    return player.destroy()
  })
  .then(destroyedCount => {
    console.log(destroyedCount) // 1
    return Promise.all([
      Player.findOne(where: {id: player.id, include: {all: true}),
      User.findOne(where: {id: user.id, include: {all: true})
    ]);
  })
  .then(([newPlayerInstance, newUserInstance]) => {
    console.log(newPlayerInstance) // null
    console.log(newUserInstance.get({plain: true}))
    // {
    //   username: 'bobtheblob',
    //   password: 123,
    //   playerId: 1   <--- would be 'null' with paranoid turned off
    //   player: null  <--- eagerly loaded data is now null, same as if paranoid was turned off
    // }
  })
```

## What do you expect to happen?
I would expect, in the above case, for playerId in the final .then block to equal null, in concordance with ON DELETE SET NULL. (I would also expect, when the "deleted_at" field in a soft deleted instance is set to null through restoration, for playerId or an equivalent foreign key to be restored to its original value.)

## What is actually happening?
playerId does not get set to null and instead stays at the same value.

__Dialect:__ postgres
__Dialect version:__ pg@^7.7.1 (also tested with pg@^7.4.3)
__Database version:__ 10.4 (AWS RDS Engine version)
__Sequelize version:__ 5.0.0-beta.15 (also tested with ^4.42.0)
__Tested with latest release:__ Yes

**Comment by craig-gordon** [comment] 2019-04-07 20:55
This is still an issue that I believe should be addressed.

Per the Sequelize docs: "All associations use CASCADE on update and SET NULL on delete, except for n:m, which also uses CASCADE on delete". It makes sense to me that soft delete should still trigger the default behavior here, but I believe that SET NULL for 1:m and CASCADE for n:m are both broken if soft delete is enabled.

**Comment by sushantdhiman** [comment] 2019-04-09 05:35
Duplicate of https://github.com/sequelize/sequelize/issues/2586

**Closed by sushantdhiman** 2019-04-09 05:35 UTC
