### ISSUE TITLE
data doesnt update

### ISSUE THREAD

**Issue by Bes-js** [sequelize/sequelize#17148] opened 2024-03-06 09:24 UTC
### Discussed in https://github.com/sequelize/sequelize/discussions/17147

<div type='discussions-op-text'>

<sup>Originally posted by **Bes-js** March  6, 2024</sup>
```js
                         var data = await this.model.findOne({ where: filter });
                                    if (!data) return
                                    if(field.includes(".")){
                                        var newValue = set(data.dataValues, field, update[key][field]);
                        
                                        if(!newValue) continue;
                                        var newField = field.split(".")[0];
                                       
                                        console.log(newValue[newField]);
                                        console.log(newField);
                                     
                                        await data.update({ [newField]: newValue[newField] });
                                    }else{
                                    await data.update({ [field]: update[key][field] });
                                    }
                                }
```
**newValue[newField]** = { zort: { kaka: 9 } }
**newField**= name
**newValue**= {id: 160094,yas: 6,ids: 22,name: { zort: { kaka: 7 } },kask: [ 1, 2, 3 ],createdAt: 2024-03-06T06:23:58.661Z,updatedAt: 2024-03-06T09:13:17.703Z}

but data doesnt update
There is no error in the code structure, it even updates the data returned from the console when I write it myself, but when I specify a parameter directly, there is no click.
</div>

**Comment by WikiRik** [comment] 2024-03-06 10:50
Closing this as it's the duplicate of the discussion

**Closed by WikiRik** 2024-03-06 10:50 UTC
Labels: pending-approval
