### ISSUE TITLE
Allow to order findAll() results by attribute on a join table

### ISSUE THREAD

**Issue by irvingswiftj** [sequelize/sequelize#3174] opened 2015-02-19 20:16 UTC
I would like to request that the API would allow me to order by an attribute in a custom join table.

i.e. 
Using the example in the documentation:
```
Project.belongsToMany(User, {through: 'UserProject'});
User.belongsToMany(Project, {through: 'UserProject'});
```
If table UserProject had an attribute or priority, I would like to be able to get results in a manner similar to this:
```
User.find(1).then(function(user) {
    user.getProjects({
        order: [sequelize.someNewFunctionName(UserProjects, "priority"), "DESC"]
    }).then(function(projects) {
        //hoping to get the user's projects with the highest priorities first
    })
} );
```

**Comment by janmeier** [comment] 2015-02-23 08:22
Duplicate of https://github.com/sequelize/sequelize/issues/3173

**Closed by janmeier** 2015-02-23 08:22 UTC
Labels: feature
