### ISSUE TITLE
Unhandled rejection TypeError: Cannot read property 'query' of undefined

### ISSUE THREAD

**Issue by gabegorelick** [sequelize/sequelize#9218] opened 2018-03-22 15:29 UTC
## What are you doing?
Still trying to reproduce, but I periodically see this error during `Resource Timeout` events:

```
Unhandled rejection TypeError: Cannot read property 'query' of undefined
    at parameters.length.Promise (/sequelize/lib/dialects/postgres/query.js:65:54)
    at Promise._execute (/sequelize/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/sequelize/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/sequelize/node_modules/bluebird/js/release/promise.js:79:10)
    at Query.run (/sequelize/lib/dialects/postgres/query.js:65:9)
    at Promise.try.then.connection (/sequelize/lib/sequelize.js:558:20)
    at tryCatcher (/sequelize/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/sequelize/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/sequelize/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/sequelize/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/sequelize/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/sequelize/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/sequelize/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

This is similar to #8087, but since a fix for that has been merged the error must come from a different source.

## What do you expect to happen?

No error

## What is actually happening?

Error

__Dialect:__ postgres
__Dialect version:__ 9.6
__Database version:__ 9.6
__Sequelize version:__ 4.37.4
__Tested with latest release:__ Yes

**Comment by gabegorelick** [comment] 2018-03-22 16:29
Tracked the issue down to this: https://github.com/sequelize/sequelize/blob/20cac7a15d2044cac9de9f33ec9b13ab349c5567/lib/sequelize.js#L552-L554

`options.transaction.connection` is `undefined` at this point, but transaction is not yet finished. After we return from this promise, `finished` is `rollback`. Could be a race condition?

Seems very similar to #8087, but I've confirmed I have the fix from #9051.

**Comment by sushantdhiman** [comment] 2018-03-23 07:18
Last I tried [my testcase](https://github.com/sequelize/sequelize/issues/8087#issuecomment-366141059) was still throwing that error with current fix, may be that test case represent your case as well

**Comment by itsmepetrov** [comment] 2018-04-25 14:41
Any updates?

**Comment by matthew-mackay-sw** [comment] 2018-05-15 04:49
I'm getting this issue on Sequelize version: 4.37.7
Anybody have any ideas on this?

**Comment by picq** [comment] 2018-06-04 13:38
This issue still exists, does anybody have a clue how fix it ?

**Comment by bjitfreelancing** [comment] 2018-07-28 18:43
Even I am facing same issue with "pg": "^7.4.3", "sequelize": "^4.37.7"

**Comment by hackhat** [comment] 2018-09-01 09:32
Still happening, any news?

**Comment by sushantdhiman** [comment] 2018-09-07 08:49
Resolved by https://github.com/sequelize/sequelize/pull/9879

Now you should see `ConnectionAcquireTimeoutError` when transaction is unable to acquire connection along with proper error `Transaction cannot be rolled back because it never started` when such transaction try to rollback

**Closed by sushantdhiman** 2018-09-07 08:49 UTC
Labels: bug

**Comment by soryy708** [comment] 2019-02-10 13:20
Somehow I got the same error by misusing transactions.
Here's code to reproduce:

    sequelize.transaction(async (transaction) => {
        models.File.create(fileInfo, {transaction: {transaction}});
    }

Note that the transaction is inside an unnecessary object.
Probably should _not_ be fixed by sequelize, but may be useful for people doing debugging.
