### ISSUE TITLE
Issues on m:n-relations with custom junction (unique violation constraint errors or setters not defined)

### ISSUE THREAD

**Issue by soletan** [sequelize/sequelize#4265] opened 2015-08-05 17:27 UTC
I'm trying to manage three models, say *Person*, *Place* and *Meeting*. Meetings are created on its own with every instance pointing to a person and a place. Basically this is a m:n-relation between *Person* and *Place* with *Meeting* being a custom junction model.

My testing script looks like this. It defines either model and their relations (though I expect to have a misunderstanding of how to define models in Sequelize) before creating a place, a person and two meetings with different dates, but both related to same person and place.

The following script has been run with Sequelize 3.5.1. It

```javascript
var db   = require( "sequelize" ),
    path = require( "path" );

var link = new db( "default", null, null, {
	dialect: "sqlite",
	storage: path.join( __dirname, "test.sqlite" )
} );

var Person = link.define( "Person", {
	uuid:   {
		type:          db.UUID,
		primaryKey:    true,
		defaultValue: db.UUIDV4
	},
	name: {
		type: db.STRING
	}
} );

var Place = link.define( "Place", {
	uuid:   {
		type:          db.UUID,
		primaryKey:    true,
		defaultValue: db.UUIDV4
	},
	name: {
		type: db.STRING
	}
} );

var Meeting = link.define( "Meeting", {
	uuid:    {
		type:          db.UUID,
		primaryKey:    true,
		defaultValue: db.UUIDV4
	},
	date: {
		type: db.DATEONLY,
		allowNull: true
	}
} );

Person.belongsToMany( Place, { through: Meeting, as: "Places" } );
Place.belongsToMany( Person, { through: Meeting, as: "People" } );

Meeting.belongsTo( Person );
Person.hasMany( Meeting );

Meeting.belongsTo( Place );
Place.hasMany( Meeting );

link.sync()
	.then( function() {
		return db.Promise.all( [
			Person.create( { name: "John Doe" } ),
			Place.create( { name: "Time Square" } )
		] );
	} )
	.spread( function( person, place ) {
		return link.transaction( function( t ) {
			return Meeting.create( {
				date: "2015-08-04"
			}, { transaction: t } )
				.then( function( meeting ) {
					return db.Promise.all( [
						meeting.setPerson( person, { transaction: t } ),
						meeting.setPlace( place, { transaction: t } )
					] );
				} );
		} )
			.then( function() {
				console.log( "got first appointment" );

				return link.transaction( function( t ) {
					return Meeting.create( {
						date: "2015-08-05"
					}, { transaction: t } )
						.then( function( meeting ) {
							return db.Promise.all( [
								meeting.setPerson( person, { transaction: t } ),
								meeting.setPlace( place, { transaction: t } )
							] );
						} );
				} )
			} )
			.then( function() {
				console.log( "got second appointment" );
			} );
	} )
	.catch( function( cause ) {
		console.dir( cause );
		console.log( cause.stack );
	} );
```

It's output looks like this:

```
Executing (default): CREATE TABLE IF NOT EXISTS `People` (`uuid` UUID PRIMARY KEY, `name` VARCHAR(255), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
Executing (default): PRAGMA INDEX_LIST(`People`)
Executing (default): PRAGMA INDEX_INFO(`sqlite_autoindex_People_1`)
Executing (default): CREATE TABLE IF NOT EXISTS `Places` (`uuid` UUID PRIMARY KEY, `name` VARCHAR(255), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
Executing (default): PRAGMA INDEX_LIST(`Places`)
Executing (default): PRAGMA INDEX_INFO(`sqlite_autoindex_Places_1`)
Executing (default): CREATE TABLE IF NOT EXISTS `Meetings` (`uuid` UUID PRIMARY KEY, `date` DATE, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `PersonUuid` UUID REFERENCES `People` (`uuid`) ON DELETE CASCADE ON UPDATE CASCADE, `PlaceUuid` UUID REFERENCES `Places` (`uuid`) ON DELETE CASCADE ON UPDATE CASCADE, UNIQUE (PersonUuid, PlaceUuid));
Executing (default): PRAGMA INDEX_LIST(`Meetings`)
Executing (default): PRAGMA INDEX_INFO(`sqlite_autoindex_Meetings_1`)
Executing (default): PRAGMA INDEX_INFO(`sqlite_autoindex_Meetings_2`)
Executing (default): INSERT INTO `People` (`uuid`,`name`,`updatedAt`,`createdAt`) VALUES ('5910bc80-7119-4307-9208-d89f3cb2067b','John Doe','2015-08-05 17:08:36.807 +00:00','2015-08-05 17:08:36.807 +00:00');
Executing (default): INSERT INTO `Places` (`uuid`,`name`,`updatedAt`,`createdAt`) VALUES ('71dfd773-e399-44a7-a64c-900d65f25742','Time Square','2015-08-05 17:08:36.815 +00:00','2015-08-05 17:08:36.815 +00:00');
Executing (aa2239f4-8e45-4264-8c7a-ea2ce8449106): BEGIN TRANSACTION;
Executing (aa2239f4-8e45-4264-8c7a-ea2ce8449106): -- SQLite is not able to choose the isolation level REPEATABLE READ.
Executing (aa2239f4-8e45-4264-8c7a-ea2ce8449106): -- SQLite does not support SET autocommit.
Executing (aa2239f4-8e45-4264-8c7a-ea2ce8449106): INSERT INTO `Meetings` (`uuid`,`date`,`updatedAt`,`createdAt`) VALUES ('6d0877c0-94eb-4bef-b4e4-b44a7778197d','2015-08-04','2015-08-05 17:08:36.886 +00:00','2015-08-05 17:08:36.886 +00:00');
Executing (aa2239f4-8e45-4264-8c7a-ea2ce8449106): UPDATE `Meetings` SET `PersonUuid`='5910bc80-7119-4307-9208-d89f3cb2067b',`updatedAt`='2015-08-05 17:08:36.891 +00:00' WHERE `uuid` = '6d0877c0-94eb-4bef-b4e4-b44a7778197d'
Executing (aa2239f4-8e45-4264-8c7a-ea2ce8449106): UPDATE `Meetings` SET `PlaceUuid`='71dfd773-e399-44a7-a64c-900d65f25742',`updatedAt`='2015-08-05 17:08:36.893 +00:00' WHERE `uuid` = '6d0877c0-94eb-4bef-b4e4-b44a7778197d'
Executing (aa2239f4-8e45-4264-8c7a-ea2ce8449106): COMMIT;
got first appointment
Executing (11c364c8-fe92-4fc9-b798-3ea27ab1bee3): BEGIN TRANSACTION;
Executing (11c364c8-fe92-4fc9-b798-3ea27ab1bee3): -- SQLite is not able to choose the isolation level REPEATABLE READ.
Executing (11c364c8-fe92-4fc9-b798-3ea27ab1bee3): -- SQLite does not support SET autocommit.
Executing (11c364c8-fe92-4fc9-b798-3ea27ab1bee3): INSERT INTO `Meetings` (`uuid`,`date`,`updatedAt`,`createdAt`) VALUES ('e7c03a2a-dc72-4a55-8d49-00452087d53c','2015-08-05','2015-08-05 17:08:36.913 +00:00','2015-08-05 17:08:36.913 +00:00');
Executing (11c364c8-fe92-4fc9-b798-3ea27ab1bee3): UPDATE `Meetings` SET `PersonUuid`='5910bc80-7119-4307-9208-d89f3cb2067b',`updatedAt`='2015-08-05 17:08:36.920 +00:00' WHERE `uuid` = 'e7c03a2a-dc72-4a55-8d49-00452087d53c'
Executing (11c364c8-fe92-4fc9-b798-3ea27ab1bee3): UPDATE `Meetings` SET `PlaceUuid`='71dfd773-e399-44a7-a64c-900d65f25742',`updatedAt`='2015-08-05 17:08:36.921 +00:00' WHERE `uuid` = 'e7c03a2a-dc72-4a55-8d49-00452087d53c'
Executing (11c364c8-fe92-4fc9-b798-3ea27ab1bee3): ROLLBACK;
{ [SequelizeUniqueConstraintError: Validation error]
  name: 'SequelizeUniqueConstraintError',
  message: 'Validation error',
  errors: 
   [ { message: '',
       type: 'unique violation',
       path: 'PersonUuid',
       value: '5910bc80-7119-4307-9208-d89f3cb2067b' },
     { message: '',
       type: 'unique violation',
       path: 'PlaceUuid',
       value: '71dfd773-e399-44a7-a64c-900d65f25742' } ],
  fields: [ 'PersonUuid', 'PlaceUuid' ] }
SequelizeUniqueConstraintError: Validation error
    at Query.formatError (c:\Users\cepharum\PhpstormProjects\soom.js\node_modules\sequelize\lib\dialects\sqlite\query.js:231:14)
    at Statement.<anonymous> (c:\Users\cepharum\PhpstormProjects\soom.js\node_modules\sequelize\lib\dialects\sqlite\query.js:47:29)
    at Statement.replacement (c:\Users\cepharum\PhpstormProjects\soom.js\node_modules\sqlite3\lib\trace.js:20:31)
```

Obviously creating multiple meetings linked with same Person or Place is triggering unique violation error. [According to the docs](http://sequelize.readthedocs.org/en/latest/docs/associations/#belongsto) it seems to be due to using `belongsTo` actually considered to define 1:1-relations which isn't the case here. But if that is the case, how to define a situation like this? 

[According to further parts of docs](http://sequelize.readthedocs.org/en/latest/docs/associations/#1m) pairing *hasMany* with *belongsTo* is quite usual in 1:m-relations, though (e.g. [in another issue](https://github.com/sequelize/sequelize/issues/4259)). So this looks like an issue with mixing m:n-relation with 1:m-relations from junction model's perspective.

### Different Definition Order, Different Behaviour

Maybe worth a second ticket here: on switching order of methods defining relations the behaviour is changing. Turning 

```javascript
Person.belongsToMany( Place, { through: Meeting, as: "Places" } );
Place.belongsToMany( Person, { through: Meeting, as: "People" } );

Meeting.belongsTo( Person );
Person.hasMany( Meeting );

Meeting.belongsTo( Place );
Place.hasMany( Meeting );
```

into

```javascript
Meeting.belongsTo( Person );
Person.hasMany( Meeting );

Meeting.belongsTo( Place );
Place.hasMany( Meeting );

Person.belongsToMany( Place, { through: Meeting, as: "Places" } );
Place.belongsToMany( Person, { through: Meeting, as: "People" } );
```

(defining m:n-relation after 1:m-relations of junction model) output is now:

```
Executing (default): CREATE TABLE IF NOT EXISTS `People` (`uuid` UUID PRIMARY KEY, `name` VARCHAR(255), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
Executing (default): PRAGMA INDEX_LIST(`People`)
Executing (default): PRAGMA INDEX_INFO(`sqlite_autoindex_People_1`)
Executing (default): CREATE TABLE IF NOT EXISTS `Places` (`uuid` UUID PRIMARY KEY, `name` VARCHAR(255), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
Executing (default): PRAGMA INDEX_LIST(`Places`)
Executing (default): PRAGMA INDEX_INFO(`sqlite_autoindex_Places_1`)
Executing (default): CREATE TABLE IF NOT EXISTS `Meetings` (`uuid` UUID PRIMARY KEY, `date` DATE, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `PersonUuid` UUID REFERENCES `People` (`uuid`) ON DELETE SET NULL ON UPDATE CASCADE, `PlaceUuid` UUID REFERENCES `Places` (`uuid`) ON DELETE SET NULL ON UPDATE CASCADE, UNIQUE (PersonUuid, PlaceUuid));
Executing (default): PRAGMA INDEX_LIST(`Meetings`)
Executing (default): PRAGMA INDEX_INFO(`sqlite_autoindex_Meetings_1`)
Executing (default): PRAGMA INDEX_INFO(`sqlite_autoindex_Meetings_2`)
Executing (default): INSERT INTO `People` (`uuid`,`name`,`updatedAt`,`createdAt`) VALUES ('44e38138-19d5-4a50-b4f7-6b9ec9361aca','John Doe','2015-08-05 17:18:24.295 +00:00','2015-08-05 17:18:24.295 +00:00');
Executing (default): INSERT INTO `Places` (`uuid`,`name`,`updatedAt`,`createdAt`) VALUES ('081405f6-30d6-4ed3-bce4-16812e243c3e','Time Square','2015-08-05 17:18:24.302 +00:00','2015-08-05 17:18:24.302 +00:00');
Executing (c01cbe14-3ae8-4a90-81f0-824a6883ae71): BEGIN TRANSACTION;
Executing (c01cbe14-3ae8-4a90-81f0-824a6883ae71): -- SQLite is not able to choose the isolation level REPEATABLE READ.
Executing (c01cbe14-3ae8-4a90-81f0-824a6883ae71): -- SQLite does not support SET autocommit.
Executing (c01cbe14-3ae8-4a90-81f0-824a6883ae71): INSERT INTO `Meetings` (`uuid`,`date`,`updatedAt`,`createdAt`) VALUES ('0bedb469-a3b3-4618-92e3-9f5637dc30f2','2015-08-04','2015-08-05 17:18:24.337 +00:00','2015-08-05 17:18:24.337 +00:00');
Executing (c01cbe14-3ae8-4a90-81f0-824a6883ae71): ROLLBACK;
[TypeError: undefined is not a function]
TypeError: undefined is not a function
    at null.<anonymous> (c:\Users\cepharum\PhpstormProjects\soom.js\test.js:66:15)
    at tryCatcher (c:\Users\cepharum\PhpstormProjects\soom.js\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (c:\Users\cepharum\PhpstormProjects\soom.js\node_modules\bluebird\js\main\promise.js:503:31)
    at Promise._settlePromiseAt (c:\Users\cepharum\PhpstormProjects\soom.js\node_modules\bluebird\js\main\promise.js:577:18)
    at Async._drainQueue (c:\Users\cepharum\PhpstormProjects\soom.js\node_modules\bluebird\js\main\async.js:128:12)
    at Async._drainQueues (c:\Users\cepharum\PhpstormProjects\soom.js\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (c:\Users\cepharum\PhpstormProjects\soom.js\node_modules\bluebird\js\main\async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

Apparently, setters of belongsTo-relation are dropped by defining belongsToMany, even though name clashes can't be expected on inspecting those defining calls only:

```javascript
Meeting.belongsTo( Person ); // Meeting#setPerson()
Person.hasMany( Meeting ); // Person#setMeetings()

Meeting.belongsTo( Place ); // Meeting#setPlace()
Place.hasMany( Meeting ); // Place#setMeetings()

Person.belongsToMany( Place, { through: Meeting, as: "Places" } ); // Person#setPlaces()
Place.belongsToMany( Person, { through: Meeting, as: "People" } ); // Place#setPeople()
```

~~I was able to link instances of Meeting using `Meeting#set( "Person", Person )` then, though this would break my application's model handling library in clearly distinguishing a model's local properties from its external relations.~~ Actually, writing this way seems to be ignored somehow.

**Comment by soletan** [comment] 2015-08-05 18:06
Okay, found solution to unique-violation-issue ... need to declare m:n as non-unique explicitly. Docs aren't quite clear about this, at least as of http://sequelize.readthedocs.org/en/latest/docs/associations/#nm giving more complex example code without explicitly explaining why giving option `unique:false` there while http://sequelize.readthedocs.org/en/latest/api/associations/belongs-to-many/ isn't even mentioning **unique** at all.

**Comment by janmeier** [comment] 2015-08-05 18:26
Unfortnately the `unique` option is not fully implemented. The only thing it does right now is turn of the unique constraint - setters and adders still assume that there will only ever be one connecting instance.

I think your best bet right now would be to use the hasMany + belongsTo assocations exclusively, working with the join table manually (you might use the belongsToMany getter, since it makes no assumptions about uniqueness). This is not ideal, but unfortunately no-one has had time to implement the feature properly.
As always, we would of course welcome a pull request, feel free to ask if you feel up to it! :)


Your second issue seems to be caused by this line https://github.com/sequelize/sequelize/blob/master/lib/associations/belongs-to-many.js#L379. BTM re-inits the through model, which reset this.Instance, loosing the instance methods added so far. I believe it should only call `refreshAttributes` instead but I'm not sure. Mind opening a seperate issue for that?

**Comment by soletan** [comment] 2015-08-05 18:39
@janmeier Your proposal is all I need at the moment. I'm creating instances of junction model exclusively, linking either dependencies using single-ref setters (just like in test script above) and using covering m:n-relation for getting related items, only. So, it works for now ...

**Comment by janmeier** [comment] 2015-10-12 16:01
Closing as solved

**Closed by janmeier** 2015-10-12 16:01 UTC
