### ISSUE TITLE
HasMany's set method tries to leave orphaned rows in the database

### ISSUE THREAD

**Issue by klausXR** [sequelize/sequelize#14048] opened 2022-02-03 19:21 UTC
## Issue Creation Checklist

[X ] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

### SSCCE

```js
// You can delete this code block if you have included a link to your SSCCE above!
const { createSequelizeInstance } = require('./dev/sscce-helpers')
const { Model, DataTypes } = require('.')

const sequelize = createSequelizeInstance({ benchmark: true })

class User extends Model {}

User.init(
    {
        username: DataTypes.STRING,
        birthday: DataTypes.DATE
    },
    { sequelize, modelName: 'user' }
)

class UserAddress extends Model {}
Address.init(
    {
        street: DataTypes.STRING,
    },
    { sequelize, modelName: 'address' }
)

Address.belongsTo(User)
User.hasMany(Address)

;(async () => {
    await sequelize.sync({ force: true })

    const jane = await User.create({
        username: 'janedoe',
        birthday: new Date(1980, 6, 20)
    })

    // Jane initially has one address
    const addr1 = await jane.createAddress({ street: 'st' })

    // Later on, we are attempting to add a second address
    const addr2 = Address.build({
        street: 'st2',
        userId: jane.id
    })

    // Save it, so the instance is persisted
    await addr2.save()

    // https://sequelize.org/master/class/lib/associations/has-many.js~HasMany.html#instance-method-set
    // I expect this line of code to unassociate addr1
    // Moreover, when there's a not null constraint on userId, it should remove the address
    // from the database. However, the line below will throw an error, because the userId field is 
    // not nullable
    await jane.setAddresses([ addr2 ])

    await sequelize.close()
})()
```

### What do you expect to happen?

If I have specified in code that `userId` is not nullable, I would expect `jane.setAddresses([addr2])` to unassociate and destroy the `addr1` row

### What is actually happening?

Sequelize will loop through the currently associated models and try to set their foreign keys to `null`, which is not desirable and throws exceptions ( `userId` is not nullable column )

### Environment

- Sequelize version: 6.6.2
- Node.js version: not related
- If TypeScript related: TypeScript version: XXX 

### How does this problem relate to dialects?

- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX
- [X] I think this problem happens regardless of the dialect.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [X] No, I don't have the time and I wouldn't even know how to start.

**Comment by evanrittenhouse** [comment] 2022-02-05 21:09
@WikiRik I can take a look at this!

**Comment by WikiRik** [comment] 2022-02-20 12:20
Hi @evanrittenhouse sorry for not responding earlier. Would be nice if you could take a look into this :)

**Comment by evanrittenhouse** [comment] 2022-02-24 22:10
@WikiRik sounds good. I am a little new to open-source contributing - is there somewhere I should check first in the codebase?

**Comment by WikiRik** [comment] 2022-02-24 22:21
If you're talking about this issue specifically; I haven't really taken a look at this so I wouldn't know right now what would be the best file to start with. But looking at the description https://github.com/sequelize/sequelize/blob/main/src/associations/has-many.js#L320-L382 might be a good start.

If you're talking about how to contribute, we have some guidelines here; https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md


Feel free to send a message here or on [our Slack](http://sequelize-slack.herokuapp.com/) if you're running into some issues

**Comment by evanrittenhouse** [comment] 2022-02-24 22:36
@WikiRik excellent, will jump on this tonight after work - thank you for the help! Very excited.

**Comment by WikiRik** [comment] 2022-02-27 01:14
Not that I know of, can you share the logs/error message from yarn?

**Comment by evanrittenhouse** [comment] 2022-02-27 01:47
Yeah, here they are. 

`❯ yarn install
yarn install v1.22.17
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning "@ephys/eslint-config-typescript > eslint-import-resolver-typescript@2.5.0" has unmet peer dependency "eslint-plugin-import@*".
warning "@ephys/eslint-config-typescript > @ephys/eslint-config > eslint-plugin-small-import@1.0.0" has incorrect peer dependency "eslint@^6.1.0".
warning "snowflake-sdk > asn1.js-rfc2560@5.0.1" has unmet peer dependency "asn1.js@^5.0.0".
warning Workspaces can only be enabled in private projects.
[5/5] 🔨  Building fresh packages...
[6/6] ⢀ sqlite3
[2/6] ⢀ esbuild
[3/6] ⢀ core-js
[4/6] ⢀ ibm_db
error /Users/evanrittenhouse/Desktop/projects/open_source/sequelize/node_modules/odbc: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments:
Directory: /Users/evanrittenhouse/Desktop/projects/open_source/sequelize/node_modules/odbc
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.8
node-pre-gyp info using node@16.14.0 | darwin | x64
node-pre-gyp info check checked for "/Users/evanrittenhouse/Desktop/projects/open_source/sequelize/node_modules/odbc/lib/bindings/napi-v6/odbc.node" (not found)
node-pre-gyp http GET https://github.com/markdirish/node-odbc/releases/download/v2.4.2/odbc-v2.4.2-darwin-x64-napi-v6.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/markdirish/node-odbc/releases/download/v2.4.2/odbc-v2.4.2-darwin-x64-napi-v6.tar.gz
node-pre-gyp WARN Pre-built binaries not installable for odbc@2.4.2 and node@16.14.0 (node-v93 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/markdirish/node-odbc/releases/download/v2.4.2/odbc-v2.4.2-darwin-x64-napi-v6.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@16.14.0 | darwin | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@16.14.0 | darwin | x64
gyp info find Python using Python version 3.9.1 found at "/Library/Frameworks/Python.framework/Versions/3.9/bin/python3"
gyp info spawn /Library/Frameworks/Python.framework/Versions/3.9/bin/python3
gyp info spawn args [
gyp info spawn args   '/Users/evanrittenhouse/Desktop/projects/open_source/sequelize/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/evanrittenhouse/Desktop/projects/open_source/sequelize/node_modules/odbc/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/evanrittenhouse/Desktop/projects/open_source/sequelize/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/evanrittenhouse/Library/Caches/node-gyp/16.14.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/evanrittenhouse/Library/Caches/node-gyp/16.14.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/evanrittenhouse/Desktop/projects/open_source/sequelize/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/evanrittenhouse/Library/Caches/node-gyp/16.14.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/evanrittenhouse/Desktop/projects/open_source/sequelize/node_modules/odbc',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@16.14.0 | darwin | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/odbc/src/odbc.o
In file included from ../src/odbc.cpp:22:
../src/odbc.h:36:10: fatal error: 'sql.h' file not found
#include <sql.h>
         ^~~~~~~
1 error generated.
make: *** [Release/obj.target/odbc/src/odbc.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/evanrittenhouse/Desktop/projects/open_source/sequelize/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Darwin 20.6.0
gyp ERR! command "/Users/evanrittenhouse/.nvm/versions/node/v16.14.0/bin/node" "/Users/evanrittenhouse/Desktop/projects/open_source/sequelize/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/evanrittenhouse/Desktop/projects/open_source/sequelize/node_modules/odbc/lib/bindings/napi-v6/odbc.node" "--module_name=odbc" "--module_path=/Users/evanrittenhouse/Desktop/projects/open_source/sequelize/node_modules/odbc/lib/bindings/napi-v6" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=6" "--node_napi_label=napi-v6"
gyp ERR! cwd /Users/evanrittenhouse/Desktop/projects/open_source/sequelize/node_modules/odbc
gyp ERR! node -v v16.14.0
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/evanrittenhouse/.nvm/versions/node/v16.14.0/bin/node /Users/evanrittenhouse/Desktop/projects/open_source/sequelize/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/evanrittenhouse/Desktop/projects/open_source/sequelize/node_modules/odbc/lib/bindings/napi-v6/odbc.node --module_name=odbc --module_path=/Users/evanrittenhouse/Desktop/projects/open_source/sequelize/node_modules/odbc/lib/bindings/napi-v6 --napi_version=8 --node_abi_napi=napi --napi_build_version=6 --node_napi_label=napi-v6' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/evanrittenhouse/Desktop/projects/open_source/sequelize/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
node-pre-gyp ERR! System Darwin 20.6.0
node-pre-gyp ERR! command "/Users/evanrittenhouse/.nvm/versions/node/v16.14.0/bin/node" "/Users/evanrittenhouse/Desktop/projects/open_source/sequelize/node_modules/odbc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/evanrittenhouse/Desktop/projects/open_source/sequelize/node_modules/odbc
node-pre-gyp ERR! node -v v16.14.0
node-pre-gyp ERR! node-pre-gyp -v v1.0.8
node-pre-gyp ERR! not ok`

**Comment by WikiRik** [comment] 2022-02-27 08:59
Interesting. I will take a closer look at it later but for now you can just remove odbc from devDependencies and try again. odbc is only used for the ibmi dialect so it won't impact other parts of the code if you're not using that dialect

**Comment by evanrittenhouse** [comment] 2022-02-27 15:23
@WikiRik awesome - that got me past that step, thank you! I'm now seeing a failing test (before I've modified anything). 

1) [SQLITE] Transaction
       fails with SQLITE_BUSY when retry.match is changed:
     AssertionError: expected promise to be rejected with an error including 'SQLITE_BUSY: database is locked' but it was fulfilled with [ undefined, undefined ]
      at assertIfNotNegated (node_modules/chai-as-promised/lib/chai-as-promised.js:68:19)
      at /Users/evanrittenhouse/Desktop/projects/open_source/sequelize/node_modules/chai-as-promised/lib/chai-as-promised.js:183:17
      at async Context.<anonymous> (test/integration/transaction.test.js:739:9)

Not sure if this is intended/expected given a fresh clone of the repo?

**Comment by ephys** [comment] 2022-02-27 15:33
You can ignore this specific error, it's one of the errors we're getting randomly but haven't have had time to resolve https://github.com/sequelize/sequelize/issues/14161

**Comment by evanrittenhouse** [comment] 2022-03-05 20:31
@klausXR can you please confirm that your SSCCE, as posted, throws an error? I've been investigating but haven't seen the error mentioned in your comments.

**Comment by evanrittenhouse** [comment] 2022-03-06 14:25
@ephys cool, thank you. I rebased my branch on top of main today, and am now getting this error when running `yarn test-unit-sqlite`. Is this behavior known?

**Comment by ephys** [comment] 2022-03-07 07:54
@evanrittenhouse the source code has been moved from `/lib` to `/src`, `/lib` is now the build output of `/src`. If `/lib` is missing, try running `yarn build`

**Comment by evanrittenhouse** [comment] 2022-03-10 04:04
Awesome @ephys thank you. I'm not seeing the error mentioned in the bug report - I am, however, seeing that setting the list of addresses without a null constraint doesn't delete the first address from the database. Can you confirm that this is expected behavior that's missing?

**Comment by evanrittenhouse** [comment] 2022-03-21 23:38
@WikiRik wanted to bump this ^.

**Comment by ephys** [comment] 2022-03-23 09:31
Sorry, I missed your notification (almost missed it twice, actually).

In my opinion the behavior for `set` should be this:
- If there is a non-null constraint on the foreign key: delete the old entities, as disassociating them is impossible.
- If there isn't a non-null constraint of the foreign key: simply disassociate them.

**Comment by evanrittenhouse** [comment] 2022-03-26 02:17
@ephys okay, I believe I've fixed the problem. I am, however, experiencing an issue with the test case. If I specify the foreignKey field in the relationship, like so: 
` Address.belongsTo(User, { foreignKey: { allowNull: false } });`
my test passes, but a `SQLITE_CONSTRAINT_FOREIGNKEY: FOREIGN KEY constraint failed` error is thrown. 

If I DON'T specify the foreign key in the relationship, my test fails. Do you have any idea why that'd be?

**Comment by evanrittenhouse** [comment] 2022-03-27 02:25
Hey @ephys good news - I think I've solved the issue. I've opened a PR for this - I am, however, getting an error in this test. Is this an expected error? 

```
  1) [SQLITE Specific] QueryGenerator
       "before each" hook for "Should use the plus operator":
     SQLITE_CONSTRAINT_FOREIGNKEY: FOREIGN KEY constraint failed
 ```

Any help on debugging this? Not sure how it fits into the equation - searching the codebase only led me to `query-generator.test.js`, line 59, in an array called arithmeticQuery.

**Comment by evanrittenhouse** [comment] 2022-04-14 21:25
@ephys Saw that the stale label got removed - is your TS PR passing? If so, I can rebase and try to finish this out.

**Comment by klausXR** [comment] 2022-06-22 06:26
Is there any movement on this? I think this is a fundamental feature for any orm to have

**Comment by WikiRik** [comment] 2022-06-24 11:12
The PR (#14277) for this will be updated soon by @ephys

**Comment by klausXR** [comment] 2022-08-30 05:33
> The PR (#14277) for this will be updated soon by @ephys

Any updates?

**Comment by klausXR** [comment] 2022-12-10 09:01
@WikiRik hey, is there any movement on this? 

I think that if the pr is fine, it should be merged, this is a core feature of an ORM and it doesn't work

**Closed** 2023-04-28 08:44 UTC
Labels: type: feature
