### ISSUE TITLE
 Raw queries Replacement for table name?

### ISSUE THREAD

**Issue by mikeRead** [sequelize/sequelize#4565] opened 2015-09-25 04:40 UTC
I have a complex raw query that I am using. The table name is passed by the client and I would like to use the replacement features to set the table name. However when the replacement is a string it wraps the ' char around the variable. Is it possible to use the ` or force the replacement to not wrap any char around a string? 

simplified example: 
```Javascript

sequelize.query(
"SELECT * FROM `:tableName`",
{ replacements: {tableName: req.params.accountId}, type: sequelize.QueryTypes.SELECT }
)...
```
will run
```Javascript
SELECT * FROM `'account12345'`
```

I need
```Javascript
SELECT * FROM `account12345`
```

Thanks so much

**Comment by janmeier** [comment] 2015-09-30 19:50
Duplicate of https://github.com/sequelize/sequelize/issues/4494

**Closed by janmeier** 2015-09-30 19:50 UTC
