### ISSUE TITLE
Instance get() does not invoke virtual getters

### ISSUE THREAD

**Issue by marc-ferrer** [sequelize/sequelize#8953] opened 2018-01-26 09:47 UTC
## What are you doing?
I am migrating from v3 to v4 and I wanted to use the new class syntax to define the models, but I'm having some issues with getters and setters. Calling `this.get()` from the toJSON instance method, does not call the virtual getters as expected.

```js
const Sequelize = require('sequelize');
const sequelize = new Sequelize('mysql://root@localhost:3306/db');

class Article extends Sequelize.Model {
  get picture() {
    return 'http://picture.url';
  }

  toJSON() {
    const values = this.get();
    console.log('This values', values);

    delete values.secretColumn;
    return values;
  }
}

Article.init({
  name: Sequelize.DataTypes.STRING,
  secretColumn: Sequelize.DataTypes.STRING
}, {
  sequelize
});

const a = new Article({name: 'MyArticle'});
console.log(a.toJSON());
```

## What do you expect to happen?
As stated in the docs, `get()` should invoke virtual getters.

> If no key is given, returns all values of the instance, also invoking virtual getters.

## What is actually happening?
`picture` getter is not invoked

__Dialect:__ mysql
__Dialect version:__ 1.5.1
__Database version:__ Not relevant
__Sequelize version:__ 4.32.1

**Comment by marc-ferrer** [comment] 2018-01-26 09:58
I can workaround the issue setting the attribute `getterMethods` in the `init`'s options parameter, but that is not documented and I got the feeling it could be removed any time...

P.S.: There is another issue with setters defined in the class, which are not invoked on Model.create I might open another issue in the next days if I have the time to create a SSCCE

**Comment by marc-ferrer** [comment] 2018-04-26 10:44
This is still an issue obviously. According to #6524 It should be possible to define getters/setters inside the class, and the documentation of the [get](http://docs.sequelizejs.com/class/lib/model.js~Model.html#instance-method-get) states that it should invoke virtual getters, which it does not do when they are defined inside the class.

On the other hand when invoked directly through an instance, i.e. `instance.picture()` (following my example), they do are invoked correctly.

P.S.: I would gladly update the docs or help with any implementation but I feel like you have still not decided which is the way to go with this...

**Comment by sushantdhiman** [comment] 2018-07-25 11:46
For now please use `getterMethods` as ES6 getters does not allow parameters

Duplicate of https://github.com/sequelize/sequelize/issues/9300

**Closed by sushantdhiman** 2018-07-25 11:46 UTC

**Comment by cavalos0086** [comment] 2018-07-31 19:30
Still an issue!
