### ISSUE TITLE
sequelize@5.1.0 nodjes, I can't see logging sql value detail

### ISSUE THREAD

**Issue by zacard-orc** [sequelize/sequelize#10661] opened 2019-03-30 12:22 UTC
```js
// previos version 
Executed (default): INSERT INTO `moni_gain` (`id`,`user_id`,`order_id`,`gain`,`reason`,`create_at`,`update_at`) VALUES (auto,1001,983,13,'afdadf',now(),xxxxx);

//5.0++ version
Executed (default): INSERT INTO `moni_gain` (`id`,`user_id`,`order_id`,`gain`,`reason`,`create_at`,`update_at`) VALUES (?,?,?,?,?,?,?);
```
so i can't see the sql after render  .......

## What do you expect to happen?
I wan't print sql detail after render in version 5.0++ ,how to config in constructor function

## What is actually happening?
now there are all ????????????

so ,pls take me a favor, thx ~

**Comment by ALiangLiang** [comment] 2019-03-31 07:32
Try to use `DEBUG=* node YOUR_CODE.js`

**Comment by SimonSchick** [comment] 2019-03-31 15:36
This will have the same result, this is due to sequelize now using bind parameters, we will fix this soon.

**Comment by SimonSchick** [comment] 2019-03-31 15:38
Duplicate of #10067

**Closed by SimonSchick** 2019-03-31 15:38 UTC
