### ISSUE TITLE
Cannot change model's property with type Date

### ISSUE THREAD

**Issue by mikalai-ramashka** [sequelize/sequelize#4271] opened 2015-08-06 12:23 UTC
I have model with column:

```
onlineTimestamp: {
      type: DataTypes.DATE,
      field: 'online_timestamp'
 },
```

When I load model with `findOne` this property is not converted to Date because in `set` method `options.raw = true`

```
if (!options.raw) {
          // If attribute is not in model definition, return
          if (!this._isAttribute(key)) {
            if (key.indexOf('.') > -1 && this.Model._isJsonAttribute(key.split('.')[0])) {
              Dottie.set(this.dataValues, key, value);
              this.changed(key, true);
            }
            return;
          }

          // If attempting to set primary key and primary key is already defined, return
          if (this.Model._hasPrimaryKeys && originalValue && this.Model._isPrimaryKey(key)) {
            return;
          }

          // If attempting to set read only attributes, return
          if (!this.isNewRecord && this.Model._hasReadOnlyAttributes && this.Model._isReadOnlyAttribute(key)) {
            return;
          }

          // Convert date fields to real date objects
          if (this.Model._hasDateAttributes && this.Model._isDateAttribute(key) && !!value && !value._isSequelizeMethod) {
            if (!(value instanceof Date)) {
              value = new Date(value);
            }
            if (originalValue && value.getTime() === originalValue.getTime()) {
              return;
            }
          }
        }
```

 When I tried second time to update this property I have error:

```
TypeError: undefined is not a function
    at Instance.set (d:\projects\sync-it-server\node_modules\sequelize\lib\instance.js:346:68)
```

`originalValue` is string, not Date.

Sequelize 3.5.1, dialect sqlite

**Comment by janmeier** [comment] 2015-08-06 12:24
Duplicate of https://github.com/sequelize/sequelize/issues/3611, will be fixed by https://github.com/sequelize/sequelize/pull/4186

**Closed by janmeier** 2015-08-06 12:24 UTC
