### ISSUE TITLE
Alter and UNIQUE keyword does not work well together

### ISSUE THREAD

**Issue by Patcher56** [sequelize/sequelize#9345] opened 2018-04-24 12:42 UTC
## What are you doing?
I am using the .sync({alter: true}), so I can update and edit my models without dropping the whole db every time.

Now I have one column in one table with the following syntax
```js
contractNumber: {type: Sequelize.INTEGER, allowNull: false, unique: true},
```

## What do you expect to happen?
Everything works well.

## What is actually happening?
After multiple times of restarting the server (also altering the db) my unique key gets regenerated every time, but not deleted!

So I get the following mysql error:
Too many keys specified; max 64 keys allowed

I have to manually delete over 50 unique keys to make the db work again.

I am using sequelize version 4.37.6 and MySQL for my database

**Comment by sushantdhiman** [comment] 2018-04-29 09:30
Duplicate of https://github.com/sequelize/sequelize/issues/8984

**Closed by sushantdhiman** 2018-04-29 09:30 UTC
