### ISSUE TITLE
Feature Request - RIGHT JOIN

### ISSUE THREAD

**Issue by SourceBoy** [sequelize/sequelize#4187] opened 2015-07-25 04:02 UTC
Given that we currently cannot limit the associated records (#1897), I've been exploring other options; one of the ideas is to select the associated records and right-join onto a particular main record in order to retrieve both the main and associated records.

Consider the case where there is a post, and that post may or may not have comments, and no more than 5 latest comments are to be retrieved:

```
// Ideally, we'd just do this in order to get 1 post with 0-5 latest comments:
Post.findOne({
  where: { id: 123 },
  include: [{
    model: Comment,
    required: false,
    order: [ ['timestamp'], 'DESC'] ]
    limit: 5
  }]
});
```

One of the workarounds I'm exploring is to select the comments of a post and include the post:

```
// This only retrieves latest 1-5 comments for the post along with the post.
// If the post has no comments, result set would be empty, obviously.
Comment.findOne({
  where: { post_id: 123 },
  include: [{
    model: Post,
    required: false
  }],
  order: [ ['timestamp', 'DESC'] ],
  limit: 5
});
```

A similar RIGHT JOIN would be able to retrieve **0-5** latest comments along with the post regardless there are comments or not:

```
SELECT c.*, p.*
FROM Comments AS c
RIGHT JOIN Posts AS p ON c.post_id = p.id
WHERE p.id = 123

// Perhaps something like:
Comment.findOne({
  //where: { post_id: 123 }, // Not sure if this still makes sense.
  include: [{
    model: Post,
    where: { id: 123 },
    required: false
  }],
  order: [ ['timestamp', 'DESC'] ],
  limit: 5
});
```

@janmeier @mickhansen Is this something that could be implemented for the time being while #1897 is being worked on? Thanks.

**Comment by mickhansen** [comment] 2015-07-25 07:37
LIMIT for hasMany is getting pretty far with: https://github.com/sequelize/sequelize/pull/4177

**Comment by mickhansen** [comment] 2015-07-25 07:46
Adding a `right` option to `include` to change it to a right join instead of left should be a pretty trivial change actually.

**Comment by SourceBoy** [comment] 2015-07-25 20:03
Thanks for the reference, @mickhansen. But it looks like #4177 does a separate query to get the associated records instead of getting the desired result set / models with just one query? If that's the case, I'd still like to request the RIGHT JOIN feature as it'll be able to get the records in one shot.

Do you think this could be squeezed into the next release? Thanks.

**Comment by mickhansen** [comment] 2015-07-25 20:14
@SourceBoy Yeah it does not add this specific feature you request but it goes a long way in solving the LIMIT/ORDER of includes issue.

Will release a version when the feature is merged, someone has to do the work first :)

**Comment by SourceBoy** [comment] 2015-07-25 20:16
Understood. Thanks a lot. I look forward to integrating it once it's ready.

**Comment by lukmanlukmin** [comment] 2017-04-06 03:45
hi @SourceBoy any progress how this issue going?
i think i need right join feature right now.
would you spoil me how you handle that issue.
any response will be very appreciated, thanks :)

**Comment by SourceBoy** [comment] 2017-04-06 04:11
Hi @lukmanlukmin, I'm not a contributor for Sequelize, and I haven't followed the progress of its development since this proposal was made.

I actually don't remember which project I needed this for back in summer 2015, but I believe I used a [raw query](https://github.com/sequelize/sequelize/issues/1897#issuecomment-124542900) and manually populated the models at runtime.

**Comment by marc-ferrer** [comment] 2017-07-10 10:51
I know the issue is closed, but I could not find a way to add a `right` option to the `include`.

Is there something that I am missing? or this is not possible at all? Right joins are helpful sometimes.

**Comment by lukmanlukmin** [comment] 2017-07-10 11:09
@marc-ferrer, we are not Sequelize contributor here. as a @SourceBoy suggest and i do it too.
maybe you should choose raw query to solve your problem.
and wait till the contributor add this feature.
as i know, this feature not supported yet.
hope its help

**Comment by marc-ferrer** [comment] 2017-07-10 11:16
That's why i did not reference any of you in my comment.
I just could not find a better place to ask this, than an issue called "Feature Request - RIGHT JOIN"

I appreciate your help, I guess I could use raw queries as you suggest and populate the models manually.

**Comment by DaAwesomeP** [comment] 2017-08-05 19:03
A right join is definitely a simple workaround for limiting included tables in a left join. I currently have table `Authors` and `Works`. I can get and limit works and include their authors, but I can't get an author and get and limit that author's works.

**Comment by andrewholsted** [comment] 2018-03-10 13:49
@mickhansen, from your comment in 2015

> Adding a right option to include to change it to a right join instead of left should be a pretty trivial change actually.

I'm willing to give this a stab if you could point me in the right direction.

**Comment by TakanashiOuken** [comment] 2019-06-25 05:01
This was 4 years ago. But we still don’t have RIGHT OUTER JOIN for Sequelize ?

**Comment by mickhansen** [comment] 2019-06-25 07:09
@TakanashiOuken Would appear no one has submitted a PR.

**Comment by ckeboss** [comment] 2019-10-11 03:59
@mickhansen I have made a pull request with this feature. Should we reopen this?

**Comment by sushantdhiman** [comment] 2019-10-18 06:17
Supported with https://github.com/sequelize/sequelize/pull/11537

**Closed by sushantdhiman** 2019-10-18 06:17 UTC
Labels: hard, status: wip, type: feature
