### ISSUE TITLE
MSSQL support for multiple databases

### ISSUE THREAD

**Issue by ackerdev** [sequelize/sequelize#2945] opened 2015-01-15 21:19 UTC
With MSSQL, a database server can have multiple databases that are accessible via the same connection. `[database].[schema].[table]` is a valid table reference, and you can, for instance, join two tables across databases this way. The following is a valid query in MSSQL:

```sql
SELECT *
FROM [databaseA].[foo].[bar] b
JOIN [databaseB].[baz].[qux] q ON b.id = q.bar_id
```

There doesn't appear to be any way to model this structure with Sequelize at the moment, as it links to a specific database on connection and there is no option to define what database a model belongs to like you can with schemas.

I've drafted up a script for creating an example database to demonstrate this functionality. The query above should run properly given this database setup.

```sql
-- Create databaseA.foo.bar
CREATE DATABASE databaseA;
USE databaseA;
CREATE SCHEMA foo;
CREATE  TABLE [foo].[bar]([id] BIGINT NOT NULL);
INSERT INTO [foo].[bar] (id) VALUES (1);

-- Create databaseB.baz.qux
CREATE DATABASE databaseB;
USE databaseB;
CREATE SCHEMA baz;
CREATE  TABLE [baz].[qux]([bar_id] BIGINT NOT NULL);
INSERT INTO [baz].[qux] (bar_id) VALUES (1);
```

This issue is a fairly critical obstruction to me using Sequelize, so if there is anything I can do to help move this forward just let me know.

cc: @mbroadst

**Comment by ackerdev** [comment] 2015-02-11 21:28
mbroadst set up a WIP version of this on his fork, it just needs a few tweaks to be ready for PR.

Note to self: SQL is being generated correctly, but it was causing issues on certain queries eg. showAllTables.

**Comment by mickhansen** [comment] 2015-02-12 07:37
This could ideally also benefit MySQL which has cross-database joins that operate very similar to cross-schema joins.

**Comment by treejanitor** [comment] 2015-06-02 12:30
@mickhansen I'm interested in this feature for MySQL.  Many of my projects have logically isolated databases which could benefit from using a single pool of connections, as well as the ability to join and perform transactions cross-db.

**Comment by ackerdev** [comment] 2015-06-22 18:43
I opened a PR with the work mbroadst had originally done to help set this up. If anyone is interested in giving it some love and helping it get integrated, see https://github.com/sequelize/sequelize/pull/3985

**Comment by alexraju** [comment] 2016-05-03 09:50
@mickhansen This is much essential feature. Even though I have separate connection, when I do join between tables from different databases, db name is getting appended before the table name causing query to fail. If you could get some priority to this, It will be great.

**Comment by mickhansen** [comment] 2016-05-03 09:54
@alexraju Don't post the same comment in multiple issues please.

**Comment by sushantdhiman** [comment] 2016-06-25 05:50
Duplicate of #2049

**Closed by sushantdhiman** 2016-06-25 05:50 UTC
Labels: feature, mssql

**Comment by ackerdev** [comment] 2016-06-27 17:41
@sushantdhiman This is not a duplicate of that issue. This issue is about working with linked servers in SQL Server. For instance, I can have an SQL Server instance `MyCompanyServer` and a remote instance `SharedServer`, which each have their own "databases" (schemas/catalogs), and I can write queries like:

```
FROM [MyCompanyServer].[MySchema].[MyTableFoo] foo
JOIN [SharedServer].[TheirSchema].[TheirTableBar] bar ON foo.bar_id = bar.id
```

That said, I don't really have a problem with this being closed if it's not a high priority issue. I'm not affected by this anymore as I have moved on from those projects, so I don't really have any interest in whether this functionality is added at this point.

**Comment by sushantdhiman** [comment] 2016-06-28 07:42
@ackerdev I would definitely love to support joins across multiple databases, But I think cross server support is too much for Sequelize. Sequelize and its pooling is build to run for single server.

Your original request mention using `same connection`. If these databases (from multiple servers) can be accessed over same connection, then it seems like a duplicate of #2049. In the end we just have to append the database name is query.

**Comment by ackerdev** [comment] 2016-06-28 14:10
It's a single connection. It is distinct from #2049 as it is concerned with joining tables across schema, whereas this is about joining tables across database instances and schemas, and this feature is unique to SQL Server. Fixing that issue will not fix this.

**Comment by sushantdhiman** [comment] 2016-06-29 08:01
@ackerdev I will prefer simply prefixing database name with table name so cross join will be possible (#2049).

But joining against multiple server databases is unique to MSSQL, it can't be implemented for other dialects. Thats why we will simply go with #2049

If you still want this to be implemented you can start with a PR.
