### ISSUE TITLE
Is it possible to add a limit for the included associations?

### ISSUE THREAD

**Issue by aprilmintacpineda** [sequelize/sequelize#9083] opened 2018-02-21 07:51 UTC
something like this:

```
models.ModelOne.findOne({
  where,
  include: [
    {
      model: models.ModelTwo,
      limit: 1
    }
  ]
})
```

**Comment by sushantdhiman** [comment] 2018-04-20 03:18
Duplicate of https://github.com/sequelize/sequelize/issues/1897

**Closed by sushantdhiman** 2018-04-20 03:18 UTC
