### ISSUE TITLE
Problem with enum when using with schema

### ISSUE THREAD

**Issue by Uhsac** [sequelize/sequelize#4048] opened 2015-07-02 09:12 UTC
Hi,

I have found a bug today, if i'm using enum datatypes and tried to sync in a specified schema it don't work.

Example :

```javascript
  var InnovationDetail = sequelize.define('InnovationDetail', {
    language: dataTypes.ENUM(
                  'fr',
                  'en'),
    name: dataTypes.STRING,
    description: dataTypes.STRING
  }, {
    classMethods: {
      associate: function(models) {
      }
    }
  });
```

If I try to sync this in a specific schema like this :

```javascript
InnovationDetail.sync({
  schema: 'public',
  force: true
});
```

I have this error :

```console
Unhandled rejection SequelizeDatabaseError: type "enum_public.InnovationDetails_language" does not exist
```

It prefix the enum with the schema and I think it don't have to do that.

If I remove the schema it work.

Thanks.

**Comment by janmeier** [comment] 2015-07-02 09:13
Duplicate of https://github.com/sequelize/sequelize/issues/3171

**Closed by janmeier** 2015-07-02 09:13 UTC
