### ISSUE TITLE
[BUG]? When use where in Model.count(), it throws exception from sql-string.js#144

### ISSUE THREAD

**Issue by ppoo24** [sequelize/sequelize#4489] opened 2015-09-14 04:17 UTC
I realized the v3.7.0 made more break changes, so i'm working on upgrading to this version from v2.0.x, then i found this bug, check codes below:
```js
_checkLaySupportDevice: function (id, idType, device) {
	var self = this;
	var ItemLay = self.M('ItemLay'),
		TplLay = self.M('TplLay'),
		Tpl = self.M('Tpl');
	return (idType == 'ItemLay' ? ItemLay : TplLay).count({
		attributes: ['id'],
		where: [['current=?', 0]]
	})
	.then(function (count) { if (count <= 0) { throw new Error('Not support this device-' + Static.deviceList[device]); }  });
}
```
at this line: `where: [['current=?', 0]]`, it will cause an `undefined is not a function` tracked in `sequelize\lib\sql-string.js` line 144:
```js
SqlString.format = function(sql, values, timeZone, dialect) {
  values = [].concat(values);

  return sql.replace(/\?/g, function(match) { //!!!!!!!! HERE GOES ON !!!!!!!!!!!!!!!!!!!!
    if (!values.length) {
      return match;
    }

    return SqlString.escape(values.shift(), false, timeZone, dialect);
  });
};
```
then, if i change to `where: [['current=?', 0], { id: 10 }]` or `where: ['current=?', 0]`, the sql is executed.
may please fix this fatal bug!

**Comment by mickhansen** [comment] 2015-09-14 07:26
2 -> 3 contains breaking changes, hence the SemVer major bump.
Looks like a regression indeed.

**Comment by sushantdhiman** [comment] 2016-06-11 08:47
@mickhansen @janmeier 

I have fixed this issue, but then I get deprecation error from [here](https://github.com/sequelize/sequelize/blob/master/lib/dialects/abstract/query-generator.js#L1840) 

Do we want to support this syntax? I can remove / modify the deprecation check, if you think this syntax should be supported ? 

I think it shouldn't be supported.

**Comment by mickhansen** [comment] 2016-06-12 10:23
@sushantdhiman `where: ""` is not supported but `where: ["", []]` is - we can remove it but we need a good alternative way for raw where queries with escaping then.

**Comment by sushantdhiman** [comment] 2016-06-13 11:05
@mickhansen 

Syntax `where: ["query", ["replacements", "replacements"]]` is good to have.

But `[ ["query",  "replacement"] ]`, do we need this ? And is it possible to do this `[ ["query",  "replacement"], ["query",  "replacement"], .... ]` ?

I think we should only support 1st case `where: ["query", ["replacements", "replacements"]]`

I can write an test to verify that we don't support old syntax (we need array of replacements now, rather than replacement string)

**Comment by mickhansen** [comment] 2016-06-13 11:06
@sushantdhiman `$and` shoud probably be sufficient in that case.

**Comment by sushantdhiman** [comment] 2016-06-13 11:10
So we don't need to support `[['current=?', 0]]` as we support `[ 'current=?', [0] ]` @mickhansen , for other cases `$and` can be used.

**Comment by sushantdhiman** [comment] 2016-06-14 06:13
@mickhansen Please suggest a suitable course of action here. If we have `[ 'current=?', [0] ]` do we still need `[['current=?', 0]]` ? If you closely look at [logic](https://github.com/sequelize/sequelize/blob/master/lib/utils.js#L288) , supporting both will be ugly :)

**Comment by mickhansen** [comment] 2016-06-14 07:12
@sushantdhiman No i'm fine with killing array as $and logic and asking users to use {$and: []} instead, will need @janmeier's confirmation on this tho.

**Comment by janmeier** [comment] 2016-06-14 07:20
+1

**Comment by sushantdhiman** [comment] 2016-06-14 07:22
So we can just close the issue in that case @mickhansen @janmeier 

`[ 'current=?', [0] ]` supported
`{ $and : [] }` should be used for other cases
`[['current=?', 0]]` will not be supported

**Comment by mickhansen** [comment] 2016-06-14 07:27
Hmm, i'll need to give it some thought, we have supported using multiple args via `[]`, but i'm not sure there's a great deal of usecase anymore (other than if you need to combine multiple sequelize.where statements)

**Comment by janmeier** [comment] 2016-06-14 07:30
Which can still be done with `$and` - I still we should kill it :fire:

**Comment by sushantdhiman** [comment] 2016-06-14 07:30
[`[]` usecase](https://github.com/sequelize/sequelize/blob/16b39c612c721612e65323bb875bd07a5a6e3811/test/unit/sql/select.test.js#L300)

**Comment by mickhansen** [comment] 2016-06-14 07:33
@sushantdhiman That's the raw query usecase, i was thinking about the multiple statement usecase.
But yes, agreed.

**Closed by mickhansen** 2016-06-14 07:33 UTC
Labels: bug, regression
