### ISSUE TITLE
sequlize does not support timezones from momentjs

### ISSUE THREAD

**Issue by PavelPolyakov** [sequelize/sequelize#5001] opened 2015-12-08 16:57 UTC
It's stated here: http://docs.sequelizejs.com/en/latest/api/sequelize/, that it's possible to pass the timezone in the format which is accepted by momentjs.

However this code:
```javascript
let sequelize = new Sequelize(config.get('storage.uri'), {
    logging: debug, //false

    define: {
        timestamps: false
    },

    timezone: "Europe/Berlin",

    pool: {
        max: 20,
        min: 0,
        idle: 5000
    }
});
```

Results to the next error:
![image](https://cloud.githubusercontent.com/assets/839290/11662023/0ddce968-9dd5-11e5-82f0-0d06c22c46c5.png)

This code works:
```javascript
let sequelize = new Sequelize(config.get('storage.uri'), {
    logging: debug, //false

    define: {
        timestamps: false
    },

    timezone: "+01:00",

    pool: {
        max: 20,
        min: 0,
        idle: 5000
    }
});
```

Regards,

**Comment by janmeier** [comment] 2015-12-08 17:11
Duplicate of https://github.com/sequelize/sequelize/issues/4307

**Closed by janmeier** 2015-12-08 17:11 UTC
