### ISSUE TITLE
Nested Include With Limit Causes Unknown Column Error

### ISSUE THREAD

**Issue by sshaw** [sequelize/sequelize#10165] opened 2018-11-16 04:11 UTC
## What are you doing?

```js
Event.findAll({
    include: [
        {
            model: Reaction,
            required: true,
            include: [
                {
                    model: User,
                    required: true,
                    where: {
                       tId: tId, userId: userId
                    }
                }
            ]
        }
    ],
    order: [['updatedAt', 'desc']],
    limit: 5
})
```

## What do you expect to happen?

Retrieve latest 5 events with reactions by `{tId: tId, userId: userId}`. 

## What is actually happening?

`error: SequelizeDatabaseError: Unknown column 'Reactions.userId' in 'on clause'`

```sql
SELECT `Event`.*, `Reactions`.`id` AS `Reactions.id`, `Reactions`.`eventId` AS `Reactions.eventId`, `Reactions`.`reaction` AS `Reactions.reaction`, `Reactions`.`userId` AS `Reactions.userId`, `Reactions`.`createdAt` AS `Reactions.createdAt` FROM (SELECT `Event`.`id`, `Event`.`eventTs`, `Event`.`type`, `Event`.`context`, `Event`.`createdById`, `Event`.`occuredAt`, `Event`.`updatedAt`, `User`.`id` AS `User.id`, `User`.`name` AS `User.name`, `User`.`userId` AS `User.userId`, `User`.`tId` AS `User.tId`, `User`.`realName` AS `User.realName`, `User`.`createdAt` AS `User.createdAt`, `User`.`updatedAt` AS `User.updatedAt`, `Reactions->User`.`id` AS `Reactions.User.id`, `Reactions->User`.`name` AS `Reactions.User.name`, `Reactions->User`.`userId` AS `Reactions.User.userId`, `Reactions->User`.`tId` AS `Reactions.User.tId`, `Reactions->User`.`realName` AS `Reactions.User.realName`, `Reactions->User`.`createdAt` AS `Reactions.User.createdAt`, `Reactions->User`.`updatedAt` AS `Reactions.User.updatedAt` FROM `Events` AS `Event` INNER JOIN `Users` AS `User` ON `Event`.`createdById` = `User`.`id` INNER JOIN `Users` AS `Reactions->User` ON `Reactions`.`userId` = `Reactions->User`.`id` AND `Reactions->User`.`tId` = '123' AND `Reactions->User`.`userId` = 'X1' WHERE ( SELECT `Reactions`.`eventId` FROM `Reactions` AS `Reactions` INNER JOIN `Users` AS `User` ON `Reactions`.`userId` = `User`.`id` AND `User`.`tId` = '123' AND `User`.`userId` = 'X1' WHERE (`Reactions`.`eventId` = `Event`.`id`) LIMIT 1 ) IS NOT NULL ORDER BY `Event`.`updatedAt` DESC LIMIT 5) AS `Event` INNER JOIN `Reactions` AS `Reactions` ON `Event`.`id` = `Reactions`.`eventId` ORDER BY `Event`.`updatedAt` DESC;
```

__Dialect:__ mysql
__Database version:__ 10.0.13-MariaDB
__Sequelize version:__  4.37.6
__Tested with latest release:__ No, but checked Changelog and didn't see fix. 

This _does_ work when without the `limit`.

**Comment by mortenko** [comment] 2018-11-23 15:49
http://docs.sequelizejs.com/class/lib/model.js~Model.html#static-method-findAndCountAll
use rather this method then findAll

**Comment by sushantdhiman** [comment] 2018-12-01 12:08
Duplicate of https://github.com/sequelize/sequelize/issues/9869

**Closed by sushantdhiman** 2018-12-01 12:08 UTC
