### ISSUE TITLE
Foreign keys from migrations and from associations

### ISSUE THREAD

**Issue by gcatto** [sequelize/sequelize#3384] opened 2015-03-20 20:44 UTC
I recently noticed that when I run migrations, it does not generate any foreign keys. If I then run all of the associations, the foreign keys still do not get generated, vs. if I don't run the migrations and just run the associations, it does create foreign keys for all of the associations.

Is this by design? And, if so, how should I go about adding the foreign keys to my migrations (or when using migrations)?

I am using sequelize 2.0.4 and sequelize-cli 1.4.0 against postgres.

Thanks!

**Comment by mickhansen** [comment] 2015-03-21 16:13
What does your migration code look like?
I recall earlier issues about this, we might not fully support it yet.

**Comment by gcatto** [comment] 2015-03-21 17:16
Sure thing, see below. I am not doing anything fancy, nor anything explicit to generate foreign keys.

```
module.exports =
  up: (migration, DataTypes, done) ->
    migration.createTable("backgrounds",
      # Associations
      characterId:
        type: DataTypes.INTEGER
        allowNull: false

      # Data
      name:
        type: DataTypes.TEXT
        allowNull: false

      type:
        type: DataTypes.STRING
        allowNull: false

      description:
        type: DataTypes.TEXT

      id:
        type: DataTypes.INTEGER
        primaryKey: true
        allowNull: false
        autoIncrement: true

      createdAt:
        type: DataTypes.DATE
        allowNull: false

      updatedAt:
        type: DataTypes.DATE
        allowNull: false
    ).complete(done)

  down: (migration, DataTypes, done) ->
    migration.dropTable('backgrounds').complete(done)
```

In this case, the column characterId is the reference to another table. If I don't run the migrations and just create the models and associations, I can see the FKs (e.g., in PGAdmin), but if I run the migrations, they never seem to get made

Thanks!

**Comment by mickhansen** [comment] 2015-03-21 17:56
Not seeing any reference statements in the create table statement.
I assume you are expecting relationship definitions to have an effect on your createTable statement, unfortuneatly this is not the case.

You will have to use `references: "table"` and `referencesKey: "column"` on the specific attributes.

**Comment by gcatto** [comment] 2015-03-21 22:42
Ah okay, I will do that, thanks!

For whatever it's worth, I *think* those details are missing from the documentation for the migrations stuff, but perhaps I overlooked them.

**Comment by mickhansen** [comment] 2015-03-22 08:36
@gcatto You are right about that, i'm working on new code and new docs for migrations to make it better :)

**Comment by gcatto** [comment] 2015-03-22 14:12
Great! Let me know if there's anything I can do to be useful.

**Comment by gcatto** [comment] 2015-03-22 14:30
I tried writing a migration to change an existing column using the references and referencesKey stuff:
```
promises.push(migration.changeColumn('backgrounds', 'characterId', {
  type: DataTypes.INTEGER
  references: 'characters'
  referencesKey: 'id'
}))
```
But I end up getting an exception:
```
Possibly unhandled SequelizeDatabaseError: syntax error at or near "REFERENCES"
  at [object Object].module.exports.Query.formatError (C:\dev\node_modules\sequelize\lib\dialects\postgres\query.js:415:16)
  at [object Object].<anonymous> (C:\dev\node_modules\sequelize\lib\dialects\postgres\query.js:110:21)
  at [object Object].emit (events.js:107:17)
  at [object Object].Query.handleError (C:\dev\node_modules\pg\lib\query.js:99:8)
  at [object Object].<anonymous> (C:\dev\node_modules\pg\lib\client.js:166:26)
  at [object Object].emit (events.js:107:17)
  at Socket.<anonymous> (C:\dev\node_modules\pg\lib\connection.js:109:12)
  at Socket.emit (events.js:107:17)
  at readableAddChunk (_stream_readable.js:163:16)
  at Socket.Readable.push (_stream_readable.js:126:10)
  at TCP.onread (net.js:529:20)
```
The documentation states that "it is possible to change the default value, allowance of null or the data type," so perhaps I cannot use changeColumn() to add the foreign key? Is there another way? Thanks!

**Comment by BridgeAR** [comment] 2015-05-31 13:30
Duplicate of #966

**Closed** 2015-05-31 20:36 UTC
