### ISSUE TITLE
Updating only updatedAt on a model does not cause an update, even with silent: true

### ISSUE THREAD

**Issue by jamelling** [sequelize/sequelize#11183] opened 2019-07-11 19:11 UTC
## What are you doing?
```js
person = Person.create({ name: 'Original Name'})
await Person.update({ updatedAt: new Date('02-26-1991')}, {where: { id: person.id }, silent: true})
// [ 0 ]

await person.reload()
await person.updatedAt
// 2019-04-12T20:13:52.923Z

await Person.update({ updatedAt: new Date('02-26-1991'), name: 'A New Name'}, {where: { id: person.id }, silent: true})
Executing (default): UPDATE "Person" SET "updatedAt"=$1,"name"=$2 WHERE "id" = $3
// [ 1 ]

await person.reload()
person.updatedAt
// 1991-02-26T05:00:00.000Z
```
**To Reproduce**
1. Create a model `Person` and an instance `person`
2. Use `Person.update` to update only the updatedAt field on person
3. Reload `person` to see that updatedAt has not been updated

## What do you expect to happen?
I expected updatedAt to be updated,

## What is actually happening?
updatedAt was not updated

## Environment
Dialect:
- [ ] mysql
- [ ] postgres
- [ ] sqlite
- [ ] mssql
- [x] any
Dialect **library** version: XXX
Database version: PostgreSQL 9.6
Sequelize version: 5.10.0
Node Version:  10.15.3
OS: Ubuntu 18.04.1 on Windows 10
Tested with latest release:
- [ ] No
- [x] Yes, specify that version: 5.10.0

**Comment by papb** [comment] 2019-07-11 21:15
What is the use case for updating only the updatedAt field?

**Comment by jamelling** [comment] 2019-07-11 21:22
I only use it while doing tests for some filtering of data by updatedAt times.

**Comment by Ladvace** [comment] 2019-07-12 13:54
I have the same problem

**Comment by wangzhilongh** [comment] 2019-07-26 07:26
I have the same problem

**Comment by papb** [comment] 2019-10-17 12:14
Duplicate of #3759

**Closed by papb** 2019-10-17 12:14 UTC
Labels: status: understood, type: bug
