### ISSUE TITLE
Sync with alter errors out when constraint exists

### ISSUE THREAD

**Issue by Misiur** [sequelize/sequelize#8041] opened 2017-07-31 16:58 UTC
## What you are doing?
```js
import Sequelize from 'sequelize';

const db = new Sequelize('testdb', 'root', '', {
  host: 'localhost',
  dialect: 'mysql',
});

db.authenticate()
  .then(() => {
    console.log('Connection has been established successfully.');
  })
  .catch(err => {
    console.log(`Unable to connect to the database: ${err}`);
  });

db.sync({ alter: true });

const Foo = db.define('foos', {});

const Bar = db.define('bars', {});

Bar.hasMany(Foo);
```

## What do you expect to happen?
_It should create my schema on first run, and add new columns on subsequent runs_

## What is actually happening?
_It creates schema on first run, but on second run it errors out_

```
Unhandled rejection SequelizeDatabaseError: Can't create table `testdb`.`#sql-8cc_61` (errno: 121 "Duplicate key on write or update")
```

__Dialect:__ mysql
__Database version:__ 10.1.8-MariaDB
__Sequelize version:__ 4.4.2

**Comment by whittakergroupinc** [comment] 2017-08-08 13:13
Same: Unhandled rejection SequelizeDatabaseError: Can't write; duplicate key in table '#sql-6215_4f2'

**Comment by bruno02100** [comment] 2017-08-11 18:24
Having the same issue.

**Comment by zl810881283** [comment] 2017-08-22 16:23
Having the same issue.

**Comment by Misiur** [comment] 2017-09-22 15:25
Still an issue with 4.10

**Comment by lessu** [comment] 2017-09-30 15:24
Having the same issue.with 4.12.0

**Comment by robin-garnham** [comment] 2017-10-04 05:44
Also having this issue. I have it with a number of tables and find if I remove the constraints manually in the DB then it passes over them... but then the next time it re-syncs it fails again

**Comment by grahammills** [comment] 2017-11-01 16:35
This still seems to be an issue in 4.20.3
Does anyone have an update to this?

**Comment by cyrille-gaucher** [comment] 2017-11-03 17:03
related to this: https://github.com/sequelize/sequelize/issues/7606

**Comment by sushantdhiman** [comment] 2017-12-03 04:23
Duplicate of https://github.com/sequelize/sequelize/issues/8041

**Closed by sushantdhiman** 2017-12-03 04:23 UTC

**Comment by niksudan** [comment] 2017-12-05 11:06
@sushantdhiman This is issue 8041 - did you close this by mistake?

**Comment by kartik-proctur** [comment] 2018-11-15 12:06
Do Anyone have solution for this??

**Comment by RahmatAliMalik5** [comment] 2019-09-20 05:36
I have the same issue. I have updated the `sequelize` and it solved my problem...
