### ISSUE TITLE
Can  support MySQL full-text indexing? Does Op.match currently only support PG

### ISSUE THREAD

**Issue by lwmxiaobei** [sequelize/sequelize#16267] opened 2023-07-14 10:03 UTC
Can support MySQL full-text indexing? Does Op.match currently only support PG

<img width="498" alt="image" src="https://github.com/sequelize/sequelize/assets/16284775/77429003-c763-487c-b408-9ae6f3100edd">

**Comment by WikiRik** [comment] 2023-07-15 20:26
Closing this as it's a duplicate of #16266

**Closed by WikiRik** 2023-07-15 20:26 UTC
Labels: type: bug, pending-approval
