### ISSUE TITLE
Calling MODE INOUT store procedure in Sequelize 

### ISSUE THREAD

**Issue by ahsanvbase** [sequelize/sequelize#3902] opened 2015-06-09 11:22 UTC
I've created INOUT mode store procedure in MySQL, i'm sending the response in message variable  from Store Procedure and in navicat i'm running the following raw query to call store procedure and fetch message 

```mysql
CALL createCoupon(1236,321, @message);
SELECT @message AS message
```

now i need to call this Store Procedure in Sequelize, i've tried calling it as one query as

```
var createCouponSQL = "CALL createCoupon(1236,321, @message);";
          createCouponSQL += "SELECT @message AS message";

    sequelize.query(createCouponSQL, null, {
        raw: true
    }).success(function(createCoupon) {
            sails.log.info(createCoupon);
            setCouponResponse(null, createCoupon);
    }).error(function(err) {
        sails.log.error(err);
            setCouponResponse(err, null);
    });
```

but sequelize trigger the error 

```
Executing (default): CALL createCoupon(1236,321, @message);SELECT @message AS m
essage
error: Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the m
anual that corresponds to your MySQL server version for the right syntax to use
 near 'SELECT @message AS message' at line 1
    at Query.Sequence._packetToError (C:\Users\asd\Desktop\Website\
node_modules\mysql\lib\protocol\sequences\Sequence.js:30:14)
```

is there any way to call this Store Procedure in sequelize sailsjs project ?

**Comment by janmeier** [comment] 2015-06-09 12:15
You could set multiple statements to true:

```js
new Sequelize(... ,{
  dialectOptions: {
     multipleStatements: true
  }
}
```
Or run two seperate queries in a transaction

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).

**Closed by janmeier** 2015-06-09 12:15 UTC

**Comment by ahsanvbase** [comment] 2015-06-09 14:03
@janmeier may be i'm doing it wrong way but i want to clear you that whenever i try to run it in sequelize like two queries it don't return proper result and 2 out of 10 request return the null in message object.

I've tried following examples

      sequelize.query(createCouponSQL, null, {
          raw: true
      }).success(function(createCoupon) {
          sails.log.info('1', createCoupon);
              sequelize.query(createCouponSQL1, null, {
                  raw: true
              }).success(function(createCoupon1) {
                  sails.log.info('2', createCoupon1)
              })
          setCouponResponse(null, createCoupon);
      }).error(function(err) {
          sails.log.error(err);
          setCouponResponse(err, null);
      });


AND 
    var chain = new Sequelize.Utils.QueryChainer();

    chain
    .add(sequelize.query(createCouponSQL, null, { raw: true }))
    .add(sequelize.query(createCouponSQL1, null, { raw: true, plain: true }))
    .run()
    .success(function(results) {
      sails.log.info(results);
    })


and the object i get in case it's not working properly is
info:  [ { message: null } ]

Also i need to tell you whenever i run this store procedure in some mysql tool like Navicat it returns 100% proper result on each try.

is there any proper way to call INOUT MODE Store Procedure in Seqeulize, like we use .update OR .find OR i need to run raw query, and if Raw query is only the solution then how can i call this without getting corrupted.

Please Guide.

Thanks.

**Comment by janmeier** [comment] 2015-06-09 14:10
Querychainer makes me think that you are using a very old version. I'd recommend you to update to latest 2 / 3 version since 1.7 and old 2 versions have exactly the problems with raw queries that you describe

**Comment by ahsanvbase** [comment] 2015-06-09 14:23
@janmeier  I've updated the sequelize version to ```3.2.0```, but the project is not running now and it's saying 

```Error: Sequelize.query was refactored to only use the parameters `sql` and `options`. Please read the changelog about BC.```

I'm stuck here , there are thousand of raw & other queries like using .update OR find method of sequelize in my project .. 

Please suggest what should i do now ?

**Comment by janmeier** [comment] 2015-06-09 14:29
Well, do what it says :). There is no way to undo backwards-compat breaks, thats why they are breaking changes.

I'm not trying to be rude here, but we've changed the API, and you'll have to change your code accordingly to get the new functionality.

Perhaps you could create a small sample project and test that the newest version fixes the issue. If not, create a new issue with a small, complete, reproducible testcase and we can take it from there.

Perhaps you could overwrite the `sequelize.query` function in your own code to map calls between the old and new style

**Comment by janmeier** [comment] 2015-06-09 14:30
Also, the BC break only concerns `sequelize.query`, not any methods used on models. So if you are using the ORM to the fullest there shouldn't be too much work ;)
