### ISSUE TITLE
Nested include with limit and order generates incorrect SQL

### ISSUE THREAD

**Issue by a60814billy** [sequelize/sequelize#8321] opened 2017-09-17 17:39 UTC
## What are you doing?

The code in line 39 (`return User.findAll( ...`) is to find top 25 users and their Posts, then order by users createdAt time

```js
'use strict'

const Sequelize = require('sequelize')

const sequelize = new Sequelize('postgres://user@localhost:5432/test', {
  logging: console.log
})

const User = sequelize.define('User', {
  id: {
    type: Sequelize.UUID,
    primaryKey: true
  },
  username: Sequelize.STRING,
  password: Sequelize.STRING,
  createdAt: Sequelize.DATE,
  updatedAt: Sequelize.DATE
})
const Post = sequelize.define('Post', {
  id: {
    type: Sequelize.UUID,
    primaryKey: true
  },
  title: Sequelize.STRING,
  content: Sequelize.STRING,
  ownerId: Sequelize.UUID,
  createdAt: Sequelize.DATE,
  updatedAt: Sequelize.DATE
})

User.hasMany(Post, {foreignKey: 'ownerId', as: 'ownedPost'})
Post.belongsTo(User, {foreignKey: 'ownerId', as: 'owner'})

sequelize.authenticate()
  .then(() => {
    return sequelize.sync()
  })
  .then(() => {
    return User.findAll({
      limit: 25,
      include: ['ownedPost'],
      order: ['createdAt']
    }).then((result) => {
      console.log(result)
      return sequelize.close()
    })
  })

```

## What do you expect to happen?

expect order both in subquery and main query.
it works correctly in sequelize <= 4.8.3

```sql
SELECT "User".*, "ownedPost"."id" AS "ownedPost.id", "ownedPost"."title" AS "ownedPost.title", "ownedPost"."content" AS "ownedPost.content", "ownedPost"."ownerId" AS "ownedPost.ownerId", "ownedPost"."createdAt" AS "ownedPost.createdAt", "ownedPost"."updatedAt" AS "ownedPost.updatedAt" 
FROM (
    SELECT "User"."id", "User"."username", "User"."password", "User"."createdAt", "User"."updatedAt" FROM "Users" AS "User" ORDER BY "User"."createdAt" LIMIT 25) AS "User" 
LEFT OUTER JOIN "Posts" AS "ownedPost" ON "User"."id" = "ownedPost"."ownerId"
ORDER BY "User"."createdAt"
```

## What is actually happening?

but in sequelize 4.8.4, in main query isn't order users createdAt, therefore the result is incorrect. maybe it's caused by https://github.com/sequelize/sequelize/pull/8278

```sql
SELECT "User".*, "ownedPost"."id" AS "ownedPost.id", "ownedPost"."title" AS "ownedPost.title", "ownedPost"."content" AS "ownedPost.content", "ownedPost"."ownerId" AS "ownedPost.ownerId", "ownedPost"."createdAt" AS "ownedPost.createdAt", "ownedPost"."updatedAt" AS "ownedPost.updatedAt" 
FROM (
  SELECT "User"."id", "User"."username", "User"."password", "User"."createdAt", "User"."updatedAt" 
  FROM "Users" AS "User" 
  ORDER BY "User"."createdAt" LIMIT 25) AS "User" 
LEFT OUTER JOIN "Posts" AS "ownedPost" ON "User"."id" = "ownedPost"."ownerId";
```

__Dialect:__ postgres
__Dialect version:__ pg:7.3.0, pg-hstore: 2.3.2
__Database version:__ 9.6.5
__Sequelize version:__ 4.8.4
__Tested with master branch:__ YES

**Comment by Alexsey** [comment] 2017-09-19 09:51
You didn't describe the problem. What is happening wrong?

**Comment by danconnell** [comment] 2017-09-19 20:10
@Alexsey The problem is caused by your change from https://github.com/sequelize/sequelize/pull/8278.

The old behaviour of sequelize worked because if you selected the attribute you were ordering by, then you could order on the outer query. After your change, the order by is only in the inner query so any left joins break the ordering.

I don't know what the correct solution is here, since your original issue that you made the change for is also a valid problem (which I've encountered), but is resolvable by including that attribute in the query. The problem described in this issue is also valid and requires the order to also be present on the outer query. 

My initial reaction is that your change should be rolled back until a proper solution is made as the new behaviour is a breaking change since the results are not correctly ordered (which in the case of something like an inbox is bad).

**Comment by Alexsey** [comment] 2017-09-19 20:55
@danconnell while you do common left joins everything should be ok. If you have one - could you please provide a complete minimal example of code that reproduce the issue?

**Comment by danconnell** [comment] 2017-09-20 02:31
@Alexsey I made a pull request https://github.com/sequelize/sequelize/pull/8341 of an example that passes on v4.8.3 and doesn't pass on v4.8.4. Let me know if you need anything more.

**Comment by hiradimir** [comment] 2017-09-20 10:43
I have same problem.

I think query-generator have to also add "order" to main query.
Because result of main-query order is in disorder;

**Comment by yonjah** [comment] 2017-09-21 02:03
I think this might only be reproducible with MariaDB.
I'm getting local test fail when using MariaDB(10.1.21) but they are not failing on TravisCI -

`findCount` at https://github.com/sequelize/sequelize/blob/master/test/integration/associations/belongs-to.test.js#L888 generates a query that does not actually follow the order and causes the test to fail-

```sql
SELECT `entry`.*, `mail->recipients`.`id` AS `mail.recipients.id`, `mail->recipients->MailRecipients`.`mailId` AS `mail.recipients.MailRecipients.mailId`, `mail->recipients->MailRecipients`.`recipientId` AS `mail.recipients.MailRecipients.recipientId` FROM (SELECT `entry`.`id`, `entry`.`ownerId`, `entry`.`mailId`, `mail`.`id` AS `mail.id` FROM `entries` AS `entry` INNER JOIN `mails` AS `mail` ON `entry`.`mailId` = `mail`.`id` WHERE ( SELECT `mail`.`id` FROM `mails` AS `mail` INNER JOIN ( `MailRecipients` AS `recipients->MailRecipients` INNER JOIN `users` AS `recipients` ON `recipients`.`id` = `recipients->MailRecipients`.`recipientId` AND `recipients->MailRecipients`.`recipientId` = 1) ON `mail`.`id` = `recipients->MailRecipients`.`mailId` WHERE `entry`.`mailId` = `mail`.`id` LIMIT 1 ) IS NOT NULL ORDER BY `entry`.`id` DESC LIMIT 0, 10) AS `entry` INNER JOIN ( `MailRecipients` AS `mail->recipients->MailRecipients` INNER JOIN `users` AS `mail->recipients` ON `mail->recipients`.`id` = `mail->recipients->MailRecipients`.`recipientId` AND `mail->recipients->MailRecipients`.`recipientId` = 1) ON `mail.id` = `mail->recipients->MailRecipients`.`mailId`;
```

**Comment by danconnell** [comment] 2017-09-21 02:48
It's not only reproducible on MariaDB, it just depends on the ordering of the included relation. The test that I wrote I was running Postgres and it passes on v4.8.3 and fails on v4.8.4.

It would be great to get a quick fix for this issue in by reverting https://github.com/sequelize/sequelize/pull/8278, since I really want the changes from 4.9.0.

**Comment by sushantdhiman** [comment] 2017-09-24 06:07
Reverted in https://github.com/sequelize/sequelize/commit/79485c3c59a62d43db70e1bad0765e2a7c7d0d50

It should be fixed in latest release

**Closed by sushantdhiman** 2017-09-24 06:07 UTC

**Comment by keyiis** [comment] 2017-10-09 10:18
I  have same problem.does this fixed the problem?

**Comment by keyiis** [comment] 2017-10-09 10:31
This issues still in 4.13.6

**Comment by danconnell** [comment] 2017-10-09 12:12
It was fixed for me @keyiis. I haven't been able to upgrade to 4.12.0 though, because something is broken with `separate: true` on it that I haven't had time yet to reproduce

**Comment by keyiis** [comment] 2017-10-10 01:54
@danconnell if i add order to a query(has include) options,like below
```
return Item.findAll({
      include: [{
           model:Cat,as cat
      }],
      order: [['inPrice','desc']]
    });
```
it will generate incorrect sql,the order  occurs 2 times
```
SELECT `item`.*, `cat`.`fid` AS `cat.id`, `cat`.`fname` AS `cat.name` 
FROM (SELECT `item`.`id`, `item`.`fcode` AS `code`, `item`.`fname` AS `name`,`item`.`finprice` AS `inPrice` FROM `kpos_item` AS `item` ORDER BY `item`.`finprice` DESC LIMIT 10) AS `item` LEFT OUTER JOIN `kpos_cat` AS `cat` ON `item`.`fcat` = `cat`.`id` ORDER BY `item`.`finprice` DESC; 
```
**error**
`SequelizeDatabaseError: SQLITE_ERROR: no such column: item.finprice`

**Comment by danconnell** [comment] 2017-10-10 02:01
The order is supposed to occur twice. If it didn't, you could get results returned in an incorrect order depending on your data. You need to make sure to explicitly select the attributes you want returned so that it can be ordered by that column

**Comment by keyiis** [comment] 2017-10-10 02:20
@danconnell the order field is dynamic,so i need explicitly select all attributes?
  in sequelize 3.9,the code work well, if not include,the generate sql is correct.

**Comment by danconnell** [comment] 2017-10-10 11:12
I don't know. Your problem sounds more like the problem that was attempted to be solved by https://github.com/sequelize/sequelize/pull/8278 but ended up causing other misordering issues which is what this issue is about. All I know is the ordering issue has been resolved.

**Comment by keyiis** [comment] 2017-10-16 03:43
@danconnell thanks reply! i opened new issues [https://github.com/sequelize/sequelize/issues/8449](url).
