### ISSUE TITLE
require `Model#findAll` to have a `where` clause

### ISSUE THREAD

**Issue by defunctzombie** [sequelize/sequelize#2998] opened 2015-01-24 23:13 UTC
I have been bitten a number of times by forgetting to have a `where` clause in my use of `findAll` or `find`.

I think a nice default behavior would be to require the presence of a `where` field in the object unless the user has specified they don't want a `where` field via an option.

This is dangerous and leads to no filtering happening and no error typically.
```js
User.find({ user_id: '...' })
```

The developer instead meant to use ```User.find({ where: { user_id: '...' }})``` but overlooked it.

**Comment by mickhansen** [comment] 2015-01-25 09:26
Yeah i've been bitten once or two myself and you should think i would know the syntax.
It's something i've been thinking about, and i think i agree for `find`, i'm not quite sure about `findAll` though.

But i suppose there could be an argument for forcing the same behaviour as for `update` and `destroy` where you must define `where` and define it empty if you explicitely want it empty.

@janmeier

**Comment by janmeier** [comment] 2015-02-01 12:50
Automatically moving the attributes from the main objcet into `where` if `where` is not set does not sound good to me. 

Throwing an explict error sounds good, to keep consistent with `update` and `destroy` as mick said

**Comment by harto** [comment] 2016-04-08 18:06
> require the presence of a `where` field in the object

Would it alternatively be possible to error on attributes that don't appear in some whitelist? (`where`, `include`, etc).

**Comment by mickhansen** [comment] 2016-04-09 14:15
@harto We want to allow non-sequelize options since it's usefull to plugins and hooks.

**Comment by harto** [comment] 2016-04-09 16:51
Ah, I see. Thanks for clarifying.

**Comment by sushantdhiman** [comment] 2016-06-01 15:42
Duplicate of #5322 @mickhansen @janmeier

**Closed** 2016-06-02 08:24 UTC
Labels: discussion
