### ISSUE TITLE
MySQL JSON column type?

### ISSUE THREAD

**Issue by wzup** [sequelize/sequelize#6562] opened 2016-09-07 17:08 UTC
https://dev.mysql.com/doc/refman/5.7/en/json.html

> As of MySQL 5.7.8, MySQL supports a native JSON data type that enables efficient access to data in JSON (JavaScript Object Notation) documents.

Do you eventually support?

**Comment by noderat** [comment] 2016-09-07 17:50
Duplicate of #4727

**Comment by felixfbecker** [comment] 2016-09-07 18:18
Yep, thanks!

**Closed by felixfbecker** 2016-09-07 18:18 UTC
Labels: duplicate
