### ISSUE TITLE
v4 to v5 | Problem with sequelize structure, Sequelize module methods auto-complete not working

### ISSUE THREAD

**Issue by neilveil** [sequelize/sequelize#11250] opened 2019-07-30 12:51 UTC
I'm a developer and I've been using sequelize from last few years. MySQL, MSSQL etc are so vast and updating, I understand that it's hard to cover everything in one ORM. You must have resolved a lot of things in v5 but there is a serious issue that I'm facing right now is auto-complete feature in my code editor (VS code). It might not a big thing for you but for me as a developer it's huge because we developers are totally dependent on this small feature which is removed in v5 as now we are extending sequelize models class. And just because of this I don't want to migrate to v5, it's really useless for me.

**Comment by sushantdhiman** [comment] 2019-07-30 13:03
I don't know how we can control VS-Code auto complete but perhaps https://github.com/sequelize/sequelize/issues/8616#issuecomment-502097536 could help?

**Comment by papb** [comment] 2019-07-30 13:18
Duplicate of #11103

**Comment by neilveil** [comment] 2019-07-30 15:50
@sushantdhiman  @papb You didn't understand..

Assume I have created a model named `Users`

Earlier I used to get suggestion like `Users.create` or `Users.update`, but in v5 `Users` is class which extends sequelize.models, and with this structure any code editor can't auto-complete

I am not talking about sequelize module auto-complete, it works!

It's not a duplicate issue!!!

**Comment by papb** [comment] 2019-07-30 15:56
@neilveil Sorry for the confusion. I have reopened it. Do you think an improvement in the typescript typings could solve this issue?

**Comment by sushantdhiman** [comment] 2019-07-30 15:59
@neilveil May be it will be better if you can share some code for which auto complete does not work. I still don't see how sequelize can fix auto-complete issues for an editor

**Comment by aat2703** [comment] 2019-08-08 13:51
I'm also experiencing this... I've just upgraded sequelize-typescript v4 to v5 and in v5 sequelize-typescript uses the native sequelize typescript mappings... The issue seems to be that for example the CreateOptions does not take the model as input and therefor does not know the class attributes.

If CreateOptions could receive a model of type M, it would work :)

Check on this line:
https://github.com/sequelize/sequelize/blob/488c048ca7d57ee77f817b4cdd2302980a13b47c/types/lib/model.d.ts#L1916

In v4 i could

**Comment by papb** [comment] 2019-08-08 13:57
@aat2703 As @sushantdhiman said, can you show a real example of the autocomplete not working that we can reproduce?

**Comment by aat2703** [comment] 2019-08-08 14:01
Inside the fields: [] attributes cannot be auto-completed or recognized by the IDE

`		Bookings.create(
			event.body.booking,
			{
				fields: [
					'state',
					'type',
					'startDate',
					'endDate',
					'name',
					'phone',
					'email',
					'guests',
					'note',
					'walkIn'
				],
				include: [
					{
						model: Tables,
						as: 'tables',
						association: 'tables'
					},
					{
						model: BookingTableLinks,
						as: 'setTables',
						attributes: [
							'tableID'
						]
					}
				]
			}
		)`

**Comment by papb** [comment] 2019-08-08 16:12
@aat2703 You mean this?

![](https://i.imgur.com/1HnznS3.png)

Autocomplete should work here?

**Comment by aat2703** [comment] 2019-08-08 16:48
Webstorm cannot find the declaration? This works with sequelize-typescript v4 interfaces which generally makes much more sense that native sequelize interfaces...

<img width="706" alt="tenant" src="https://user-images.githubusercontent.com/10488234/62721406-6944c800-ba0c-11e9-8b62-8a0485fcfa7f.png">

Lets look at the difference

sequelize-typescript declaration:
https://github.com/RobinBuschmann/sequelize-typescript/blob/a05f4fcaa619ab04455ca87a39dacbeb8447a2c1/lib/models/Model.d.ts#L239-L241

sequelize declaration:
https://github.com/sequelize/sequelize/blob/488c048ca7d57ee77f817b4cdd2302980a13b47c/types/lib/model.d.ts#L1791-L1795

**Comment by papb** [comment] 2019-08-08 20:37
@aat2703 Can you guide me on how to make this intellisense work?

**Comment by aat2703** [comment] 2019-08-08 21:15
Making FindOptions take a generic type FindOptions<M> and pass it into the WhereOptions. This would make auto-completion work anywhere. What do you think?

```typescript
export type WhereOptions<M> = WhereAttributeHash | AndOperator | OrOperator | Literal | Where | M;

public static findOne<M extends Model>( 
   this: { new (): M } & typeof Model, 
   options?: FindOptions<M>
 ): Promise<M | null>; 
 public static findOne<M extends Model>(this: { new (): M } & typeof Model, options: NonNullFindOptions): Promise<M>;

**Comment by papb** [comment] 2019-08-08 21:32
@aat2703 Thanks for the snippet, although I have to apologize because I wasn't clear... I wanted to ask something else...

What I wanted to ask is: is the behavior you want currently achievable somehow? Some specific IDE, some specific version of sequelize, sequelize-typescript, etc?

**Comment by aat2703** [comment] 2019-08-08 21:47
Yeah, it works great with sequelize-typescript v0.6.11 & sequelize v4.43.2

Its because sequelize-typescript < 1 implements its own interfaces that works as i've described above

**Comment by papb** [comment] 2019-08-08 22:27
@aat2703 ah, I see! Would you be willing to submit a PR?

**Comment by aat2703** [comment] 2019-08-08 22:52
Yeah, i'm working on it right now actually 👍

**Comment by maidanskyi** [comment] 2019-10-06 17:00
@papb any update?
is there opened PR or maybe it's already merged?

**Comment by papb** [comment] 2019-10-06 18:24
@maidanskyi I don't know, @aat2703 was apparently working on it but I don't know the state of their work

**Comment by ThomasEg** [comment] 2019-12-12 10:16
I've previously used https://github.com/RobinBuschmann/sequelize-typescript to make this happen... and it works nicely... why not look at how it is implemented there and reuse it in the core of sequelize?

We would like to sponsor someone to implement this....

**Comment by papb** [comment] 2020-01-16 05:06
Hi @ThomasEg, perhaps @RobinBuschmann himself would have an idea on an easy way to do this?

I am completely out of time currently

**Comment by RobinBuschmann** [comment] 2020-01-16 07:47
Hey, I'm not 100% sure what this issue is exactly about, but type safety and auto completion for model creation is already addressed with this PR #11820 

Regarding `fields` option in `CreateOptions`: I think it means the column names not necessarily the attribute names of the model. (@papb Let me know if I'm mistaken) Since camel cased column names can be converted to underscored names using `underscored` option in `ModelOptions` autocompletion cannot implemented for this.

**Comment by papb** [comment] 2020-01-16 20:40
Thanks for chiming in @RobinBuschmann !

> Regarding `fields` option in `CreateOptions`: I think it means the column names not necessarily the attribute names of the model. (@papb Let me know if I'm mistaken)

This is correct

**Comment by ephys** [comment] 2022-02-05 01:32
There have been a lot of improvements to the typescript typings since this issue was first opened.

I think `FindOptions.attributes` is still pretty loose. Is there anything else that could be improved in our typings?

**Closed** 2022-04-16 13:51 UTC
Labels: type: typescript, status: wip
