### ISSUE TITLE
Syntax error on order by on JSONB column for an include table (postgre)

### ISSUE THREAD

**Issue by fgirard78** [sequelize/sequelize#9983] opened 2018-10-02 18:21 UTC
## What are you doing?

```js
const catalogTable = sequelize.define('catalog', {
	publicId: { type: DataTypes.STRING, allowNull: false },
	tenantId: { type: DataTypes.STRING, allowNull: false },
	context: { type: DataTypes.STRING, allowNull: false },
	status: { type: DataTypes.STRING, allowNull: false },
	businessAccountId: { type: DataTypes.STRING, allowNull: false },
	description: { type: DataTypes.STRING, allowNull: false }

}, {
	name: {
		singular: 'catalog',
		plural: 'catalogs'
	}
});

const itemTable = sequelize.define('catalogItem', {
	publicId: { type: DataTypes.STRING, allowNull: false },
	status: { type: DataTypes.STRING, allowNull: false },
	code: { type: DataTypes.STRING, allowNull: true },
	name: { type: DataTypes.JSONB, allowNull: false },
	description: { type: DataTypes.JSONB, allowNull: false },
	costPrice: { type: DataTypes.DOUBLE, allowNull: true },
	salesPrice: { type: DataTypes.DOUBLE, allowNull: false },
	tags: { type: DataTypes.JSONB, allowNull: false }
}, {
	name: {
		singular: 'catalogItem',
		plural: 'catalogItems'
	}
});

catalogTable.hasMany(itemTable, { onDelete: 'CASCADE' });
itemTable.belongsTo(catalogTable);

const sequelizeResult = catalogTable.findAll({
	include: [{
		model: itemTable,
		required: false
	}],
	order: [
		[itemTable, sequelize.json('name.fr')]
	]
});
```

## What do you expect to happen?
_Sort data using JSONB column in an included table. It work when JSONB column is on the primary table. It'S stop to work when JSONB column is on an included table. 

Example:

main table:  ORDER BY  ("name"#>>'{fr}')
included table: ORDER BY "catalogItems".("name"#>>'{fr}')

the error for this is in postgres\query-generator.js line 205. When parenthesis are removed it works as expected.

Change return `(${quotedColumn}#>>${pathStr})`; for return `${quotedColumn}#>>${pathStr}`;
_

## What is actually happening?
_SequelizeDatabaseError: syntax error at or near \"(\"\n    at Query.formatError (T:\\node_modules\\sequelize\\lib\\dialects\\postgres\\query.js:363:16)\n    at query.catch.err (T:\\node_modules\\sequelize\\lib\\dialects\\postgres\\query.js:86:18)\n    at tryCatcher (T:\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at Promise._settlePromiseFromHandler (T:\\node_modules\\bluebird\\js\\release\\promise.js:512:31)\n    at Promise._settlePromise (T:\\node_modules\\bluebird\\js\\release\\promise.js:569:18)\n    at Promise._settlePromise0 (T:\\node_modules\\bluebird\\js\\release\\promise.js:614:10)\n    at Promise._settlePromises (T:\\node_modules\\bluebird\\js\\release\\promise.js:690:18)\n    at _drainQueueStep (T:\\node_modules\\bluebird\\js\\release\\async.js:138:12)\n    at _drainQueue (T:\\node_modules\\bluebird\\js\\release\\async.js:131:9)\n    at Async._drainQueues (T:\\node_modules\\bluebird\\js\\release\\async.js:147:5)\n    at Immediate.Async.drainQueues (T:\\node_modules\\bluebird\\js\\release\\async.js:17:14)\n    at runCallback (timers.js:789:20)\n    at tryOnImmediate (timers.js:751:5)\n    at processImmediate [as _immediateCallback] (timers.js:722:5)"}_

_SELECT 
	"catalog".*, "catalogItems"."id" AS "catalogItems.id", 
	"catalogItems"."publicId" AS "catalogItems.publicId", 
	"catalogItems"."status" AS "catalogItems.status", 
	"catalogItems"."code" AS "catalogItems.code", 
	"catalogItems"."name" AS "catalogItems.name", 
	"catalogItems"."description" AS "catalogItems.description", 
	"catalogItems"."costPrice" AS "catalogItems.costPrice", 
	"catalogItems"."salesPrice" AS "catalogItems.salesPrice", 
	"catalogItems"."tags" AS "catalogItems.tags", 
	"catalogItems"."createdAt" AS "catalogItems.createdAt", 
	"catalogItems"."updatedAt" AS "catalogItems.updatedAt", 
	"catalogItems"."catalogId" AS "catalogItems.catalogId" 
FROM 
	(
		SELECT 
			"catalog"."id", 
			"catalog"."publicId", 
			"catalog"."tenantId", 
			"catalog"."context", 
			"catalog"."status", 
			"catalog"."businessAccountId", 
			"catalog"."description", 
			"catalog"."createdAt", 
			"catalog"."updatedAt" 
		FROM 
			"catalog"."catalogs" AS "catalog" 
	) AS "catalog" 
	LEFT OUTER JOIN "catalog"."catalogItems" AS "catalogItems" ON "catalog"."id" = "catalogItems"."catalogId"
ORDER BY 
	"catalogItems".("name"#>>'{fr}');_

__Dialect:__ postgres
__Dialect version:__ 
__Database version:__ 9.6
__Sequelize version:__ 4.39.0
__Tested with latest release:__ Yes

**Comment by sushantdhiman** [comment] 2018-10-21 06:41
Duplicate of https://github.com/sequelize/sequelize/issues/9726

**Closed by sushantdhiman** 2018-10-21 06:41 UTC
