### ISSUE TITLE
MySQL, CREATE INDEX renames table to lowercase

### ISSUE THREAD

**Issue by psayre23** [sequelize/sequelize#3598] opened 2015-04-25 17:55 UTC
When creating an index on a MySQL table, running `CREATE INDEX name ON Table (field)` will cause the "Table" to be renamed to lowercase "table". Instead, running `ALTER TABLE Table ADD INDEX name (field)` will keep the table name intact.

**Comment by psayre23** [comment] 2015-04-25 18:00
Here is a simple test case. Tested on Mac v10.10.3, Node.js v0.12.2, MySQL v5.5.42, sequalize (npm) v2.0.6, mysql (npm) v2.6.2.

sequalize.define('SomeTable', {
        field: {
            type: sequalize.STRING
        }
    }, {
        indexes: [
            {
                name: 'name',
                fields: ['field']
            }
        ]
    }).sync()

**Comment by janmeier** [comment] 2015-04-25 18:02
Cannot reproduce this on unix. It seems that table names in mysql are not case sensitive on osx (on HFS volumes)

https://dev.mysql.com/doc/refman/5.0/en/identifier-case-sensitivity.html

What is your setting for `lower_case_table_names` https://dev.mysql.com/doc/refman/5.0/en/server-system-variables.html#sysvar_lower_case_table_names?

**Comment by psayre23** [comment] 2015-04-25 18:04
lower_case_table_names = 2

MySQL table names are not case sensitive, correct. But changing the casing because an index was added with one SQL query vs another is strange behavior. Ideally, the only thing that changes would be the addition of an index.

**Comment by janmeier** [comment] 2015-04-25 18:08
Do you have a link describing this behaviour? I cannot replicate it on Ubuntu.

The query looks correct - is the table name actually lower cased when you do SHOW tables or similar?

**Comment by psayre23** [comment] 2015-04-25 18:15
Here are screenshots of running the same queries generated by Sequelize, and one that I added (alter).

### Create Table
![create table](https://cloud.githubusercontent.com/assets/209575/7334087/5537e3fe-eb3c-11e4-9e74-64006fb36bce.png)

### Create Index
![create index](https://cloud.githubusercontent.com/assets/209575/7334085/5535df5a-eb3c-11e4-8875-4d9baf47d125.png)

### Alter Table
![alter table](https://cloud.githubusercontent.com/assets/209575/7334086/5536903a-eb3c-11e4-8865-8eb0a55bb4c0.png)

**Comment by janmeier** [comment] 2015-04-25 18:18
Oh, I found it now http://bugs.mysql.com/bug.php?id=48875

Since this is a bug in mysql, and you are the first one to report being affected by it, this is not something the sequelize core team is going to fix. Furthermore, as far as I understand this is purely cosmetical, since comparison will still work, correct?

You are welcome to provide a PR that changes how sequelize creates indexes however

**Comment by psayre23** [comment] 2015-04-25 18:18
I just checked the information schema table to make sure it wasn't just my editor being weird. It's lower case there too. This is _totally_ a bug in MySQL and not in Sequelize. Hopefully there is something you can do about it, nonetheless.

**Comment by psayre23** [comment] 2015-04-25 18:18
I'll make a PR now. Thanks for helping. :)

**Comment by janmeier** [comment] 2015-05-18 20:43
Fixed in https://github.com/sequelize/sequelize/commit/c4b5f2af0f4ea1082d98a2c19239cbcf5c83a77c

**Closed by janmeier** 2015-05-18 20:43 UTC
