### ISSUE TITLE
Add TSVECTOR to documentation

### ISSUE THREAD

**Issue by danil212211** [sequelize/sequelize#15521] opened 2023-01-03 17:58 UTC
## Issue Creation Checklist

- [x] I understand that my issue will be automatically closed if I don't fill in the requested information
- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Feature Description
Add TSVECTOR data type to docs
### Describe the feature you'd like to see implemented
Mention TSVECTOR in Other Types artice of Sequelize documentation for v6.

### Describe why you would like this feature to be added to Sequelize
It would be easier for people to understand that they can implement fts with sequelize without too much trouble.

### Is this feature dialect-specific?

- [ ] No. This feature is relevant to Sequelize as a whole.
- [x] Yes. This feature only applies to the following dialect(s): postgres

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I will need guidance.
- [ ] No, I don't have the time, but my company or I are [supporting Sequelize through donations on OpenCollective](https://opencollective.com/sequelize).
- [x] No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in implementing my feature.

---

*Indicate your interest in the addition of this feature by adding the 👍 reaction. Comments such as "+1" will be removed.*

**Comment by WikiRik** [comment] 2023-01-03 22:48
Duplicate of https://github.com/sequelize/website/issues/91

**Closed by WikiRik** 2023-01-03 22:48 UTC
Labels: type: feature, pending-approval
