### ISSUE TITLE
ER_SP_DOES_NOT_EXIST: FUNCTION users.AsText does not exist

### ISSUE THREAD

**Issue by zhfish** [sequelize/sequelize#4715] opened 2015-10-23 10:05 UTC
```
mysql> select `users`.AsText(`location`) from users;
FUNCTION users.AsText does not exist
mysql> select AsText(`location`) from users;
+--------------------+
| AsText(`location`) |
+--------------------+
| POINT(10 10)       |
| POINT(10 10)       |
| POINT(10 10)       |
+--------------------+
3 rows in set (0.05 sec)
```

could i not use `users` default ?

**Comment by zhfish** [comment] 2015-10-23 10:07
select AsText(`users`.`location`) from users;
is right

**Comment by janmeier** [comment] 2015-10-23 10:36
Can you please show the actual sequelize code that produces the issue?

**Comment by zhfish** [comment] 2015-10-23 10:37
```
        yield connect.users.update({
            location: user.location
        },{
            where:{
                ID:user.ID
            }
        });
```

**Comment by janmeier** [comment] 2015-10-23 10:38
And the model definitons, and some actual data?

**Comment by zhfish** [comment] 2015-10-23 10:42
model
```
/* jshint indent: 2 */

module.exports = function(sequelize, DataTypes) {
  return sequelize.define('users', {
    ID: {
      type: 'CHAR(36)',
      allowNull: false,
      defaultValue: '',
      primaryKey: true
    },
    userName: {
      type: DataTypes.STRING,
      allowNull: true
    },
    password: {
      type: DataTypes.STRING,
      allowNull: true
    },
    location: {
      type: DataTypes.GEOMETRY,
      allowNull: true
    }
  });
};

```
data
```
+--------------------------------------+-------------+--------------------------------------------------------------+----------------------------+
| ID                                   | username    | password                                                     | AsText(`users`.`location`) |
+--------------------------------------+-------------+--------------------------------------------------------------+----------------------------+
| 09c20a66-e4c5-4ecd-b8d7-567559847827 | 13800138000 | $2a$10$c9gmMhN4L63K1rmSF4poauzELud8X6MumK./efE/I32mxmo8npeNe | POINT(10 10)               |
| 55d2d8e5-855f-4bdd-b374-b540cd8ec288 | 13800138001 | $2a$10$Vge6nXgY6jw5D4HzeuekoOimF80wSrszkyOCH7vXY2ffgK0qWgsNq | POINT(10 10)               |
| b71ee44e-87a1-4678-b241-081a206d7e80 | 13800138002 | $2a$10$J.zrGp8Vy28jvbxkwaNHqeY.iRc9tOhrRmqUdaCxqjeFv7Soc0Nuq | POINT(10 10)               |
+--------------------------------------+-------------+--------------------------------------------------------------+----------------------------+
3 rows in set (0.03 sec)

```

**Comment by mickhansen** [comment] 2015-10-23 10:58
@zhfish Please add the entire find call.

**Comment by zhfish** [comment] 2015-10-23 13:03
i won't  call asText directly, 
geometry for mysql do it

**Comment by zhfish** [comment] 2015-10-24 13:59
i try to fix it
i'm sorry ,i don't understand how to write unit test

**Comment by mickhansen** [comment] 2015-10-25 17:40
Please include the full query called that errors and it would be helpfull to have a SSCCE.
You can check out the test/ folder for ways to write test cases, specifically look for the geometry tests.

**Comment by alxarch** [comment] 2015-11-06 15:07
The issue is more complex than the solution the proposed patch gives.
This occurs on models that have a GEOMETRY column when used in conjunction
with an `include` option. The abstract query writer for tries to prefix column names with table names for `include` to work properly but the GEOMETRY type uses `selectGeometry()` which in mysql uses a function call (`AsText(column)`).

Things are even worse if the table with the GEOMETRY column is not the primary table. Then `geometrySelect()` is not called at all, returning the blob as column value. 

Currently GEOMETRY type is broken for the `inlcude` option. A proper solution requires checking for GEOMETRY columns in more places in `selectQuery` and passing the `mainTableAs` as an option to `geometrySelect` so it can prefix column names appropriately.

Also a more general solution would require a refactor to handle function calling attributes in more gracefully instead of filling the code up with `if (isGeometrySelect(attr)) { ...` because every function-calling custom column will require special treatment.

**Comment by janmeier** [comment] 2015-11-06 15:09
@alxarch Agreed, thats why the proposed PR has not been merged yet - the solution is too simple, and it includes no tests :(

It would be a great help if you could provide those test cases :=

**Comment by alxarch** [comment] 2015-11-06 16:26
@janmeier I browsed through the [tests](https://github.com/sequelize/sequelize/blob/master/test/integration/dialects/mysql/query-generator.test.js) for mysql query-generator but there is nothing that tests the `include` option. (Although it influences the behavior of `selectQuery` substancially) Is there some place else I should add tests? Having tests for `include` only for GEOMETRY columns is pointless. I could provide examples of failing combinations of `define('Foo', {blah..})` and `Foo.findAll({where: {blah...}, include{blah...})` if that's what you mean. Otherwise I'll need some guidance for writing the appropriate tests

**Comment by alxarch** [comment] 2015-11-06 17:38
@janmeier there seems to exist such a function that it's docstring says it handles function attributes called `query()`. But the code doesn't handle the {fn:'foo'} case. I could start from there for a patch.

**Comment by janmeier** [comment] 2015-11-06 17:50
Those tests are old - we are hoping to migrate them at some point. Unit tests for include sql are here https://github.com/sequelize/sequelize/blob/master/test/unit/sql/select.test.js

Which function are you referring to?

**Comment by alxarch** [comment] 2015-11-06 17:59
I found `dialects/abstract/QueryGenerator.quote()`. As i look through the code, I see that quoting of attr is inconsistent. At some places names are quoted properly with backticks but some cases the names are joined by `.` without quoting the parts. I am trying to add the `fn` case to solve the geometry issue by returning an {fn: 'asText', cols: ['foo']} object from `selectGeometry()`.

**Comment by alxarch** [comment] 2015-11-07 10:19
@janmeier I added a working solution that passes two simple inclusion tests (primary and secondary table). The test only checks mysql dialect. I see in the code that postgres simply returns the geometry value. Does postgres convert geometry to text automatically or should is try to fix this for postgres dialect as well?

**Comment by janmeier** [comment] 2015-12-04 15:27
We no longer use `axText` when selecting geometry

**Closed by janmeier** 2015-12-04 15:27 UTC
