### ISSUE TITLE
Migration on ENUM with postgres dialect: type already exists

### ISSUE THREAD

**Issue by kytwb** [sequelize/sequelize#2554] opened 2014-11-10 05:41 UTC
Deleting previously existing ENUM column and re-creating it but with a different ENUM results in:

```
Executing (default): ALTER TABLE "Trackers" DROP COLUMN "type";
Executing (default): CREATE TYPE "enum_Trackers_type" AS ENUM('image', 'javascript', 'snippet'); ALTER TABLE "Trackers" ADD COLUMN "type" "enum_Trackers_type";
Possibly unhandled SequelizeDatabaseError: error: type "enum_Trackers_type" already exists
```

**Comment by laser** [comment] 2015-01-09 19:23
@kytwb 

> Any idea how to correctly edit enum values through migration then?

I was able to modify an ENUM by:

1. Modifying the array assigned to the `values` property of the configuration object passed as the second argument to `sequelize.define` to include a new value
2. Create a migration in which the `up` simply calls `ModelNameHere.sync()`

That generated the SQL statements required to modify the ENUM-type to match what I'd expressed in JavaScript code.

Erin

**Comment by kytwb** [comment] 2015-03-22 16:17
@laser Tried what you said, it does work when you add only one new value at a time. 

```
Executing (default): ALTER TYPE "enum_warehouses_type" ADD VALUE 'postmaster' BEFORE 'amazon'
Executing (default): ALTER TYPE "enum_warehouses_type" ADD VALUE 'amazon' AFTER 'postmaster'
Possibly unhandled SequelizeDatabaseError: "amazon" is not an existing enum label
```

`amazon` and `postmaster` being the two new values here.

**Comment by Victor08** [comment] 2016-02-06 18:45
I am facing the same issue. I was able to bypass it with using raw query
```
module.exports = {
  up: function (queryInterface, Sequelize) {
    return queryInterface.sequelize.query("CREATE TYPE \"enum_users_sellerAccountType\" AS ENUM(\'sa\', \'sm\'); ALTER TABLE \"users\" ADD COLUMN \"sellerAccountType\" \"enum_users_sellerAccountType\";");
  },

  down: function (queryInterface, Sequelize) {
    return queryInterface.sequelize.query("DROP TYPE \"enum_users_sellerAccountType\"; ALTER TABLE \"users\" DROP COLUMN \"sellerAccountType\";");
  }
};
```
Is it a bug in sequelize, that causes enum migration to fail?

**Comment by delveintechnolabs** [comment] 2016-03-12 08:28
Facing same issue. To add to the problem, sequelize only allows changing `default value`, `allowance of null` or the `data type`. If you want to change some other attribute of a column, you will have to find a hack for it.

**Comment by thealmightygrant** [comment] 2016-10-04 21:37
Heads up that if you are decide to do raw queries like @Victor08 points out above, the down migration should drop the column first so that nothing depends on the data type, like this:
```js
 down: function (queryInterface, Sequelize) {
    return queryInterface.sequelize.query("ALTER TABLE \"users\" DROP COLUMN \"userType\"; DROP TYPE \"enum_users_userType\";");
  }
```

**Comment by felixfbecker** [comment] 2016-10-05 08:13
We have `QueryInterface.dropAllEnums()`, I think we should add a simple `dropEnum()` method.

**Comment by kgalli** [comment] 2017-02-21 10:01
@felixfbecker is there an update on the `dropEnum()` method? This would really be very handy. What is the context of `QueryInterface.dropAllEnums()`? Is it the whole database or maybe a table?

**Comment by felixfbecker** [comment] 2017-02-21 10:04
No, there is no update. Can't answer your second question.

**Comment by markelog** [comment] 2017-07-18 13:05
This is still an issue

**Comment by mariano-aguero** [comment] 2017-09-08 17:57
This is how I solved it, not the best way but it allows adding a new field with an existing enum without it throwing an error.

```
queryInterface.addColumn(
            'Users',
            'language', {
                type: Sequelize.ENUM('nl', 'en'),
                allowNull: false,
                defaultValue: 'nl'
            }).then(function (response) {
                console.log(response);
                done();
            }).catch(function (err) {
                return queryInterface.sequelize.query(`ALTER TABLE "Users" ADD COLUMN "language" "public"."enum_Users_language" NOT NULL DEFAULT 'nl';`)
                    .then(function (response) {
                        console.log(response);
                        done();
                    }).catch(function (err) {
                        done();
                    });
            });
```

**Comment by Edudjr** [comment] 2017-09-15 17:24
finally got it working:

```javascript
'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.sequelize.query("ALTER TYPE enum_type_name ADD VALUE 'new_value'");
  },

  down: (queryInterface, Sequelize) => {
    var query = 'DELETE FROM pg_enum ' +
      'WHERE enumlabel = \'new_value\' ' +
      'AND enumtypid = ( SELECT oid FROM pg_type WHERE typname = \'enum_type_name\')';
    return queryInterface.sequelize.query(query);
  }
};
```
change **enum_type_name** and **new_value** to fit your needs.

**Comment by JustBlackBird** [comment] 2017-09-25 20:36
Any plans for adding `QueryInterface.dropEnum()` method?

**Comment by ajmueller** [comment] 2017-10-20 02:18
@Edudjr that almost worked for me, but I had to make an ever so slight change to your `up` function:

```javascript
up: (queryInterface, Sequelize) => {
    return queryInterface.sequelize.query(`ALTER TYPE "enum_type_name" ADD VALUE 'new_value'`);
}
```

As you can see, I had to wrap my enum name in double quotes; for whatever reason, that's how Sequelize created my enum, so without the double quotes I got a "type does not exist" error.  I'm not sure if this is a standard for Sequelize, but I figured I'd post my findings here in case anyone else ran into a similar issue.  Also note that due to the use of both single and double quotes, I wrapped the query in tick marks since I'm using a new enough version of Node that supports template strings, thereby avoiding the need to escape any strings.

**Comment by abelosorio** [comment] 2017-11-14 12:47
See my comment https://github.com/sequelize/sequelize/issues/7151#issuecomment-344246084.

I've written a function to entirely replace the ENUM. It works inside a transaction and supports default value.

Hope you find it helpul.

**Comment by theSuiGenerisAakash** [comment] 2018-02-13 19:51
I asked this on SO [here](https://stackoverflow.com/questions/48730477/sequelize-migration-queryinterface-removecolum-fails-to-work) and this is something sweet and simple that seems to be doing it

`down: (queryInterface, Sequelize) =>  
    queryInterface.removeColumn('Books', 'Rating')
      .then(() => queryInterface.sequelize.query('DROP TYPE "enum_Books_Rating";'));
  };`

**Comment by tomprogers** [comment] 2018-06-05 20:58
The best way to modify enum values is to [`queryInterface.changeColumn`](https://github.com/sequelize/sequelize/issues/7151#issuecomment-275444651):

```
module.exports = {
  up  : function (queryInterface, Sequelize) {
    return queryInterface
      .changeColumn(tableName, 'status', {
        type: Sequelize.ENUM('a', 'b', 'c', 'd'),
        allowNull: false
      });
  },
  down: function (queryInterface, Sequelize) {
    return queryInterface
      .changeColumn(tableName, 'status', {
        type: Sequelize.ENUM('a', 'b', 'c'),
        allowNull: false
      });
  }
};
```

**Comment by naartjie** [comment] 2018-06-10 10:54
> The best way to modify enum values is to queryInterface.changeColumn:

@tomprogers does it work with Postgres?

**Comment by jraut** [comment] 2018-06-18 10:17
@naartjie @tomprogers  No, it does not seem to work on Postgres. ```ERROR: type "tableName_status" already exists```

**Comment by abelosorio** [comment] 2018-06-18 13:08
@naartjie @tomprogers @jraut is not possible to "change" an enum in Postgres. You have to destroy it and create it again with the new values.

Checkout this issue https://github.com/sequelize/sequelize/issues/7151 and this comment https://github.com/sequelize/sequelize/issues/7151#issuecomment-344246084.

I created this npm package to change enums in Postgres: https://www.npmjs.com/package/sequelize-replace-enum-postgres. Hope it helps.

Good luck!

**Closed** 2018-07-16 07:08 UTC
Labels: bug, feature

**Comment by robcresswell** [comment] 2018-08-20 15:34
@abelosorio It seems like you've been able to alter ENUMs since at least Postgres 9.1https://www.postgresql.org/docs/9.1/static/sql-altertype.html so I'm not sure why you are saying it isn't possible. Can we get this issue reopened @sushantdhiman ?

**Comment by rostismal** [comment] 2018-12-17 07:01
is not fixed

**Comment by DaddyWarbucks** [comment] 2019-04-10 16:54
This may be a bit off topic to this particular thread, but I wanted to post my solution to a similar problem incase anyone ends up here like I did.

I was trying to set an ENUM along with `allowNull: true`, then do a bulk update, and then `changeColumn` to `allowNull: false`

```
await queryInterface.addColumn(
        'payments',
        'entity_type',
        {
          type: Sequelize.ENUM,
          allowNull: true // set to true to allow bulk update
          values: [SHIPPER, CARRIER]
        },
        { transaction }
      );

await queryInterface.bulkUpdate(
        'payments',
        {
          entity_id: 1,
          entity_type: SHIPPER
        },
        {},
        { transaction }
      );

await queryInterface.changeColumn(
        'payments',
        'entity_type',
        {
          type: Sequelize.ENUM,
          allowNull: false,
          values: [SHIPPER, CARRIER]
        },
        { transaction }
      );
```

^^ This code threw the error `enum_payments_entity_type already exists`. Even when trying to manually drop it, alter the column, etc, I could never get it to work.
My solution was to set the column as a STRING first, then come back and set it as an ENUM.

```
await queryInterface.addColumn(
        'payments',
        'entity_type',
        {
          type: Sequelize.STRING, // NOTE THIS IS A STRING
          allowNull: true // set to true to allow bulk update
        },
        { transaction }
      );

await queryInterface.bulkUpdate(
        'payments',
        {
          entity_id: 1,
          entity_type: SHIPPER
        },
        {},
        { transaction }
      );

await queryInterface.changeColumn(
        'payments',
        'entity_type',
        {
          type: Sequelize.ENUM,
          allowNull: false,
          values: [SHIPPER, CARRIER]
        },
        { transaction }
      );
```

I am not very well versed in Sequelize (or in RDMS in general) but this bug kicked my butt. Hopefully if this is helpful to someone. And if this is bad practice, feel free to downvote it and tell me why.

**Comment by Dakkers** [comment] 2019-07-16 18:24
still not fixed 😭

**Comment by Otavioensa** [comment] 2019-07-23 17:57
I'm still running on the same problem

**Comment by Otavioensa** [comment] 2019-07-23 17:58
This issue should definitely be reopened

**Comment by papb** [comment] 2019-07-23 18:11
Hello, this thread is very long and was closed twice already... Can someone please provide an up-to-date [MVCE](https://stackoverflow.com/help/minimal-reproducible-example) for this? Something that I can just copy+paste and run and see the problem. If I can easily reproduce it, I will reopen this issue. Thanks!!

**Comment by MaxMls** [comment] 2019-12-14 06:23
i have this problem with code:

```
module.exports = (sequelize, DataTypes) => {
	const tag = sequelize.define('tag', {
		name: {allowNull: false, type: DataTypes.TEXT},
		type: {allowNull: false, type: DataTypes.ENUM('lang', 'category', 'author')}
	}, {});
	tag.associate = function (models) {
		tag.belongsToMany(models.chapter, {through: 'titlesTags'});

		tag.belongsToMany(models.user, {through: 'tagBlackList'});

	};
	return tag;
};
```
error:
`(node:24616) UnhandledPromiseRejectionWarning: SequelizeDatabaseError: тип "enum_tags_type" уже существует`

**Comment by papb** [comment] 2020-01-16 05:49
I think issues #2577 and #7649 cover everything mentioned in this issue already.

**Comment by navsaini53** [comment] 2022-03-03 11:39
> @janmeier: Any idea how to correctly edit enum values through migration then?



> We have `QueryInterface.dropAllEnums()`, I think we should add a simple `dropEnum()` method.

test

**Comment by navsaini53** [comment] 2022-03-03 11:39
> > @janmeier: Any idea how to correctly edit enum values through migration then?
> 
> > We have `QueryInterface.dropAllEnums()`, I think we should add a simple `dropEnum()` method.
> 
> test

agai test

**Comment by RasenGUY** [comment] 2022-09-11 17:22
> @kytwb
> 
> > Any idea how to correctly edit enum values through migration then?
> 
> I was able to modify an ENUM by:
> 
>     1. Modifying the array assigned to the `values` property of the configuration object passed as the second argument to `sequelize.define` to include a new value
> 
>     2. Create a migration in which the `up` simply calls `ModelNameHere.sync()`
> 
> 
> That generated the SQL statements required to modify the ENUM-type to match what I'd expressed in JavaScript code.
> 
> Erin

this works thanks for sharing.
