### ISSUE TITLE
Asycn Await with Relationship

### ISSUE THREAD

**Issue by Wikiko** [sequelize/sequelize#10740] opened 2019-04-09 17:11 UTC
## What are you doing?
When I use a method that is BelongsToManyCreateAssociationMixin<RealEstate> and that throw an exception, the async await don't capture that to the try catch statement. 

```js
// the BaseModel is just a class that extends Model

// UserEntity

class User extends BaseModel implements UserAttributes {
    public id!: number;

    public email!: string;

    public cellphone?: string;

    public active!: boolean;

    public getRealEstateAgencies!: BelongsToManyGetAssociationsMixin<RealEstateAgency>;

    public addRealEstateAgency!: BelongsToManyAddAssociationMixin<RealEstateAgency, number>;

    public hasRealEstateAgency!: BelongsToManyHasAssociationMixin<RealEstateAgency, number>;

    public countRealEstateAgencies!: BelongsToManyCountAssociationsMixin;

    public createRealEstateAgency!: BelongsToManyCreateAssociationMixin<RealEstateAgency>;

    public readonly realEstateAgencies?: RealEstateAgency[];

    public static associate(models: Models): typeof User {
        User.belongsToMany(models.RealEstateAgency, {
            through: models.RealEstateAgencyUser,
            foreignKey: 'userId',
        });

        return User;
    }
}

function initUser(sequelize: Sequelize): typeof User {
    User.init({
        id: {
            type: DataTypes.INTEGER.UNSIGNED,
            autoIncrement: true,
            primaryKey: true,
        },
        email: {
            type: DataTypes.STRING,
            allowNull: false,
            unique: true,
        },
        cellphone: {
            type: DataTypes.STRING,
            allowNull: true,
            unique: true,
        },
        active: {
            type: DataTypes.BOOLEAN,
            allowNull: false,
            defaultValue: true,
        },
    }, {
        name: {
            singular: 'user',
            plural: 'users',
        },
        sequelize,
    });

    return User;
}

export {
    initUser,
};

export default User;

// RealEstateAgency
import {
    Sequelize,
    DataTypes,
    BelongsToManyGetAssociationsMixin,
    BelongsToManyAddAssociationMixin,
    BelongsToManyHasAssociationMixin,
    BelongsToManyCountAssociationsMixin,
    BelongsToCreateAssociationMixin,
} from 'sequelize';

import {
    Models,
    RealEstateAgencyAttributes,
} from './types';
import BaseModel from './BaseModel';
import { User } from '.';


class RealEstateAgency extends BaseModel implements RealEstateAgencyAttributes {
    public id!: number;

    public name!: string;

    public systemIdentifier!: string;

    public getUsers!: BelongsToManyGetAssociationsMixin<User>;

    public addUser!: BelongsToManyAddAssociationMixin<User, number>;

    public hasUser!: BelongsToManyHasAssociationMixin<User, number>;

    public countUser!: BelongsToManyCountAssociationsMixin;

    public createUser!: BelongsToCreateAssociationMixin<User>;

    public static associate(models: Models): typeof RealEstateAgency {
        RealEstateAgency.belongsToMany(models.User, {
            through: models.RealEstateAgencyUser,
            foreignKey: 'realEstateAgencyId',
        });
        return RealEstateAgency;
    }
}

function initRealEstateAgency(sequelize: Sequelize): typeof RealEstateAgency {
    RealEstateAgency.init({
        id: {
            type: DataTypes.INTEGER.UNSIGNED,
            autoIncrement: true,
            primaryKey: true,
        },
        name: {
            type: DataTypes.STRING,
            allowNull: false,
        },
        systemIdentifier: {
            type: DataTypes.STRING,
            allowNull: false,
        },
        active: {
            type: DataTypes.BOOLEAN,
            allowNull: false,
            defaultValue: true,
        },
    }, {
        name: {
            singular: 'realEstateAgency',
            plural: 'realEstateAgencies',
        },
        sequelize,
    });

    return RealEstateAgency;
}

export {
    initRealEstateAgency,
};

export default RealEstateAgency;


//UserService that error can be throw 

import { Transaction, Sequelize } from 'sequelize';
import { UserAttributes, RealEstateAgencyAttributes } from '../models/types';
import { User } from '../models';

class UserService {
    public async createUserToRealEstateAgency(
        userObject: UserAttributes,
        realEstateAgencyObject: RealEstateAgencyAttributes,
    ): Promise<User> {
        const sequelize = User.sequelize as Sequelize;
        const transaction = await sequelize.transaction() as Transaction;
        try {
            const newUser = await User.create({
                ...userObject,
            }) as User;

            // error can be throw here and don't appear on catch
            await newUser.createRealEstateAgency(realEstateAgencyObject);

            await transaction.commit();

            return newUser;
        } catch (error) {
            await transaction.rollback();
            throw error;
        }
    }
}


export default new UserService();


```

## What do you expect to happen?
Errors inside a promise when use with async await should be put in catch handler.

## What is actually happening?
It's like I have no handled errors.

_Output, either JSON or SQL_

__Dialect:__ mysql and sqlite
__Sequelize version: "^5.2.1"

**Comment by SimonSchick** [comment] 2019-04-11 16:36
@sushantdhiman could this be a CLS problem?

**Comment by SimonSchick** [comment] 2019-04-11 16:38
You have to pass your `transaction` object to the your query operations.
Are you getting an uncaught exception? If yes please post the stack.

**Comment by Wikiko** [comment] 2019-04-11 18:09
When I pass the transaction error continue to be executed.



> You have to pass your `transaction` object to the your query operations.
In my actual code I do that but error continue to be executed.
> Are you getting an uncaught exception? If yes please post the stack.
Yes the error is:
SequelizeForeignKeyConstraintError: SQLITE_CONSTRAINT: FOREIGN KEY constraint failed

      at Query.formatError (node_modules/sequelize/lib/dialects/sqlite/query.js:383:18)
      at Query._handleQueryResponse (node_modules/sequelize/lib/dialects/sqlite/query.js:77:18)
      at Statement.afterExecute (node_modules/sequelize/lib/dialects/sqlite/query.js:260:31)
      at Statement.replacement (node_modules/sqlite3/lib/trace.js:19:31)
      at Statement.replacement (node_modules/sqlite3/lib/trace.js:19:31)

**Comment by SimonSchick** [comment] 2019-04-11 18:21
I need an isolated minimal test case I can run locally please.
I am pretty sure you are just using transaction wrong.

**Comment by Wikiko** [comment] 2019-04-11 18:38
```javascript
import supertest from 'supertest';

import app from '../../../src/app';
import { createUserObject, createRealEstateObject } from '../../faker';
import { User, RealEstateAgency } from '../../../src/app/models';


describe('UserController', () => {
    it('Should create a User and link he to RealEstateAgency', async () => {
        const userMockup = createUserObject();
        const realEstateAgencyMockup = createRealEstateObject();
        const res = await supertest(app)
            .post('/usuarios/imobiliarias')
            .send({
                user: userMockup,
                realEstateAgency: realEstateAgencyMockup,
            });

        const userFound = await User.findOne({
            include: [
                RealEstateAgency,
            ],
            where: {
                email: userMockup.email,
            },
        }) as User;

        expect(res).toHaveProperty('status', 201);
        expect(userFound).not.toBeNull();
        expect(userFound.realEstateAgencies).toHaveLength(1);
    });
});
```

My test case is that and my new code with correct transaction use is that:
```javascript
class UserService {
    public async createUserToRealEstateAgency(
        userObject: UserAttributes,
        realEstateAgencyObject: RealEstateAgencyAttributes,
    ): Promise<User> {
        const sequelize = User.sequelize as Sequelize;
        const transaction = await sequelize.transaction() as Transaction;
        try {
            const user = head(await User.findOrCreate({
                where: {
                    email: userObject.email,
                    cellphone: userObject.cellphone || null,
                },
                transaction,
            })) as User;

            const realEstateAgency = head(await RealEstateAgency.findOrCreate({
                where: {
                    name: realEstateAgencyObject.name,
                    systemIdentifier: realEstateAgencyObject.systemIdentifier,
                },
                transaction,
            })) as RealEstateAgency;

            if (await user.hasRealEstateAgency(realEstateAgency)) {
                await RealEstateAgencyUser.update({ active: true }, {
                    where: {
                        userId: user.id,
                        realEstateAgencyId: realEstateAgency.id,
                    },
                });
            } else {
                await user
                    .addRealEstateAgency(realEstateAgency, { transaction });
            }

            await transaction.commit();
            return user;
        } catch (error) {
            await transaction.rollback();
            throw error;
        }
    }
}
```

**Comment by SimonSchick** [comment] 2019-04-11 19:35
This is not an isolated test case, and I was unable to reproduce this issue at all.
Please provide and *isolated* *minimal* test case, I will close this issue until then.

**Closed by SimonSchick** 2019-04-11 19:35 UTC
Labels: needs more info
