### ISSUE TITLE
BelongsToMany destory with cascade is now working.

### ISSUE THREAD

**Issue by keepcosmos** [sequelize/sequelize#10678] opened 2019-04-01 02:36 UTC
https://github.com/sequelize/sequelize/issues/7149 is not fixed, but closed. nobody reopen it. It's actually bug.

**Comment by ALiangLiang** [comment] 2019-04-01 04:14
Are you set the constraint on pivot tables? Because I found the test script and it's pass. I think you dosen't set the constraint.

https://github.com/sequelize/sequelize/blob/4ec86a4bd43aa65e45546e2d4177ffcbeb2b4bac/test/integration/associations/belongs-to-many.test.js#L2265-2311

**Comment by keepcosmos** [comment] 2019-04-01 04:51
@ALiangLiang 

Sorry, I mean with `paranoid` option. 
It actually run `update` not `delete` -> https://github.com/sequelize/sequelize/blob/master/lib/model.js#L4023

It seems cascade flow does not run.

**Comment by ALiangLiang** [comment] 2019-04-01 05:05
Sorry can you paste your reproduce code on this post? I'm not sure what you happen.

**Comment by keepcosmos** [comment] 2019-04-01 05:07
```js
```

**Comment by keepcosmos** [comment] 2019-04-01 05:12
```js
  this.Task = this.sequelize.define('task', { title: DataTypes.STRING }, { paranoid: true } );
  this.User = this.sequelize.define('user', { username: DataTypes.STRING }, { paranoid: true });
  this.UserTasks = this.sequelize.define('tasksusers', { userId: DataTypes.INTEGER, taskId: DataTypes.INTEGER }, { paranoid: true });

  this.User.belongsToMany(this.Task, { through: 'tasksusers' });
  this.Task.belongsToMany(this.User, { through: 'tasksusers' });
```
If I define model with `{ paranoid: true }`, it actually run `QueryInterface.update`. But cascade flow runs on `QueryInterface.delete` (https://github.com/sequelize/sequelize/blob/master/lib/query-interface.js#L1041). As a result, deleting with paranoid is not working with cascade.

**Comment by keepcosmos** [comment] 2019-04-06 09:16
@ALiangLiang Do you need more information?

**Comment by sushantdhiman** [comment] 2019-04-09 05:35
Duplicate of https://github.com/sequelize/sequelize/issues/2586

**Closed by sushantdhiman** 2019-04-09 05:35 UTC
