### ISSUE TITLE
PostgreSQL Decimal precision

### ISSUE THREAD

**Issue by PyroSA** [sequelize/sequelize#4893] opened 2015-11-20 14:11 UTC
Sequelize seems to parse decimals to float since [V3.14.0] (https://github.com/sequelize/sequelize/blob/v3.14.0/lib/dialects/postgres/data-types.js#L38)

This greatly limits the amount of precision that you can get from the database.
We, declare one of our fields as DataTypes.DECIMAL(32, 15), and now have no way to retrieve all the significant digits.

**Comment by mickhansen** [comment] 2015-11-20 14:15
That would definitely be an error, cc @janmeier

**Comment by felixfbecker** [comment] 2016-01-14 10:02
applies to mysql aswell. Maybe we can have an additional parameter that specifies how the decimal should be converted?
```js
price: Sequelize.DECIMAL(32, 15, 'string') // 0.010 => '0.010', can be parsed by parseFloat
price: Sequelize.DECIMAL(32, 15, 'int') // 0.010 => 0010, must be divided by 1000
price: Sequelize.DECIMAL(32, 15, 'float') // 0.010 => 0.010
```
imo string should be default because it preserves both accuracy and floating point position.

**Comment by cwhatley** [comment] 2016-01-30 01:07
@janmeier When checking back on this ticket, I noticed the related ticket that got closed was assigned to you and this is unassigned.

**Comment by janmeier** [comment] 2016-01-30 09:50
@cwhatley https://github.com/sequelize/sequelize/issues/4893 is still open :)

**Comment by PyroSA** [comment] 2016-02-03 15:46
I like @felixfbecker's suggestion for allowing int or float conversion, in addition to string.
Only one change: For the Int case you would have to shift it based on the scale parameter to get back to the accurate number.
````
Sequelize.DECIMAL(10,4, 'int') // 1.234 => 12340
Sequelize.DECIMAL(10,3, 'int') // 1.234 => 1234
Sequelize.DECIMAL(10,2, 'int') // 1.234 => 123 
Sequelize.DECIMAL(10,1, 'int') // 1.234 => 12
```

**Comment by cwhatley** [comment] 2016-03-11 19:19
Is there any way we can just get this back to the way it was 3.14 and earlier rather than adding another solution for converting decimals? 

I'm stuck at 3.14 and would really like to get up to date and be on postgres 9.5.

I'm sorry to push for a fix and that I don't have the bandwidth to contribute more than complaining.

**Comment by PyroSA** [comment] 2016-05-05 12:23
I agree. I'll quite happily put together a PR that reverts it to 3.14 (proper) behaviour.

I fear there will be plenty of people using the incorrect behaviour already, and it will be a breaking change. But the longer this is left broken, the bigger the affected user-base will get.

**Comment by janmeier** [comment] 2016-05-06 08:03
> Adding 'fancy' auto-convert logic would be nice, but it can be done by the user if it is required for them. 
Then the lost precision is a conscious decision on their side.

Agreed, I think we should stick to just returning the raw string value - for now at least. A PR to revert to that behaviour is very welcome

**Closed** 2016-05-07 19:07 UTC
Labels: bug, postgres

**Comment by PyroSA** [comment] 2016-05-07 20:38
Thanks @janmeier !

**Comment by aides** [comment] 2016-05-12 15:20
Hi guys, 

As it was mentioned above, it really does break a lot of things. Is there any recommended workaround for this or I just need to add parseFloat wherever I need the value as number?

**Comment by mickhansen** [comment] 2016-05-12 16:40
@aides And fixes somethings, unfortunetaly not all PG numbers can be expressed in javascript so it's better not to try.

Easiest work around is to override the data typer parser, or the get function for the attributes.

**Comment by toddbluhm** [comment] 2016-05-19 19:47
Hey guys, this really really really should have been marked as semver breaking change. Literally broke environments for us because of this change. I don't care what way it goes, but it is a major breaking change that went in as a patch change...never good. In the future if you could be more considerate of these types of things I and many others would be very appreciative of that.

**Comment by felixfbecker** [comment] 2016-05-19 20:26
@toddbluhm While you are right, this really is an edge-case, because this can be considered a serious bug, which was introduced itself in a minor release. So this is patch to revert to the expected, correct behaviour. I would consider this a patch, but some big red warnings in the changelog should have been added.

**Comment by toddbluhm** [comment] 2016-05-19 20:51
@felixfbecker Ah okay. I did not know this was considered a bug (yes I know the tag says bug). From the discussion above it sounded like a preference choice. Maybe we could add something to the documentation stating that decimal types return strings?(also for BIGINTs too?) This way people can know what the intended behavior is.

Either way I am glad it got fixed. Just not a surprise I was expecting to see today :)

**Comment by PyroSA** [comment] 2016-05-19 21:13
The main concern is the people using somewhat flexible version numbers.
We allowed minor version bumps so were surprised when we noticed test start failing.

Changelogs are useful to find out why it broke in that case, but it doesn't stop unstable servers from going up.

**Comment by p4bloch** [comment] 2016-08-01 15:25
Is there a recommended way of overwriting the parser for the cases where data type is more important than precision?

**Comment by holden-caulfield** [comment] 2016-08-01 15:35
> Is there a recommended way of overwriting the parser for the cases where data type is more important than precision?

👍 

@mickhansen mentioned:

> Easiest work around is to override the data typer parser

Is there any pointer on how to do that? Couldn't find anything on the docs

**Comment by janmeier** [comment] 2016-08-02 07:56
@holden-caulfield @p4bloch The API is being finalized - see https://github.com/sequelize/sequelize/issues/6290
