### ISSUE TITLE
Complex join causes model instance to cut off property names

### ISSUE THREAD

**Issue by ataube** [sequelize/sequelize#4211] opened 2015-07-29 22:00 UTC
Have a look at the following example:
https://github.com/ataube/sequelize-join-bug

which defines the following entity model

```
Calculation => CalculationPosition <=> CalculationLineItem => CalculationValue           
        ^==================================^
```
Fetching a calculation with multiple includes 

```
Calculation.findOne({
            include : [
                { model : CalculationPosition, as : 'calculationPositions', include : [
                        { model : CalculationLineItem, as : 'calculationLineItems', include : [
                                {model : CalculationValue, as : 'calculationValues'}
                            ]
                        }
                    ]
                }
            ]
```

causes the very last entity to be constructed in a strange way. All the property names of a *CalculationValue* instance are cut off to max 3 characters, like:
```
{   id: 1,
    val: 1,
    typ: 'lineItem',
    cal: 1,
    cre: Wed Jul 29 2015 22:56:19 GMT+0200 (CEST),
    upd: Wed Jul 29 2015 22:56:19 GMT+0200 (CEST)
}
```
If the include order is changed to the following order the error disappears: 
```
{ model : db.CalculationLineItem, as: 'calculationLineItems', include: [
                { model: db.CalculationPosition, as: 'calculationPosition'},
                { model: db.CalculationValue, as: 'calculationValues'}
            ]}
```
This seems like a bug for me or is there a wrong association definition which causes this issue?

thanks and kind regards
Andreas

**Comment by mickhansen** [comment] 2015-07-30 06:37
It's likely your database cutting off the names, postgres has a limit i believe, there's another issue for it somewhere (to lazy to find it atm).

**Comment by janmeier** [comment] 2015-07-30 07:03
Duplicate of https://github.com/sequelize/sequelize/issues/2084

**Closed by janmeier** 2015-07-30 07:03 UTC

**Comment by ataube** [comment] 2015-07-31 11:37
Thanks for pointing out the duplicate, I was able to solve this issue with the `separate: true` option.

**Comment by zebkailash** [comment] 2020-09-23 07:28
Does that have any performance hit?
