### ISSUE TITLE
Multi column foreign key constraints

### ISSUE THREAD

**Issue by l-jonas** [sequelize/sequelize#11331] opened 2019-08-18 11:52 UTC
**Is your feature request related to a problem? Please describe.**

I want to add a foreign key constraint with two columns. It is possible to use multiple columns  for a constraint, but references.field only accepts a single field from the other table.

**Describe the solution you'd like**

When adding foreign key constrains, add a alternative parameter references.fields

**Why should this be in Sequelize**

It is required for some database models.

**Describe alternatives you've considered**

Not using a constraint - works, but is not clean

**Usage example**

-

**Additional context**

-

**Comment by sushantdhiman** [comment] 2019-08-18 13:28
Duplicate of https://github.com/sequelize/sequelize/issues/311

**Closed by sushantdhiman** 2019-08-18 13:28 UTC
