### ISSUE TITLE
Unhandled rejection SequelizeDatabaseError: type "enum_templates_type" already exists on PostgreSql

### ISSUE THREAD

**Issue by marcingasior** [sequelize/sequelize#4001] opened 2015-06-24 16:37 UTC
With every sync, sequelize tries to create a type
Executing (default): CREATE TYPE "enum_templates_type" AS ENUM('TEMPLATE', 'FRAGMENT');
which fails with: 

Unhandled rejection SequelizeDatabaseError: type "enum_templates_type" already exists
    at Query.formatError (~node_modules/sequelize/lib/dialects/postgres/query.js:423:14)
    at null.<anonymous> ~node_modules/sequelize/lib/dialects/postgres/query.js:104:19)
    at EventEmitter.emit (events.js:95:17)
    at Query.handleError (~node_modules/pg/lib/query.js:99:8)
    at null.<anonymous> (~node_modules/pg/lib/client.js:163:26)
    at EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (~node_modules/pg/lib/connection.js:109:12)
    at Socket.EventEmitter.emit (events.js:95:17)

My model looks like:
    var Template = sequelize.define("template",

        {
            id: {
                type: DataTypes.UUID,
                primaryKey: true,
                defaultValue: DataTypes.UUIDV4,
                allowNull: false
            },

            type: {
                type: DataTypes.ENUM('TEMPLATE','FRAGMENT')
            }
});

**Comment by janmeier** [comment] 2015-06-24 19:00
Works fine for me, please try on latest master

**Comment by ataube** [comment] 2015-06-24 21:06
I am having the same issue. Just tried out master and v3.3.1 from npm but still getting the same error. 
What infos do you need to isolate the problem? I am having two models with enum types defined, something like:
`unit: {type: DataTypes.ENUM, values: ['EUR', 'h', 'EUR/h']}`

**Comment by ataube** [comment] 2015-06-24 21:29
I got it working now. You have to use the `force:true` flag within the sync command
`db.sequelize.sync({force: true})`

**Comment by janmeier** [comment] 2015-06-25 07:15
Do remember that `force: true` will drop your tables each time!

**Comment by janmeier** [comment] 2015-06-25 07:17
We should be checking for existence of the enum before trying to create it. Don't you see anything like this in the logs?

```sql
SELECT t.typname enum_name, array_agg(e.enumlabel) enum_value FROM pg_type t JOIN pg_enum e ON t.oid = e.enumtypid JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public'  AND t.typname='NAME OF ENUM'  GROUP BY 1
```

**Comment by marcingasior** [comment] 2015-06-25 09:16
@janmeier 
Unfortunately our use case does not allow us to drop data every time we start up application :( 

The only check I see in logs
SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND a.attnum = ANY(ix.indkey) AND t.relkind = 'r' and t.relname = 'templates' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;

**Comment by janmeier** [comment] 2015-06-25 09:22
@marcingasior That was my guess, that's why I mentioned that forcing the sync might not be a viable solution :)

We are definitely executing a quqery to find existing enums at create time https://github.com/sequelize/sequelize/blob/master/lib/query-interface.js#L121. Are you sure this code is not executed?

**Comment by marcingasior** [comment] 2015-06-25 09:57
@janmeier 
No I definitely don't see a line like that.

I run regular sync on startup
----------------------------------------------------------------------
models.sequelize.sync().then(function () {
    var server = app.listen(app.get('port'), function() {
.....
}}
----------------------------------------------------------------------
index.js in models
"use strict";

var fs        = require("fs");
var path      = require("path");
var Sequelize = require("sequelize");
var env       = process.env.NODE_ENV || "development";
var config    = require(__dirname + '/../config/config.json')[env].db;
var sequelize = new Sequelize(config.database, config.username, config.password, config);
var db        = {};

fs.readdirSync(__dirname)
  .filter(function(file) {
    return (file.indexOf(".") !== 0) && (file !== "index.js");
  })
  .forEach(function(file) {
    var model = sequelize["import"](path.join(__dirname, file));
    db[model.name] = model;
  });

Object.keys(db).forEach(function(modelName) {
  if ("associate" in db[modelName]) {
    db[modelName].associate(db);
  }
});

db.sequelize = sequelize;
db.Sequelize = Sequelize;

module.exports = db;
--------------------------------------------------------------------------------

**Comment by janmeier** [comment] 2015-06-25 10:00
Please read up on [github flavored markdown](https://help.github.com/articles/github-flavored-markdown/) - I edited your post :)

Everything looks alright, so you'll have to go into the code i linked and test why its not executing - Since I can't reproduce with yuor sample

**Comment by ataube** [comment] 2015-06-25 11:04
@janmeier you're right - using the `force` flag does not really solve the issue.

Anyhow the select statement you postet is getting executed in my setup but it uses the wrong schema. The schema is actually null and therefore the public one is used which is wrong for my DB setup. Do I need to explicitly define the schema in the options? Right now I am using the following config:
```
{
  "database": "myDb",
  "user": "myUser",
  "pass": "myPass",
  "dialect": "postgres",
  "port": 5432
}
```

**Comment by janmeier** [comment] 2015-06-25 11:12
You can either specify schema per model or in the define options

**Comment by marcingasior** [comment] 2015-06-25 11:24
@janmeier 
I get it working on latest 3.3.2, the only change I had to make is specify schema when creating Sequelize object.

Thanks for help.

**Comment by janmeier** [comment] 2015-06-25 11:28
Ah, I assumed that you didn't have a schema set, since you don't specify any in the example.... :)

**Comment by ataube** [comment] 2015-06-25 21:05
@janmeier Setting the `schema` property did not solve the issue for me. There is still a bug hiding. In my db setup I am not using a public schema. But the enum select statement is having the `public` schema hardcoded. That's the reason why no enum types are found during the sync run. 

```SELECT t.typname enum_name, array_agg(e.enumlabel) enum_value FROM pg_type t JOIN pg_enum e ON t.oid = e.enumtypid JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public'  AND t.typname='enum_calculation_rates_rateType'  GROUP BY 1```

Have a look at the postgres [query-generator.js](https://github.com/sequelize/sequelize/blob/master/lib/dialects/postgres/query-generator.js#L771) Line 771

My guess is to make the `n.nspname` clause configurable based on the current defined schema. What do you think?

**Comment by marcingasior** [comment] 2015-06-25 21:32
@ataube 

try this, it solved my problem, and it sets nspname to your schema
var sequelize = new Sequelize(config.database, config.username, config.password, {schema: 'your schema'});

**Comment by marcingasior** [comment] 2015-06-26 11:19
@janmeier 
I run the project again, and have same issue as described by @ataube.
Yesterday it created a type with different namespace, that's why I thought it was solved.

**Comment by janmeier** [comment] 2015-06-28 14:54
@ataube Sounds right

**Comment by janmeier** [comment] 2015-06-28 14:54
Closing as duplicate of https://github.com/sequelize/sequelize/issues/3171

**Closed by janmeier** 2015-06-28 14:54 UTC
