### ISSUE TITLE
Help writing more TypeScript documentation

### ISSUE THREAD

**Issue by mjdavidson** [sequelize/sequelize#10750] opened 2019-04-11 06:47 UTC
When doing a query the manual says to do this:
```js
const ourUser = await User.findByPk(1, {
    include: [User.associations.Project],
    rejectOnEmpty: true, // Specifying true here removes `null` from the return type!
  });
```
if we're wanting to load multiple nested models, how should i go about doing this: 
```js
  const user = await User.findAll({
        attributes: ['id', 'name', 'email'],
        include: {
          model: Role,
          required: true,
          where: { projectId },

          include: [
            {
              model: Project,
              required: true
            },
            {
              model: Group,
              required: true,
              where: { code: 'cli' }
            }
          ]
        }
      });
```
Currently I'm getting the error 
```
Type '{ model: typeof Role; required: boolean; where: { projectId: any; }; include: ({ model: typeof Project; required: boolean; } | { model: typeof Group; required: boolean; where: { code: string; }; })[]; }' is not assignable to type 'Includeable[]'.
  Object literal may only specify known properties, and 'model' does not exist in type 'Includeable[]'.ts(2322)
```

**Comment by SimonSchick** [comment] 2019-04-11 16:19
`associations` is available everywhere, you can use it even in nested contexts.

Also `include` should always be an array.

**Comment by mjdavidson** [comment] 2019-04-12 00:02
@SimonSchick do you have an example of a v5 sequelize typescript project? I'm struggling with the simple example in the docs. Would be happy to write more documentation, but currently struggling myself with the implementation

**Comment by SimonSchick** [comment] 2019-04-12 11:55
@mjdavidson I'd invite you to our slack to speed up this discussion, feel free to ping me there.

**Comment by levibostian** [comment] 2019-04-12 14:38
@mjdavidson I am working with Typescript and sequelize v5 for the first time myself as well. I am interested in hearing how you feel the docs could be improved to see if there is any overlap between us. 

I am happy to help improve the docs as well where it needs it.

**Comment by sangaman** [comment] 2019-04-19 20:57
I just spent a couple of hours going nowhere trying to migrate sequlieze v4 with the @types/sequelize package to sequelize v5 with the built-in types. It would be extremely helpful to have better typescript documentation/support as well as any examples of typescript implementations with v5, if anyone knows of any. Thanks.

**Comment by SimonSchick** [comment] 2019-04-19 21:26
It would be helpful if you could provide a few bullet points on what you'd like to see exactly.

**Comment by sangaman** [comment] 2019-04-20 00:04
One of the key things I couldn't achieve that we have working in v4 is having it so each model's `create` function accepts a typed object, instead it appeared to be accepting a generic `object` type. I tried this with both the class that extends `Model` approach and the `define` example from the docs, neither was working for me.

More info & examples around model definition would be good, how to set up types/classes where the compiler knows what properties are required to create instances and which properties are available when we fetch instances from the database. Also, examples of how to transition from the v4 type definitions (as are outlined well [here](https://vivacitylabs.com/setup-typescript-sequelize/)) to v5 would be good if possible, as they seem to be set up quite differently.

Thanks and let me know if that gives you what you were asking for.

**Comment by SimonSchick** [comment] 2019-04-20 11:04
@sangaman If you are referring to the previously available generic parameter for model properties, this is currently not present by design.
The reason behind is there were too many cases where correct usage would be reported as incorrect with this approach.

You are free to create a PR to add this in a non breaking way and we can work on ironing out the issues from there.

**Comment by levibostian** [comment] 2019-04-20 20:34
I understand your concern with untyped objects in some of the Model functions, @sangaman. 

The way I get around this is to create my own typed model objects that are used my application code. Inside of this typed model object, I call the appropriate sequelize functions such as, `create()`. You can think of it like creating a wrapper around sequelize code. 

So, I abstract away from my application code the fact that I am even using Sequelize. Abstraction is a good code design anyway so it works out.

**Comment by colwynmyself** [comment] 2019-04-26 21:35
@SimonSchick I've only used JS with older versions of Sequelize and am now using TS with Sequelize 5 so sorry if this question is a little basic since I'm unfamiliar with `@types/sequelize`.

Just to clarify, does that mean given some example code like:

``` typescript
interface User extends Model {
  id: number;
  name: string;
}

type UserStatic = typeof Model & {
  new (values?: object, options?: BuildOptions): User;
}

const attributes: ModelAttributes = {
  id: {
    type: new DataTypes.INTEGER({ unsigned: true }),
    primaryKey: true,
    autoIncrement: true
  },
  name: {
    type: new DataTypes.STRING(120),
    allowNull: false
  }
};

const UserModel = sequelize.define('users', attributes) as UserStatic;
const userInstance = UserModel.findOne();
```

`userInstance` in this case is always going to be `any` until you cast it to the correct type? Is there a good way to get `findOne` to return the expected type or does that break some expectations with the built in types?

**Comment by SimonSchick** [comment] 2019-04-26 22:23
We don't support @types/sequelize.

**Comment by colwynmyself** [comment] 2019-04-28 19:39
Sorry, should have clarified, my example and question are for Sequelize 5 using the built in types. I just bought up `@types/sequelize` since I don't have a frame of reference for how things changed from there to Sequelize 5.

**Comment by mmiszy** [comment] 2019-04-29 00:40
@SimonSchick are you saying that the built-in type definitions in Sequelize are _type-unsafe by design_?
Does it mean we should ignore them and continue using safer `@types/sequelize` instead?

**Comment by SimonSchick** [comment] 2019-04-29 01:04
@mmiszy Ultimately yes, some specific functionality was impossible to reflect in typings when using the generic attributes approach that `@types/sequelize` uses, we therefor made the typings a fair bit more lenient to allow this.

Please note that this *only* affects functions with `where` clauses, everything else is considered at least as type safe as the DT version.

However those problems can be addressed now and might land in v6, it requires a fair bit of refactors so I haven't touched it yet.

I would not suggest to use `@types/sequelize` with v5 for now since the types are missing quite a bit of functionality such as model constructor and support for symbol operators and many more..

**Comment by jessep** [comment] 2019-04-29 15:54
@SimonSchick First, just wanted to say thanks for all your work on this, i'm excited about using sequelize with typescript. Just wanted to chime in I do hope you find time to address these issues in v6. When I realized `create` wasn't typesafe, I felt 😢😿😭

**Comment by SimonSchick** [comment] 2019-04-29 16:26
@jessep you are welcome to also work on this, the general approach of @types/sequelize should work, I will just have to make a bunch of tweaks to make it 100% correctly.

One problem is though that `Model` is a class now and no longer an interface, which makes declaring static generics very annoying, it's doable but will be a piece of work.

I'm currently travelling and will probably jetlagged for the next day or 2.

**Comment by jessep** [comment] 2019-05-07 14:04
Sorry for the slow reply. @SimonSchick. 

I'm sure this is is an ignorant question, but why is `Model` typed as a class instead of an interface now?

**Comment by sanketCactus** [comment] 2020-04-07 12:57
What is the correct Type for Model defined by Class extends Model?

Below is the documented way at https://sequelize.org/v5/manual/typescript.html
```
class Project extends Model {
  public id!: number;
  public ownerId!: number;
  public name!: string;

  public readonly createdAt!: Date;
  public readonly updatedAt!: Date;
}
```
What is the type of Project ?
Also, How we can we give type for object of multiple models
like 
```
const a: IModel = {
project:Project,
user:User,
employee: Employee
}
```

```
export interface IModel {
  [name: string]: typeof Model & {
    new (values?: object, options?: BuildOptions): Model;
  };
}
```
Here in above example if I consider type of `a` as IModel then it works everywhere else but it gives error where I use association with findAll or findOne


```
a.User.findAll({
      include: {
        model: a.Employee
        where: {
          active: true,
        },
        as: 'employees',
      }
    });
```

The error is 
```
Type '{ model: typeof Model & (new (values?: object | undefined, options?: Sequelize.BuildOptions | undefined) => Model<any, any>); where: { active: boolean; }; as: string; }' is not assignable to type 'Includeable[]'.
```

I am new to Sequelize, please correct me if I am wrong.

**Comment by ybrodsky** [comment] 2020-07-15 15:32
More docs are needed regarding typescript.
There's only a single page that doesnt cover practically anything. To put an example. the docs tells you how to use `include: [User.associations.projects],` but when you try to use as an object `[{ model: x }]` it no longer works as its expecting a type Model and not a type Association. But when you provide a class that extends Model it doesnt like it neither.

**Comment by sanketCactus** [comment] 2020-07-16 06:31
> More docs are needed regarding typescript.
> There's only a single page that doesnt cover practically anything. To put an example. the docs tells you how to use `include: [User.associations.projects],` but when you try to use as an object `[{ model: x }]` it no longer works as its expecting a type Model and not a type Association. But when you provide a class that extends Model it doesnt like it neither.

Totally Agree with you!

Is anyone even looking at this issue ? This issue is open since last one year :disappointed: 

contributors?

**Comment by wavded** [comment] 2020-08-12 14:20
I am encountering the same issue as @ybrodsky and @sanketCactus , any workarounds?

**Comment by sanketCactus** [comment] 2020-08-20 10:05
> I am encountering the same issue as @ybrodsky and @sanketCactus , any workarounds? If I use the `Association` that will work only for the non-object version of `include`. I can't get the model to work in either spot as well, says it doesn't match `typeof Model`. If I cast to any I can get around it but not preferable:
> 
> ```js
>   const invoice = await Invoice.findByPk(id, {
>     include: [
>       Invoice.associations.Employee,
>       {
>         model: InvoiceItem as any,
>         include: [
>           InvoiceItem.associations.Part,
>           {
>             model: InventoryItem as any,
>             include: [InventoryItem.associations.Piece],
>           },
>         ],
>       },
>     ],
>   })
> ```

Hi @wavded ,
I ended up using any at the root as in my case I am using sequelize with graphQL and the models are coming from a context property.
One thing I didn't get is why you used `Invoice.associations.Employee`  over simple model include.


Thanks,
Sanket Y.

**Comment by wavded** [comment] 2020-08-20 14:59
> One thing I didn't get is why you used Invoice.associations.Employee over simple model include

@sanketCactus Perhaps I was lead by the docs to do it that way. It seems either should work there. But neither worked for me when the include is an object.

**Comment by ephys** [comment] 2022-02-05 01:42
The issues with static Models being rejected were likely fixed by https://github.com/sequelize/sequelize/pull/13890

Looking through the thread, I'm not sure there is anything left unaddressed. Can we close this issue?

**Closed** 2022-04-16 16:46 UTC
Labels: question, type: typescript, status: awaiting investigation, P4: nice to have
