### ISSUE TITLE
"exclude" instead of "include" / find where not exists

### ISSUE THREAD

**Issue by tommedema** [sequelize/sequelize#4099] opened 2015-07-13 02:33 UTC
The following:

        User.findAndCountAll({
		  include: [
		     { model: Profile, required: true}
		  ]
		});

Will return users that have a profile.

How do I return users that have no profile? Is there an `exclude`?

Also, can I perform additional `where` statements on the relation? E.g. I want to return all users that have no profile with an avatar. Something like this?

        User.findAndCountAll({
		  include: [
		     { model: Profile, required: true, where: {avatar: null}}
		  ]
		});

**Comment by janmeier** [comment] 2015-07-13 07:11
This can be achieved by adding  `userId IS NULL` to the outer where clause. For it to be fully supported in sequelize you'll need to wait for https://github.com/sequelize/sequelize/issues/3095, but in the meantime you can do

```js
User.findAll({
    where: sequelize.literal('profiles.userId IS null'),
    include: [
    { model: Profile}
    ]
  })
```

**Comment by janmeier** [comment] 2015-07-13 07:11
Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).

**Closed by janmeier** 2015-07-13 07:11 UTC

**Comment by tommedema** [comment] 2015-07-14 03:46
Thanks -- I can't seem to get this to work though, posted a question at Stackoverflow at https://stackoverflow.com/questions/31397271/sequelize-where-has-not

**Comment by slawo** [comment] 2015-07-27 13:40
I have a big issue with this. Doing: 
````
User.findAll({
    where: sequelize.literal('profiles.userId IS null'),
    include: [
    { model: Profile}
    ]
  })
````
Works OK. But now try :
````
User.findAndCountAll({
    where: sequelize.literal('profiles.userId IS null'),
    include: [
    { model: Profile}
    ]
  })
````

And observe the crash...

**Comment by janmeier** [comment] 2015-07-27 14:00
@slawo You'll have to be more specific than 'the crash'

**Comment by Djalmar** [comment] 2016-05-16 22:28
@janmeier the problem is that the include is not recognized by the count method, see #5680
There is any way to make this work?

**Comment by atomdmac** [comment] 2017-07-19 15:38
I believe that this will fail with the following error if you include a "limit" clause.

```
Unhandled rejection SequelizeBaseError: missing FROM-clause entry for table "profiles"
```
