### ISSUE TITLE
TypeError: Object '...' has no method 'getTime'

### ISSUE THREAD

**Issue by santiagoaguiar** [sequelize/sequelize#4289] opened 2015-08-10 19:52 UTC
On 3.5.1, while calling a:

    ...
    instance.updateAttributes({ dateField: new Date() }, { transaction: tx})
    ...

On a model defined as:

    var Model = sequelize.define("Model", {
        dateField: { type: Sequelize.DATE, allowNull: false, defaultValue: Sequelize.NOW }
    });

Over SQLite, I get a:

    TypeError: Object 2015-08-10 19:41:54.000 +00:00 has no method 'getTime'

The code causing the issue seems to be this [recent commit](https://github.com/gutobortolozzo/sequelize/commit/8eafb4e9bf44ad8d9d4d78c22e1cb767e2ef9a56), where `originalValue` is, in this case (for some reason), a string.

I had other cases where fields I expected to be of type `Date` where actually strings. Wasn't able to track down the cause and had to default to handle that the value of the property might be either a string or a Date, but this time I can't work around it since it's on the libraries code.

Ideas of why this might be happening?

**Comment by janmeier** [comment] 2015-08-10 19:54
Are you using field aliasses, or does the instance come from an include? Those cases have trouble with date parsing in sqlite

**Comment by santiagoaguiar** [comment] 2015-08-10 19:59
Yes, it's comming from an include. 

If it's a known issue, I think best would be to consider [here](https://github.com/gutobortolozzo/sequelize/blob/8eafb4e9bf44ad8d9d4d78c22e1cb767e2ef9a56/lib/instance.js#L346) that `originalValue` can be a string, as it's already considered for value.

Thanks for the quick reply!!

**Comment by janmeier** [comment] 2015-08-10 20:01
Duplicate of https://github.com/sequelize/sequelize/issues/2644, will be fixed by https://github.com/sequelize/sequelize/pull/4186

**Closed by janmeier** 2015-08-10 20:01 UTC
