### ISSUE TITLE
Auto increments default value does not update between two different create methods 

### ISSUE THREAD

**Issue by Piepongwong** [sequelize/sequelize#8509] opened 2017-10-19 13:37 UTC
I have created 1000 mock instances via create bulk. When I try to create 1 additional instance by calling Book.addBook (which uses create), it gives me an unique constraint error. However, I haven't set any contraints, which leaves the default unique constraint for the primary keys. When I try to create an instance by using postgres directly in the terminal, postgres indeed thinks the sequence number is 2, but it should be 1001. 

Postgres version: psql (PostgreSQL) 9.5.9
Sequelize version: 4.5.0

The code that creates the mock data:

```
(async function(db) {
	await db.sequelize.sync({force: true})
		  .then(()=> {
			//create mock data
			db.book.bulkCreate(require("./models/mockBookData.json"))
		  })
})(db)
```

The model:

```
module.exports = function(sequelize, DataTypes){
  let Book =  sequelize.define('book', {
      id: {
          type: DataTypes.INTEGER,
          primaryKey: true,
          autoIncrement: true
      },
      isbn: {
        type: DataTypes.STRING
      },
      isbn2: {
        type: DataTypes.STRING
      },
      title: {
        type: DataTypes.STRING
      },
      author: { //several authors?
        type: DataTypes.STRING
      },
      description: {
        type: DataTypes.STRING
      },
      status: {
        type: DataTypes.STRING 
      },
      thumbnail: {
        type: DataTypes.STRING
      }
  });

  Book.getAllBooks = function() {
    return Book.findAll({limit: 100})
           .then(result => {
             return JSON.stringify(result)
           })
  }

  Book.addBook = function(theBook) {
      console.log("Add book controller reached, " + JSON.stringify(theBook,null,2))

       return Book.create(theBook)
      .then((createdBook, err) => {
        if(err) {
          throw err
        }
        if(theBook) {
          return "success"
        }
      })
    }
  return Book
}
```

The postgres injection + response:

`INSERT INTO "books" ("id","isbn","title","author","createdAt","updatedAt") VALUES (DEFAULT,'123456','A Brave New World','Aldous Huxly','2017-10-19 12:49:47.009 +00:00','2017-10-19 12:49:47.009 +00:00');
ERROR:  duplicate key value violates unique constraint "books_pkey"
DETAIL:  Key (id)=(2) already exists.
`

The sequelize error message:

`Unhandled rejection SequelizeUniqueConstraintError: Validation error
    at Query.formatError (/home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/sequelize/lib/dialects/postgres/query.js:313:18)
    at query.catch.err (/home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/sequelize/lib/dialects/postgres/query.js:86:18)
From previous event:
    at Query.run (/home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/sequelize/lib/dialects/postgres/query.js:79:23)
    at retry (/home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/sequelize/lib/sequelize.js:533:32)
    at /home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/retry-as-promised/index.js:39:21
    at retryAsPromised (/home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/retry-as-promised/index.js:29:10)
    at Promise.try.then.connection (/home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/sequelize/lib/sequelize.js:533:14)
From previous event:
    at Sequelize.query (/home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/sequelize/lib/sequelize.js:529:8)
    at QueryInterface.insert (/home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/sequelize/lib/query-interface.js:837:27)
    at Promise.try.then.then.then (/home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/sequelize/lib/model.js:3591:56)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at model.save (/home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/sequelize/lib/model.js:3567:8)
    at Function.create (/home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/sequelize/lib/model.js:1975:8)
    at Function.Book.addBook (/home/piepongwong/Programming/self/ownProjects/libraryCreator/server/models/book.js:42:20)
    at router.post (/home/piepongwong/Programming/self/ownProjects/libraryCreator/server/routes/user/addbook.js:10:11)
    at Layer.handle [as handle_request] (/home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/express/lib/router/layer.js:95:5)
    at /home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/express/lib/router/index.js:335:12)
    at next (/home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/express/lib/router/index.js:275:10)
    at next (/home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/express/lib/router/route.js:127:14)
    at isLoggedIn (/home/piepongwong/Programming/self/ownProjects/libraryCreator/server/routes/index.js:26:3)
    at Layer.handle [as handle_request] (/home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/express/lib/router/layer.js:95:5)
    at /home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/express/lib/router/index.js:281:22
    at param (/home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/express/lib/router/index.js:354:14)
    at param (/home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/express/lib/router/index.js:410:3)
    at next (/home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/express/lib/router/index.js:174:3)
    at router (/home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/express/lib/router/index.js:47:12)
From previous event:
    at /home/piepongwong/Programming/self/ownProjects/libraryCreator/server/routes/auth/passport.js:21:4
    at pass (/home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/passport/lib/authenticator.js:357:9)
    at Authenticator.deserializeUser (/home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/passport/lib/authenticator.js:362:5)
    at SessionStrategy.authenticate (/home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/passport/lib/strategies/session.js:60:10)
    at attempt (/home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/passport/lib/middleware/authenticate.js:361:16)
    at authenticate (/home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/passport/lib/middleware/authenticate.js:362:7)
    at Layer.handle [as handle_request] (/home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/express/lib/router/index.js:317:13)
    at /home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/express/lib/router/index.js:335:12)
    at next (/home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/express/lib/router/index.js:275:10)
    at initialize (/home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/passport/lib/middleware/initialize.js:53:5)
    at Layer.handle [as handle_request] (/home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/express/lib/router/index.js:317:13)
    at /home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/express/lib/router/index.js:335:12)
    at next (/home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/express/lib/router/index.js:275:10)
    at jsonParser (/home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/body-parser/lib/types/json.js:100:7)
    at Layer.handle [as handle_request] (/home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/express/lib/router/index.js:317:13)
    at /home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/express/lib/router/index.js:335:12)
    at next (/home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/express/lib/router/index.js:275:10)
    at /home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/body-parser/lib/read.js:125:5
    at invokeCallback (/home/piepongwong/Programming/self/ownProjects/libraryCreator/server/node_modules/raw-body/index.js:224:16)
`

**Comment by iamjochem** [comment] 2017-10-19 14:27
can you confirm that running the following SQL directly does work:

```sql
INSERT INTO "books" ("id","isbn","title","author","createdAt","updatedAt") VALUES (DEFAULT,'123456','A Brave New World','Aldous Huxley','2017-10-19 12:49:47.009 +00:00','2017-10-19 12:49:47.009 +00:00')
INSERT INTO "books" ("id","isbn","title","author","createdAt","updatedAt") VALUES (DEFAULT,'123456','1984','George Orwell','2017-10-19 12:49:47.009 +00:00','2017-10-19 12:49:47.009 +00:00')
```

if not then your table/sequence setup is borked somehow and it would seem to be that there is an issue not with `bulkCreate` but with `Model.sync()` (not sure whether your `sync()` call did anything .. maybe the borked DB definitions were already in place)

**Comment by NaifousBS** [comment] 2017-10-19 15:14
I have the same problem.
I think it may be resolved in the database itself : i tried "INSERT INTO" queries a couple of times.
First I got primaryConstraint error and then after entering the query again that was successful.
In my case I got this problem because I manipulate the database manually and my default ID was not synchronized.

**Comment by Piepongwong** [comment] 2017-10-19 15:45
@iamjochem That doesn't caused any problems. The problem arises only when I use "bulk create" and and "normal create" . I can add as many singular instances as I like.

@NaifousBS Thanks for sharing your suggestions. I tried to synchronize after the bulk create as well. Unfortunately that didn't work either.

**Comment by Piepongwong** [comment] 2017-10-19 23:07
@iamjochem  Yes, the PK values are hardcoded. I did not have any reason to hard code them, so I got rid of them and that solved the issue. Thank you for the fix! I can not really think of an use case where you want to hard code auto incremented PK's, so I guess this is not really a bug.

**Comment by iamjochem** [comment] 2017-10-20 00:01
no problem. not a bug it seems, possible an edge-case related directly to Postgres, definitely doesn't feel as if sequelize has anything to do with it thought. probably worth closing the issue.

**Closed** 2017-12-16 13:25 UTC
