### ISSUE TITLE
Sequelize findAndCountAll returns wrong

### ISSUE THREAD

**Issue by NiloufarPadkan** [sequelize/sequelize#16084] opened 2023-06-01 06:39 UTC
I have models like picture below:

![image](https://github.com/sequelize/sequelize/assets/50741400/b2159e44-90da-432e-a113-5fbd8f6d85f0)

and the relations are defined as :
‍‍‍‍‍
`Level.hasMany(DoctorSpecializtion);
DoctorSpecializtion.belongsTo(Level);

DoctorSpecializtion.belongsTo(Specialization)
Doctor.hasMany(DoctorSpecializtion)
DoctorSpecializtion.belongsTo(Doctor)

Service.belongsToMany(Doctor, { through: DoctorService })
Doctor.belongsToMany(Service, { through: DoctorService })
Service.hasMany(DoctorService)
DoctorService.belongsTo(Service)
Doctor.hasMany(DoctorService)
DoctorService.belongsTo(Doctor)
`
now when i include DoctorService or DoctorSpecializtion, find and count all returns wrong number. I also tried separete:true

     include: [
                        {
                             separate: true,
                           
                            model: DoctorSpecializtion,
                            

                            attributes: ['id'],
                            where: { specializationId: { [Op.or]: value } },
                            include: [
                                {
                                    model: Specialization,
                                    attributes: ['title', 'slug'],
                                },
                                {
                                    model: Level,
                                    attributes: ['title', 'slug'],
                                },
                            ],
                        },
                    ],

but when i use seperate true the filting part which is

 where: { specializationId: { [Op.or]: value } },
it does not return my required result.

_Originally posted by @NiloufarPadkan in https://github.com/sequelize/sequelize/discussions/16083_

**Comment by ephys** [comment] 2023-06-17 15:58
Duplicate of https://github.com/sequelize/sequelize/issues/9481

**Closed by ephys** 2023-06-17 15:58 UTC
Labels: pending-approval
