### ISSUE TITLE
Validation error with IsAlphanumeric & validator

### ISSUE THREAD

**Issue by jpgdev** [sequelize/sequelize#5377] opened 2016-02-07 00:58 UTC
Hi, 

I've been using Sequelize for a while, and without changing my model there is a new validation error, we updated the package, but can't remember which version it was earlier.

I'm currently using Sequelize 3.19.2 (tested with 3.18 too) with PostgreSQL 9.4.5. 

There is an error when using a `IsAlphanumeric` validation for a field with `validator.js`.

Simplified model which should trigger the error. : 

```javascript 
sequelize.define('MyModel', {
		myField: {
			type: DataTypes.STRING,
			allowNull: true,
			validate: {
				isAlphanumeric: true,
			}
		}
};
```

The actual error : 
```
SequelizeValidationError: Validation error: Cannot read property 'test' of undefined
    at /.../node_modules/sequelize/lib/instance-validator.js:74:14
```

Investigating the error, it seems to trigger because when Sequelize is validating (on save), it will call the `validator.isAlphanumeric` with `true` as the second parameter, which is the locale.

```javascript
// .../validator/validator.js
 validator.isAlphanumeric = function (str, locale) {
        locale = locale || 'en-US';
        return alphanumeric[locale].test(str);
    };
```

Since `alphanumeric[true]` does not exist it calls `undefined.test(str)`.

The problem may be linked to the `validator` package update (0bdbec8).

Ask up if you need more info.

Thanks.

**Comment by mickhansen** [comment] 2016-02-07 09:54
Thanks for providing all the info. Definitely some breakage there.

**Comment by oss92** [comment] 2016-02-08 12:27
I created a PR to `validator.js` https://github.com/chriso/validator.js/pull/488

I think it will eventually fix the breakage but we still to fix it in `sequelize` now.

**Comment by superclarkk** [comment] 2016-02-08 22:27
Thanks for raising this @jpgdev - I'm also experiencing it.
All versions between `3.9` and `3.19.1` work fine for me.

**Comment by mickhansen** [comment] 2016-02-09 12:47
@oss92 The issue is with Sequelize, not with validator.js

**Comment by janmeier** [comment] 2016-02-16 08:08
Fixed by https://github.com/sequelize/sequelize/pull/5429

**Closed by janmeier** 2016-02-16 08:08 UTC
Labels: bug
