### ISSUE TITLE
Conversion failed when converting date and/or time from character string.

### ISSUE THREAD

**Issue by epozsh** [sequelize/sequelize#7930] opened 2017-07-11 13:13 UTC
on sequelize version 4.3.0, i get this error 
cause when i give new Date() sequelize pass this format

> 2014-04-11 14:38:44.000 +00:00 

on sequelize version 3.27.0 i do not get error
cause it pass it like this 
> 2014-04-11 14:38:44.000

How i remove +00:00? so i can use newer version?

**Comment by cladjules** [comment] 2017-08-14 15:42
@Shadowman4205 that may look ugly but, in sequelize/lib/data-types.js, you can replace the method:

`DATE.prototype._stringify = function _stringify(date, options) {
  date = this._applyTimezone(date, options);

  // Z here means current timezone, _not_ UTC
  // return date.format('YYYY-MM-DD HH:mm:ss.SSS Z');
  return date.format('YYYY-MM-DD HH:mm:ss.SSS');
};`

**Comment by Shadowman4205** [comment] 2017-09-25 07:12
@cladjules  Thank you for this solution for now.

**Comment by carlosscheffer** [comment] 2017-11-03 16:08
I'm facing the same problem, however it's within the ambit of comparison:
` WHERE [PedidoVenda].[DATA_ALTERACAO] > N'2017-11-01 11:14:03.267 +00:00'`

thats returns me 

> DatabaseError: Conversion failed when converting date and/or time from character string.

**Comment by jnreynoso** [comment] 2018-01-29 19:36
+1

**Comment by andersao** [comment] 2018-02-07 22:04
+1

**Comment by balazsnemeth** [comment] 2018-02-08 16:24
+1 -> Same issue with dateformat "2018-02-08T05:00:00.000Z" on version 4.32.6

**Comment by spyter** [comment] 2018-02-12 20:34
+1

The date value below is a result of setting processed = new Date();

UPDATE [dbo].[Alert] SET [Processed]=N'2018-02-12 20:31:19.470 +00:00' OUTPUT INSERTED.* WHERE [Id] = N'27961F66-E5A5-47FE-8B89-0DA140D2C1EC'

**Comment by RicardoDMelo** [comment] 2018-02-18 18:24
+1

**Comment by Vovka19** [comment] 2018-02-18 19:14
THANK YOU! I JUST TRY, but too many keys dosent work at macbook. i will
check later didnt slept 2 days.

вс, 18 февр. 2018 г. в 20:24, Ricardo Melo <notifications@github.com>:

**Comment by balazsnemeth** [comment] 2018-02-27 20:07
Any news on this?

**Comment by HenryJW** [comment] 2018-03-23 15:37
The workaround I'm currently using is to use strings instead of dates for my models and then passing the ISO string instead of the date object.

```
// Doesn't work because new Date() is an object, not a string
MyModel.create({
   imported_date: new Date()
});

// Works (if type of imported_date is STRING)
MyModel.create({
   imported_date: new Date().toISOString()
});
```

**Comment by UziTech** [comment] 2018-06-13 15:01
Would it be possible to create a `DataTypes.DATE(format)` type?

**Comment by juniortarcisio** [comment] 2018-08-03 17:41
+1 I've just added @cladjules logic in a separated mapping file instead of replacing the module source from sequelize/lib/data-types.js:

> import * as DataTypes from 'sequelize/lib/data-types'
>
>         DataTypes.DATE.prototype._stringify = function _stringify(date, options) {
>            date = this._applyTimezone(date, options);
>            return date.format('YYYY-MM-DD HH:mm:ss.SSS');
>        };

**Comment by archae0pteryx** [comment] 2018-09-10 00:04
+1

**Comment by ElliottJRo** [comment] 2018-10-16 18:49
Is there a reason why the datetime string is converted to [JS Date object on grabbing data](https://github.com/sequelize/sequelize/blob/master/lib/data-types.js#L583) from db? this bug was quite hard to track down and it isn't documented anywhere.

It is unexpected behaviour when you put something in db and it automagically transforms when UI pulls the data

**Comment by ElliottJRo** [comment] 2018-11-13 23:30
@sushantdhiman is there any PRs open with this?

**Comment by ThePaavero** [comment] 2018-12-10 15:37
> +1 I've just added @cladjules logic in a separated mapping file instead of replacing the module source from sequelize/lib/data-types.js:
> 
> > import * as DataTypes from 'sequelize/lib/data-types'
> > ```
> >     DataTypes.DATE.prototype._stringify = function _stringify(date, options) {
> >        date = this._applyTimezone(date, options);
> >        return date.format('YYYY-MM-DD HH:mm:ss.SSS');
> >    };
> > ```

This saved my arse, thank you so much.
Example without import syntax:
`const DataTypes = require('sequelize/lib/data-types')

DataTypes.DATE.prototype._stringify = function _stringify(date, options) {
  date = this._applyTimezone(date, options)
  return date.format('YYYY-MM-DD HH:mm:ss.SSS')
}`

**Comment by victorschinaider** [comment] 2018-12-21 23:15
No news?

**Comment by juniortarcisio** [comment] 2018-12-21 23:51
What do you all think about sending a pull request with some fix for this situation? I don't know how the devs are working properly to treat this mismatch logics between different RDMSs, so I don't feel confident enough to pull request it.

**Comment by molaux** [comment] 2019-04-17 13:40
Had the same problem with mssql and found that casting to `DATETIMEOFFSET` worked for me in my where clause, without removing timezone serialization in DATE _stringify prototype :
```
Sequelize.cast(dateObj, 'DATETIMEOFFSET')
```
Don't know how to get Sequelize handle this directly...

**Comment by Shadowman4205** [comment] 2020-05-04 12:12
So this is issue still on!
Any news for regarding this?

**Comment by enkopvand** [comment] 2022-02-24 09:00
This is still an issue.

**Comment by Naim-Bijapure** [comment] 2022-03-23 04:51
still an issue

**Comment by ephys** [comment] 2022-03-23 08:40
This issue has been open for a long time and I believe it's because we don't have enough information to properly understand it.

According to the documentation, `DataTypes.DATE` is supposed to be `DATE WITH TIMEZONE` (or equivalent).

To resolve this issue we need to know:
- Which dialects are impacted
- Which Sequelize version is in use

Providing a [SSCCE](https://github.com/sequelize/sequelize-sscce) that reproduces this issue would also greatly help getting this resolved.

**Comment by byron70** [comment] 2022-04-22 06:42
This is more to note for future reference, then request a fix. 

My scenario is with mssql dialect.  Sequelize: sequelize@6.19.0.  MS SQL 2014 and 2017.

The database was not generated by Sequelize and I cannot change the data type of the column from `datetime` to `datetimeoffset`.

In the example Sequelize is generating the following string for a date.  Which cannot be explicitly converted by mssql to `datetime`.

```
select * from stock 
-- stockTSCreate is datetime
WHERE stockTSCreated > N'2022-04-20 16:09:54.000 +00:00';

Conversion failed when converting date and/or time from character string.
```

The workaround to `Sequelize.cast(lastUpdated, 'DATETIMEOFFSET')` works just fine.

**Comment by ephys** [comment] 2022-04-22 06:59
@byron70 Then I have some good news. Adding support for `datetime2` (without offset) for mssql is somewhere on my backlog https://github.com/sequelize/sequelize/issues/14295

**Comment by qq578023708** [comment] 2022-06-18 17:20
Up to now, this problem has existed for at least 3 years, and the current version 6.21 has not been repaired. If your database has a date type primary key, if you use serialize Save() method, in case you modify the _stringify () method is not affected. It still throws you type conversion errors. Perhaps the best way is to directly change your model Sequelize.DATE to Sequelize.STRING()

dialect: mssql

**Closed** 2022-11-06 19:03 UTC
Labels: type: bug, status: awaiting investigation, topic: dates & times

**Comment by Lancer92** [comment] 2023-01-20 10:47
Still not works on Windows with mssql 2019
sequalize version: 6.28.0
column type: datetime
DATA_TYPE: DATE

**Comment by ephys** [comment] 2023-01-20 10:59
As indicated above, DataTypes.DATE is mapped to [`datetimeoffset`](https://docs.microsoft.com/en-us/sql/t-sql/data-types/datetimeoffset-transact-sql), not `datetime` nor `datetime2`. If you need a DataType that maps to `datetime` or `datetime2`, here are the relevant issues:

- The addition of `DataTypes.DATETIME`, in which `DataTypes.DATETIME.PLAIN` maps to `datetime2`: https://github.com/sequelize/sequelize/issues/14295
- The addition of `DataTypes.DATE.PLAIN`, which also maps to `datetime2`: https://github.com/sequelize/sequelize/pull/15565

While we do plan on supporting `datetime2`, we are not currently planning on adding support for mssql's `datetime` data type. This will need to be handled by [writing a custom data types or extending an existing one](https://sequelize.org/docs/v7/other-topics/extending-data-types/)  (Sequelize 7)

These are the relevant issues, please head to these instead
