### ISSUE TITLE
.save() appears to be ignoring changed DataTypes.JSONB values

### ISSUE THREAD

**Issue by trevorlanyon** [sequelize/sequelize#3544] opened 2015-04-16 14:16 UTC
Version 2.0.5 with postgreSQL

using the following model definition:

````javascript
 module.exports = function(sequelize, DataTypes) { 
 
  return sequelize.define('User', { 
    id: { 
      type: DataTypes.UUID,
      defaultValue: DataTypes.UUIDV1,
      primaryKey: true,
      allowNull: false 
    },
    name: {                                            
      type: DataTypes.STRING,                            
      allowNull: false,                                  
      field: 'last_name',                                
      validate: {                                        
        notEmpty: { msg: "Please provide a last name"},
      },                                                 
    },                                                     
    rights: { 
      type: DataTypes.JSONB,
      defaultValue: {}, 
      allowNull: false
    }
    instanceMethods: {                                  
      addRight: function(right) {
        this.rights[right.name] = right.rights;     
        return true;                                
      },
    });
);
````

the following:

````javascript
var adminUser = {name: 'foo'};

app.get('models').User.create(adminUser).then(
  function(user) {
    user.addRight({
      name: 'users',
      rights: {view: 1, edit: 1}
    });
    console.log(user.get({plain: true}));
    user.save();
});
````
creates:
````sql
 UPDATE "user" SET "updated_at"='2015-04-16 13:58:42.563 +00:00' WHERE "id" = 'b0ee61d0-e440-11e4-8285-6df3016aff3e'
````
where as:
````javascript
    user.save({fields: ['rights']});
````
results in:
````sql
UPDATE "user" SET "rights"='{"rights":{"view":1,"edit":1}}',"updated_at"='2015-04-16 13:56:51.569 +00:00' WHERE "id" = '6ec6a6f0-e440-11e4-8c20-97a82ae855b3'
````

**Comment by mickhansen** [comment] 2015-04-16 14:21
Duplicate of https://github.com/sequelize/sequelize/issues/2862

**Closed by mickhansen** 2015-04-16 14:21 UTC
