### ISSUE TITLE
Upsert uses a WHERE clause with both primary key and other columns combination

### ISSUE THREAD

**Issue by wl1711** [sequelize/sequelize#12292] opened 2020-05-21 16:05 UTC
Upsert uses a WHERE clause with both primary key and other columns combination, causing duplicate key value violates unique constraint

I am using upsert to insert new recored when it doesn't exsit and update record when it already exists.

Model:

```js
    const Document = sequelize.define('Document', {
        id: {
            type: DataTypes.INTEGER,
            field: 'id',
            allowNull: false,
            primaryKey: true,
            autoIncrement: true
        },
        name: {
            type: DataTypes.STRING(255),
            field: 'name',
            allowNull: false
        },
        ...
        documentCategoryId: {
            type: DataTypes.INTEGER,
            field: 'documentCategoryId',
            allowNull: false,
            defaultValue: 1,
            references: {
                model: 'DocumentCategory',
                key: 'id'
            },
            onUpdate: 'NO ACTION',
            onDelete: 'NO ACTION'
        },
        assessmentId: {
            type: DataTypes.INTEGER,
            field: 'assessmentId',
            allowNull: false,
            references: {
                model: 'Assessment',
                key: 'id'
            },
            onUpdate: 'NO ACTION',
            onDelete: 'NO ACTION'
        },
       ...
        updatedById: {
            type: DataTypes.INTEGER,
            field: 'updatedById',
            allowNull: false,
            references: {
                model: 'User',
                key: 'id'
            },
            onUpdate: 'NO ACTION',
            onDelete: 'NO ACTION'
        },
       ... 
        createdById: {
            type: DataTypes.INTEGER,
            field: 'createdById',
            allowNull: false,
            references: {
                model: 'User',
                key: 'id'
            },
            onUpdate: 'NO ACTION',
            onDelete: 'NO ACTION'
        }
    }, {
        schema: 'public',
        tableName: 'Document',
        timestamps: true
    });
```
```js
                  await document.upsert({
                    id: doc.id,
                    name: doc.name.trim(),
                    description: doc.description,
                    documentCategoryId: doc.documentCategoryId,
                    assessmentId: req.query.id,
                    link: doc.link,
                    originalLink: doc.originalLink,
                    deleted: doc.deleted,
                    updatedById: user.id,
                    createdById: user.id
                  }, {transaction: t});
```

### What do you expect to happen?

I expected updating existing record without error

### What is actually happening?

when updating existing record, got error : duplicate key value violates unique constraint "Document_pkey". Below is the raw query generated by upsert

```
CREATE 
OR REPLACE FUNCTION pg_temp.sequelize_upsert(OUT created boolean, OUT primary_key text) AS $ func $ 
BEGIN
   INSERT INTO
      "public"."Document" ("id", "name", "description", "documentCategoryId", "assessmentId", "link", "originalLink", "deleted", "updatedById", "createdById", "createdAt", "updatedAt") 
   VALUES
      (
         50, 'doc2-updated', NULL, 1, '56', 'file-1589855657569.png', 'aasdf.png', false, 4, 4, '2020-05-21 14:05:18.240 +00:00', '2020-05-21 14:05:18.240 +00:00'
      )
;
created : = true;
EXCEPTION 
WHEN
   unique_violation 
THEN
   UPDATE
      "public"."Document" 
   SET
      "id" = 50, "name" = 'doc2-updated', "description" = NULL, "assessmentId" = '56', "link" = 'file-1589855657569.png', "originalLink" = 'asdfsfd.png', "deleted" = false, "updatedById" = 4, "createdById" = 4, "updatedAt" = '2020-05-21 14:05:18.240 +00:00' 
   WHERE
      (
         "id" = 50 
         OR 
         (
            "documentCategoryId" = 1 
            AND "createdById" = 4
         )
         OR "assessmentId" = '56' 
         OR "updatedById" = 4
      )
;
created : = false;
END
;
$ func $ LANGUAGE plpgsql;
SELECT
   * 
FROM
   pg_temp.sequelize_upsert();
```
### Additional context

related issue [here](https://github.com/sequelize/sequelize/issues/8552)
if I comment out the 3 ORs in the where clause, it appears working.

### Environment

- Sequelize version: 5.21.3
- Node.js version: v10.16.0
- Operating System: MacOS 10.14.6
- If TypeScript related: TypeScript version: XXX

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [x ] I don't know, I was using posgres, with connector library version 42.2.5(not 100% sure) and database version 11.7

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x ] No, I don't have the time, although I believe I could do it if I had the time...
- [] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment] 2020-05-24 11:00
Duplicate of https://github.com/sequelize/sequelize/issues/8552

**Closed by sushantdhiman** 2020-05-24 11:00 UTC
