### ISSUE TITLE
String values for decimal fields no longer accepted

### ISSUE THREAD

**Issue by vinkaga** [sequelize/sequelize#4237] opened 2015-07-31 14:47 UTC
With the latest update of sequelize (3.5.1), providing string scaler for a decimal field fails in an error similar to
```
[SequelizeValidationError: "7.50" is not a valid decimal]
  name: 'SequelizeValidationError',
  message: '"7.50" is not a valid decimal',
  errors: []
```
It works just fine if a number of value 7.50 is provided.

But, the purpose of the decimal field is to avoid issues caused by floating point representing decimal numbers. If the decimal fields take only the floating point scalar input, doesn't it defeat the purpose of the decimal fields?

**Comment by janmeier** [comment] 2015-07-31 20:58
Duplicate of https://github.com/sequelize/sequelize/issues/4197. Yes - the validation shouldn't be so strict :)

**Closed by janmeier** 2015-07-31 20:58 UTC

**Comment by vinkaga** [comment] 2015-10-10 17:43
It still isn't working for me in 3.11.0 although all dependent tickets #4197 and #4314 have been closed. Should it work now?

**Comment by mickhansen** [comment] 2015-10-10 17:54
@vinkaga 3.11.0 was published before those issues were closed.
