### ISSUE TITLE
sequelize reference error relation not defined

### ISSUE THREAD

**Issue by efraindrummer** [sequelize/sequelize#16893] opened 2023-12-20 21:59 UTC
I am experiencing this relationship error, so I have done this before but now these things are causing me conflict.

I share the following code fragment and the definition of my model and relationship

Route_Request.belongsTo(Operator, { foreignKey: 'route_request_operator_id' });
                        ^

ReferenceError: Operator is not defined

`const routeRequests = await Route_Request.findAll({
            order: [
                ['route_request_id', 'DESC']
            ],
            //offset: 0,
            //limit: 5,
            attributes: [
                'route_request_operator_id',
            ],
            include: [
                {
                    model: Operator,
                    attributes: ['operator_id', 'operator_name'],
                },
                
            ]
        });`

Route_Request.belongsTo(Operator, { foreignKey: 'route_request_operator_id' });

I am using esm modules, not require, the problem is that it does not detect that the table has any union but it does

**Comment by ephys** [comment] 2023-12-21 07:51
Errors `ReferenceError: x is not defined` mean that the variable `x` is not present in scope, which likely comes from a missing import

In any case, closing as this is not a bug on our end and does not follow the bug report template

**Closed by ephys** 2023-12-21 07:51 UTC
Labels: type: bug, pending-approval

**Comment by efraindrummer** [comment] 2023-12-21 19:11
I have the imports done correctly, I have other models that have not given me problems but this error cannot be removed even by cleaning the cache and deleting the node_modules
