### ISSUE TITLE
Should not be restricted in attribute names on join table for N:M

### ISSUE THREAD

**Issue by akotranza** [sequelize/sequelize#5169] opened 2016-01-08 03:42 UTC
Having an attribute 'order' on an explicitly defined join table model results in the error "Error: Unknown structure passed to order / group: <my order value here>"

e.g.  define N:M Gizmos:Widgets by
```
    Gizmo.belongsToMany(models.Widget, {through: 'GizmoWidgets'});
    Widget.belongsToMany(models.Gizmo, {through: 'GizmoWidgets'});
```
with the relevant portion of GizmoWidgets being
```
 ...define(
"GizmoWidgets", {
      type : {
        type : DataTypes.ENUM,
        values : ['super', 'awesome'],
        defaultValue : 'super'
      },
      order : {
        type : DataTypes.INTEGER,
        defaultValue : 0
      }
}, ...);
```

then, 
```
myGizmoInstance.addWidget(someWidgetInstance, {type: 'super'})
```
works perfectly, but
```
myGizmoInstance.addWidget(someWidgetInstance, {type: 'super', order: 99})
```
results in
"Error: Unknown structure passed to order / group: 99"

Either the documentation is incorrect and there's a different way to specify those attribute values or there's some wonky handling of the attribute value object / it's being mixed up with the 'options' object you'd expect to pass in other contexts e.g. myGizmoInstance.getWidgets({order: ['blah','ASC']})

Edit: this is only mildly annoying since you can just rename the attribute to e.g. 'my_order', but presumably any attributes with names conflicting with options would cause this error.

**Comment by mickhansen** [comment] 2016-01-08 07:18
It's an issue with us using the second argument for both values and options.
There's an existing issue somewhere to change that, @janmeier?

**Comment by janmeier** [comment] 2016-01-08 07:48
Here's another issue saying I can't find the issue https://github.com/sequelize/sequelize/issues/4835

**Comment by mickhansen** [comment] 2016-01-08 10:19
@janmeier I just recall some discussions about a new API for setting targets?

**Comment by janmeier** [comment] 2016-01-08 10:19
@mickhansen I do too, but can't find it :D

**Comment by sushantdhiman** [comment] 2016-07-21 11:11
Duplicate of #4597

**Closed by sushantdhiman** 2016-07-21 11:11 UTC
