### ISSUE TITLE
findOrCreate returns TypeError if not exists, but does create an entry

### ISSUE THREAD

**Issue by Piepongwong** [sequelize/sequelize#8857] opened 2018-01-08 11:08 UTC
findOrCreate returns a typerror if the entry does not exists, but does create the entry in the database. If the entry does exists, everthing works as it should. I have ran the example code twice. The first time the user with email John@snow.com is created. If I run the code a second time I get a typererror instead of the found user object. 

**Self-contained code sample that reproduces the issue**

> const Sequelize = require('sequelize');
> require('dotenv').config();
> const sequelize = new Sequelize(
> 	'woz', process.env.user, process.env.password, {
>   host: 'localhost',
>   dialect:'postgres'
> 
> });
> 
> sequelize
>   .authenticate()
>   .then(() => {
>     console.log('Connection has been established successfully.');
>   })
>   .catch(err => {
>     console.error('Unable to connect to the database:', err);
>   });
> 
> const User = sequelize.define('user', {
>   email: {
>     type: Sequelize.STRING
>   },
>   password: {
>     type: Sequelize.STRING
>   }
> });
>  
> sequelize.sync({force: false}).then(()=> {
>       User
>       .findOrCreate({where: {email: "John@snow.com"}}) // 
>       .spread((user, created) => {
>         console.log(user)
>       }).catch((err)=>{
>         console.log(err)
>       })  
> })

**Error/Output**

> Executing (5c8a5631-5df8-490e-939f-7721933cc5f2): SELECT "id", "email", "password", "createdAt", "updatedAt" FROM "users" AS
"user" WHERE "user"."email" = 'John@snow.com' LIMIT 1;
Executing (5c8a5631-5df8-490e-939f-7721933cc5f2): CREATE OR REPLACE FUNCTION pg_temp.testfunc(OUT response "users", OUT seque
lize_caught_exception text) RETURNS RECORD AS $func_c4f74dff4e644190bd221c4d493afaa0$ BEGIN INSERT INTO "users" ("id","email"
,"createdAt","updatedAt") VALUES (DEFAULT,'John@snow.com','2018-01-08 10:41:30.674 +00:00','2018-01-08 10:41:30.674 +00:00') RETURNIN
G * INTO response; EXCEPTION WHEN unique_violation THEN GET STACKED DIAGNOSTICS sequelize_caught_exception = PG_EXCEPTION_DET
AIL; END $func_c4f74dff4e644190bd221c4d493afaa0$ LANGUAGE plpgsql; SELECT (testfunc.response).*, testfunc.sequelize_caught_ex
ception FROM pg_temp.testfunc(); DROP FUNCTION IF EXISTS pg_temp.testfunc();
Executing (5c8a5631-5df8-490e-939f-7721933cc5f2): COMMIT;
TypeError: Cannot read property '0' of undefined

__Dialect: postgres
__Dialect version: 7.4.0
__Database version: 10.1
__Sequelize version: 4.29.1
__Tested with latest release: Yes (4.29.1)

**Comment by mogadanez** [comment] 2018-01-08 12:46
have same  issue

/sequelize/lib/dialects/postgres/query.js:112:17
```
     .then(queryResult => {
        const rows = queryResult.rows;
```
but queryResult  is array itself  with several results

![sequalize](https://user-images.githubusercontent.com/790307/34671309-61393672-f47a-11e7-8db4-284059b1445c.png)

**Comment by sushantdhiman** [comment] 2018-01-09 02:07
`pg@7` not supported. Duplicate of https://github.com/sequelize/sequelize/issues/8043

**Closed by sushantdhiman** 2018-01-09 02:07 UTC
