### ISSUE TITLE
v4.43.0 broke delete flag handling

### ISSUE THREAD

**Issue by PaddyMann** [sequelize/sequelize#10600] opened 2019-03-22 11:14 UTC
## What are you doing?

After upgrading to `4.43.0` (from `4.42.0`), we can see the following SQL being produced:

```sql
UPDATE `Response` SET `deleted`='true',`updatedBy`=24751,`updatedAt`=NOW() WHERE `id` = 416695 AND `deleted` = 'false'
```

Note that `deleted` is being correctly to a string. This leads to the following error:

```
Error Code: 1292. Truncated incorrect DOUBLE value: 'false'
```

This code being used is:

```js
await Response.update(
  {
    deleted: true,
  },
  {
    where: {id: existingResponse.id},
    ...context,
  }
);
```

The column is defined in the model as:

```js
deleted: {
  type: DataTypes.TINYINT,
},
```

Reverting to 4.42.0 fixes the issue.

## What do you expect to happen?

The latest version of Sequelize 4 should not convert my deleted booleans to strings.

## What is actually happening?

The latest version of Sequelize 4 is converting my deleted booleans to strings.

__Dialect:__ mysql
__Database version:__ 5.7.23
__Sequelize version:__ 4.43.0
__Tested with latest release:__ Yes (of Sequelize 4)

**Comment by SimonSchick** [comment] 2019-03-22 12:41
Apparently https://github.com/sequelize/sequelize/pull/10496 broke this?

**Comment by SimonSchick** [comment] 2019-03-23 15:28
Please provide a full repro.

**Comment by gabegorelick** [comment] 2019-03-28 20:21
Sorry about that.

> Note that deleted is being correctly to a string

The issue is that it should not be converted to the string `'false'`. Instead it should be the literal `FALSE` (or `0`).

#10644 should fix this. It will need to be backported to v4 once it's merged, but I'm happy to do that.

**Closed** 2019-03-29 06:38 UTC
Labels: needs more info

**Comment by PaddyMann** [comment] 2019-04-01 06:53
Awesome — thank you!
