### ISSUE TITLE
Using a between filter with DateOnly field does nto produces correct query

### ISSUE THREAD

**Issue by Bene-Graham** [sequelize/sequelize#11059] opened 2019-06-12 16:56 UTC
## What are you doing?

```js
myModel.findAll({
    attributes: [
        "id"
    ],
    where: {
        dateOfCheque: {
            [Op.between]: [input.startDate, input.endDate]
        }
    },
    logging: true
});
```
**To Reproduce**
1. Define a model where `dateOfCheque` is dateonly
2. Create a query that will find all records that are between a start and end date (Note: input.startDate and input.endDate are Date objects) See sample query above
3. Look at generated sql from he logging

## What do you expect to happen?
The date value in the between clause should not have a timestamp on them

## What is actually happening?
The query is adding timestamps to the dates that are within the between clause. Based on the sample query above the following sql is produced.

```sql
SELECT `id` 
FROM `myModel` AS `myModel` 
WHERE `myModel`.`dateOfCheque` BETWEEN '2019-03-01 05:00:00' AND '2019-03-31 04:00:00';
```

This does not happen in the case where you are directly comparing a date.

```js
myModel.findAll({
    attributes: [
        "id"
    ],
    where: {
        dateOfCheque: input.startDate
    },
    logging: true
});
```
Outputs
```sql
SELECT `id` 
FROM `myModel` AS `myModel` 
WHERE `myModel`.`dateOfCheque` = '2019-03-01';
```

My current workaround is to manually format the date as a string and pass it to the between filter.

## Environment
Dialect:
- [x] mysql
- [ ] postgres
- [ ] sqlite
- [ ] mssql
- [ ] any
Dialect **mysql2** version: 1.6.5
Database version: 5.7.26
Sequelize version: 4.44.0
Node Version: 12.3.1
OS: Mac OS 10.14.5
If TypeScript related: TypeScript version: 3.5.1

Tested with latest release:
- [x] No
- [ ] Yes, specify that version:

**Comment by papb** [comment] 2019-07-29 02:38
Thanks for the report!

Can you please test this with another dialect? This is important to know whether the problem is dialect-specific or not.

You can instantiate an in-memory SQLite instance very easily:

1. `npm install sqlite3`
2. `new Sequelize('sqlite::memory:')`

You can instantiate a local postgres instance very easily:

1. Run a local postgres
    * On windows: [PostgreSQLPortable_10.4.1.zip](https://github.com/garethflowers/postgresql-portable/releases/download/v10.4.1/PostgreSQLPortable_10.4.1.zip) (no need to install, just unzip and run)
        * Run the `.exe` and then `CREATE DATABASE testdb;` (don't close the `.exe`)
    * On linux (with docker): `docker pull postgres && docker run --rm --name pg -d -p 5432:5432 postgres`
        * Run `docker exec -t pg psql -U postgres -c 'CREATE DATABASE testdb;'`
2. `new Sequelize('postgres://postgres@localhost:5432/testdb')`

**Comment by Bene-Graham** [comment] 2019-07-29 14:43
I ran my example using sqlite and I get the same results.

Sequelize v5 does not have this issue.

**Comment by papb** [comment] 2019-07-29 16:06
@Bene-Graham Thanks! Since sequelize v5 does not have this issue, can I close it?

**Comment by Bene-Graham** [comment] 2019-07-29 16:09
Sure.

**Closed** 2019-07-29 16:11 UTC
Labels: status: awaiting response, type: bug
