### ISSUE TITLE
beforeDestroy hook invocation with onDelete cascade

### ISSUE THREAD

**Issue by pierrekraemer** [sequelize/sequelize#2547] opened 2014-11-07 16:43 UTC
Is there a chance that a beforeDestroy hook is invoked for an element that is deleted because a referenced row has been deleted and onDelete was set to CASCADE ?

Example setup :

``` javascript
var Document = sequelize.define(
    'Document',
    { ... },
    {
        hooks : {
            beforeDestroy : function (document) { ... }
        }
    }
);

var Category = sequelize.define(
    'Category',
    { ... }
);

Category.hasMany(Document);
Document.belongsTo(Category, {
    foreignKeyConstraint : true,
    onDelete : 'cascade'
});
```

When I destroy a document, the beforeDestroy hook is properly called.
When I destroy a category, the documents that reference this category are deleted from the database BUT the beforeDestroy hook is not called for these documents.

Is there a way to achieve such hook invocation ?

**Comment by machajew** [comment] 2018-06-11 06:09
Hi - I am running into issues with this. In my case, I have the following setup:

`

    const Comment = db.define('comment', {
      body: {
        type: db.Sequelize.TEXT,
        allowNull: false,
      },
    });

`

    const Asset = db.define('asset', {
      title: {
        type: db.Sequelize.STRING,
        allowNull: false,
      },
      key: {
        type: db.Sequelize.STRING,
        allowNull: false,
      },
    },
    {
      hooks: {
        beforeDestroy: (asset) => {
          console.log('beforeDestroy hook running');
          return null
        },
        beforeBulkDestroy: (asset) => {
          console.log('beforeBulkDestroy hook running');
          return null
        },
      },
    });
  `

Then, if I use this association:

```
  Asset.belongsTo(Comment, { onDelete: 'CASCADE' });
  Comment.hasMany(Asset);
```

When I destroy a comment (with an associated asset) with:

`Comment.destroy({ where: { id: 5 } })`

It successfully destroys the comment, and removes the corresponding asset from the database, but the beforeDestroy and beforeBulkDestroy hooks on the Asset model are **NOT** being called.

Per the docs, I have tried this configuration, based on the Associations section of [this doc page](http://docs.sequelizejs.com/manual/tutorial/hooks.html), which suggests to use:

 ```
  Comment.hasMany(Asset, { onDelete: 'CASCADE', hooks: true });
  Asset.belongsTo(Comment, { hooks: true });
```
However, neither the beforeDestroy and beforeBulkDestroy hooks are firing. I have also tried adding:

`Comment.destroy({ where: { id: 5 }, individualHooks: true })`

on the actual destroy call. Still no luck :(

**Comment by tidehayk** [comment] 2019-11-14 14:47
@davidmackhello , have you resolved this issue? I'd be thankful if you told be how.

**Comment by papb** [comment] 2020-01-15 16:24
I have reopened this as a docs issue - we could show an example of triggering the beforeDestroy hook upon cascades.

**Comment by adamup928** [comment] 2020-04-10 20:23
@papb, following the example of @davidmackhello with the latest Sequelize version, 5.21.6, the `beforeDestroy` hook is not called on _some_ associated models (even those with `{ onDelete: 'CASCADE', hooks: true }` set for a `hasMany` or `hasOne` assocation per the docs).

Specifically, the models where the hooks aren't called have a `belongsToMany` association in addition to a `hasOne` or `hasMany` assocation.  When I remove the `belongsToMany` assocation, the hooks are called correctly on the related models.

Can we add the `type:bug` tag back?

**Comment by SimoneLeoni1987** [comment] 2020-04-15 13:31
Still doesn't work guys, i even tried all three setup methods... none of them works.

**Comment by LasseRaatz** [comment] 2020-08-07 14:17
I had a similar problem and fixed it by writing something equivalent of
```
const comment = await Comment.findByPk(5);
comment.destroy();
```
instead of `Comment.destroy({ where: { id: 5 } })`
Hope this helps!

**Comment by ErtugrulBEKTIK** [comment] 2020-08-08 15:00
@LasseRaatz , thank you it worked!

**Comment by guicsou-lw** [comment] 2021-03-04 20:42
@LasseRaatz 

It worked!

However, I don't think this is intended to work like this. 
**type: bug** should definitely be added back.

**Comment by GregdTd** [comment] 2022-09-01 09:22
Still having this issue, using @LasseRaatz tricks did the job. 
@janmeier any work planned on the matter ?

**Comment by fzn0x** [comment] 2022-09-17 11:36
> Still having this issue, using @LasseRaatz tricks did the job. @janmeier any work planned on the matter ?

Sadly, @janmeier is not active on maintain anymore, you should tag active maintainers.

**Comment by tdd** [comment] 2022-12-22 10:53
Hey there!

I fall prey to the same issue.

I've got an `Upload` model defined like this:

```js
Upload.init(UploadSchema, { /* … */ }).afterDestroy(removeFile)
```

Calling a `.destroy()` on upload instances does trigger the hook, which works fine.

Then I've got another model with associations defined like this:

```js
User.hasMany(Upload, {
  foreignKey: 'parent_id',
  scope: { parent_type: 'user' },
  constraints: false,
  onDelete: 'cascade',
  hooks: true,
  as: 'uploads',
})
Upload.belongsTo(User, {
  foreignKey: 'parent_id',
  constraints: false,
  as: 'user',
})
```

Now, doing a `user.destroy()` does trigger cascaded deletion of `upload` rows, **but doesn't trigger `afterDestroy` on individual upload instances!**

This is in direct conflict with [that part of the docs](https://sequelize.org/docs/v6/other-topics/hooks/#one-to-one-and-one-to-many-associations).

What's going on?

- sequelize 6.21.4
- dialect: 'mariadb'
- MariaDB 10.3.34

**Comment by ephys** [comment] 2022-12-22 11:16
I can confirm that the documentation is wrong. Based on the history, this feature never existed. It looks like the documentation was incorrectly updated based on this issue having been closed with an alternative workaround but no built-in solution.

The `hooks` option on association is only used to control whether defining the association will trigger the `beforeAssociate` and `afterAssociate` hooks. It does not cause `destroy` to manually handle the ON DELETE CASCADE option.

I will remove the erroneous documentation, and replace this repurposed issue with a proper feature request where we can discuss how this use case can be properly supported

**Comment by tdd** [comment] 2022-12-22 11:28
Yes, not only that but even the `individualHooks` option in bulk (model-level) operations seems not to work. Doing a manual `Upload.destroy({ where: …, individualHooks: true })` doesn't trigger my `afterDestroy` hooks, only the `afterBulkDestroy` one.

Sad, sad state of the library…

**Comment by ephys** [comment] 2022-12-22 12:34
I've just ran a test for `individualHooks` and did not see anything wrong. If you're encountering bugs with that option, consider opening its own bug report with a reproducible example so we can look into it

**Comment by ephys** [comment] 2022-12-22 12:59
Here is a feature proposal that could resolve this issue: https://github.com/sequelize/sequelize/issues/15493. Feedback welcome :)

**Comment by tdd** [comment] 2022-12-22 13:18
Hey @ephys!

Thanks for looking into this!

As for a change proposal, personally I think I'd just favor `hooks: true` and `individualHooks: true` working as advertised...

I'll try and create a tiny reproducible use case on my end, staying in my app, and see whether it works. If it does, then there's something very fishy going on with my original model definitions. It's a lot of dynamic code so there's def room for subtle bugs.

**Comment by tdd** [comment] 2022-12-22 13:49
OK so **my bad**, really.

The `hooks: true` option on relationships **does work** (and I'm guessing `individualHooks` works as well).

I "just" had let a discrepancy creep in on my STI parent type column's value between creating my uploads (I used model constructor names) and polymorphic relationship scope settings (I used model table names, as several situations, including test isolation, require dynamic table names distinct from a common model name).

So Sequelize did perform the selects (I should have enabled SQL logging way earlier! Silly me!) but found nothing to then run individual hooks on.

I guess prior poor experience of docs being out-of-sync on Sequelize (e.g. cascaded deletion with `truncate`, that doesn't work as advertised and needs different value settings) had me jump to the conclusion that the issue was with Sequelize on this.

Best,

**Comment by ephys** [comment] 2022-12-22 15:08
Well it does turn out [this feature exists](https://github.com/sequelize/sequelize/blob/main/src/dialects/abstract/query-interface.js#L1046-L1075) after all

To be honest I really dislike that it's repurposing the `hooks` option which already has a very different purpose and is true by default.

I'll close this issue since the feature exists, but I'll look into reworking this in a future major

**Closed by ephys** 2022-12-22 15:08 UTC
Labels: type: docs, status: awaiting investigation

**Comment by ephys** [comment] 2023-07-01 12:17
I've updated the link to the relevant piece of code:

https://github.com/sequelize/sequelize/blob/340993dc4a220c0cf493bfdb2eec335498e8abf6/packages/core/src/dialects/abstract/query-interface.js#L799-L806C7

**Comment by EinfachHans** [comment] 2023-10-13 08:57
It works for me, but not on a destory with `individualHooks: true`:

1. **Works**
```ts
const models = await model.findAll({ where: {}, paranoid: false });
await Promise.all(models.map((m) => m.destroy({ force: true })));
```

2. **Doesn't work**
```ts
await model.destroy({ where: {}, force: true, individualHooks: true });
```

I would expect this to work as passing the `individualHooks` in my understanding executes the same as the working example 1? so first performs a select and then performs a delete?
