### ISSUE TITLE
findAndCountAll results in a count per group not count of total rows

### ISSUE THREAD

**Issue by mschipperheyn** [sequelize/sequelize#9598] opened 2018-06-27 14:42 UTC
## What are you doing?

I'm retrieving grouped counts of records. 
I would expect to be able to paginate through these, and in order to do this I need a count. The count relates however to the counts per group and not the total record count. 

Perhaps there is a different way in which I need to formulate the query. If I'm doing it right, it would seem a bug to me.  

```js
User.findAndCountAll({
    group: [sequelize.fn('date_format', sequelize.col('createdAt'), '%Y-%m-%d')],
    attributes: [
      [sequelize.fn('date_format', sequelize.col('createdAt'), '%Y-%m-%d'), 'date'],
      [sequelize.fn('count', '*'), 'total']
    ],
    ...parameters,
    order: [sequelize.literal('date DESC')]
  });
```

## What do you expect to happen?
```
 {    count: 3,
      rows: 
       [ User {
           dataValues: [Object],
           _previousDataValues: [Object],
           _changed: {},
           _modelOptions: [Object],
           _options: [Object],
           __eagerlyLoadedAssociations: [],
           isNewRecord: false },
         User {
           dataValues: [Object],
           _previousDataValues: [Object],
           _changed: {},
           _modelOptions: [Object],
           _options: [Object],
           __eagerlyLoadedAssociations: [],
           isNewRecord: false } ] }
```
## What is actually happening?
```
 {    count: [ { count: 1 }, { count: 2 } ],
      rows: 
       [ User {
           dataValues: [Object],
           _previousDataValues: [Object],
           _changed: {},
           _modelOptions: [Object],
           _options: [Object],
           __eagerlyLoadedAssociations: [],
           isNewRecord: false },
         User {
           dataValues: [Object],
           _previousDataValues: [Object],
           _changed: {},
           _modelOptions: [Object],
           _options: [Object],
           __eagerlyLoadedAssociations: [],
           isNewRecord: false } ] }
```
_Output, either JSON or SQL_

__Dialect:__ mysql
__Dialect version:__ mysql2 1.5.2
__Database version:__ 5.7.x
__Sequelize version:__ 4.37.10
__Tested with latest release:__ Yes

**Comment by Alexsey** [comment] 2018-07-20 12:33
same as https://github.com/sequelize/sequelize/issues/9109

**Comment by sushantdhiman** [comment] 2018-07-20 13:47
Thanks @Alexsey, I was trying to remember where I've seen this issue before :D 

Closing as duplicate of #9109

**Closed by sushantdhiman** 2018-07-20 13:47 UTC
Labels: bug
