### ISSUE TITLE
Attribute name used in ORDER BY instead of actual column name if model has attributes with custom field names

### ISSUE THREAD

**Issue by sheepcount** [sequelize/sequelize#4218] opened 2015-07-30 09:03 UTC
I have a model that uses custom field names, e.g. for the `id` column

    id: {
        field: 'taskId',
        type: DataTypes.INTEGER, 
    }

When doing a `findAll()` using `order: [['id', 'asc']]`, the resulting SQL query is

    SELECT "taskId" AS "id" ... ORDER BY "tablename"."id" ASC;

This query fails because the actual table column is `taskId`, not `id`. It should be

    SELECT "taskId" AS "id" ... ORDER BY "tablename"."taskId" ASC;

or

    SELECT "taskId" AS "id" ... ORDER BY "id" ASC;

From a quick look at `query-generator.js`, something like this should fix it:

	--- a/lib/dialects/abstract/query-generator.js
	+++ b/lib/dialects/abstract/query-generator.js
	@@ -1448,9 +1448,25 @@ var QueryGenerator = {
	               if (typeof t[t.length - 2] === 'string') {
	                 validateOrder(_.last(t));
	               }
	+              if (t[0] instanceof Model) {
	+                if (t[0].rawAttributes[t[1]]) {
	+                  t[1] = t[0].rawAttributes[t[1]].field || t[1];
	+                }
	+              } else if (t[0].model instanceof Model) {
	+                if (t[0].model.rawAttributes[t[1]]) {
	+                  t[1] = t[0].model.rawAttributes[t[1]].field || t[1];
	+                }
	+              }
	             } else {
	+              if (model.rawAttributes[t[0]]) {
	+                t[0] = model.rawAttributes[t[0]].field || t[0];
	+              }
	               validateOrder(_.last(t));
	             }
	+          } else {
	+            if (model.rawAttributes[t]) {
	+              t = model.rawAttributes[t].field || t;
	+            }
	           }
	 
	           if (subQuery && (Array.isArray(t) && !(t[0] instanceof Model) && !(t[0].model instanceof Model))) {

**Comment by janmeier** [comment] 2015-07-30 09:05
Duplicate of https://github.com/sequelize/sequelize/issues/4167

I think this would be better handled in https://github.com/sequelize/sequelize/blob/master/lib/utils.js#L80, where we handle `.field` for where and attributes

**Closed by janmeier** 2015-07-30 09:05 UTC
