### ISSUE TITLE
PostgreSQL like

### ISSUE THREAD

**Issue by pinducin** [sequelize/sequelize#4813] opened 2015-11-05 21:08 UTC
hi, sorry my english. I understand Castilian, the last version 3.13, has the following problem to work with postgresql... in lib/dialects/abstract/query-generator.js

should be replaced in line .. 

```
2153           if (escapeValue) {
2154               value = '(' + this.escape(value, field) + ')';
2155               value = value.replace('::VARCHAR','');
2156           }
```
To successfully build the SQL query.

**Comment by janmeier** [comment] 2015-11-05 21:10
Please show some sequelize code, models and find calls, and the generated sql

**Comment by pinducin** [comment] 2015-11-05 21:29
models:
```
var Sequelize = require("sequelize");
module.exports = function (sequelize) {
    return sequelize.define('provider', {
        id: {
            type: Sequelize.BIGINT,
            autoIncrement: true,
            primaryKey: true
        },
        coefficient_buy: Sequelize.DECIMAL(15, 5),
        coefficient_sale: Sequelize.DECIMAL(15, 5),
        coefficient_plus: Sequelize.DECIMAL(15, 5)
    }, {
        freezeTableName: true,
        timestamps: false,
        underscored: true
                // define the table's name
                //tableName: 'my_very_custom_table_name'
    });
};
```
```
var Sequelize = require("sequelize");
module.exports = function (sequelize) {
    return sequelize.define('provider_items', {
        id: {
            type: Sequelize.BIGINT,
            autoIncrement: true,
            primaryKey: true
        },
        date_insert: Sequelize.DATE,
        code: Sequelize.STRING,
        object_name: Sequelize.STRING,
        brand: Sequelize.STRING,
        price: Sequelize.DECIMAL(15, 5)
    }, {
        freezeTableName: true,
        timestamps: false,
        underscored: true
                // define the table's name
                //tableName: 'my_very_custom_table_name'
    });
};
```
```
module.exports = function (app, sequelize) {
    var Provider = require('../models/provider')(sequelize);
    var ProviderItems = require('../models/provider_items')(sequelize);
    var path = '/rest/provideritems';
    app.get(path + '/:_regExp', app.oauth.authorise(), function (req, res) {
        var value = req.params._regExp.split(" ");
        var arrString = [];

        value.forEach(function (entry) {
            arrString.push('%' + entry.toUpperCase() + '%');
        });
        Provider.hasMany(ProviderItems, {as: 'provider_items', foreignKey: 'provider'});
        Provider.findAll({
            include: [
                    {model: ProviderItems, as: ProviderItems.tableName, where: {$or: [{
                                code: {$ilike: {$all: arrString}}},
                            {object_name: {$ilike: {$all: arrString}}}
                        ]
                    }}
            ],raw: true
        }).then(function (objects) {
            res.json({
                message: 'Total find ' + objects.length,
                data: objects
            });
        });
    });
};
```
the original code in sequalize is...
```
2154            if (escapeValue) {
2155                value = this.escape(value, field);
2156            }
```
and the SQL generated is:
```
                   SELECT "provider"."id", "provider"."coefficient_buy", "provider"."coefficient_sale", "provider"."coefficient_plus", "provider_items"."id" AS "provider_items.id", "provider_items"."date_insert" AS "provider_items.date_insert", "provider_items"."code" AS "provider_items.code", "provider_items"."object_name" AS "provider_items.object_name", "provider_items"."brand" AS "provider_items.brand", "provider_items"."price" AS "provider_items.price", "provider_items"."provider" AS "provider_items.provider" FROM "provider" AS "provider" INNER JOIN "provider_items" AS "provider_items" ON "provider"."id" = "provider_items"."provider" AND ("provider_items"."code" ILIKE ALL ARRAY['%44426%']::VARCHAR OR "provider_items"."object_name" ILIKE ALL ARRAY['%44426%']::VARCHAR);
```
with modification
```
2153           if (escapeValue) {
2154               value = '(' + this.escape(value, field) + ')';
2155               value = value.replace('::VARCHAR','');
2156           }
```
the SQL result is:
```
                   SELECT "provider"."id", "provider"."coefficient_buy", "provider"."coefficient_sale", "provider"."coefficient_plus", "provider_items"."id" AS "provider_items.id", "provider_items"."date_insert" AS "provider_items.date_insert", "provider_items"."code" AS "provider_items.code", "provider_items"."object_name" AS "provider_items.object_name", "provider_items"."brand" AS "provider_items.brand", "provider_items"."price" AS "provider_items.price", "provider_items"."provider" AS "provider_items.provider" FROM "provider" AS "provider" INNER JOIN "provider_items" AS "provider_items" ON "provider"."id" = "provider_items"."provider" AND ("provider_items"."code" ILIKE ALL (ARRAY['%44426%']) OR "provider_items"."object_name" ILIKE ALL (ARRAY['%44426%']));
```
that is right for postgresql

**Comment by janmeier** [comment] 2015-11-05 21:35
Duplicate of https://github.com/sequelize/sequelize/issues/4064

Feel free to provide a PR, then we can discus the change further. Remember to include tests

**Closed by janmeier** 2015-11-05 21:35 UTC
