### ISSUE TITLE
Is it possible to use transactions for add[AS][singular] and add[AS][plural]?

### ISSUE THREAD

**Issue by basco-johnkevin** [sequelize/sequelize#3844] opened 2015-06-01 03:26 UTC
is this the correct way to use transactions in add[singular]? `tickets.addLabel(label, {transaction: t});`

In the code below:
```
tickets.forEach(function(ticket, index) {
  var hasLabelPromises = [];

  labels.forEach(function(label) {
    hasLabelPromises.push(ticket.hasLabel(label));
  });

  Q.all(hasLabelPromises).then(function(results) {
    results.forEach(function(hasLabel, index2) {
      if (! hasLabel) {
        addLabelPromises.push(tickets[index].addLabel(labels[index2], {transaction: options.transaction}));
      }
    });
  }).catch(function(err) {
    return cb(err);
  });
});
```
 the 
```
addLabelPromises.push(tickets[index].addLabel(labels[index2], {transaction: options.transaction}));
```
causes this error:

`Possibly unhandled Error: commit has been called on this transaction, you can no longer use it`

**Comment by janmeier** [comment] 2015-06-01 06:59
You need to show some more code, including where you create the transaction and commit it. Are you using auto-callback transaction (`sequelize.transaction(callback)`) - in that case maybe you are forgetting to return a promise chain so the transaction is comitted before you are done

**Comment by basco-johnkevin** [comment] 2015-06-01 07:41
@janmeier I'm using a managed transaction.

Controller:
```
sequelize.transaction().then(function (t) {
  var bulkAttachLabelForm = BulkAttachLabelForm(inputs);

  bulkAttachLabelForm.save(function(err, result) {
    if (err) {
      t.rollback();
      return next(err);
    }

    if (! result) {
      t.rollback();
      return res.status(422).json(bulkAttachLabelForm.formErrors);
    }

    t.commit();
    io.emit('attachedLabels', result);
    return res.status(200).json(result);
  }, {transaction: t});
});
```
Form:
```
save: function(cb, options) {
  var me = this;

  if (typeof(options) === 'undefined') {
    var options = {};
  }

  // fetch the tickets
  Ticket.findAll({
    where: {
      id: {
        $in: inputs.ticketIds
      },
      CompanyId: inputs.companyId
    },
    include: [
      { model: Label }
    ]
  }, {transaction: options.transaction}).then(function(tickets) {

    // check that all the labels are valid
    Label.findAll({
      where: {
        name: {
          $in: inputs.labels
        },
        CompanyId: inputs.companyId
      }
    }, {transaction: options.transaction}).then(function(labels) {

      // if the length of the results and the length of the labels (input)
      // are not the same, it means one or more of the labels (inputs)
      // are not found, that means it's invalid.
      if (labels.length !== inputs.labels.length) {
        var error = {
          field: 'labels',
          message: 'One of the labels are invalid.'
        };
        me.formErrors.push(error);
      }

      if (me.formErrors.length > 0) {
        return cb(null, false);
      }

      var addLabelPromises = [];

      tickets.forEach(function(ticket, index) {
        var hasLabelPromises = [];

        labels.forEach(function(label) {
          hasLabelPromises.push(ticket.hasLabel(label, {transaction: options.transaction}));
        });

        Q.all(hasLabelPromises).then(function(results) {
          results.forEach(function(hasLabel, index2) {
            if (! hasLabel) {
              addLabelPromises.push(tickets[index].addLabel(labels[index2], {transaction: options.transaction}));
            }
          });
        }).catch(function(err) {
          return cb(err);
        });
      });

      Q.all(addLabelPromises).then(function(results) {
        return cb(null, {
          ticketIds: inputs.ticketIds,
          labels: labels
        });
      }).catch(function(err) {
        return cb(err);
      });
    });
  }).catch(function(err) {
    return cb(err);
  });
}
```

**Comment by mickhansen** [comment] 2015-06-01 08:01
@basco-johnkevin You're not supposed to use `t.commit()` with a managed transaction. If you want to commit manually use an unmanaged one.

If you want to use managed transactions you need to refactor your code quite a bit to actually use promises correctly.

**Comment by basco-johnkevin** [comment] 2015-06-01 08:03
@mickhansen Oh, sorry, got confused. I'm using an unmanaged transaction.

**Comment by janmeier** [comment] 2015-06-01 08:04
The code you posted does not use a managed transaction :)

My guess is that at the time you call `Q.all(addLabelPromises)` the `addLabelPromises` array is empty (because items are added to it by some async code that you haven't reached yet), and thus the callback is resolved too soon.

**Comment by mickhansen** [comment] 2015-06-01 08:04
@basco-johnkevin Your problem is likely that the callback is called 2+ times.

**Comment by basco-johnkevin** [comment] 2015-06-01 08:09
@mickhansen It's only called once. I added `console.log('CALLBACK CALLED!');` inside the callback
```
    bulkAttachLabelForm.save(function(err, result) {
      console.log('CALLBACK CALLED!');

      // removed code....
```
You'll see that `CALLBACK CALLED!` text only appeared once in the output:
```
Jun 16:06:38 - [nodemon] v1.3.7
1 Jun 16:06:38 - [nodemon] to restart at any time, enter `rs`
1 Jun 16:06:38 - [nodemon] watching: *.*
1 Jun 16:06:38 - [nodemon] starting `node bin/www`
CALLBACK CALLED!
POST /api/tickets/bulk/label 200 365.722 ms - 156
```

**Comment by janmeier** [comment] 2015-06-01 08:11
@basco-johnkevin But it's called too soon - as per my comment above

**Comment by BridgeAR** [comment] 2015-06-01 08:11
The problem is that you do not wait for the result... you handle it as sync code. You have to insert a couple of `return`s.

**Comment by basco-johnkevin** [comment] 2015-06-01 08:11
@janmeier Makes sense! I missed that one. Let me try fixing it...

**Comment by mickhansen** [comment] 2015-06-01 08:11
Right, ignore my double commit comment - @janmeier  is right, there's a few things wrong with your code that makes it return to quickly and commit before all queries are executed.

**Comment by janmeier** [comment] 2015-06-01 08:12
Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).

**Closed** 2015-06-01 08:12 UTC

**Comment by basco-johnkevin** [comment] 2015-06-01 08:14
Alright, will do. Thanks guys!
