### ISSUE TITLE
build and save with associations

### ISSUE THREAD

**Issue by ro70** [sequelize/sequelize#9233] opened 2018-03-23 19:57 UTC
## What are you doing?
According to http://docs.sequelizejs.com/class/lib/model.js~Model.html#static-method-build I can build an instance with associations.
```js
const a = await db.A.build({
   id: 1,
   name: 'A',
   B: {
       id: 1,
       user: 2
   }
}, {
   isNewRecord: false,
   include: [db.B]
})
await a.save()
```

## What do you expect to happen?
How can I save this instance with its association into the database?

## What is actually happening?
The build seems to work but only the `name` value is stored into the database not the `B.user` data.

__Dialect:__ mysql
__Dialect version:__ XXX
__Database version:__ XXX
__Sequelize version:__ 4.28.1
__Tested with latest release:__ No (If yes, specify that version)

**Comment by sushantdhiman** [comment] 2018-03-23 20:09
You have to try with latest version, I remember fixing this

**Comment by ro70** [comment] 2018-03-23 20:25
@sushantdhiman I updated to 4.37.4 but it's still not working.

**Comment by sushantdhiman** [comment] 2018-03-24 04:31
It works, here is full [testcase](https://github.com/sequelize/sequelize/blob/3fd065cafb6633b4bfcd993a641976b829f8e0cc/test/integration/model.test.js#L582), if you think it doesn't may be try presenting a SSCCE

**Comment by sushantdhiman** [comment] 2018-03-24 04:33
Ah, may be it builds properly but doesn't save? In any case I will need an SSCCE

**Comment by sushantdhiman** [comment] 2018-03-24 06:42
Have you tried this

```js
const a = await db.A.build({
   id: 1,
   name: 'A',
   B: {
       id: 1,
       user: 2
   }
}, {
   isNewRecord: false,
   include: [db.B]
});

await a.save({
  include: [db.B]
})
```

**Comment by ro70** [comment] 2018-03-24 08:46
@sushantdhiman Thanks for your reply. The build method is working. The save method seems to have a problem. I tried both with and without the include option.

```
const Sequelize = require('sequelize')
const sequelize = new Sequelize({username: 'root', password: '', database: 'test', dialect: 'mysql', logging: false})

const A = sequelize.define('A', {name: Sequelize.TEXT})
const B = sequelize.define('B', {user: Sequelize.INTEGER})

A.belongsTo(B, {foreignKey: 'id'})
B.hasOne(A, {foreignKey: 'id'})

sequelize.sync({force: true})
.then(async () => {
  let a = await A.create({
    id: 1,
    name: '',
    B: {
      id: 1,
      user: 1
    }
  }, {
    include: [B]
  })
  console.log('CREATED', a.toJSON())  // works

  a = await A.build({
    id: 1,
    name: 'A',
    B: {
      id: 1,
      user: 2
    }
  }, {
    isNewRecord: false,
    include: [B]
  })
  console.log('BUILT', a.toJSON())  // works

  //await a.save()     // not working as expected
  await a.save({include: [B]})    // not working as expected

  let reloadedA = await a.reload()
  console.log('RELOADED', reloadedA.toJSON())
})
```

Output is
```
CREATED { id: 1,
  name: '',
  B: 
   { id: 1,
     user: 1,
     updatedAt: 2018-03-24T08:37:35.570Z,
     createdAt: 2018-03-24T08:37:35.570Z },
  updatedAt: 2018-03-24T08:37:35.566Z,
  createdAt: 2018-03-24T08:37:35.566Z }
BUILT { id: 1, name: 'A', B: { id: 1, user: 2 } }
RELOADED { id: 1,
  name: 'A',   // OK, changed
  createdAt: 2018-03-24T08:37:35.000Z,
  updatedAt: 2018-03-24T08:37:35.000Z,
  B: 
   { id: 1,
     user: 1,   // NOT changed
     createdAt: 2018-03-24T08:37:35.000Z,
     updatedAt: 2018-03-24T08:37:35.000Z } }
```

**Comment by ro70** [comment] 2018-03-24 11:25
This is the mysql statement of the save() call
```
UPDATE `As` SET `id`=1,`name`='A',`updatedAt`='2018-03-24 11:23:22' WHERE `id` = 1
```
No association update...

**Comment by sushantdhiman** [comment] 2018-03-25 05:00
What you want is update entire includes chain, rather than creating them. This is not supported in Sequelize yet. I will tag this as feature request.

**Comment by ro70** [comment] 2018-03-25 10:06
Thanks for the information. I think in the meantime I will do like
```
a.name = 'B'
a.B.user = 2

let aPlain = a.get({plain: true})
  
let queue = []
queue.push(a.update(aPlain))
queue.push(a.B.update(aPlain.B))
await Promise.all(queue)
```
What do you think?

**Comment by mirkojotic** [comment] 2018-07-04 21:54
@sushantdhiman Hey, I'd love to tackle this one. I have a use-case for this at work too so its a win/win :D 
All that being said I do need some direction. I've gone through the code, wrote test cases and poked through but I am not 100% sure where to start :) and what needs to be touched.

**Comment by RoelRoel** [comment] 2019-05-10 07:57
When I called the save function I thought I could finnaly taking advantage of the fact that I use an ORM and I don't have to write all the update and delete queries myself for the assosiations. Was I disappointed that only the main object was saved. I now still don't understand what the advances are using an ORM like this.... You lose a lot of control and development is nothing faster.....

**Comment by aat2703** [comment] 2019-08-02 18:39
I'm also running in to theese issues.. Also why is there no filtering available on build method? 

For some reason fields: [] option is not available?

**Comment by papb** [comment] 2019-08-02 19:00
@RoelRoel Although `build`+`save` apparently don't work, I know that `create` works with associations. Have you tried that as a workaround?

**Comment by papb** [comment] 2019-08-02 19:00
@aat2703
> Why is there no filtering available on build method?

Can you clarify what you mean by this? What did you want to do that can't be done?

**Comment by papb** [comment] 2020-01-09 01:55
Duplicate of #6808

**Closed by papb** 2020-01-09 01:55 UTC
Labels: type: feature

**Comment by papb** [comment] 2020-01-16 21:25
This has been centralized in #11836
