### ISSUE TITLE
Sync docs broken link

### ISSUE THREAD

**Issue by blairvanderhoof** [sequelize/sequelize#3140] opened 2015-02-15 03:10 UTC
http://sequelize.readthedocs.org/en/latest/sequelize#sync leads to a 404.

**Comment by mickhansen** [comment] 2015-02-15 08:39
Thank you @blairvanderhoof, where are you seeing that link so we can fix it?

**Comment by blairvanderhoof** [comment] 2015-02-15 09:27
It's on this page under Sync http://sequelize.readthedocs.org/en/latest/api/model/index.html?highlight=Sync

**Comment by janmeier** [comment] 2015-02-15 20:45
Duplicate of https://github.com/sequelize/sequelize/issues/3085

**Closed by janmeier** 2015-02-15 20:45 UTC
Labels: documentation
