### ISSUE TITLE
add straight_join function 

### ISSUE THREAD

**Issue by JuTiger-Lee** [sequelize/sequelize#15931] opened 2023-04-16 15:41 UTC
## Issue Creation Checklist

- [ ] I understand that my issue will be automatically closed if I don't fill in the requested information
- [ ] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

### Describe the feature you'd like to see implemented
need to add sequelize option mysql `straight_join`

### Describe why you would like this feature to be added to Sequelize
If the user wants mysql `straight_join`, write raw query but most users doesn't like raw query and 
if used specification pattern difficult change raw query

### Is this feature dialect-specific?

- [x] No. This feature is relevant to Sequelize as a whole.
- [ ] Yes. This feature only applies to the following dialect(s): 

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I will need guidance.
- [ ] No, I don't have the time, but my company or I are [supporting Sequelize through donations on OpenCollective](https://opencollective.com/sequelize).
- [ ] No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in implementing my feature.

---

*Indicate your interest in the addition of this feature by adding the 👍 reaction. Comments such as "+1" will be removed.*

**Comment by ephys** [comment] 2023-04-16 19:00
Duplicate of https://github.com/sequelize/sequelize/issues/11907

**Closed by ephys** 2023-04-16 19:00 UTC
Labels: type: feature, pending-approval

**Comment by JuTiger-Lee** [comment] 2023-04-17 11:59
Why don't add straight_join function?
I want to know accurate reason, Thanks.

**Comment by WikiRik** [comment] 2023-04-17 15:11
In the future, please discuss this feature in #11907. We are not against adding `straight_join` but it's not on our roadmap for the forseeable future so we welcome any PRs from the community
