### ISSUE TITLE
Unmanaged transactions with CLS

### ISSUE THREAD

**Issue by krmannix** [sequelize/sequelize#5432] opened 2016-02-16 15:06 UTC
Not really an issue, but more a question to clear up a part of the documentation.

Under the [transactions](http://docs.sequelizejs.com/en/latest/docs/transactions/#automatically-pass-transactions-to-all-queries) documentation, it states that "CLS works like a thread-local storage for callbacks.", which would allow the following snippet to pass the transaction automatically to all queries.
```js
sequelize.transaction(function (t1) {
  // With CLS enabled, the user will be created inside the transaction
  return User.create({ name: 'Alice' });
});
```

Do the same rules of sharing transactions automatically using the `cls` module apply to unmanaged transactions? I'm attempting to implement this & the transaction does not seem to automatically apply to queries with the transaction `then()` block - is this by design, or perhaps my implementation is wrong (example snippet is below).

```js
var userJson = { username: 'Kevin', password: 'secret' };
sequelize.transaction().then(function (t) {
  return User.create(userJson)
  .then(function () {
    return Promise.all([
      sequelize.models.Project.create(),
      sequelize.models.Issue.create(),
    ]);
  })
  .then(function () {
    return t.commit();
  })
  .catch(function (err) {
    return t.rollback();
  });
});
```

**Comment by janmeier** [comment] 2016-02-16 15:09
This is by design - When you pass a callback we can call `cls.run(callback)`, thus enabling the CLS context storage, see https://github.com/sequelize/sequelize/blob/ad8d22c9ceab9e7b55f1354ad50085d2cfb6b07a/lib/sequelize.js#L1240-L1274

We talked about hooking into the `.then` function as well, but it quickly becomes ugly :)

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).

**Closed by janmeier** 2016-02-16 15:09 UTC
