### ISSUE TITLE
getterMethods can't use async await ?

### ISSUE THREAD

**Issue by rondaful** [sequelize/sequelize#9501] opened 2018-06-03 13:58 UTC
version:4.4.2

js:  
```
.define('template_enterprise', {
   name:STRING
},
{
 getterMethods: {
    async fullName() {
      return await xxxx();// Promise
    }
  },

}

```
I can't  get fullName, get Promise

**Comment by sushantdhiman** [comment] 2018-06-03 14:53
No, this wont be in future.

1. Complexity
2. We are moving toward ES6 getters, which can't be async by design
3. Anything you are trying to implement with async getters can also be implemented with before hooks

**Closed by sushantdhiman** 2018-06-03 14:53 UTC
