### ISSUE TITLE
There's no way to know alias for nested entity field

### ISSUE THREAD

**Issue by bssergy** [sequelize/sequelize#12310] opened 2020-05-25 04:59 UTC
### What are you doing?

I need to use mysql CONCAT to my nested entity fields, but when I try to use col() function to pass fields like arguments, they don't have aliases and query craches.

Here is small demo for the situation:

```js
const sequelize = new Sequelize('sqlite::memory:');

class A extends Model {}
A.init({
  a1: DataTypes.STRING,
  a2: DataTypes.STRING,
}, { sequelize, modelName: 'A' });

class B extends Model {}
B.init({
  b1: DataTypes.STRING,
  b2: DataTypes.STRING
}, { sequelize, modelName: 'B' });

class C extends Model {}
C.init({
  c1: DataTypes.STRING,
  c2: DataTypes.STRING
}, { sequelize, modelName: 'C' });

class D extends Model {}
D.init({
  d1: DataTypes.STRING,
  d2: DataTypes.STRING
}, { sequelize, modelName: 'D' });

A.hasOne(B, { as: 'B' });
B.hasOne(C, { as: 'C' });
C.hasOne(D, { as: 'D' });

sequelize.sync()
  .then(() => A.findAll({
    include: [{
      model: B,
      as: 'B',
      include: [{
        model: C,
        as: 'C',
        include: [{
          model: D,
          as: 'D',
          where: {
            [Op.and]: [{ d1: 'test' }, where(fn('CONCAT', col('d1'), col('d2')), 'test')]
          }
        }]
      }]
    }]
  }))
  .then(result => {
    console.log(result);
  });
```

As the result I've got the next sql:

```sql
SELECT
  `A`.`id`,
  `A`.`a1`,
  `A`.`a2`,
  `A`.`createdAt`,
  `A`.`updatedAt`,
  `B`.`id` AS `B.id`,
  `B`.`b1` AS `B.b1`,
  `B`.`b2` AS `B.b2`,
  `B`.`createdAt` AS `B.createdAt`,
  `B`.`updatedAt` AS `B.updatedAt`,
  `B`.`BId` AS `B.BId`,
  `B->C`.`id` AS `B.C.id`,
  `B->C`.`c1` AS `B.C.c1`,
  `B->C`.`c2` AS `B.C.c2`,
  `B->C`.`createdAt` AS `B.C.createdAt`,
  `B->C`.`updatedAt` AS `B.C.updatedAt`,
  `B->C`.`CId` AS `B.C.CId`,
  `B->C->D`.`id` AS `B.C.D.id`,
  `B->C->D`.`d1` AS `B.C.D.d1`,
  `B->C->D`.`d2` AS `B.C.D.d2`,
  `B->C->D`.`createdAt` AS `B.C.D.createdAt`,
  `B->C->D`.`updatedAt` AS `B.C.D.updatedAt`,
  `B->C->D`.`DId` AS `B.C.D.DId`
FROM
  `As` AS `A`
  LEFT OUTER JOIN `Bs` AS `B` ON `A`.`id` = `B`.`BId`
  LEFT OUTER JOIN (
    `Cs` AS `B->C`
    INNER JOIN `Ds` AS `B->C->D` ON `B->C`.`id` = `B->C->D`.`DId`
    AND (
      `B->C->D`.`d1` = 'test'
      AND CONCAT(`d1`, 'd2') = 'test'
    )
  ) ON `B`.`id` = `B->C`.`CId`;
```

### What do you expect to happen?

Function agruments should be prefixed with generated aliases.

```sql
    AND (
      `B->C->D`.`d1` = 'test'
      AND CONCAT(`B->C->D`.`d1`, `B->C->D`.`d2`) = 'test'
    )
```

### What is actually happening?

As you can see, field d1 handled correct like \`B->C->D\`.\`d1\`, but all what I passed into fn() as argument - weren't handled at all - CONCAT(\`d1\`, 'd2').

```sql
    AND (
      `B->C->D`.`d1` = 'test'
      AND CONCAT(`d1`, 'd2') = 'test'
    )
```

### Additional context

Of course, I can hardcode this alias like fn('CONCAT', col('\`B->C->D\`.\`d1\`'), col('\`B->C->D\`.\`d2\`')) but it's terrible. I don't know how does alias looks like while I'm coding.

### Environment

- Sequelize version: 5.21.6 
- Node.js version: v12.16.3 
- Operating System: Windows 10 Home x64

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [x] I don't know, I was using mysql2, with connector library version 2.1.0 and database version 8.0.18

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment] 2020-05-25 13:07
Hello. Question: `CONCAT` returns a string, right? Why are you performing an `AND` on it in a `where` clause, as if you were checking a condition?

**Comment by bssergy** [comment] 2020-05-26 20:04
> Hello. Question: `CONCAT` returns a string, right? Why are you performing an `AND` on it in a `where` clause, as if you were checking a condition?

Thanks @papb, updated my query to make it more understandable

**Comment by sushantdhiman** [comment] 2020-06-08 08:23
Duplicate of https://github.com/sequelize/sequelize/issues/10732

**Closed by sushantdhiman** 2020-06-08 08:23 UTC
