### ISSUE TITLE
Search is broken in documentation website

### ISSUE THREAD

**Issue by teogeos** [sequelize/sequelize#6486] opened 2016-08-23 09:15 UTC
Hello

Any atempts to use the search feature on the docs website leads to an error page: 

https://readthedocs.org/search/?q=mySearchTerm&check_keywords=yes&area=default&project=sequelize&version=v3&type=file

**Comment by felixfbecker** [comment] 2016-08-23 09:17
Duplicate of #6464

**Closed by felixfbecker** 2016-08-23 09:17 UTC
