### ISSUE TITLE
V5 Logging Paramterized Query Values

### ISSUE THREAD

**Issue by mannis17** [sequelize/sequelize#10200] opened 2018-11-26 19:53 UTC
## What are you doing?
Attempting to log the values of an insert/update query using V5 Sequelize

const sequelize = new Sequelize('mydatabase',null, null, { 
  storage: config.development.storage,
  dialect: config.development.dialect,
  logging: function (str) {
    console.log('logged:', str);
}
});

## What do you expect to happen?
Prior to V5 Insert/Update did not user parameterized queries. V5 uses parameterized queries. In V4 logging the insert/update query also logged the values. V5 logging the insert/Update query logs the variable name used by the parameterized query (ie $1), instead of the actual value.

## What is actually happening?
Below is what is logged in V5
INSERT INTO `MyTable` (`id`,`name`,`address`) VALUES ($1,$2,$3);

Below is what is logged in V4
INSERT INTO `MyTable` (`id`,`name`,`address`) VALUES ('1', 'Some Name', 'Some Address);

How do you log the actual values in V5?

__Dialect: sqlite 
__Dialect version:__ XXX
__Database version:__ XXX
__Sequelize version: 5.0.0-beta-14
__Tested with latest release: yes

**Comment by sushantdhiman** [comment] 2018-11-27 05:47
Duplicate of https://github.com/sequelize/sequelize/issues/10067

**Closed by sushantdhiman** 2018-11-27 05:47 UTC
