### ISSUE TITLE
FEATURE: Run custom validation functions even if value is null

### ISSUE THREAD

**Issue by tiblu** [sequelize/sequelize#2643] opened 2014-12-01 14:42 UTC
**Intro**
Run the custom validation functions even if value is ``null``.

**The need**
IRC chat 1st of Dec 2014

*[14:41] <tiblu> Hi! Is there a way to have notNull validation on Model BUT not constraint in the DB. The idea is that by default NULL is not allowed by Model, but for a certain edge case use "skipValidation" flag and still have NULL in the DB?
[14:47] <@mickhansen> tiblu: you'd have to use a custom validation likely
[14:50] <@Janzeh> But you could extend the validator with a notNull validator :)
[14:50] <@Janzeh> The difference being that if you put notNull directly in the column def., then a constraint will be added, but 
it won't if you add it in validate
[15:33] <tiblu> mickhansen, janzeh: seems validate() is not run if value is "null" thus I cannot use the solution where I add my custom validate: ...
[15:38] <@Janzeh> tiblu: you seem to be right :(
[15:39] <@Janzeh> It makes sense that the validator.js validators are not called, but custom validators should :)
[15:39] <@Janzeh> Go and report an issue, that should be fixed :)*

**Comment by sushantdhiman** [comment] 2016-06-15 16:38
Duplicate of #5189

**Closed by sushantdhiman** 2016-06-15 16:38 UTC
Labels: feature
