### ISSUE TITLE
JSON property dirty checking broken in v6

### ISSUE THREAD

**Issue by erwinw** [sequelize/sequelize#13006] opened 2021-02-05 08:15 UTC
### What are you doing?

Updating a JSON property on a model instance does not check for dirty; changes do not get submitted.

```js

class User extends Model {}
User.init({
  id: {type: Sequelize.UUID, primaryKey: true, defaultValue: Sequelize.UUIDV4},
  status: DataTypes.JSON
}, { sequelize, modelName: 'user' });

await sequelize.sync();

const aUser = await User.create({
    status: { mood: 'sad' }
 };

aUser.status.mood = 'happy';
aUser.update({status: aUser.status });

const bUser = await User.findByPk(aUser.id);
console.log(bUser.status.mood); // 'sad', not 'happy'
```

### What do you expect to happen?

Just like in Sequelize v5, I expected the row to be updated in the database.

### What is actually happening?

Nothing; the record is not updated.

### Additional context

As mentioned, this is a breaking change from v5 to v6.

This problem was actually first raised in #12960 , but then closed again 🤷🏻 

We were in the process of migrating from Sequelize v5 to v6 in a medium-large code base (50+ models), and have to put that on hold because of this breaking change, and the risk that not all instances of this behaviour have been identified by our tests.

### Environment

- Sequelize version: 6.4.0
- Node.js version: v12.17.0
- Operating System: MacOS Big Sur 11.2, Alpine Linux 3.12
- If TypeScript related: TypeScript version: 4.1.3 (not TS related)

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by RufusHamade** [comment] 2021-04-13 16:05
I'm suffering from the same issue. Interestingly, it is very much dependent on how you do the update.  Using the following test script: 
```const {Sequelize, DataTypes, Model} = require('sequelize');

(async () => {
  const path = 'mysql://os_moderator:password@localhost:3306/testdb';
  const sequelize = new Sequelize(path, {
    operatorsAliases: false
  });

  class Dummy extends Model {}

  Dummy.init({
    description: DataTypes.STRING,
    otherAt: DataTypes.DATE,
    data: DataTypes.JSON,
  }, {
    sequelize,
    modelName: 'Dummy',
  });

  await Dummy.sync();
  console.log('New table created');
  let id;
  {
    const d = Dummy.build({
      description: 'test',
      otherAt: Sequelize.fn('now'),
      data: {counter: 1},
    });
    await d.save();
    id = d.id
  }

  {
    const d = await Dummy.findByPk(id)
    console.log(d.id, d.data)
    await d.update({
      description: 'test2',
      data: {counter: 2},
    })
  }

  {
    const d = await Dummy.findByPk(id)
    console.log(d.id, d.data)
    const data = d.data;
    data.counter = 3;
    await d.update({
      description: 'test3',
      data,
    })
  }
  {
    const d = await Dummy.findByPk(id)
    console.log(d.id, d.data)
  }
  await sequelize.close()
})();
```
Produces the following output:
```
New table created
Executing (default): INSERT INTO `Dummies` (`id`,`description`,`otherAt`,`data`,`createdAt`,`updatedAt`) VALUES (DEFAULT,?,now(),?,?,?);
Executing (default): SELECT `id`, `description`, `otherAt`, `data`, `createdAt`, `updatedAt` FROM `Dummies` AS `Dummy` WHERE `Dummy`.`id` = 7;
7 { counter: 1 }
Executing (default): UPDATE `Dummies` SET `description`=?,`data`=?,`updatedAt`=? WHERE `id` = ?
Executing (default): SELECT `id`, `description`, `otherAt`, `data`, `createdAt`, `updatedAt` FROM `Dummies` AS `Dummy` WHERE `Dummy`.`id` = 7;
7 { counter: 2 }
Executing (default): UPDATE `Dummies` SET `description`=?,`updatedAt`=? WHERE `id` = ?
Executing (default): SELECT `id`, `description`, `otherAt`, `data`, `createdAt`, `updatedAt` FROM `Dummies` AS `Dummy` WHERE `Dummy`.`id` = 7;
7 { counter: 2 }
```
Notice the first update works, but the second one does not.

Tested with Sequelize 6.6.2

**Comment by vkaracic** [comment] 2021-07-14 11:44
I had the same issue and after going through the source code I believe the issue is the way that Sequelize now tests what has changed. As evident from @RufusHamade comment, Sequelize now checks if the updated value is the same as the model instance property value instead of the value that is currently in the database.
So in this case:
```javascript
class User extends Model {}
User.init({
  id: {type: Sequelize.UUID, primaryKey: true, defaultValue: Sequelize.UUIDV4},
  status: DataTypes.JSON
}, { sequelize, modelName: 'user' });

await sequelize.sync();

const aUser = await User.create({
    status: { mood: 'sad' }
 };

const { status } = aUser;
status.mood = 'happy';
aUser.update({ status });

const bUser = await User.findByPk(aUser.id);
console.log(bUser.status.mood); // 'sad', not 'happy'
```

the `aUser.update` checks if `aUser.status === status`, which is equal since it is the same object, and doesn't run any save/updates to the database. Even if you would clone the object it wouldn't work because the values are still the same. I presume in the previous Sequelize version it would check if the database value has changed, so something like `aUser.valuesFromDatabase.status === status` and make the change. Not sure if this change is intentional, I certainly couldn't find any documentation explaining this.

**Comment by mekantor** [comment] 2021-09-20 13:27
Came by this today, you can manually do `instance.changed('column', true);` but this is not ideal. My basic test for it:

```
model = sequelize.define('table', {
    test: {
        type: DataTypes.JSON,
        defaultValue: {}
    }
});

instance = new model();
instance.test.foo = 'bar';

// expecting true, get false
console.log(instance.changed('test'));
```

**Comment by mooncfrat2019** [comment] 2021-11-06 15:00
Confirming the issue. Very annoying. Hope someone can fix it soon)

**Comment by AllAwesome497** [comment] 2023-04-18 21:01
fwiw the issue appears to be that sequelize only checks to see if the reference to the object is the same, i.e. `oldValues.status === newValues.status`.  Could probably solve this by saving the jsonified value as a string and comparing, though that would be at the cost of memory usage.

**Comment by ephys** [comment] 2023-06-22 07:35
That's by design. The new documentation has a big warning about treating the values as immutable: https://sequelize.org/docs/v7/querying/update/#updating-a-row-using-modelsave

Keeping a stringified version (or ideally a `structuredClone`), then deep-equaling them would be expensive. I think it's better to make them immutable. In the future we could even switch to Record & Tuples

I'll close this as working as designed now that it's documented

**Closed by ephys** 2023-06-22 07:35 UTC
Labels: type: bug
