### ISSUE TITLE
queryInterface.bulkUpdate usage

### ISSUE THREAD

**Issue by chaoxihailing** [sequelize/sequelize#8687] opened 2017-11-24 10:29 UTC
I dont understand how pass parameters of function
queryInterface.bulkUpdate(tableName, values, identifier, options, attributes);

I hava a table monitorDevice has fileld like id, monitorSpotId, alarmTypeDeviceSubType, isAvailable;
and I want to update column alarmTypeDeviceSubType, but it not work;

I write query like below, How can I work bulkquery
![image](https://user-images.githubusercontent.com/17508916/33206489-6591905a-d145-11e7-8261-8d02adb42639.png)

#6909

**Comment by mhombach** [comment] 2018-01-15 11:40
In my opinion it seems that you didn't fully understand how the models of Sequelize are used.
First let's all use the same vocabulary:
`I hava a table monitorDevice` -> You mean you have a Sequelize-MODEL called "MonitorDevice" which has the following attributes:

- id
- monitorSpotId
- alarm
- (TypeDeviceSubType ?)
- isAvailable

You query this Model by using `MonitorDevice.doSomething`.
For example `MonitorDevice.findByID(1)`, which gives you the entry with the id 1.
If you want to CREATE a new entry, then you use:
`MonitorDevice.create({ 
id: 5,
monitorSpotId: 99,
alarm: 'something',
isAvailable: false
})`.
This creates and saves these data to the database.
Bulk-create works the same, you just pass it an array which can contain many new entries which are written exactly like the one i wrote above.
So you create an array and fill it. Let's say you called that array "newDataArray".
you then do:
`MonitorDevice.bulkCreate(newDataArray);` which creates and saves new entries for all of the containing entries within the array.
I hope this helpful and you did understand the Sequelize-concept a little bit more :)

**Comment by Taylor123** [comment] 2018-01-18 19:25
I believe the question was asking how to run a bulkUpdate on the Sequelize Model, not a bulkCreate.
Which the documentation never really discusses.

I am having issues with the bulkUpdate trying to update where attribute = X OR attribute = Y.

`return queryInterface.bulkUpdate('table',
  { attributeToUpdate: 'value' },
  {
    attributeToSearchBy: { [Sequelize.Op.or]: [ { attributeToSearchBy: 'X' }, { attributeToSearchBy: 'Y' }]
  });
`

I've attempted a few variations of the identifier parameter, but can't figure out the right way to perform the bulkUpdate. Better documentation and error messages would be much appreciated.

If I get some free time, I would like to eventually contribute as I like the ORM but have ran into some drawbacks with it mainly due to lack of docs and a few missing features.

**Comment by Taylor123** [comment] 2018-01-18 19:35
The question was asking about the bulkUpdate, which currently lacks documentation, not bulkCreate.

I was able to get the bulkUpdate function to run as follows:
`
return queryInterface.bulkUpdate('table', 
  { attributeToUpdate: 'newValue' },
  { 
    attributeToUpdateBy: 'valueToChange' 
  });
`

However, I have not figured out how to set the identifier parameter to allow myself to bulk update via 
`attributeToSearchBy: 'value1' OR 'value2'`

 A code example would be greatly appreciated.

**Comment by Taylor123** [comment] 2018-01-18 19:42
working example of searching a column/attribute by multiple values:

`return queryInterface.bulkUpdate('table', { attributeToUpdate: 'newValue' }, { attributeToUpdateBy: { [Sequelize.Op.or]: [ 'value1', 'value2' ] } });`

My issue was using an object that specified the multiple values I wanted to select columns to update by. My reasoning for using objects instead of an array of values was because that's how the bulkDelete was able to function. I will try and make an update to the docs if I get some time to contribute (and find where to update docs).

**Comment by cyrilchapon** [comment] 2018-02-20 15:00
@Taylor123 thanks for sharing.

Can you paste 1 or 2 full working examples of updates, including mutation ?

Thanks ☺️

**Comment by cyrilchapon** [comment] 2018-05-22 04:46
This is still a god damned issue

**Comment by mhombach** [comment] 2018-05-22 06:28
@cyrilchapon OP is not responding since his first post so we have no way to communicate about the source issue of this thread. OP also had at least one big mistake in his original query (declaring an object without any attribute) so we can ignore that original error. Also, no offense, it seems because of this issue, that OP maybe lacks some general JS skills and may have more logical errors in his code.
If you have this or a related issue with TypeORM, please feel free to create your own issue :)

**Comment by cyrilchapon** [comment] 2018-05-22 07:48
@mhombach, IMHO the issue is not about "bulkUpdate is not usable"; the issue is about "knowing how to use bulkUpdate", which implies, mostly, documentation.

Digging through doc and sourceCode, I've been able to use `bulkUpdate` (in migrations in my case) spending 2 hours understanding the whole concept of Sequelize query and stuff, while I've been able to use `bulkInsert` in less than 5 minutes.

This lacks documentation, but this is a duplicate of https://github.com/sequelize/sequelize/issues/8820

**Comment by mhombach** [comment] 2018-05-22 08:29
@cyrilchapon Yep, i also think that documentation could be better. My whole point was that in my opinion we should let this issue be closed, as the OP seems to not be interested in communicating here. So OP can never close this issue by himself or even tell us, if his problem was solved. So a different issue targeting the lack of documentation is the right way, i think. My point was primary on OP not responding, so this thread here can be considered "dead", at least "a dead end" :/

**Comment by sushantdhiman** [comment] 2018-05-22 08:35
Duplicate of #8820

**Closed by sushantdhiman** 2018-05-22 08:35 UTC
Labels: question
