### ISSUE TITLE
sequelize support for jsonb ,  search by subkey inside array with @> or #>>

### ISSUE THREAD

**Issue by webmobiles** [sequelize/sequelize#8796] opened 2017-12-18 04:34 UTC
I hava a field JSONB called 'tourbooking' inside has this content:

```
[
   {
    "tour_id":
      {
        "id":"d61802ff-3eec-4a72-97ca-832f51b96bf0","name":"Paris  2018"
      },
      "amount":"500.00",
      "customer_id":
          {
             "id":"f492b26d-d260-4bcb-8e96-6532fdf38665",
             "name":"OBAMA John"
          },
     "id":"5cd8338c-15c2-48c5-b305-9e172bb33a9a"
   },
   {
    "tour_id":
      {
        "id":"a52d38d4-9bfb-4ffa-1122-e536f04b0c60","name":"London  2018"
      },
      "amount":"500.00",
      "customer_id":
          {
             "id":"f492b26d-d260-4bcb-8e96-6532fdf38665",
             "name":"OBAMA John"
          },
     "id":"5cd8338c-15c2-48c5-b305-9e172bb33a9a"
   },
]

```
Sequelize give a solution to look subkeys like that: ( point like separator ):
http://docs.sequelizejs.com/manual/tutorial/querying.html  ( Nested key)
```
{
  "tour.tour_id.id": {
    [Op.gt]: 'd61802ff-3eec-4a72-97ca-832f51b96bf0'
  }
}
```

but that is not able to look for data inside arrays.

in Postgresql can do:

```
SELECT *
FROM   toourbooking
WHERE  tour @> '[{"tour_id": {"id":"d61802ff-3eec-4a72-97ca-832f51b96bf0"}}]'
```
 or if I look in the first element:

```
SELECT *
FROM   toourbooking
WHERE  tour  #>> '{0, tour_id, id}' = 'd61802ff-3eec-4a72-97ca-832f51b96bf0'
ORDER  BY "createdAt" DESC;
```

Sequelize give me:

 "toorbooking"."tour"#>>'{tour_id,id}') = 'd61802ff-3eec-4a72-97ca-832f51b96bf0'

but the right would be this for first row in array :

 '{0,tour_id,id}' and not '{tour_id,id}'

but really the right solution is:

tour @> '[{"tour_id": {"id":"d61802ff-3eec-4a72-97ca-832f51b96bf0"}}]'

am I'm doing something wrong? i know change this can take a lot of time, but i'm working in production, and I realize jsonb alternatives with sql in postgresql are very complet and i don't know if sequelize think support it.

I'd like to know, please someone can knows  which js files touch on sequelize, to change by hand the code where sequelize create  '#>>' so i can use an special sequelize version locally;

**Comment by sushantdhiman** [comment] 2017-12-18 07:07
Have you tried `Op.contains` http://docs.sequelizejs.com/manual/tutorial/querying.html#containment

**Comment by webmobiles** [comment] 2017-12-18 08:34
thanks @sushantdhiman , but it does not work, sequelize give now:

`"toorbooking"."tour" @> '{"tour_id":{"id":"d61802ff-3eec-4a72-97ca-832f51b96bf0"}}'`

but it needed the  bracketse ; because it's an array : like this:

`tour @> '[{"tour_id": {"id":"d61802ff-3eec-4a72-97ca-832f51b96bf0"}}]'`

please give a clue; of the file in sequelize where i can modify and study the code, maybe i can  write a PR. it's urgent because i'm production can't do that.

**Comment by webmobiles** [comment] 2017-12-18 09:39
I've fixed it modifying query-generator.js

    ```
if (isPlainObject) {
      if (this.OperatorMap[valueKeys[0]]) {
        /// I've added this block 
        let where2 = this._whereParseSingleValueObject(key, field, valueKeys[0], value[valueKeys[0]], options);
        where2  = where2.replace(' @> \'',' @> \'[');
        where2  = where2.replace('}}\'','}}]\'');
        console.log('where transfor :::::',where2 );
        return  where2;
        //end my block
        //return this._whereParseSingleValueObject(key, field, valueKeys[0], value[valueKeys[0]], options);
      } else {
        return this._whereParseSingleValueObject(key, field, this.OperatorMap[Op.eq], value, options);
      }
    }
```
can I send a pr?

**Comment by webmobiles** [comment] 2017-12-18 16:33
@sushantdhiman what is the way in sequelize to look for jsonb ket with like, 

in postgresql

`select * from module_data where data::json->>'title' like '%Board%'`

i'd like to conver the support of potsgresql (if there is) to search in array too. please tell me the way the sequelize for search with like , thanks

**Comment by sushantdhiman** [comment] 2017-12-19 03:49
@webmobiles I haven't tried searching on JSONB with like 

Something like this should work.

```js
{
    title: {
         $like: '%Board%'
    }
}
```

This issue is duplicate of https://github.com/sequelize/sequelize/issues/5173 , so I am closing this one.

> can I send a pr?

Yes you can submit PR with that fix so others can review as well. You need to add some tests as well https://github.com/sequelize/sequelize/blob/master/test/integration/json.test.js

**Closed by sushantdhiman** 2017-12-19 03:49 UTC

**Comment by vkm912** [comment] 2018-10-03 19:33
Has this been merged with the Master Branch?

> I've fixed it modifying query-generator.js
> 
> ```
> if (isPlainObject) {
>       if (this.OperatorMap[valueKeys[0]]) {
>         /// I've added this block 
>         let where2 = this._whereParseSingleValueObject(key, field, valueKeys[0], value[valueKeys[0]], options);
>         where2  = where2.replace(' @> \'',' @> \'[');
>         where2  = where2.replace('}}\'','}}]\'');
>         console.log('where transfor :::::',where2 );
>         return  where2;
>         //end my block
>         //return this._whereParseSingleValueObject(key, field, valueKeys[0], value[valueKeys[0]], options);
>       } else {
>         return this._whereParseSingleValueObject(key, field, this.OperatorMap[Op.eq], value, options);
>       }
>     }
> ```
> can I send a pr?

Has this been merged with the Master Branch?
