### ISSUE TITLE
Automatically get all table columns in a sequelize model

### ISSUE THREAD

**Issue by spimou** [sequelize/sequelize#11822] opened 2020-01-13 13:30 UTC
## Issue Description

Is there is a way to define a Model and have it get all the table columns automatically ?

We have a huge dataset and the table that I will base the Model on, has 200 columns. Even if I need only 50 from the 200 columns, it is still a lot.

Is there a way to define the Model and it will automatically get all the columns with their names, instead of me defining each columns by hand ? 

Something like

```
const HugeData = db.define('likeALotOfData', {
  //got all 200 columns 
  //I can start using it now
})
```

### StackOverflow / Slack attempts

[stackoverflow](https://stackoverflow.com/questions/59715943/automatically-get-all-table-columns-in-a-sequelize-model)

### Additional context
I am using mssql and tedious

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [x ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ x] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment] 2020-01-19 19:11
Duplicate of #11770

**Closed by papb** 2020-01-19 19:11 UTC
