### ISSUE TITLE
Issue with findByPk(1) 

### ISSUE THREAD

**Issue by smuralimohan** [sequelize/sequelize#13792] opened 2021-12-19 08:57 UTC
Hi, I am testing Sequelize using Postgres dialect. For some reason, **findByPk(1)** (with id = 1) does not work at all. And it is not just findByPk(1) that does not work, but also **findOne({where: {id:1}}), findAll({ where: {id:1} }) and findAll({ where: { id: { [Op.eq] : 1} }})** don't work.

However, for ids > 1 it is working fine. I tested using in-memory SQLite also and the problem exists there as well.
My sequelize and node versions are as below.

"pg": "^8.7.1",
"pg-hstore": "^2.3.4",
"sequelize": "^6.12.0",

Node: v16.13.0

My database table have the following records.
id name notes
1 "Daily Dose" "Diabetes, BP"
2 "Daily Dose" "Diabetes, BP"
3 "Daily Dose" "Sugar, BP"

**Comment by AfonsoDev** [comment] 2021-12-29 03:15
I'm having the same problems, did you find any solution?

**Comment by WikiRik** [comment] 2021-12-29 12:06
findByPk(1) is used in various of our integration tests, also for postgres (for example [here])(https://github.com/sequelize/sequelize/blob/main/test/integration/dialects/postgres/dao.test.js#L1035-L1161). Same with findOne({ where: { id: 1 }}) (for example [here](https://github.com/sequelize/sequelize/blob/main/test/integration/data-types.test.js#L467-L487))

Can you make a [SSCCE](https://github.com/papb/sequelize-sscce) or a Pull Request with a failing test so we can debug this issue?

**Comment by smuralimohan** [comment] 2021-12-30 05:42
Hello @AfonsoDev 
No. no solution yet. I have switched to TypeORM after trying several options like Sequelize, Knex+Bookshelf, Knex+Objection etc etc..

**Comment by smuralimohan** [comment] 2022-01-14 03:21
Any updates on this one please? This is a serious bug.

**Comment by WikiRik** [comment] 2022-01-14 08:44
> findByPk(1) is used in various of our integration tests, also for postgres (for example [here])(https://github.com/sequelize/sequelize/blob/main/test/integration/dialects/postgres/dao.test.js#L1035-L1161). Same with findOne({ where: { id: 1 }}) (for example [here](https://github.com/sequelize/sequelize/blob/main/test/integration/data-types.test.js#L467-L487))
> 
> Can you make a [SSCCE](https://github.com/papb/sequelize-sscce) or a Pull Request with a failing test so we can debug this issue?

Hi @smuralimohan 
Since I have not had a response on my previous message no work has been done yet. Could you make a SSCCE or a PR with a failing test so we can debug this issue?

**Comment by WikiRik** [comment] 2022-01-16 12:45
I see that you've submitted a small SSCCE here; https://github.com/sequelize/sequelize-sscce/pull/203 but that passes for the non-TS tests (the TS tests fail for an issue unrelated to the SSCCE). So therefore I will close this issue unless we have enough information to reproduce that this is an issue.

This extra information can be submitted in this ticket and then we can reopen it.

**Closed by WikiRik** 2022-01-16 12:45 UTC
Labels: status: awaiting investigation
