### ISSUE TITLE
queryInterface.removeColumn doesn't drop enum type (Postgres)

### ISSUE THREAD

**Issue by jedwards1211** [sequelize/sequelize#8859] opened 2018-01-08 22:13 UTC
## What are you doing?

I have the a migration that removes a column with an `ENUM` type.  Reverting the migration fails because Sequelize didn't drop the enum type, and reversion fails when it tries to recreate the already-existing type.

Maybe this is intended behavior, but I would think that `removeColumn` should always clean up everything that `addColumn` or `sync` created.

```js
// @flow

import type SequelizeClass, {QueryInterface} from 'sequelize'

const Channels = 'Channels'

module.exports = {
  async up(queryInterface: QueryInterface, Sequelize: Class<SequelizeClass>): Promise<void> {
    await queryInterface.removeColumn(Channels, 'mode')
  },
  async down(queryInterface: QueryInterface, Sequelize: Class<SequelizeClass>): Promise<void> {
    await queryInterface.addColumn(Channels, 'mode', {
      type: Sequelize.ENUM('ANALOG_INPUT', 'DIGITAL_INPUT', 'DIGITAL_OUTPUT', 'DISABLED'),
      allowNull: false,
      defaultValue: 'DISABLED',
    })
  },
}
```

## What do you expect to happen?
The `down` method succeeds after `up` has been performed

## What is actually happening?
`down` results in the following error:
```
SequelizeDatabaseError: type "enum_Channels_mode" already exists
```

__Dialect:__ postgres
__Dialect version:__ 6.4.2
__Database version:__ 10
__Sequelize version:__ 4.29.2
__Tested with latest release:__ Yes (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment] 2018-01-11 04:43
Thats true but that enum may be used by other columns so we dont drop it. What do you propose for those cases

**Comment by jedwards1211** [comment] 2018-01-11 07:02
@sushantdhiman did you guys assume that Postgres can't handle that properly? Looks like it can:
https://www.postgresql.org/docs/8.2/static/sql-droptype.html
```
DROP TYPE [ IF EXISTS ] name [, ...] [ CASCADE | RESTRICT ]
```
> RESTRICT
Refuse to drop the type if any objects depend on it. This is the default.

**Comment by plumSemPy** [comment] 2018-01-12 00:57
I don't think type should be dropped with a column. They are two different things on the database and dropping a type with a column is implicit and will cause confusion. SQLAlchemy also does not drop types. Moreover, it is not just Postgres, this should remain functional for all databases should Sequelize choose to extend its functionality

**Comment by jedwards1211** [comment] 2018-01-12 04:54
@plumSemPy it would only drop the type if nothing is using it.  After all, Sequelize implicitly created the type to begin with.  You really think that would cause any problems?

**Comment by sushantdhiman** [comment] 2018-01-20 07:01
Actually this is a duplicate of long standing issue https://github.com/sequelize/sequelize/issues/2554

**Closed by sushantdhiman** 2018-01-20 07:01 UTC
Labels: bug, good first issue
