### ISSUE TITLE
how can I create a Model to support GeoData in Sequelize?

### ISSUE THREAD

**Issue by uchsarath** [sequelize/sequelize#3323] opened 2015-03-11 11:01 UTC
I have problem in Model. I don't know which data should use to store GeoData - POINT(12312312,234234)

Anyway, how to insert long & lat into the Sequelize?

**Comment by janmeier** [comment] 2015-04-07 11:09
Geometry types are not currently supported in sequelize. You can define the column as a string with `col: 'POINT'` 

Dupe of https://github.com/sequelize/sequelize/issues/2839

**Closed by janmeier** 2015-04-07 11:09 UTC

**Comment by emil-alexandrescu** [comment] 2015-08-21 11:52
saved me bunch of time. Thanks!
