### ISSUE TITLE
Auto Generating Migrations

### ISSUE THREAD

**Issue by dhayaleswaran** [sequelize/sequelize#16538] opened 2023-09-23 15:33 UTC
## Issue Creation Checklist

- [x] I understand that my issue will be automatically closed if I don't fill in the requested information
- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

### Describe the feature you'd like to see implemented

Once I've created models like User.model.ts, my aim is to be able to run a command like `sequelize-cli models:automigrations`. This command should generate a file named `<model-name>-<timestamp>.sql`, which will encapsulate the SQL representation of the model change (before and after versions)

### Describe why you would like this feature to be added to Sequelize

When I work with Sequelize to create DAOs, I find that the most challenging aspect is generating migrations. It often requires relying on third-party libraries to automatically generate migrations because manually creating them can be quite difficult, especially when dealing with a constantly evolving database schema. I believe it would greatly improve Sequelize if it had a built-in feature for automatically generating migrations based on the existing models. My idea is to have these migrations generated as distinct versions in SQL files, making them easily consumable by both JavaScript and TypeScript projects.

While I do have the time to dedicate to this, I would greatly appreciate someone's assistance in getting started and becoming comfortable with the process.

### Is this feature dialect-specific?

- [x] No. This feature is relevant to Sequelize as a whole.
- [ ] Yes. This feature only applies to the following dialect(s): 

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I will need guidance.
- [ ] No, I don't have the time, but my company or I are [supporting Sequelize through donations on OpenCollective](https://opencollective.com/sequelize).
- [ ] No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in implementing my feature.

---

*Indicate your interest in the addition of this feature by adding the 👍 reaction. Comments such as "+1" will be removed.*

**Comment by ephys** [comment] 2023-12-13 15:00
This is planned, but is part of the CLI.
Closing as duplicate of https://github.com/sequelize/cli/issues/257

**Closed by ephys** 2023-12-13 15:00 UTC
Labels: type: feature, pending-approval
