### ISSUE TITLE
Using a leak library <bluebird>, got any plan to replace it?

### ISSUE THREAD

**Issue by axetroy** [sequelize/sequelize#8315] opened 2017-09-16 09:00 UTC
https://github.com/petkaantonov/bluebird/issues/1445
https://github.com/petkaantonov/bluebird/issues/1446

I search the blurbird's method in squelize/lib with keyword "**Promise.**"

and found methods are being used:
- [x] Promise.all (Standard)
- [x] Promise.reject (Standard)
- [x] Promise.resolve (Standard)
- [x] Promsie.race (Standard)
- [ ] Promise.try
- [ ] Promise.each
- [ ] Promise.map
- [ ] Promise.promisfy

And we can see, haft of them are ECMA Standard, and why will we need a complicated library?

Actually, others method can be implement by self.

Every SQL query comes with memory rises and can not be released. Don't need much time, the process crash.

More library you need, more bugs come.

**Comment by benjamingr** [comment] 2017-09-16 09:46
Bluebird only leaks in long stack traces mode and not in production - this is intended behavior and a debugging feature. You can turn it off if you'd like :)

If you create a promise chain, then having a long stack trace literally means keeping that information around.

Sequelize has been using bluebird for several years now and needs to support older versions of Node.js.

Note that the Bluebird team is basically all Node.js contributors and collaborators and we're actively working to put ourselves out of business by helping native promises become fast enough. I think a year is a reasonable goal. 

We're all the same people really, so when you're bashing how promises work in Node.js or bashing bluebird, it's still our F**K up :D

**Comment by sushantdhiman** [comment] 2017-09-16 15:59
Bluebird promises ares still faster than their native counterparts, at least for Node v4 / v6. Bluebird provides lots of useful methods which are actively used by our codebase.

As already noted, this memory leak is caused by longStackTraces and is not something unexpected. Production version should not be affected by this.

Bluebird is widely used library and well tested, I dont think we will drop Bluebird any time soon

**Comment by loyd** [comment] 2017-09-20 12:00
https://github.com/petkaantonov/bluebird/issues/1445 doesn't include `longStackTraces`.

**Comment by consense** [comment] 2017-09-21 19:05
Usage of Bluebird makes overwriting Model methods annoying when using Typescript as return signatures of Bluebird.Promise<xyz> and Promise<xyz> are not compatible.
Might not be a problem for the majority of Sequelize users, so just pointing out an additional point :-)

Thanks for the great ORM by the way

**Comment by benjamingr** [comment] 2017-09-21 19:25
> petkaantonov/bluebird#1445 doesn't include longStackTraces.

We have not been able to reproduce that, I'm waiting for Petka to take a look

**Comment by mouhamed** [comment] 2017-09-27 13:12
@consense For Typescript, you can use `PromiseLike` instead of `Promise` so typehinting will be ok whichever Promise library is beeing used

**Comment by scarlac** [comment] 2018-05-16 01:12
Newer versions of Node now has better stack traces for native promises. Am I correct in assuming that switching to native Promise would make it easier to debug SQL errors? That's personally my main concern.

**Comment by benjamingr** [comment] 2018-05-16 07:49
@scarlac not at the moment - we're actually going to discuss this at the Node collaborator summit the end of the month. 

If you feel like being generous and doing me a favour - can you please open this as a use case for that discussion at https://github.com/nodejs/promise-use-cases I would appreciate it.

The end-game is definitely to switch to native promises and we're working on making them viable - as someone involved with both Bluebird and Node I recommend native promises for app developers (where performance isn't super critical and you can add bluebird later + async functions are native anyway) and I recommend bluebird to library authors (the bigger the library the more important less overhead is).

**Comment by benjamingr** [comment] 2018-10-15 08:04
> Newer versions of Node now has better stack traces for native promises. 

Worth mentioning this is WIP, we will make an announcement when native async/await (currently - just async/await np promise chaining) will have async stack traces in production.

The v8 team has been amazing in receiving feedback and implementing this for us and it's WIP, the initial PR landed just last week :)

**Comment by muayyad-alsadi** [comment] 2019-04-24 17:05
Can't we have sequelize.promise and that either assigned to native promise or bluebird's promise

The missing methods can be added  (we can wrap the native to provide the missing p.try). So that it will be a matter of choice (no need to rewrite code)

**Comment by papb** [comment] 2019-07-26 00:02
@SimonSchick [started to work on it](https://github.com/sequelize/sequelize/commit/2fc27f68fcdf17a6c96e50856a5e20b5cd5de5fe).

**Comment by benjamingr** [comment] 2019-07-26 08:44
@papb awesome news, let me know if you have any questions about debuggability with native promises vs. bluebird

**Comment by SimonSchick** [comment] 2019-07-26 13:41
I *was* working on it, it's a tremendous amount of work and probably won't happen this year.

**Comment by benjamingr** [comment] 2019-07-26 22:30
@SimonSchick anything I (as both Node core and Bluebird core) can help with? Anything in particular missing?

**Comment by SimonSchick** [comment] 2019-07-26 23:24
@benjamingr you can look at https://github.com/sequelize/sequelize/tree/chore/remove-bluebird
I will attempt to rebase this on the vnext branch, and you can dabble with it a bit 😛

**Comment by papb** [comment] 2019-07-27 04:25
@benjamingr It is great to have your support, thank you!

**Comment by SimonSchick** [comment] 2019-07-27 16:59
@benjamingr I rebased ontop of the `next` (v6) branch, all unit tests are passing, there are quite a few integration test failures however.

**Comment by benjamingr** [comment] 2019-07-27 21:26
It's a huge PR with a lot of changes unrelated to promises and bluebird. Anything in particular I should look at?

The fact transactions always have to be explicit now is a bit annoying but I understand why it works this way. Just so you know - you can keep the old behavior by using [async_hooks](https://nodejs.org/api/async_hooks.html) and establishing context.

Native promises are going to be slower in Node 8, but Node 10 is going to be as fast and Node 12 (with async functions) is going to have async stack traces like bluebird which is good.

**Comment by papb** [comment] 2019-07-27 21:31
@benjamingr Am I mistaken, or async_hooks can only be used in Node 12?

**Comment by benjamingr** [comment] 2019-07-27 22:07
@papb async hooks work from Node 8 +, in general all our [api pages](https://nodejs.org/api/async_hooks.html) have the earliest supported Node.js version on APIs.

**Comment by papb** [comment] 2019-07-27 22:16
@benjamingr Oops, that's right! Awsome.

**Comment by SimonSchick** [comment] 2019-07-27 22:21
@benjamingr Please focus on the last commit on this branch, there should be *very* few unrelated changes, 4-5 lines max.

**Comment by HopefulLlama** [comment] 2019-09-18 13:04
What happened here?

**Comment by papb** [comment] 2019-09-18 16:01
@HopefulLlama Can you be more specific?

**Comment by HopefulLlama** [comment] 2019-09-18 16:04
Sorry, I guess I should have been to begin with.

Is the Promise library still planned to be replaced?
What happened with the pull request talked about in this thread?

**Comment by papb** [comment] 2019-09-18 16:11
@HopefulLlama Yes, it is still planned to be replaced, but this probably won't happen in the very near future because maintainers are busy with other priorities now.

**Comment by papb** [comment] 2019-10-18 12:31
By the way as I mentioned in the duplicate issue, I am a big fan of [sindresorhus/promise-fun](https://github.com/sindresorhus/promise-fun), we could use that where necessary.

However, to be honest, I also think that keeping Bluebird is not that bad... Bluebird is a really good Promise library :)

**Comment by sushantdhiman** [comment] 2020-04-25 11:43
Bluebird removed https://github.com/sequelize/sequelize/pull/12140

**Closed by sushantdhiman** 2020-04-25 11:43 UTC
Labels: breaking change, status: wip

**Comment by benjamingr** [comment] 2020-04-25 12:02
Congrats 🎉 Let us know in what utils or tools core can help with
