### ISSUE TITLE
model.changed() returns id if I change from int to string

### ISSUE THREAD

**Issue by jamesaspence** [sequelize/sequelize#5284] opened 2016-01-22 16:17 UTC
Let's say I have a model that has data like this:
    
    {
        order_id: 12345,
        name: 'Johhny'
    }

If I changed that order_id to `'12345'`, and called `changed()` on the model, it'll return `['order_id']`.

Is there a way I can turn off strict checking? I just want to ensure the values are correct, rather than the types match.

**Comment by jamesaspence** [comment] 2016-01-22 16:22
For now I set a custom setter for that `order_id` that converts it to a number on storage. I'm just hoping to remove that necessity in the future because I worry it'll become busy work and that it'll be easy to miss.

**Comment by BridgeAR** [comment] 2016-01-22 18:11
Duplicate of #4845

**Closed** 2016-01-23 09:36 UTC
