### ISSUE TITLE
Error: Connection lost: The server closed the connection.

### ISSUE THREAD

**Issue by iamchairs** [sequelize/sequelize#2675] opened 2014-12-05 13:33 UTC
I get this error occasionally. Is there a way sequelize can reconnect automatically when this happens?

    Error: Connection lost: The server closed the connection.
        at Protocol.end (/Users/micahwilliamson/projects/googlepredict/server/node_modules/mysql/lib/protocol/Protocol.js:103:13)
        at Socket.<anonymous> (/Users/micahwilliamson/projects/googlepredict/server/node_modules/mysql/lib/Connection.js:88:28)
        at Socket.emit (events.js:117:20)
        at _stream_readable.js:943:16
        at process._tickDomainCallback (node.js:463:13)
        --------------------
        at Protocol._enqueue (/Users/micahwilliamson/projects/googlepredict/server/node_modules/mysql/lib/protocol/Protocol.js:135:48)
        at Connection.query (/Users/micahwilliamson/projects/googlepredict/server/node_modules/mysql/lib/Connection.js:185:25)
        at module.exports.Query.run (/Users/micahwilliamson/projects/googlepredict/server/node_modules/snooze/node_modules/sequelize/lib/dialects/mysql/query.js:26:17)
        at Function.<anonymous> (/Users/micahwilliamson/projects/googlepredict/server/node_modules/snooze/node_modules/sequelize/lib/dialects/mysql/connector-manager.js:410:23)
        at null.<anonymous> (/Users/micahwilliamson/projects/googlepredict/server/node_modules/snooze/node_modules/sequelize/lib/emitters/custom-event-emitter.js:105:15)
        at emit (events.js:95:17)
        at module.exports.CustomEventEmitter.emit (/Users/micahwilliamson/projects/googlepredict/server/node_modules/snooze/node_modules/sequelize/lib/emitters/custom-event-emitter.js:61:33)
        at /Users/micahwilliamson/projects/googlepredict/server/node_modules/snooze/node_modules/sequelize/lib/dialects/mysql/connector-manager.js:245:19
        at /Users/micahwilliamson/projects/googlepredict/server/node_modules/snooze/node_modules/sequelize/node_modules/generic-pool/lib/generic-pool.js:278:11
        at /Users/micahwilliamson/projects/googlepredict/server/node_modules/snooze/node_modules/sequelize/lib/dialects/mysql/connector-manager.js:133:13

**Comment by unmanner89** [comment] 2015-03-16 10:47
Hi guys!

So.. how to handle this error: 'SequelizeConnectionError: Connection lost: The server closed the connection.' ?

It's very difficult to handle it in esch '.catch()' method for me.

**Comment by mickhansen** [comment] 2015-03-16 10:53
@unmanner89 As stated Sequelize doesn't support automatic reconnects/automatic re-sending of query.
How you handle it is mostly up to you and the specific context.

**Comment by janmeier** [comment] 2015-03-24 15:03
Duplicate of https://github.com/sequelize/sequelize/issues/2113

**Closed by janmeier** 2015-03-24 15:03 UTC
Labels: bug, discussion, feature
