### ISSUE TITLE
Site Search doesn't work

### ISSUE THREAD

**Issue by wzup** [sequelize/sequelize#6566] opened 2016-09-08 04:56 UTC
Each and every search request returns this:

![server error _ read the docs - google chrome 2016-09-08 12 55 22](https://cloud.githubusercontent.com/assets/3880497/18337471/895c8b2c-75c3-11e6-819e-7f2a587503bf.png)

How may I conduct search for functionality?

**Comment by felixfbecker** [comment] 2016-09-08 05:18
Duplicate of #6486

**Closed by felixfbecker** 2016-09-08 05:18 UTC
