### ISSUE TITLE
FindAndCountAll returns wrong count 

### ISSUE THREAD

**Issue by yalamber** [sequelize/sequelize#10239] opened 2018-12-06 20:17 UTC
## What are you doing?
I have two models with many to many association. Below are Client and user models which are associated through ClientUser model, I am trying to use findAndCountAll using ClientUser model, when I don't use distinct: true, I get wrong result may be as it counts all associated models but even if I do distinct: true I always get count 1 as it seems to be doing distinct in ClientUser.ClientId which is always 1 as i am trying to get all users in specific client id. 
```js
//clients model
module.exports = (sequelize, DataTypes) => {
  let Client = sequelize.define('Client', {
    clientId: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
    name: { type: DataTypes.STRING(255), allowNull: false },
  });
  Client.associate = (models) => {
    Client.belongsToMany(models.User, {
      through: models.ClientUser,
      as: 'users',
      foreignKey: 'clientId',
      otherKey: 'userId'
    });
  };
  return Client;
}
//user model
module.exports = (sequelize, DataTypes) => {
  let User = sequelize.define('User', {
    userId: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
    username: {
      type: DataTypes.STRING(255), unique: true, validate: {
        min: 3,
        max: 30,
        is: /^[a-z\d](?:[a-z\d]|-(?=[a-z\d])){0,30}$/i
      }
    },
    password: {
      type: DataTypes.STRING(255),
      validate: {
        min: 6
      }
    },
  }, {
      defaultScope: {
        attributes: { exclude: ['password'] },
      }
    });
  User.associate = (models) => {
    User.belongsToMany(models.Client, {
      through: models.ClientUser,
      as: 'clients',
      foreignKey: 'userId',
      otherKey: 'clientId'
    });
  };
  return User;
}
//client user
module.exports = (sequelize, DataTypes) => {
    let ClientUser = sequelize.define('ClientUser', {
      status: {
        type: DataTypes.ENUM,
        values: ['active', 'inactive']
      }
    });
    ClientUser.associate = (models) => {
      ClientUser.belongsTo(models.Client, {as: 'client', foreignKey: 'clientId'});
      ClientUser.belongsTo(models.User, {as: 'user', foreignKey: 'userId'});
    };
    return ClientUser;
}
//query here
let params = {
    include: [{
      model: User,
      as: 'user',
    }],
    where: {
       clientId: 1
    },
    distinct: true
};
let result = await ClientUser.findAndCountAll(params);
```

## What do you expect to happen?
I expect the correct result with correct count. 

## What is actually happening?
produces wrong count. 
without distinct: true
```sql
SELECT count(`ClientUser`.`clientId`) AS `count` FROM `ClientUsers` AS `ClientUser` LEFT OUTER JOIN `Users` AS `user` ON `ClientUser`.`userId` = `user`.`userId` LEFT OUTER JOIN `ContactInformations` AS `user->contactInformation` ON `user`.`userId` = `user->contactInformation`.`userId` LEFT OUTER JOIN `InstantMessengerInfos` AS `user->instantMessengerInfos` ON `user`.`userId` = `user->instantMessengerInfos`.`userId` LEFT OUTER JOIN `Roles` AS `role` ON `ClientUser`.`roleId` = `role`.`roleId` WHERE `ClientUser`.`clientId` = '1';
```
with distinct: true
```sql
 SELECT count(DISTINCT(`ClientUser`.`clientId`)) AS `count` FROM `ClientUsers` AS `ClientUser` LEFT OUTER JOIN `Users` AS `user` ON `ClientUser`.`userId` = `user`.`userId` LEFT OUTER JOIN `ContactInformations` AS `user->contactInformation` ON `user`.`userId` = `user->contactInformation`.`userId` LEFT OUTER JOIN `InstantMessengerInfos` AS `user->instantMessengerInfos` ON `user`.`userId` = `user->instantMessengerInfos`.`userId`
LEFT OUTER JOIN `Roles` AS `role` ON `ClientUser`.`roleId` = `role`.`roleId` WHERE `ClientUser`.`clientId` = '1';
```

__Dialect:__ mysql 
__Dialect version:__ 1.6.4
__Database version:__  5.7.24
__Sequelize version:__ 4.41.2
__Tested with latest release:__ Yes 4.41.2 (If yes, specify that version)

**Comment by leogoesger** [comment] 2018-12-08 06:35
+1

**Comment by ricardomoura** [comment] 2018-12-27 15:41
same issue here.
very annoying any group by query is returning count as like `[{count: '1'}, {count: '1'}, {count: '1'}]`

**Comment by MatthewHerbst** [comment] 2019-01-02 01:37
Possibly related: #9481 and #9669

**Comment by Alexsey** [comment] 2019-01-16 18:10
The first issue on this https://github.com/sequelize/sequelize/issues/9109

**Comment by MatthewHerbst** [comment] 2019-04-16 19:24
This is not a stale issue, and in fact (imho) is one of Sequelize's most egregious bugs.

**Comment by MatthewHerbst** [comment] 2019-07-15 19:47
This is not a stale issue.

**Comment by papb** [comment] 2019-07-25 20:22
Is this an issue only with MySQL or does it happen with another dialect too?

**Comment by papb** [comment] 2019-07-30 21:49
Duplicate of #9109

**Closed by papb** 2019-07-30 21:49 UTC
Labels: status: awaiting response, type: bug

**Comment by faraz9x** [comment] 2022-01-24 15:03
distinct: true works but remember, your query must include an @Index column
