### ISSUE TITLE
JSON Type returning as string with latest patch 2.0.3

### ISSUE THREAD

**Issue by joeylgutierrez** [sequelize/sequelize#3200] opened 2015-02-23 18:27 UTC
We're saving a JSON template to a JSON Type in postgres 9.3.

```javascript
self.update = function (productionTemplate) {
        let orig, newTemplate;
        return self.get()
            .then(function (oldTemplate) {
                orig = oldTemplate;
                return db.productionTemplate.build(productionTemplate).save();
            })
            .then(function (template) {
                newTemplate = template;
                return orig.updateAttributes({active: false});
            })
            .then(function (data) {
                return Q.when(newTemplate);
            })
            .catch(function (err) {
                return Q.reject(err);
            });
    };
```
productionTemplate.template is the JSON object. I would expect that productionTemplate.template would be returned as an Object as it was with 2.0.2.  We are using the Postgres dialect.

**Comment by jfairley** [comment] 2015-02-23 18:36
Adding a little more context...

This is our model:
```javascript
    sequelize.define('ProductionTemplate', {
        id: Sequelize.INTEGER,
        name: Sequelize.STRING,
        active: Sequelize.BOOLEAN,
        createdAt: Sequelize.DATE,
        updatedAt: Sequelize.DATE,
        canDelete: {type: Sequelize.BOOLEAN, set: false},
        template: Sequelize.JSON
    }, {
        tableName: 'production_templates', // this will define the table's name
        timestamps: true
    });
```

And this is a test that passes in sequelize 2.0.2, but fails with sequelize 2.0.3:
```javascript
    it('should update the production template', function () {
        let jsonData = '{ "test" : "data" }',
            template = {name: 'test_template_11', template: jsonData};

        return templateService.update(template)
            .then(function (data) {
                assert.deepEqual(data.template, JSON.parse(jsonData));
                return templateService.get();
            })
            .then(function (data) {
                // compare formatted JSON
                assert.deepEqual(data.template, JSON.parse(jsonData));
            });
    });
```

```
  2) ProductionTemplateService should update the production template:
     AssertionError: "{ \"test\" : \"data\" }" deepEqual {"test":"data"}
```

**Comment by joeylgutierrez** [comment] 2015-02-23 18:48
we looked at this more closely and we're passing in a string and it's going in as a string with additional escaped characters but i would expect something like this.

``` javascript
   // stringify JSON structure
        if (typeof productionTemplate.template === 'string') {
            try {
                // validate JSON by parsing
               JSON.parse(productionTemplate.template);
            } catch (err) {
                return Q.reject(err);
            }
        }
```

Where if it is a string and we're storing as a string, you would use the string I provide, otherwise use the object i provide and turn it into a string.  By changing my string, it actually makes it hard to validate our tests.  We are going to do the code above on our service and will change the string to an object but it would be nice to have the library do it.

**Comment by mickhansen** [comment] 2015-02-23 18:59
Might be related to the changes @janmeier implemented

**Comment by jfairley** [comment] 2015-02-23 19:25
Yeah, I bet this is the culprit.

https://github.com/sequelize/sequelize/pull/3081/files#diff-7e347c4738c97261969fbeb802a3c363L874

**Comment by janmeier** [comment] 2015-02-24 08:04
I believe the behaviour added in my latest PR is correct. According to the PG docs, http://www.postgresql.org/docs/9.4/static/datatype-json.html primitives types (strings, numbers etc) are also valid JSON, and as such they should also be JSON encoded before being inserted. 

In  your case I'd add a  `JSON.parse` call in a custom setter

**Comment by jfairley** [comment] 2015-02-24 22:23
Setting a string into the database isn't incorrect. The problem is that the change enables `JSON.stringify()` to be called regardless of what's passed in.

In our case, we have:

```javascript
JSON.stringify('{ "test" : "data" }');
```

But this string does not need to be stringified as it is already a string.

Alternatively, the code could look like:

```javascript
if (typeof input !== 'string') {
    JSON.stringify(input);
}
```

**Comment by janmeier** [comment] 2015-02-25 08:30
The code you proposed does not cover all cases however.

`value` could be a plain string, as per the PG docs. If we don't call stringify on that, the insert query will look like this:
```sql
("jsonfield") VALUES ('plain string')
```
Which gives the error `invalid input syntax for type json`.  Of course we could do `try { JSON.parse }` to see if the passed in data is already stringified, but I believe that adds unnecessary complexity to sequelize core. 

My suggestion would still be to add a setter to the JSON field(s) that tries to do JSON.parse

**Comment by janmeier** [comment] 2015-04-07 11:12
Closing - this should be solved using `JSON.parse / stringify` in user-land

**Closed by janmeier** 2015-04-07 11:12 UTC
