### ISSUE TITLE
Cannot find module 'pg-native'

### ISSUE THREAD

**Issue by dylanchau** [sequelize/sequelize#11543] opened 2019-10-13 08:57 UTC
### What are you doing?

When I started the app(Webpack: 4.40.2 + sequelize: 5.19.6), I got the error as below:

```js
Cannot find module 'pg-native'
Require stack:
- ..\app\node_modules\pg\lib\native\client.js
- ..\app\node_modules\pg\lib\native\index.js
- ..\app\node_modules\pg\lib\index.js
- ..\app\dist\main.js
(node:9256) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.dirname (path.js:583:5)
    at Sequelize.import (..\app\node_modules\sequelize\lib\sequelize.js:475:31)
```
This is my sequelize config
```js
import Sequelize from 'sequelize'
import pg from 'pg'

const sequelize = new Sequelize('database', 'username', 'password', {
  host: 'localhost',
  dialect: 'postgres',
  dialectModule: pg
})
...
```

and webpack.config.js
```js
...

module.exports = env => {
  return merge([
    {
      entry: './src/index.js',
      output: {
        path: path.resolve(__dirname, './dist')
      },
      target: 'node',
      externals: [nodeExternals()],
      stats: 'errors-only',
      module: {
        rules: [
          {
            test: /\.js$/,
            exclude: /node_modules/,
            use: {
              loader: 'babel-loader',
              options: {
                plugins: [
                    "@babel/plugin-syntax-dynamic-import"
                ]
            }
            },
          },
          {
            test: /\.(graphql|gql)$/,
            exclude: /node_modules/,
            use: 'raw-loader'
          },
        ],
      },
      [
		new webpack.IgnorePlugin(/\.\/native/, /\/pg\//),
		new NodemonPlugin({
		  ignore: ['node_modules/*']
		})
	  ]
    },
  ])
}
```

I have tried many solutions on google, but they did not working for my situation

### Environment

- Dialect: postgres
- Sequelize version: 5.19.6 
- Node.js version: v12.10.0

**Comment by papb** [comment] 2019-10-13 18:16
Duplicate of #3781 

Please try the workarounds suggested there, such as [the most recent one](https://github.com/sequelize/sequelize/issues/3781#issuecomment-537979334) by AlariCode.

**Closed by papb** 2019-10-13 18:16 UTC
