### ISSUE TITLE
Creating associations between 2 separate databases?

### ISSUE THREAD

**Issue by marbuser** [sequelize/sequelize#10191] opened 2018-11-22 14:09 UTC
I'm developing an application that works together with a popular forum software (XenForo).
XenForo comes with the table `xf_user`.

In my application let's say I have a model/table `transactions`, and wanted to make it so that when a transaction is created, I can reference the users forum id from the `xf_user` table. How would I go about doing that?

I've tried looking through the docs and googling but can't seem to find a solution to this. I've created 2 separate Sequelize instances inside my node app but not sure where else to go from here or if this is even possible.

If it isn't possible, what would be the next best solution to this?

Thanks!

**Comment by sushantdhiman** [comment] 2018-11-28 05:58
Duplicate of https://github.com/sequelize/sequelize/issues/2049

**Closed by sushantdhiman** 2018-11-28 05:58 UTC
