### ISSUE TITLE
find, getX querying on join table

### ISSUE THREAD

**Issue by elliotstokes** [sequelize/sequelize#3222] opened 2015-02-25 10:33 UTC
I have a many to many relationship

User has many events through EventUser
Event has many User through EventUser

EventUser has a column status

I was pre 2.0 doing this

      event.getUsers({where: {"EventUser.status": "invited"}}),

Now this no longer works. I have tried

      event.getUsers({include : [{model:"EventUser", where: {status: "invited"}}]});

but I get the error

Possibly unhandled Error: EventUser is not associated to User!

I'm probably missing something obvious here but I couldn't seem to find anything related to this in the docs.

**Comment by janmeier** [comment] 2015-02-25 10:41
Duplicate of https://github.com/sequelize/sequelize/issues/3198

**Closed by janmeier** 2015-02-25 10:41 UTC
