### ISSUE TITLE
Async model validation stopped working on 2.0.0-rc4

### ISSUE THREAD

**Issue by GuilhermeReda** [sequelize/sequelize#2788] opened 2014-12-29 12:05 UTC
Hi,
On my model I have a field like this.
```javascript
    cpf: {
      type          : DataTypes.STRING,
      allowNull     : false,
      unique        : true,
      validate      : {
        isUnique    : function(value, next) {
          Pf.find({
            where: sequelize.and({cpf: value}, ['id <> ?', this.PessoaId]),
            attributes: ['id']
          })
          .done(function(error, user) {
            if (error)
              return next(error);

            if (user)
              return next('CPF já está em uso!');

            next();

          });

        }
      }
    }
```

On 2.0.0-rc3 this works flawlessly and on 2.0.0-rc4 it throws a validation error with this message:
```
sequelize cannot read property 'field' of undefined
```

**Comment by chris-rock** [comment] 2015-01-05 23:33
I confirm this error and it was introduced with rc4

```bash
"Cannot read property 'field' of undefined","name":"TypeError","stack":"TypeError: Cannot read property 'field' of undefined\n    at /app/node_modules/sequelize/lib/instance.js:595:49\n    at Array.forEach (native)\n    at /app/node_modules/sequelize/lib/instance.js:589:28\n    at tryCatch1 (/app/node_modules/sequelize/node_modules/bluebird/js/main/util.js:45:21)\n    at Promise$_callHandler [as _callHandler] (/app/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:660:13)\n    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/app/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:675:18)\n    at Promise$_settlePromiseAt (/app/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:845:14)\n    at Promise._settlePromiseAt (/app/node_modules/sequelize/lib/promise.js:66:18)\n    at Promise$_settlePromises [as _settlePromises] (/app/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:988:14)\n    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/app/node_modules/sequelize/node_modules/bluebird/js/main/async.js:77:12)"
```

**Comment by mickhansen** [comment] 2015-01-06 07:19
@chris-rock Can you show me your model definition and create that triggers this error?

**Comment by mickhansen** [comment] 2015-01-06 07:20
Looking at the code that error should only happen if you passed a set of attributes to `fields` where one of them isn't on the model.

**Comment by chris-rock** [comment] 2015-01-06 09:36
@mickhansen I ensured, that only attributes are set that are part of the model. No ID is specified:

```javascript
var Event = sequelize.define('Event', {
    start: {
      type: DataTypes.DATE
    },
    end: {
      type: DataTypes.DATE
    },
  }, {});
```

I try to update the data via:

```javascript
  return Event
    .findOrCreate({
      defaults: eventData,
      where: {
        Id: id
      }
    }, options).spread(function (evt, created) {
      // only update if it is an existing event
      if (!created) {
        if (eventData.start) evt.start = eventData.start;
        if (eventData.end) evt.end = eventData.end;

        return evt.save(options);
      }
    })
```

I have the same issue if I use `evt.updateAttributes(eventData, options)`. I need to further investigate this topic, but it appears, that rc6 works with Mac+Postgres, but not with Ubuntu Trusty+Postgres. I am not sure why yet.

**Comment by mickhansen** [comment] 2015-01-06 10:50
@chris-rock hmm there shouldn't be any difference between mac and ubuntu. Is there a difference in the PG versions?

**Comment by chris-rock** [comment] 2015-01-06 10:53
@mickhansen thats what I thought, too. Especially since this is a sequelize error. PG is 9.3 in both cases.

**Comment by mickhansen** [comment] 2015-01-06 15:24
@chris-rock there's no validation in your sample code, sure it's related to the original issue?

**Comment by mickhansen** [comment] 2015-01-06 15:25
@GuilhermeReda please post the entire stack of the error that is thrown

**Comment by chris-rock** [comment] 2015-01-06 15:39
@mickhansen the error happens during the call of save() or updateAttributes(). in my original code I catch all promise errors.

**Comment by cusspvz** [comment] 2015-01-06 15:45
Is this bug `PG` specific? Can't reproduce with `mysql` yet.

**Comment by mickhansen** [comment] 2015-01-06 15:46
Is `Id: id` a typo in this issue or do you actually have uppercase 'Id` in your code?

**Comment by GuilhermeReda** [comment] 2015-01-06 15:46
```
TypeError: Cannot read property \'field\' of undefined
    at C:\Users\Guilherme\Documents\node\iapo1\node_modules\sequelize\lib\model.js:1727:47
    at Array.map (native)
    at module.exports.mapFieldNames (C:\Users\Guilherme\Documents\node\iapo1\node_modules\sequelize\lib\model.js:1723:47)
    at Promise.bind.then.then.then.then.QueryInterface.select.Utils._.defaults.type (C:\Users\Guilherme\Documents\node\iapo1\node_modules\sequelize\lib\model.js:720:21)
    at tryCatch1 (C:\Users\Guilherme\Documents\node\iapo1\node_modules\sequelize\node_modules\bluebird\js\main\util.js:45:21)
    at Promise$_callHandler [as _callHandler] (C:\Users\Guilherme\Documents\node\iapo1\node_modules\sequelize\node_modules\bluebird\js\main\promise.js:660:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (C:\Users\Guilherme\Documents\node\iapo1\node_modules\sequelize\node_modules\bluebird\js\main\promise.js:675:18)
    at Promise$_settlePromiseAt (C:\Users\Guilherme\Documents\node\iapo1\node_modules\sequelize\node_modules\bluebird\js\main\promise.js:845:14)
    at Promise._settlePromiseAt (C:\Users\Guilherme\Documents\node\iapo1\node_modules\sequelize\lib\promise.js:66:18)
    at Promise$_settlePromises [as _settlePromises] (C:\Users\Guilherme\Documents\node\iapo1\node_modules\sequelize\node_modules\bluebird\js\main\promise.js:988:14)
```

**Comment by GuilhermeReda** [comment] 2015-01-06 15:49
I think that the error is in the attributes parameter, because if I remove it or put it like this 
```javascript
attributes: [ ['id', 'id'] ]
```
it works;

**Comment by mickhansen** [comment] 2015-01-06 16:02
Looks like it's expected you to use `attributes: [ 'PessoaId ]` instead.

**Comment by mickhansen** [comment] 2015-01-06 16:03
@GuilhermeReda your issue should be fixed by https://github.com/sequelize/sequelize/commit/c61753df6d3079cb9bd6e82f131eff396f3c60d5
Although i disagree with your notion that the primary key should be named like the table, generally you just name it `id`

**Comment by mickhansen** [comment] 2015-01-06 16:05
@chris-rock https://github.com/sequelize/sequelize/commit/3150ef40fdf92a478794c3e7d7f3a0d2a54a1f0a should fix your issue, but it looks like you are passing in a bad set of `fields`

**Comment by GuilhermeReda** [comment] 2015-01-06 16:12
@mickhansen its not my notion that. But if I don't do this sequelize will create a field on my DB with that name.

**Comment by mickhansen** [comment] 2015-01-06 16:16
@GuilhermeReda no those things are unrelated. belongsTo is creating a foreignKey to facilitate the relationship. I think you are misunderstanding something - Can you show your relations and expectations?

**Comment by GuilhermeReda** [comment] 2015-01-06 16:21
Model Pessoa
```javascript
"use strict";
var validacoes = require('../libs/validacoes.js');

module.exports = function(sequelize, DataTypes) {
  var Pessoa = sequelize.define("Pessoa", {
    nome: { 
      type          : DataTypes.STRING,
      allowNull     : false,
      validate      : {
        notEmpty: { 
          msg: 'Nome é obrigatório.'
        } 
      }
    },

    email: { 
      type          : DataTypes.STRING, 
      allowNull     : false ,
      validate      : {
        isEmail: { 
          msg: 'O email é inválido' 
        }
      }
    },

    telefone_principal: { 
      type          : DataTypes.STRING, 
      allowNull     : false ,
      validate      : {
        isPhone: function(value) { 
          validacoes.isPhone(value, 'Telefone Principal');
        }
      }
    },

    telefone_secundario: { 
      type          : DataTypes.STRING,
      validate      : {
        isPhone: function(value) { 
          validacoes.isPhone(value, 'Telefone Secundário');
        }
      }
    },

    cep: { 
      type          : DataTypes.STRING(8), 
      allowNull     : false,
      validate      : { 
        notEmpty: { 
          msg: 'CEP é obrigatório' 
        },
        isInt: {
          msg: 'CEP não é um número válido'
        }
      }
    },
    
    rua: { 
      type          : DataTypes.STRING, 
      allowNull     : false,
      validate      : { 
        notEmpty: { 
          msg: 'Rua é obrigatório' 
        }
      }
    },

    bairro: { 
      type          : DataTypes.STRING, 
      allowNull     : false,
      validate      : { 
        notEmpty: { 
          msg: 'Bairro é obrigatório' 
        }
      }
    },

    numero: { 
      type          : DataTypes.STRING, 
      allowNull     : false,
      validate      : {
        notEmpty: { 
          msg: 'Número da casa é requerido' 
        },
        isInt: {
          msg: 'Número da casa não é um número válido'
        }
      }
    },

    AnexoId: {
      type          : DataTypes.INTEGER,
      field         : 'FotoId',
      validate      : {
        isInt: {
          msg: 'Número da casa não é um número válido'
        }
      }
    },

    complemento: DataTypes.STRING

  }, {
    classMethods: {
      associate: function(models) {
        Pessoa.hasOne(models.Pj);
        Pessoa.belongsTo(models.Cidade, { 
          foreignKey: { 
            allowNull: false 
          } 
        });

      }
    }
  });

  return Pessoa;
};
```
and I changed the PessoaId to id on my Pf model and now is like this
```javascript
"use strict";
var validacoes = require('../libs/validacoes.js');

module.exports = function(sequelize, DataTypes) {
  var Pf = sequelize.define("Pf", {
    id: { 
      type          : DataTypes.INTEGER, 
      primaryKey    : true, 
      references    : 'Pessoas', 
      referencesKey : 'id', 
      field         : 'id'
    },

    cpf: {
      type          : DataTypes.STRING,
      allowNull     : false,
      unique        : true,
      validate      : {
        isCPF       : function(value) {
          validacoes.isCPF(value) 
        },
        isUnique    : function(value, next) {

          Pf.find({
            where: sequelize.and({cpf: value}, ['id <> ?', this.PessoaId]),
            attributes: ['cpf']
          })
          .then(function(pf) {
            if (pf)
              return next('CPF já está em uso!');

            next();

          })
          .catch(function(err) {

            return next(err);

          });

        }
      }
    },

    rg: DataTypes.STRING,

    sexo: { 
      type          : DataTypes.STRING(1),
      validate      : {
        isIn: {
          args: [['m', 'f']],
          msg: "Sexo é Inválido"
        }
      }
    },

    data_nasc: { 
      type          : DataTypes.DATEONLY, 
      validate      : {
        isDateBR    : function(value) {
          validacoes.isDateBR(value, 'Data de Nascimento') 
        }
      } 
    },

    }

  }, {
    classMethods: {
      associate: function(models) {
        
        Pf.belongsTo(models.Pessoa, { 
          foreignKey: { 
            allowNull: false 
          } 
        });
      }
    }
  });

  return Pf;
};
```

and my db table is now like this
```sql

CREATE TABLE "Pfs"
(
  id integer NOT NULL,
  cpf character varying(255) NOT NULL,
  rg character varying(255),
  nome_pai character varying(255),
  nome_mae character varying(255),
  sexo character varying(1),
  data_nasc date,
  "createdAt" timestamp with time zone NOT NULL,
  "updatedAt" timestamp with time zone NOT NULL,
  "PessoaId" integer NOT NULL,
  CONSTRAINT "Pfs_pkey" PRIMARY KEY (id),
  CONSTRAINT "Pfs_FuncaoId_fkey" FOREIGN KEY ("FuncaoId")
      REFERENCES "Funcoes" (id) MATCH SIMPLE
      ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT "Pfs_PessoaId_fkey" FOREIGN KEY ("PessoaId")
      REFERENCES "Pessoas" (id) MATCH SIMPLE
      ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT "Pfs_id_fkey" FOREIGN KEY (id)
      REFERENCES "Pessoas" (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "Pfs_cpf_key" UNIQUE (cpf),
  CONSTRAINT "Pfs_matricula_key" UNIQUE (matricula)
)
```

It created 2 foreign keys.

**Comment by mickhansen** [comment] 2015-01-11 09:01
@GuilhermeReda I have a hard time reasoning about your models when they are in portuguese and this large. Any way you could show your issue in a smaller sample?

**Comment by GuilhermeReda** [comment] 2015-01-21 16:48
resolved on #2971

**Comment by mickhansen** [comment] 2015-01-21 17:16
@GuilhermeReda so we can close this?

**Comment by GuilhermeReda** [comment] 2015-01-21 17:18
@mickhansen I don't see why not.

**Closed** 2015-01-21 17:32 UTC
Labels: bug

**Comment by chris-rock** [comment] 2015-01-21 18:47
@mickhansen and @GuilhermeReda thank you very much for great work. I will try it for my case. If there is still an error, I am going to open a new ticket.
