### ISSUE TITLE
createFunction wrongly inserts BEGIN and END

### ISSUE THREAD

**Issue by flashspys** [sequelize/sequelize#11445] opened 2019-09-17 11:49 UTC
###  Issue Description
The createFunctions adds BEGIN and END between the function code, which leads to a SQL error.

### What are you doing?

```js
await queryInterface.createFunction(
    "timetz_subtype_diff",
    [
      { type: "time with time zone", name: "x", direction: "IN" },
      { type: "time with time zone", name: "y", direction: "IN" }
    ],
    "float8",
    "sql",
    "SELECT EXTRACT(EPOCH FROM (x::time - y::time))",
    [
      "STRICT",
      "IMMUTABLE"
    ]
  );
```

### What do you expect to happen?

The generated SQL should be:

`CREATE FUNCTION timetz_subtype_diff(IN x time with time zone, IN y time with time zone) RETURNS float8 AS $func$ SELECT EXTRACT(EPOCH FROM (x::time - y::time)) $func$ language 'sql' STRICT IMMUTABLE;`

At least, I'm using this manually and it works

### What is actually happening?

The following SQL was generated:

```
CREATE FUNCTION timetz_subtype_diff(IN x time with time zone, IN y time with time zone) RETURNS float8 AS $func$ BEGIN SELECT EXTRACT(EPOCH FROM (x - y)) END; $func$ language 'sql'STRICT IMMUTABLE;
```

BEGIN and END is added to every function, there is no option to disable this behaviour. Postgres says there is an error near Select. If I remove begin and end manually, the query will be successful. (Furthermore, there is a missing space between the language and the additional attributes.)

The question is, if my query can be adapted so it will be accepted by Postgres, or if this is a bug with sequelize and there are some function where BEGIN/END must not be added. Unfortunately, my SQL knowledge stops at functions.

### Environment

- Database: Postgres 11.5
- Sequelize version: sequelize@6.0.0
- Node.js version: v12.4.0
- Operating System: macOS

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [x] I don't know, I was using postgres, with connector library version ? and database version 11.5

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment] 2019-09-17 13:51
Thanks for the report, but this is a duplicate of #11312, so I will close this one.

**Closed by papb** 2019-09-17 13:51 UTC
