### ISSUE TITLE
Return value of sequelize.fn('NOW') not as expected

### ISSUE THREAD

**Issue by dshiells** [sequelize/sequelize#10156] opened 2018-11-13 10:48 UTC
When setting a field to the current timestamp, the return value is not as I'd expect.

Calling:
`goal.update({ completed_at: sequelize.fn('NOW') })`

updates to the current timestamp in the database OK, however my model returns as:
```
{
    "id": 1,
    "user_id": 12,
    "title": "new title 2",
    "description": null,
    "target_date": null,
    "completed_at": {
        "fn": "NOW",
        "args": []
    },
    "created_at": "2018-11-13T10:05:20.000Z",
    "updated_at": "2018-11-13T10:34:30.592Z"
}
```

I'd expect the `completed_at` field to contain the new value - or am I missing something / doing something wrong?

**Comment by sushantdhiman** [comment] 2018-11-13 10:52
Duplicate of https://github.com/sequelize/sequelize/issues/9151

**Closed by sushantdhiman** 2018-11-13 10:52 UTC
