### ISSUE TITLE
Is there a way to exclude an attribute? 

### ISSUE THREAD

**Issue by kasszz** [sequelize/sequelize#4262] opened 2015-08-05 08:17 UTC
Dear Sequelizers,

I'm trying to exclude an attribute from my models.<object>.findAll(). The reason why I really want to exclude the attribute and not include all the other attributes is because the model changes a lot, so the attributes will change all the time.

Hopefully I informed you enough to answer my question.

Casper

**Comment by janmeier** [comment] 2015-08-05 08:18
Not currently :)

Duplicate of https://github.com/sequelize/sequelize/issues/4074

**Closed by janmeier** 2015-08-05 08:18 UTC

**Comment by boiawang** [comment] 2015-08-14 08:14
+1
