### ISSUE TITLE
ignoreDuplicates for postgre 9.5+

### ISSUE THREAD

**Issue by leachiM2k** [sequelize/sequelize#9557] opened 2018-06-19 06:45 UTC
I saw an error using ignoreDuplicates using PostGRE. I'm just wondering, because there is actually an option to ignore duplicate errors.

The situation is described on stackOverflow (https://stackoverflow.com/questions/31455520/bulkcreate-records-using-sequelize-in-nodejs)

Is there a reason, that it is still not implemented in sequelize.js or is it just a question of time or a PR?
In the latter I would be pleased to contribute a PR to the project.

**Comment by sushantdhiman** [comment] 2018-06-19 06:50
We would love to support this feature as MySQL / MSSQL already supports it, I am busy with v5 mostly so a PR will be much appreciated

**Comment by sushantdhiman** [comment] 2018-06-19 06:52
Duplicate of #4132

**Closed by sushantdhiman** 2018-06-19 06:52 UTC
