### ISSUE TITLE
Model.init , attributes.column.defaultValue should be supporting Promise

### ISSUE THREAD

**Issue by sys234** [sequelize/sequelize#11054] opened 2019-06-11 14:47 UTC
**Is your feature request related to a problem? Please describe.**
http://docs.sequelizejs.com/class/lib/model.js~Model.html#static-method-init
I read the docs, making `defaultValue` function reuturn a `Promise`,but it didnot resolve the value,it turned out the `[object Object]`, the sql  error message is `sqlMessage: "Incorrect integer value: '[object Object]' for column 'id' at row 1",`

**Describe the solution you'd like**
`attributes.column.defaultValue` should be supporting async function or return  `Promise` as defaultValue

**Why should this be in Sequelize**
In some case, the defaultValue is asynchronously generating, one of the best ways is to return a `Promise`。

**Describe alternatives you've considered**
In my Case, I did not have a good way to solve `Promise` value as `defaultValue` 

**Usage example**
```javascript
    id: {
      type: BIGINT.UNSIGNED,
      primaryKey: true,
      autoIncrement: false,
      defaultValue() {
        return snowflake();//snowflake() return  `Promise`
      }
    },
```

**Additional context**
none

**Comment by papb** [comment] 2019-07-25 22:58
Duplicate of #11033

**Closed by papb** 2019-07-25 22:58 UTC
Labels: type: feature
