### ISSUE TITLE
Attribute 'onDelete' override issue

### ISSUE THREAD

**Issue by dontry** [sequelize/sequelize#9013] opened 2018-02-07 01:11 UTC
## What are you doing?

I defined both hasMany and belongsTo relationship between User and Quiz model and tried to employ 'CASCADE' strategy for DELETE operation on Quiz model.  

```js
//User Model
 const Model = sequelize.define('User', {
    username: {
      type: Sequelize.STRING,
      unique: true,
      allowNull: false
    },
  /* other attributes */
    {
    freezeTableName: true
  });

  Model.associate = (models) => {
    models.User.hasMany(models.Quiz, {
      foreignKey: 'author',
      as: 'quizzes'
    });
  };
```

```js
//Quiz Model
 const Model = sequelize.define('Quiz', {
    title: {
      type: Sequelize.TEXT,
      allowNull: false
    },
    /* other attributes */
   {
    freezeTableName: true
   }
 );

    models.Quiz.belongsTo(models.User, {
      onDelete: 'CASCADE',
      foreignKey: {
        name: 'author',
        allowNull: false
      }
    });
  };
```

## What do you expect to happen?
I wanted the Quiz Association used **CASCADE** on delete.  

## What is actually happening?
The Quiz still used **SET NULL**  on delete.

__Dialect:__ mysql 
__Dialect version:__ 2.15.0
__Database version:__5.7.20
__Sequelize version:__ 4.27
__Tested with latest release:__ No (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment] 2018-02-09 05:44
Duplicate of https://github.com/sequelize/sequelize/issues/6586

**Closed by sushantdhiman** 2018-02-09 05:44 UTC
