### ISSUE TITLE
model include add order

### ISSUE THREAD

**Issue by leowutao** [sequelize/sequelize#11217] opened 2019-07-24 03:04 UTC

**Comment by papb** [comment] 2019-07-24 15:46
Please add some explanation.

**Comment by leowutao** [comment] 2019-07-25 05:41
Include defined by model does not support sorting.

I want to add the order parameter to the model in include.

Example Code:

```js
User.associate = function(){
   app.model.User.hasMany(app.model.UserLog, {
       foreignKey:'userId',sourceKey:'id', as: 'userLogs'
   });
}
```

```js
this.ctx.model.User.findByPk(id,{
   include: {
       model: this.ctx.model.UserLog.
       as: 'userLogs',
       order: [['updatedAt','Desc']]
   }
});
```

I need to sort 'UserLog' by 'updatedAt' settings.

**Comment by papb** [comment] 2019-07-25 16:29
Actually, I realize now that this is a duplicate of #11222

**Closed by papb** 2019-07-25 16:29 UTC
Labels: question
