### ISSUE TITLE
DATEONLY not return

### ISSUE THREAD

**Issue by moslemezzati** [sequelize/sequelize#5005] opened 2015-12-09 07:48 UTC
I needed to updateAt column return just DATE rather than date and time zone due to I changed uodateAt to DATEONLY, here its code in migration:
```javascript
updatedAt: {
        allowNull: false,
        type: Sequelize.DATEONLY
      }
```
and its code in model:
```javascript
    updatedAt: DataTypes.DATEONLY
```
But when I fetch a record despite of its content that is for example `"2015-12-09"`, it returns `"2015-12-08T20:30:00.000Z"`, how can I gain its read content?

**Comment by janmeier** [comment] 2015-12-09 07:50
Duplicate of https://github.com/sequelize/sequelize/issues/4858

**Closed by janmeier** 2015-12-09 07:50 UTC
