### ISSUE TITLE
[Question] Relation between tables cancel allowNull

### ISSUE THREAD

**Issue by cybernadinou** [sequelize/sequelize#4121] opened 2015-07-15 14:51 UTC
Hi guys,

I don't really know if it's a bug or nop but I got a problem there :
When I define my model in Sequelize like this one : 

    return  sequelize.define("User",{
            id :{
                primaryKey      : true,
                autoIncrement   : true,
                type            : DataTypes.INTEGER,
                allowNull       : false
            },
            lastname :{
                type            : DataTypes.STRING
            },
            firstname :{
                type            : DataTypes.STRING
            },
            idPlatform :{
                field           : 'id_platform',
                type            : DataTypes.INTEGER,
                allowNull       : false,
                references      : 'platform',
                referencesKey    : 'id'
            
            },
        {
            tableName : 'user',
            timestamps: true,
            createdAt: "created_at",
            updatedAt: "updated_at",
            deletedAt: "deleted_at",
            paranoid: true
        });

My SQL request is :

    // WITHOUT RELATION
    CREATE TABLE IF NOT EXISTS `user` (`id` INTEGER NOT NULL auto_increment , `lastname` VARCHAR(255), `firstname` VARCHAR(255), `id_platform` INTEGER NOT NULL, `created_at` DATETIME NOT NULL, `updated_at` DATETIME NOT NULL, `deleted_at` DATETIME, 
    PRIMARY KEY (`id`), FOREIGN KEY (`id_platform`) REFERENCES `platform` (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_general_ci;
That's perfect :D but now if I want to add some stuffs like this one :

    // Platform
    m.platform.hasMany(m.user,              { as : 'Users'             , foreignKey : 'id_platform' });
    //User
    m.user.belongsTo(m.platform,            { as : 'Platform'          , foreignKey : 'id_platform' });

My new request SQL is :

    // WITH RELATION
    CREATE TABLE IF NOT EXISTS `user` (`id` INTEGER NOT NULL auto_increment , `lastname` VARCHAR(255), `firstname` VARCHAR(255), `id_platform` INTEGER, `created_at` DATETIME NOT NULL, `updated_at` DATETIME NOT NULL, `deleted_at` DATETIME, 
    PRIMARY KEY (`id`), FOREIGN KEY (`id_platform`) REFERENCES `platform` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_general_ci;

So there my idPlatform can be null and me I don't want it as null... So does I miss something and how can I set my id_platform as NOT NULL WITH my relation belongsTo and hasMany ?

Thanks in advance for your help

**Comment by janmeier** [comment] 2015-07-15 15:04
Please format your code properly using [Github flavored markdown](https://help.github.com/articles/github-flavored-markdown/) 

The problem is because sequelize is not able to properly identify the fact that you already have a column definition in your model. When you specify `foreignKey : 'id_platform'` sequelize thinks that both the attribute in the model and in the table should be called  `id_platform` - this clashes with yuor model def. which  says that the attribute should be `idPlatform` in the model and `id_platform` in the db. The definition from the association is overwriting whats in yuor model.

Associations don't have perfect support for the `field` property.

You have two options:

```js
// Use the attribute you have already defined in the model:
User.belongsTo(Platform, { foreignKey : User.rawAttributes.idPlatform });

// Remove the attribute definiton from the model and pass it as foreignKey instead
User.belongsTo(Platform, { foreignKey : {
  field : 'id_platform',
  name: 'idPlatform',
  allowNull : false,
}});
```
Notice that I've removed the references parts and the type, since they will automatically be added by sequelize. This also applies if you go with `User.rawAttributes.idPlatform` - sequelize adds these automatically.

One last thing - you probably need to set `onDelete: 'CASCADE'` or something similar, since the default is `SET NULL` which doesnt play well with not allowing nulls

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).

**Closed by janmeier** 2015-07-15 15:04 UTC

**Comment by cybernadinou** [comment] 2015-07-15 15:10
Thank you very much for your explanation and next time I'll use StackOverflow.
Thanks
