### ISSUE TITLE
targetKey for hasMany and hasOne

### ISSUE THREAD

**Issue by rm-richard** [sequelize/sequelize#4258] opened 2015-08-04 19:37 UTC
I have two legacy tables in a 1:m association:
**Property**(id, statistical_id, name, ...), **VisitorStats**(id, statistical_id, total, ...)

The following works:

`VisitorStats.belongsTo(Property, { foreignKey: 'statistical_id', targetKey: 'statistical_id'} );`

Then, in the controller, I can query for VisitorStats and eager-load the Property for it.

However, I want to query the Property table and include the VisitorStats model. For this, I would have to do a hasMany association, like this:

`Property.hasMany(VisitorStats, { foreignKey: 'statistical_id' });`

**hasMany's doesn't support the targetKey parameter option, and automatically joins VisitorStats.statistical_id on Property.id when I query.** I expected the targetKey property to work like at a belongsTo association.

Is it possible to change the target key using hasMany? If not, how should I represent this 1:m association?

**Comment by janmeier** [comment] 2015-08-05 18:28
`targetKey` is not yet supported for hasMany

**Comment by treejanitor** [comment] 2015-08-29 12:31
This seems like a very useful modeling feature, especially for legacy databases.

**Comment by sijmenvos** [comment] 2015-08-31 10:12
I agree +1

**Comment by treejanitor** [comment] 2015-08-31 12:35
I ended up having to use a raw SQL query, otherwise I would have had to invert the true object model to make the query work.  So, it's possible to get the job done, but my premise is that an ORM ideally models logically the object tree as it should exist.

**Comment by PyroSA** [comment] 2015-09-07 14:08
As per #4269, it is not working for HasOne/BelongsTo relationships either.
The ForeignKey works, but it still uses .id for the include statement.

**Comment by mickhansen** [comment] 2015-09-07 14:10
@PyroSA BelongsTo is the only one it works for, are you saying it no longer works, or are you saying it doesn't work from the HasOne side (which it never has)?

**Comment by PyroSA** [comment] 2015-09-07 15:10
It does not work for the BelongsTo in our case either.

Not my project, but off the top of my head it would look like:
```Model: Ta:
columns(id, guid, stuff)
associate: Ta.hasOne Tb, foreignKey: 'guid'```

```Model: Tb:
columns: id, guid, json
associate: Tb.belongsTo Ta, (foreignKey: 'guid', targetKey: 'guid')```

Not sure of the order (Ta/Tb) but:
Tb.findAll with include [Ta] then tries to join on Ta.id instead of Tb.guid

I can confirm the exact sequence if it's unclear.
guids are stored as strings in this case.

**Comment by PyroSA** [comment] 2015-09-07 15:17
@mickhansen - Tried to clarify above

**Comment by mickhansen** [comment] 2015-09-07 15:35
@PyroSA We have a test for that feature, so it should work - Please open a seperate issue with a reproduceable case since this issue deals with expanding the feature.

**Comment by PyroSA** [comment] 2015-09-07 22:27
@mickhansen - I brought it up because #4269 was closed and referred to this feature.  If it's considered a separate issue, can't that issue be re-opened?

If not I can create a new issue.

**Comment by guigrpa** [comment] 2015-09-08 07:08
I have opened a new issue, as @mickhansen suggested: #4455

**Comment by mickhansen** [comment] 2015-09-08 07:30
@PyroSA that issue is about HasOne, not Belongsto :)

**Comment by colegleason** [comment] 2015-09-16 19:18
Hey, I also have legacy tables and would love this feature. Is there any good workaround in the meantime?

**Comment by janmeier** [comment] 2015-09-16 19:20
@colegleason No workaround unfortunately

**Comment by rm-richard** [comment] 2015-09-16 19:43
The cleanest solution I found was to create a dummy table, holding the commonly referenced IDs. Following up on the original example:

**Property**(id, statistical_id, name, ...), **VisitorStats**(id, statistical_id, total, ...)
Add the following table: **Stats**(statistical_id)

Set the associations:
```
Property.belongsTo(Stats, { foreignKey: 'statistical_id', targetKey: 'statistical_id'} );
Stats.hasMany(Property, { foreignKey: 'statistical_id'} );
Stats.hasMany(VisitorStats, { foreignKey: 'statistical_id'} );
```
After this, you can simply include either model in a query.
If you think about it, the legacy database model is flawed, since the 'statistical_id' points to a common, missing entity from both tables, they were never meant to reference each other. What I ended up doing was creating the table as I described, inserting all the 'statistical_id'-s into the new table and writing triggers to keep it updated with the new values from the legacy app.

**Comment by renewooller** [comment] 2016-02-15 21:44
Is this issue on the roadmap, or is it 'does not work as intended' ?

I think it would be useful, and would also make the package more consistent.

**Comment by mickhansen** [comment] 2016-02-16 08:06
@renewooller It's an open feature request, however not specifically on any roadmap.

**Comment by renewooller** [comment] 2016-02-22 07:20
ok great I will find it very useful as I name all my primary keys as '<table_name>_id' with foreign keys having the same column name. I prefer this scheme to the default 'id' as it is very easy to dump specific relational data from multiple tables using the --where option from mysql dump. I'm not sure how many other people are in a similar situation.

**Comment by moxious** [comment] 2016-03-02 15:02
I hate to "me too" on this issue/feature, but uh....me too?    Doing some research and looking back through this thread, it appears a similar issue was opened and fixed on BelongsTo (https://github.com/sequelize/sequelize/issues/4455) - the actual commit looks dead simple.   Is this a much more complex situation for hasMany or could it be done similarly and then a pull request created?

**Comment by mickhansen** [comment] 2016-03-02 15:11
@moxious It's not overly complicated, just takes some work making sure most cases are covered.

**Comment by arenddeboer** [comment] 2016-03-08 11:20
I would vote this up if there was a button, for now +1. 
Currently stuck looking for a solution to map some legacy federated mysql tables into the sequelize mix.

**Comment by matthewhardern** [comment] 2016-04-29 13:17
I have a fix for this, but not sure whether i have covered all bases. I could submit a pull request, but probs best to check out fix first

**Comment by janmeier** [comment] 2016-04-29 13:18
@matthewhardern Go ahead, its easiest for us to review in PR form ;)

**Comment by matthewhardern** [comment] 2016-04-29 14:33
have submitted, but its got issues that will need solving by the looks of it

**Comment by truginis** [comment] 2016-06-09 20:07
is this part of sequelize now?

**Comment by Paxa** [comment] 2016-09-30 06:26
@truginis Still pending https://github.com/sequelize/sequelize/issues/4258

**Comment by andrewholsted** [comment] 2016-10-28 22:00
I came across this today trying to refactor our codebase to exclusively use sequalize. It's a deal breaker for us that I can't declare a targetKey for a hasOne relation. As @treejanitor mentioned, I would have to invert our relations to make it work as stands. Is there any open pull request or branch in progress I could take a look at?

**Comment by felixfbecker** [comment] 2016-10-28 23:06
@andrewholsted That PR was approved but it doesn't have any tests and has been stale for a while. All you need to do is pick up his work, rebase and add some tests :)

**Comment by justinpincar** [comment] 2016-11-28 00:21
Over a year later and still no fix? 😞 

I worked around this by making a second query and manually joining json representations.

**Comment by LoneWolfPR** [comment] 2017-01-23 19:34
Is there any chance of this getting addressed anytime soon. We have a project using Heroku Connect with Salesforce. Salesforce tables join using the 'sfid' field which is not an integer primary key. I really need to be able specify a 1 to many relationship with hasMany setting the targetKey to this field instead of the primary key. Just seems strange to me that this has been sitting out so long.

**Comment by janmeier** [comment] 2017-01-23 20:02
@LoneWolfPR it's been sitting so long because no one has taken the time to finish the code and tests. 

As Felix mentions, the code is actually there, some one just needs to pick it up and add some tests

**Comment by LoneWolfPR** [comment] 2017-01-23 21:07
@janmeier Thanks, I guess I missed that. That said this PR seems to address all the issues. Is it possible to just get the conflict in the changelog fixed so this can get merged? https://github.com/sequelize/sequelize/pull/6652

**Closed** 2017-01-24 08:10 UTC
Labels: feature

**Comment by joe-angell** [comment] 2017-05-11 01:15
How about `sourceKey` for `hasOne`?

**Comment by mlyticsAdamGe** [comment] 2018-02-02 03:40
To describe the relationship
belongsTo --->use  targetKey to set the  foreigner key from
hasMany   --->use sourceKey to set the foreigner key from

**Comment by philipimperato** [comment] 2018-04-03 20:08
Is Sequelize still being actively developed? There a bunch of issues that have are stale.

**Comment by eggerand13** [comment] 2018-11-28 07:30
Maybe this information should be added to the legacy database handling in the documentation (http://docs.sequelizejs.com/manual/advanced/legacy.html)

**Comment by williamkwao** [comment] 2019-05-21 18:17
```js
Country.hasMany(City, {foreignKey: 'countryCode', sourceKey: 'isoCode'});
City.belongsTo(Country, {foreignKey: 'countryCode', targetKey: 'isoCode'});
```
This example from the pr worked for me. I wish the documentation would be updated correctly. It took a while to figure it out.

**Comment by piotrgulbis** [comment] 2019-06-29 19:17
> ```js
> Country.hasMany(City, {foreignKey: 'countryCode', sourceKey: 'isoCode'});
> City.belongsTo(Country, {foreignKey: 'countryCode', targetKey: 'isoCode'});
> ```
> 
> This example from the pr worked for me. I wish the documentation would be updated correctly. It took a while to figure it out.

This fixed the issue for me as well. Would be very helpful to update the docs!

**Comment by dilipsuthar97** [comment] 2021-04-13 06:09
> ```js
> Country.hasMany(City, {foreignKey: 'countryCode', sourceKey: 'isoCode'});
> City.belongsTo(Country, {foreignKey: 'countryCode', targetKey: 'isoCode'});
> ```
> 
> This example from the pr worked for me. I wish the documentation would be updated correctly. It took a while to figure it out.

Thanks @williamkwao, You saved my day

**Comment by cpatti97100** [comment] 2021-04-13 08:59
please someone who tried this out update the docs :) that would be really helpful for the future!
