### ISSUE TITLE
Cannot extend ABSTRACT data type to create custom data types

### ISSUE THREAD

**Issue by dursk** [sequelize/sequelize#11472] opened 2019-09-24 17:58 UTC
## Issue Description

```javascript
class MyNewDataType extends DataTypes.ABSTRACT { ... }
```
This does not work as expected, since when the data types are exported they are exported as `Proxy` objects. The overrides are not taking on the subclass.

### What are you doing?

```javascript
class MyNewDataType extends DataTypes.ABSTRACT {
    toSql() {
        return 'foo';
    }
}

(new MyNewDataType()).toSql();
```

### What do you expect to happen?

`"foo"` should be returned

### What is actually happening?

`"ABSTRACT"` was returned
```
ABSTRACT
```

- Sequelize version: 5.8.6
- Node.js version: 10.15.3 
### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment] 2019-09-27 05:35
Duplicate of https://github.com/sequelize/sequelize/issues/11177

**Closed by sushantdhiman** 2019-09-27 05:35 UTC
