### ISSUE TITLE
raw query replacements: ANY(?::text[]) doesn't parse JS array into DB array properly

### ISSUE THREAD

**Issue by mariusa** [sequelize/sequelize#14685] opened 2022-06-26 12:17 UTC
## Issue Creation Checklist

- [x] I understand that my issue will be automatically closed if I don't fill in the requested information
- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

### Reproducible Example
```
CREATE TABLE product (
    id text NOT NULL PRIMARY KEY,
    vendor TEXT
);
INSERT INTO product (id, vendor) values ('123', 'Nike');

const products = await sequelize.query("SELECT * FROM product WHERE vendor=ANY(?::text[])", 
    {
    replacements: [ ['IBM', 'Apple'] ]
    }
  );

results in
SELECT * FROM product WHERE vendor=ANY('IBM', 'Apple'::text[])

instead of

SELECT * FROM product WHERE vendor=ANY('{"IBM", "Apple"}'::text[])

```

Here is the link to the SSCCE for this issue:
https://github.com/mariusa/sequelize-sscce-any/blob/main/src/sscce-sequelize-6.ts

### What do you expect to happen?

```
SELECT * FROM product WHERE vendor=ANY('{"IBM", "Apple"}'::text[])
```
### What is actually happening?
```
SELECT * FROM product WHERE vendor=ANY('IBM', 'Apple'::text[])
```

### Environment

- Sequelize version: sequelize@6.21.1
- Node.js version: v16.14.0
- Database & Version: 'PostgreSQL 13'
- Connector library & Version: pg@8.7.3

## Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I will need guidance.
- [ ] No, I don't have the time, but my company or I are [supporting Sequelize through donations on OpenCollective](https://opencollective.com/sequelize).
- [x] No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in resolving my issue.

---

*Indicate your interest in the resolution of this issue by adding the 👍 reaction. Comments such as "+1" will be removed.*

**Comment by mariusa** [comment] 2022-06-26 12:27
`pg` used directly works fine with the same query & params.

**Comment by ephys** [comment] 2022-06-26 14:14
This is the current intended behavior.
I'll close as duplicate of this feature request that would solve this: https://github.com/sequelize/sequelize/issues/14410

Until that feature request has been implemented, you can work around the issue by using `SELECT * FROM product WHERE vendor = ANY(ARRAY[?]::text[])`

**Closed by ephys** 2022-06-26 14:14 UTC
