### ISSUE TITLE
sequelize collection methods

### ISSUE THREAD

**Issue by PavelPolyakov** [sequelize/sequelize#3244] opened 2015-03-01 13:33 UTC
Hi,

Assuming I have the next relations:
~~~javascript
models.ClientData.belongsToMany(models.Location, {
		through    : 'clientdata_location',
		foreignKey : 'clientdata_id',
		otherKey   : 'location_id'
	});
models.Location.belongsToMany(models.ClientData, {
		through    : 'clientdata_location',
		foreignKey : 'location_id',
		otherKey   : 'clientdata_id'
	});
~~~

Then I do the next:
~~~javascript
 user.getClientDatum({include:[{model:server.methods.getModel('Location')},
                    server.methods.getModel('PhoneNumber')]}).then(function(clientdata){
                        console.log(clientdata.toJSON());
                        process.exit();
}
~~~

Under the clientdata.locations I have the next:
~~~javascript
locations: 
   [ { id: '2299003',
       city: null,
       country: 'PL',
       latitude: 53.5474829,
       longitude: 9.9860394,
       number: null,
       plz: null,
       street: null,
       locationtype: 'CURRENT',
       owner_id: null,
       clientdata_location: [Object] },
     { id: '2299002',
       city: 'Ożarów Mazowiecki',
       country: 'PL',
       latitude: null,
       longitude: null,
       number: '12',
       plz: '05-850',
       street: 'asda',
       locationtype: 'HOME',
       owner_id: null,
       clientdata_location: [Object] } ]
~~~

I have the next question - if there a place where I can define some "collection methods", which I would be able to call somehow like this:
~~~javascript
/* assuming that in the get function I would filter the internal array of the records and return the one with the locationtype=HOME */
clientdata.locations.get('HOME').number 
~~~

I know that we can define the ```classMethods``` and ```instanceMethods```, but are we able to attach something like ```collectionMethods``` ? Or there is some more elegant way to solve this?

Regards,

**Comment by janmeier** [comment] 2015-03-01 21:15
Sequelize does not return collections, it returns plain arrays. Starting to modify `Array.prototype` would be a very bad idea.

If you alway load locations as part of clientdata you could add the get method to clientdata to filter its location array

**Comment by janmeier** [comment] 2015-03-24 14:42
Not a bug or feature request, closing

**Closed by janmeier** 2015-03-24 14:42 UTC

**Comment by PavelPolyakov** [comment] 2015-03-24 15:39
Well, 

I think it could be considered as feature-request, and, like - if it would be possible to state the 'CollectionType' class, and all the collections which are returned by the sequelize would be wrapped in the collection object, so we're able to do the custom methods over the collection - it could be great.

But I suppose the feature-requests like that are already somewhere in the git-issues.

Thanks for the library!

**Comment by janmeier** [comment] 2015-03-24 16:46
@PavelPolyakov as mentioned, sequelize returns plain arrays, not collections and that is not likely to change
