### ISSUE TITLE
Read UnCommited Data

### ISSUE THREAD

**Issue by zeeshanjan82** [sequelize/sequelize#5738] opened 2016-04-13 11:01 UTC
I would like to know if it is possible in Sequelize to read Un commited data. Let me explain: I am using node.js Promise to create a transaction in sequelize and return the transaction object back and in the success part of the promise I am trying to read the database for the record I have inserted in the previous method inside a transaction, however I am getting null even though I am able to add the record in the first method. I understand that I am not commiting the transaction yet but how can I read the database for uncommited data?

**Comment by janmeier** [comment] 2016-04-13 11:09
You can set the isolation level when starting a transaction http://docs.sequelizejs.com/en/latest/docs/transactions/#isolation-levels

If you have further questions, please provide a [SSCCE](HTTP://SSCCE.ORG/)

**Comment by zeeshanjan82** [comment] 2016-04-13 12:13
Actually I have set the isolation level when creating the transaction following is the code for creating the transaction:

````js
      dbConn.sequelize.transaction({isolationLevel: Sequelize.Transaction.READ_UNCOMMITTED || "READ UNCOMMITTED"}).then(( t ) => {
         resolve(t);
      }).catch((err) => {
        reject(new Error(err));
      });

`````

**Comment by mickhansen** [comment] 2016-04-13 12:31
Any reason you can't simply do the find on the transaction?

**Comment by zeeshanjan82** [comment] 2016-04-13 13:09
Actually @mickhansen I am trying to break my dataaccess class into multiple smaller functions and each function can insert or update one entity. Example An Order has multiple Products and a single Customer. I would like to create a function to add new order only and then use that OrderId to pass it to a next function for adding Products for that order and then pass it to next function to add customer for that order. Everything is promise based and I am planning to create a sequelize transaction at start and use the same transaction object in all the 3 methods.

**Comment by mickhansen** [comment] 2016-04-13 13:11
What's the problem then? Just use the transaction in all three methods :)
Relying on being able to read uncommitted sounds like a bad idea generally.

**Comment by zeeshanjan82** [comment] 2016-04-13 13:16
thanks @mickhansen actually the problem comes when I first create the trasaction and then pass it to addOrder function which returns OrderId, addOrder function makes use of the transaction object I passed to it. My issue comes when in addProducts I need to search for the order I have added inside addOrder function using the transaction object and using the orderId returnined from addOrder function, but I am getting the order object null in addProducts fucntion which I use fineOne sequelize statement.

**Comment by mickhansen** [comment] 2016-04-13 13:17
@zeeshanjan82 That's odd, a find should simply work if you pass it the transaction option, can you show some code?

Your original code `dbConn.order.findOne({where: {OrderId: orderId}}).then((order) => {})` does not use the transaction option.

**Comment by zeeshanjan82** [comment] 2016-04-13 13:18
@mickhansen I even tried with this statement: 

````js
     dbConn.order.findOne({where: {OrderId: orderId}}, {transaction: t}).then((order) => {})

``````

**Comment by mickhansen** [comment] 2016-04-13 13:22
findOne only takes ONE option argument, not two, so that's your issue.

**Comment by zeeshanjan82** [comment] 2016-04-13 13:23
but then how can I get the order by using orderId. is there any way I can do that or do I have to specify the transaction object in findOne.

**Comment by mickhansen** [comment] 2016-04-13 13:24
You use the transaction.
I'm sorry i'm not sure i understand the question at all anymore, execute your calls in a transaction and everything should work - Perhaps start by verifying you're using the transaction everywhere by looking at logs.

Closing issue.

**Closed by mickhansen** 2016-04-13 13:24 UTC

**Comment by zeeshanjan82** [comment] 2016-04-13 13:26
well I am not sure why you guys are in a hurry to close the issue without even understanding it. This is really strange. Well thanks for really wasting my time.

**Comment by mickhansen** [comment] 2016-04-13 13:28
I could say the same to you, you fail to adequately explain what the issue is at all, wasting our time in the process.

You have made no effort to fix the syntax errors i pointed out, you have done no basic debugging.
Even though we close issues we still answer further inquiries, but unless the issue is about a bug, feature or some design discussion we generally close them, usage questions are not for github generally.

**Comment by zeeshanjan82** [comment] 2016-04-13 13:49
@mickhansen if someone is using the package in production which you are the owner and contributor of then I think you have more responsibility than just closing the issue. What is the need to close the issue, you could ask me and I can provide more understanding. teams are using your package in production and when they get stuck they approach to you, if you are not providing any assistance then what is the use of running github issues section for your package.

**Comment by mickhansen** [comment] 2016-04-13 13:53
GitHub issues are not for general questions, we don't have the resources to manage all possible questions, we suggest using community channels like Slack and SO for that.

I've suggest multiple things to you but it you have responded with feedback on any of them.
GitHub issues is for features and bugs, like it says in the issue template that you apparently simply deleted when posting this issue.

**Comment by zeeshanjan82** [comment] 2016-04-13 13:59
Agreed Github Issues is for bugs and features, how would you come to know if I have mentioned about bugs or features without even understanding my issue first and if my issue is not understood does it mean it needs to be closed, anyway I really appreciate your efforts and also do agree that managing a huge repo needs resources. thanks for really helping me out just wanted to provide you my feedback @mickhansen

**Comment by mickhansen** [comment] 2016-04-13 14:03
You completely ignored the issue template for bugs, and there's nothing to suggest that this is a feature request.

We provide modification of isolation levels, whether or not you can actually read from outside of a transaction is at that point out of the hands of any ORM.

I made a few attempts to understand your issue, as evident from me replying three times. You made no attempt to apply my fixes. Have a good day, locking this issue. You're welcome to open a new issue if you find a specific bug.
