### ISSUE TITLE
Updating JSON data-type object with dot notation doesn't update model._changed

### ISSUE THREAD

**Issue by justinkalland** [sequelize/sequelize#10053] opened 2018-10-21 00:10 UTC
## What are you doing?
```js
const Sequelize = require('sequelize')

const sequelize = new Sequelize({
  dialect: 'sqlite',
  storage: ':memory:'
})

const Album = sequelize.define('User', {
  name: Sequelize.TEXT,
  attributes: Sequelize.JSON
})

Album.sync().then(() => {
  return Album.create({
    name: 'Slow Dance Showdown',
    attributes: {
      artist: 'john smith',
      genre: 'rock'
    }
  })
}).then(album => {
  album.attributes.genre = 'classical'
  console.log('Has the data changed: ' + album.changed()) // says data hasn't changed

  album.set('attributes.genre', 'jazz')
  console.log('Has the data changed: ' + album.changed()) // works correct
})
```

## What do you expect to happen?
I expect that `album.attributes.genre = 'classical' ` should set `album._changed` and that then calling `album.save()` should cause a database update.

## What is actually happening?
It is updating the `album.dataValues` and `album._previousDataValues` but it is not adding the field to `album._changed`. So the model doesn't recognize the change and methods such as `album.save()` do not work.  

__Dialect:__ mysql / postgres / sqlite
__Dialect version:__ various
__Database version:__ various
__Sequelize version:__ master branch
__Tested with latest release:__ Yes

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment] 2018-10-21 05:49
Yes, I think it is related to equity of object which is not changed hence never updated to `_changed`.

Duplicate of https://github.com/sequelize/sequelize/issues/8916

**Closed by sushantdhiman** 2018-10-21 05:49 UTC

**Comment by justinkalland** [comment] 2018-10-21 12:10
Ahh yes I though it was updating `_previousDataValues` but it seems that with the above example that
```js
console.log(album._previousDataValues.attributes === album.dataValues.attributes)
```
is also true. Interesting.
