### ISSUE TITLE
Accessing instance method returns undefined is not a function

### ISSUE THREAD

**Issue by ivanmanolov90** [sequelize/sequelize#4190] opened 2015-07-26 01:11 UTC
Hello,
I am trying to access an instance method after querying the database, but the instance method comes back as undefined.

```javascript
//user model
module.exports = function(sequelize, DataTypes) {
  var User = sequelize.define('User', {
    username: DataTypes.STRING,
    password: DataTypes.STRING,
    email: DataTypes.STRING
  }, {
    hooks: {
      beforeCreate: hashPassword,
      beforeUpdate: hashPassword
    }
  }, {
    classMethods: {
      associate: function(models) {
        User.hasMany(models.PasswordReset);
      }
    }
  }, {
    instanceMethods: {
      comparePassword: function(candidatePassword, cb) {
        console.log("COMPARING");
        var user = this;
        bcrypt.compare(candidatePassword, user.get('password'), function(err, isMatch) {
          if (err) return cb(err);
          cb(null, isMatch);
        });
      },
      tryMe: function () {
        console.log('INSTANCE METHOD WORKS');
      }
    }
  });

  return User;
};
```

And i try execute the instance method in my passport implementation as: 
```javascript 
  passport.use(new LocalStrategy(function(username, password, done) {
    User.findOne({
        where: {
          username: username
        }
      })
      .then(function(user) {
        if (!user) return done(null, false, {
          message: 'Incorrect username'
        });
        user.comparePassword(password, function(err, isMatch) {
          if (isMatch) {
            return done(null, user);
          } else {
            return done(null, false, {
              message: 'Incorrect password.'
            });
          }
        });

      })
      .catch(function(err) {
        return done(err);
      });
  }));

``` 
The user is successfully returned from the database but  user.comparePassword() returns 'TypeError: undefined is not a function'. What am i doing wrong?

**Comment by janmeier** [comment] 2015-07-26 09:25
Duplicate of https://github.com/sequelize/sequelize/issues/4170 (you are passing the instance and class methods in two separate objects, they should be in the same)

**Closed by janmeier** 2015-07-26 09:25 UTC

**Comment by ivanmanolov90** [comment] 2015-07-26 09:37
thank. i forgot to save my updated version of the question. can you please help me as to why beforeUpdate isn't being called but beforeCreate is?

**Comment by janmeier** [comment] 2015-07-26 09:40
You are calling bulk update (which updates several), so you should attach a `beforeBulkCreate` instead - or passing `individualHooks: true` in the options object http://docs.sequelizejs.com/en/latest/api/model/#updatevalues-options-promisearrayaffectedcount-affectedrows

**Comment by ivanmanolov90** [comment] 2015-07-26 16:54
AHAAA. thank you for the help! :smiley:

**Comment by DoctypeRosenthal** [comment] 2016-08-15 19:10
Hello.

I have a question: is it possible to activate the `individualHooks`-option for **all** update, create, destroy etc. methods? The only way I found was something like:
```javascript
db.models.customers.update(args, { where: {id: args.id}, individualHooks: true })
```
Is there any other way than passing that option at runtime?

**Comment by janmeier** [comment] 2016-08-16 08:02
@DoctypeRosenthal You can add a `beforeBulkUpdate` hook which modifies the options, setting `individualHooks: true`

**Comment by DoctypeRosenthal** [comment] 2016-08-16 15:30
Thanks for your quick reply!
Unfortunately, the documentation isn't clear about what gets passed to `beforeBulkUpdate` (http://sequelize.readthedocs.io/en/v3/api/hooks/#beforebulkupdate).
I thought it would give me an array of the affected records (since `beforeUpdate` gives you the affected record as its first argument) but that was not the case. So I couldn't perform any further actions with these records. It seems I have to configure `{ individualHooks: true }` every time I call a create, update, delete, restore action :(

**Comment by janmeier** [comment] 2016-08-16 15:33
`beforeBulkUpdate` gets options -  Which means you can set `options.individualHooks = true`, and then `beforeUpdate` will be called for each row.

`beforeBulkUpdate` does not have access to the rows, since we might not even select the rows (when `individualHooks` is false)

**Comment by DoctypeRosenthal** [comment] 2016-08-16 16:53
Thanks!

I found the order in which all hooks are called:

> ```javascript
(1)
  beforeBulkCreate(instances, options, fn)
  beforeBulkDestroy(options, fn)
  beforeBulkUpdate(options, fn)
(2)
  beforeValidate(instance, options, fn)
(-)
  validate
(3)
  afterValidate(instance, options, fn)
  - or -
  validationFailed(instance, options, error, fn)
(4)
  beforeCreate(instance, options, fn)
  beforeDestroy(instance, options, fn)
  beforeUpdate(instance, options, fn)
(-)
  create
  destroy
  update
(5)
  afterCreate(instance, options, fn)
  afterDestroy(instance, options, fn)
  afterUpdate(instance, options, fn)
(6)
  afterBulkCreate(instances, options, fn)
  afterBulkDestroy(options, fn)
  afterBulkUpdate(options, fn)
```
http://sequelize.readthedocs.io/en/v3/docs/hooks/

Can I set the `individualHooks = true` for the `beforeUpdate` *and* `afterUpdate` operations within `beforeBulkUpdate`?

**Comment by janmeier** [comment] 2016-08-16 18:15
Yes, the option applies to both

**Comment by DoctypeRosenthal** [comment] 2016-08-16 18:20
Thx man!

**Comment by L3V147H4N** [comment] 2016-09-12 18:40
Has this change? my beforeUpdate hook is not running

```
'use strict';

const Moment = require('moment');
var Sequelize = require('sequelize');
var Connection = require('../database/Connection');
var bcrypt = require('bcrypt');

var sequelize = Connection.getInstance();

var User = sequelize.define('User', {
  username: { type: Sequelize.STRING, unique: true },
  name: Sequelize.STRING,
  password: Sequelize.STRING,
  token: Sequelize.STRING,
  profile: Sequelize.STRING(4000)
}, {
  timestamps: true,
  tableName: 'User',
  hooks: {
    beforeCreate: (user, options, cb) => {
      bcrypt.hash(user.password, 10, (err, hash) => {
        user.password = hash;

        return cb(null, options);
      });
    },
    beforeUpdate: (user, options, cb) => {
      bcrypt.hash(user.password, 10, (err, hash) => {
        user.password = hash;

        return cb(null, options);
      });
    }
  },
  instanceMethods: {
    comparePassword: function compare (candidatePassword, cb) {
      bcrypt.compare(candidatePassword, this.getDataValue('password'), (err, isMatch) => {
        if (err) {
          cb(err);
        } else {
          cb(null, isMatch);
        }
      });
    }
  },
  getterMethods: {
    createdAt: function getCreadtedAt () {
      return Moment(this.getDataValue('createdAt')).format('DD/MM/YYYY HH:mm:ss');
    }
  }
});

module.exports = User;
```

**Comment by L3V147H4N** [comment] 2016-09-12 19:02
If I run something like:

```javascript
return new Promise((resolve, reject) => {
    sequelize.models.User.update({
      name: 'ADMIN'
    }, {
      individualHooks: true,
      where: {
        id: 1
      }
    })
      .then(resolve)
      .catch(reject);
  });
```

Then the beforeUpdate hook runs and hashes the password, but NOT on the password update itself

**Comment by L3V147H4N** [comment] 2016-09-12 19:04
NEVERMIND! for some reason it's working know ..... nargles

**Comment by vohoangnhut** [comment] 2017-03-21 04:27
```
const updateUserByEmail = (usrNm,usrEml,usrPsw) => {
    return User.update({
                    usrNm: usrNm,
                    usrPsw: usrPsw
                }, {
                    where: {usrEml: usrEml},
                    individualHooks: true
                }
    );
}
```

Can you help my case ?
It came to beforeUpdate hook but
that update code just updated usrPsw only. it's ignore another field. I dont know why.

**Comment by L3V147H4N** [comment] 2017-03-21 22:13
My problem was that the Hook only affects individual Instances for ex:

`
let myUser = User.findById(1); 
myUser.update() // or save
`

when updating from the model, for ex:
`
User.update({}, { where: // })
`

the hook doesnt run because it's an individual hook, you need to set the option *individualHooks*

```
User.update({
    password: 'blabla123'
  }, {
    individualHooks: true,
    where: {
      username: 'admin'
    }
  });
```

**Comment by jedwards1211** [comment] 2017-09-14 17:12
@janmeier when the `where` clause has a single value for the primary key, couldn't sequelize automatically treat that as an individual update instead of a bulk update?

**Comment by AdityaAnand1** [comment] 2017-10-14 14:36
@jedwards1211 Oh my god yes. Why is so much of sequeilize so un-intuitive? And why does documentation not tell us about any such quirks?

I have to go treasure hunting for clues on Google/SO/Github to do anything with this library.

**Comment by DoctypeRosenthal** [comment] 2017-10-14 19:31
@AdityaAnand1I agree! Sequelize is relatively unintuitive in comparison. Wish there was an orm like SQLAlchemy for node...

**Comment by anton-piliugin** [comment] 2019-02-15 12:17
This "individualHooks: true" defenitely should be in a documentation with simple example, i wasted about an hour to find the problem

**Comment by MarianyFerreira** [comment] 2020-02-28 21:21
user.model.js:

```
    'use strict';
    
    const bcrypt = require('bcryptjs');
    
    const hashCostFactor = 1;
    
    const hashPassword = async (user) => {
      if (user.changed('password')) {
        user.password = await bcrypt.hash(user.password, hashCostFactor);
      }
      return user
    }
    
    module.exports = (sequelize, DataTypes) => {
      const user = sequelize.define(
        'user',
        {
          username: {
            type: DataTypes.STRING(255),
            allowNull: false,
            unique: true,
          },
          password: {
            type: DataTypes.STRING(255),
            allowNull: false,
          },
        },
        {
          tableName: 'user',
        }
      );
    
      user.beforeCreate(
        async (user) => await hashPassword(user)
      );
    
      user.beforeUpdate(
        async (user) => await hashPassword(user)
      );
    
      /**
       * Checks if the parameter matches stored password
       * @param password
       */
      user.prototype.validatePassword = function validatePassword(password) {
        if(!password || !this.password)
          return false;
        return bcrypt.compareSync(password, this.password);
      };
    
      return user;
    }
```


On Sequelize update call:

updateUserById.js:
```
    module.exports = async ({ id, ...user }, options) =>
     await models.user.update(user,
        {
          where: {
            id
          },
          individualHooks: true,
          ...options
        }
      );
    };
```

models is from Sequelize models defined

**Comment by SimoneLeoni1987** [comment] 2020-04-15 13:56
Those docs for this library is an hot mess...

**Comment by scelloo-nathanielbabalola** [comment] 2021-02-11 23:02
Thank you this just saved me after like an hour, I even tried going through the instance way. By finding one from the DB
Then doing `user.password = password` then `user.save()`
