### ISSUE TITLE
Build and save with associations

### ISSUE THREAD

**Issue by Raphoik** [sequelize/sequelize#9308] opened 2018-04-15 18:12 UTC
## What are you doing?
I am trying to build a user, create a location (I'm using google geocode API) and save all, but the association isn't created in the database. Everything is working fine. The response is exactly what I want but when I go into the database, the association isn't created. The only way I made it work was to create and save the location entity separately and directly set the foreign key "locationId" to the newly generated ID. It's been almost a week and I still can't figure out how to make it work. If it can help, I'm also using PostgreSQL. Here is the doc for creation with associations.

```js
User.belongsTo(models.Location, { as: 'location', foreignKey: 'locationId' });
Location.hasMany(models.User, { as: 'users', foreignKey: 'locationId' });
```

```js
const createRandomToken = crypto
  .randomBytesAsync(16)
  .then(buf => buf.toString('hex'));

const createUser = token => User.build({
  firstName: req.body.firstName,
  lastName: req.body.lastName,
  email: req.body.email,
  passwordResetToken: token,
  passwordResetExpires: moment().add(1, 'days'),
  role: req.body.roleId,
  active: true
}, {
  include: [{ model: Location, as: 'location' }]
});

const createLocation = (user) => {
  if (!user) return;
  if (!req.body.placeId) return user;
  return googleMapsHelper.getLocationByPlaceId(req.body.placeId).then((location) => {
    user.location = location;
    return user;
  });
};

const saveUser = (user) => {
  if (!user) return;
  return user.save()
    .then(user => res.json(user.getPublicInfo()));
};

createRandomToken
  .then(createUser)
  .then(createLocation)
  .then(saveUser)
  .catch(Sequelize.ValidationError, (err) => {
    for (let i = 0; i < err.errors.length; i++) {
      if (err.errors[i].type === 'unique violation') {
        return next(createError.Conflict(err.errors[i]));
      }
    }
  })
  .catch(err => next(createError.InternalServerError(err)));
```

## What do you expect to happen?
I expected the user and location to be created and the association to be made.

## What is actually happening?
The user is created, but the location and association isn't.

```json
{
  "id": null,
  "firstName": "FirstName",
  "lastName": "LastName",
  "email": "test@test.com",
  "lastLogin": null,
  "passwordResetExpires": "2018-04-15T21:02:34.624Z",
  "location": {
    "id": 5,
    "placeId": "ChIJs0-pQ_FzhlQRi_OBm-qWkbs",
    "streetNumber": null,
    "route": null,
    "city": "Vancouver",
    "postalCode": null,
    "country": "Canada",
    "region": "British Columbia",
    "formatted": "Vancouver, BC, Canada",
    "createdAt": "2018-04-14T20:57:54.196Z",
    "updatedAt": "2018-04-14T20:57:54.196Z"
}
```

__Dialect:__ postgres
__Dialect version:__ 10.3
__Database version:__ 10.3
__Sequelize version:__ 4.37.5
__Tested with latest release:__ Yes

**Comment by sushantdhiman** [comment] 2018-04-16 03:50
Duplicate of https://github.com/sequelize/sequelize/issues/9233

**Closed by sushantdhiman** 2018-04-16 03:50 UTC

**Comment by Raphoik** [comment] 2018-04-16 18:50
Not a duplicate since he had a problem with the `isNewRecord: false` which I don't use. Is it not working because I don't declare the location in the build function but assign it later?

**Comment by Raphoik** [comment] 2018-04-16 19:00
I made it work doing this with transactions, but it looks like trash since location isn't a required field. Is there any other way?

```js
   const createRandomToken = crypto
      .randomBytesAsync(16)
      .then(buf => buf.toString('hex'));

    const createUser = token => User.build({
      firstName: req.body.firstName,
      lastName: req.body.lastName,
      email: req.body.email,
      passwordResetToken: token,
      passwordResetExpires: moment().add(1, 'days'),
      role: req.body.roleId,
      active: true
    }, {
      include: [{ model: Location, as: 'location' }]
    });

    const createLocation = (user) => {
      if (!user) return;
      if (!req.body.placeId) return user;
      return googleMapsHelper.getLocationByPlaceId(req.body.placeId).then((location) => {
        user.location = location;
        return user;
      });
    };

    const saveUser = (user) => {
      if (!user) return;
      return sequelize.transaction((t) => {
        if (user.location) {
          if (!user.location.id) {
            return user.location.save({ transaction: t }).then((location) => {
              user.locationId = location.id;
              return user.save({ transaction: t })
                .then(user => res.json(user.getPublicInfo()));
            });
          }
          user.locationId = user.location.id;
        }
        return user.save({ transaction: t })
          .then(user => res.json(user.getPublicInfo()));
      });
    };

    createRandomToken
      .then(createUser)
      .then(createLocation)
      .then(saveUser)
      .catch(Sequelize.ValidationError, (err) => {
        for (let i = 0; i < err.errors.length; i++) {
          if (err.errors[i].type === 'unique violation') {
            return next(createError.Conflict(err.errors[i]));
          }
        }
      })
      .catch(err => next(createError.InternalServerError(err)));
  });
```

**Comment by nexequ** [comment] 2018-06-01 10:13
Why is this closed?
