### ISSUE TITLE
sequelize init creates incorrect models/index.js on Windows

### ISSUE THREAD

**Issue by ceefour** [sequelize/sequelize#10014] opened 2018-10-10 16:17 UTC
## What are you doing?
sequelize init

## What do you expect to happen?

Created `models/index.js` correctly

## What is actually happening?

`models/index.js` contains:

```js
const config = require(__dirname + '/..\config\config.json')[env];
```

which is incorrect, it should be:

```js
const config = require(__dirname + '/../config/config.json')[env];
```

__Dialect:__ `postgres`
__Dialect version:__ 7.5.0
__Database version:__ 10
__Sequelize version:__ 4.39.0
__Tested with latest release:__ Yes 4.39.0

**Comment by sushantdhiman** [comment] 2018-10-11 04:43
Please report CLI issues to CLI

Duplicate of https://github.com/sequelize/cli/issues/614

**Closed by sushantdhiman** 2018-10-11 04:43 UTC
