### ISSUE TITLE
Field with type Sequelize.JSON not working when MySQL dialect is used for a MariaDB database

### ISSUE THREAD

**Issue by Bhavin-jumpbyte** [sequelize/sequelize#13679] opened 2021-11-18 10:48 UTC
## Issue Creation Checklist

[ ] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description

When querying a model, which has a field with the type sequelize.JSON, it returns error.

```js

// Connecting to DB, params are coming from file
const sequelize = new Sequelize(database, username, password, {
    host: host,
    port: port,
    dialect: 'mariadb',
    define: {
        freezeTableName: true,
        timestamps: true
    },
});

// creating model, 

const sequelize = require('sequelize');

module.exports = () => {
    const User = sequelize.define('user', {
        firstName: {
            type: sequelize.STRING,
            allowNull: false,
            trim: true
        },
        lastName: {
            type: sequelize.STRING,
            allowNull: false,
            trim: true
        },
        OTCkeys: {
            type: sequelize.JSON
        },
    }, { tableName: 'USER' });
    return User;
};

```
### What do you expect to happen?

I expect to get a parsed JS object out of my JSON field.

### What is actually happening?

SyntaxError: Unexpected token o in JSON at position 1. issue itself with mariadb (node_modules/sequelize/lib/dialects/mariadb/query.js:187:72).

### Environment

Dialect: mariadb
Dialect library version: mariadb - 2.5.3
Database version: mysql 8.0.27 OR v5
Sequelize version: v5.22.4
Node Version: v14.18.0
OS: macOS High Sierra, 10.13.6

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [x] I think this problem happens only for the  mariadb dialect(s)
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

**Comment by WikiRik** [comment] 2021-11-18 14:08
Does this issue also occur on the latest version of Sequelize (6.9.0 at the time of writing)?

**Comment by Bhavin-jumpbyte** [comment] 2021-11-19 05:19
> Does this issue also occur on the latest version of Sequelize (6.9.0 at the time of writing)?

Yes, @WikiRik

**Comment by SeverinNovack** [comment] 2021-12-13 07:11
@Bhavin-jumpbyte any update on this?

**Comment by ephys** [comment] 2022-09-30 19:38
Using the MariaDB dialect for a MySQL database is not something we support. Each dialect is tailored to their associated database and mismatching will lead to bugs like this. Is there a reason you're not using the mysql dialect?

**Comment by ephys** [comment] 2022-10-06 17:04
Closing as duplicate of https://github.com/sequelize/sequelize/issues/10946

**Closed by ephys** 2022-10-06 17:04 UTC
Labels: type: bug, dialect: mariadb
