### ISSUE TITLE
Failure when substituting array into raw query

### ISSUE THREAD

**Issue by bblack** [sequelize/sequelize#1969] opened 2014-06-26 15:19 UTC
Using postgres:
```
dbconn.query('select * from "User" where "userId" in :ids', null, {raw: true}, {ids: [1,2,3]}).then(function(users){ console.log(users.length); })
[object Object]
> info: Executing (default): select * from "User" where "userId" in ARRAY[1,2,3]
Possibly unhandled error: syntax error at or near "ARRAY"
```

**Comment by defunctzombie** [comment] 2015-03-30 18:14
@mickhansen any way around this?

**Comment by mickhansen** [comment] 2015-03-30 19:19
@defunctzombie I don't believe so, if it's still an issue. An argument could be made to change the default array to parameter escaping since IN is probably most likely the desired effect.

**Comment by defunctzombie** [comment] 2015-04-22 02:14
No longer using raw query for my use case so not an issue for me, but I do think that the default behavior of `IN` is likely desired.

**Comment by mickhansen** [comment] 2015-04-22 05:10
@defunctzombie I agree, did you ever test if it was still the case? I was sure i fixed this previously.

**Comment by defunctzombie** [comment] 2015-04-27 05:39
have not tested if this is the case recently since switching away from the raw query

**Comment by DenisGorbachev** [comment] 2015-05-02 10:00
I'm having the same issue

**Comment by janmeier** [comment] 2015-05-02 14:51
@DenisGorbachev which version are you experiencing this on?

**Comment by DenisGorbachev** [comment] 2015-05-02 15:31
"sequelize": "2.1.0"

**Comment by juanjoLenero** [comment] 2015-07-17 16:24
Just chiming in, I'm also having this issue in sequelize v2.1.3.

```javascript
...
if (options.trunc) {
    dates = Calendar.truncTimeFromDates(dates);
    startDateField = sequelize.fn('date_trunc', 'day', startDateField);
}

return Event.findAll({
    where: {
        $and: [
            {parentEventId: this.id},
            sequelize.where(
                startDateField,
                'IN',
                dates
            )
         ]
    },
    logging: console.log
});

// Executing (default): 
// SELECT "id", "title", "location", "timeZone", "startDate", "endDate", "notes", "rrule", "type", "isDetached", "isCanceled", "isAllDay", "createdAt", "updatedAt", "courseId", "parentEventId", "ownerId" 
// FROM "Events" AS "Event" 
// WHERE ("Event"."parentEventId" = 1 AND date_trunc('day', "Event"."startDate") = ARRAY[1420005600000]);
```

**Comment by mull** [comment] 2015-11-10 10:31
Any news on this? I just ran into it as well.

**Comment by diegolmello** [comment] 2016-03-08 17:00
+1

**Comment by sushantdhiman** [comment] 2016-06-17 09:51
@mickhansen @janmeier Duplicate of #3769

**Closed** 2016-06-17 14:15 UTC
Labels: bug, postgres
