### ISSUE TITLE
Validator does not run if the field is not provided.

### ISSUE THREAD

**Issue by billxinli** [sequelize/sequelize#3430] opened 2015-03-30 18:16 UTC
Assume a very simple model:

    var user = sequelize.define('user',
      {
        email: {
          type: DataTypes.STRING,
          validate: {
            isEmail: {
              msg: 'Email must be a valid email address'
            },
            notEmpty: {
              msg: 'Email is a required field'
            }
          }
        }
      })

If I do `user.create({})` the validation rules in the email does not run.
I am wondering why this is? The only thing I can see is, I am missing the schema validator `allowNull: true` however, this does not return an user friendly error message.

**Comment by BridgeAR** [comment] 2015-03-30 18:46
The validations won't run, since the field is empty and this is a valid entry as long as you do not use allowNull: false (allowNull: true is the default value).
So using allowNull: false is fixing your issue.

**Comment by billxinli** [comment] 2015-03-30 18:58
I added `allowNull: false` to the model, so now it is:

    var user = sequelize.define('user',
      {
        email: {
          type: DataTypes.STRING,
          allowNull: false,
          validate: {
            isEmail: {
              msg: 'Email must be a valid email address'
            },
            notEmpty: {
              msg: 'Email is a required field'
            }
          }
        }
      })

I am trying to do a test with:

    User.create({})
      .then(function (user) {
        console.log(user)
      })
     .catch(function (err) {
       console.log(err)
     })


However, it is showing that email can not be null, however, it seems there is no way to custom this message. And the rest of the validators did not run.

```
{ name: 'SequelizeValidationError',
  message: 'notNull Violation: email cannot be null',
  errors:
  [ { message: 'email cannot be null',
    type: 'notNull Violation',
    path: 'email',
    value: null } ] }```

**Comment by mickhansen** [comment] 2015-03-30 19:23
`allowNull` does not support custom messages currently no: https://github.com/sequelize/sequelize/issues/1500

And no we don't run regular field validations after the schema validations (which notNull is a type of currently).

**Comment by BridgeAR** [comment] 2015-05-31 13:38
Duplicate of #1500

**Closed** 2015-05-31 13:49 UTC

**Comment by loulin** [comment] 2016-05-24 11:00
If `allowNull` not set, all regular validations will not work. But `allowNull` will add `NOT NULL` constraint on table schema which I don't need. So how can I do builtinAttrValidate like `notNull` if `allowNull` is not set?
