### ISSUE TITLE
Schema name has '$' which is recognized as a bind parameter

### ISSUE THREAD

**Issue by AbhiSivaprasad** [sequelize/sequelize#11446] opened 2019-09-18 05:06 UTC
## Issue Description

$ in schema name breaks creates.

### What are you doing?

I am trying to run a simple create where the schema name is unchangeable as 'x$y'

### What is actually happening?

The create is failing: 

 - Named bind parameter "$y" has no value in the given object.

If I escape the $ using $$ then all read queries will fail.

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment] 2019-09-18 11:33
Duplicate of #11320

**Closed by papb** 2019-09-18 11:33 UTC
