### ISSUE TITLE
How can I validate the length of an array in POSTGRES?

### ISSUE THREAD

**Issue by canebat** [sequelize/sequelize#3560] opened 2015-04-19 22:47 UTC
I want to ensure that my array field `DataTypes.ARRAY(DataTypes.STRING)` can only hold up to 5 elements.

I thought the model validator `len` would do it, but from testing that only validates the length of the individual strings in the array, instead of the array length (which is still useful). 

I guess I need to create my own custom length validator for an array field, but I'm unsure how to do that. It would also need to include the existing `len` validator to also ensure the individual strings are within a certain # of characters. Can anyone help me out?

**Comment by janmeier** [comment] 2015-04-22 07:56
Duplicate of https://github.com/sequelize/sequelize/issues/3208 - Currently we are not sure if the len validator should actually apply to the array or its elements

**Closed by janmeier** 2015-04-22 07:56 UTC
