### ISSUE TITLE
Upsert incorrectly replacing sequelize.fn

### ISSUE THREAD

**Issue by PyroSA** [sequelize/sequelize#3406] opened 2015-03-25 13:41 UTC
Upsert combined with Sequelize.fn('NOW'); does not seem to be correctly transformed to PostgreSQL.

The actual Command:
```
Model.upsert({
            key1: 'foo',
            key2: 'bar',
            value1: 'baz'
            receivedAt: sequelize.fn('NOW')
          })
```

Insert is as expected - note the receivedAt = NOW()
```
INSERT INTO "Model"
("key1","key2","value1","receivedAt","createdAt","updatedAt") 
VALUES
('foo','bar','baz',NOW(),'2015-03-25 13:31:53.138 +00:00','2015-03-25 13:31:53.138 +00:00');
```

Upsert is as expected - note the receivedAt is broken and createdAt is missing/deformed.
```
UPDATE "Model" 
SET 
"key1"='foo',
"key2"='bar',
"value1"='baz',
"receivedAt"=`fn` = 'NOW', `args` = ,
"updatedAt"='2015-03-25 13:31:53.138 +00:00' 
WHERE (("key1" = 'foo' AND "key2" = 'bar'));
```

**Comment by janmeier** [comment] 2015-03-25 13:43
Please provide some actual code https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md

**Comment by PyroSA** [comment] 2015-03-25 13:51
Sorry @janmeier: clicked too soon.

Updated the original description to contain the details.

**Comment by janmeier** [comment] 2015-03-25 13:55
Alright, no problem :)

Seems to work fine on latest master:
```sql
CREATE OR REPLACE FUNCTION pg_temp.sequelize_upsert() RETURNS integer AS $$ BEGIN INSERT INTO "models" ("key1","key2","requestedAt") VALUES ('foo','bar',NOW()); RETURN 1; EXCEPTION WHEN unique_violation THEN UPDATE "models" SET "key1"='foo',"key2"='bar',"requestedAt"=NOW(); RETURN 2; END; $$ LANGUAGE plpgsql; SELECT * FROM pg_temp.sequelize_upsert();
```

Try upgrading to the latest version. If that does not help, you'll need to post your model definiton as well

**Comment by PyroSA** [comment] 2015-03-25 15:06
Built from these columns (CoffeeScript)

```
  columns =
    key1:
      type: DataTypes.STRING
      unique: 'compositeIndex'

    key2:
      type: DataTypes.UUID
      unique: 'compositeIndex'

    value1: DataTypes.UUID
    value2: DataTypes.UUID

    requestedAt: DataTypes.DATE
    receivedAt: DataTypes.DATE
    loginAt: DataTypes.DATE
```

The method performing the update is a classMethod:

```
      requestMethod: (key1, key2) ->
        return api_call key1, key2
          .then Model.upsert
            key1: key1
            key2: key2
            requestedAt: sequelize.fn('NOW')
```

So I call Model.requestMethod 'foo', 'bar'

**Comment by janmeier** [comment] 2015-03-25 15:17
Still works fine for me ... 

Can you provide a pull request with a failing test case?

**Comment by janmeier** [comment] 2015-04-07 11:07
Closing this, please open a PR with reproducible test case

**Closed by janmeier** 2015-04-07 11:07 UTC

**Comment by FredKSchott** [comment] 2015-06-03 18:35
I can reproduce this as well, let me see if I can get something into a failing test

**Comment by FredKSchott** [comment] 2015-06-03 19:03
I can't seem to get the tests configured properly, but here's the model definition:
```js
sequelizeDB.define('Calendar', {
    id: {
      type: DataTypes.STRING,
      field: 'id',
      primaryKey: true,
      defaultValue: sequelizeDB.fn('generate_object_id')
    },
    // ...
```

And then when I upsert with other fields as values, I get this SQL statement with a syntax error around **"id"=\`fn\` = 'generate_object_id'**:

```sql
CREATE OR replace FUNCTION pg_temp.sequelize_upsert() /* function definition */; RETURN 1;EXCEPTION 
WHEN unique_violation THEN UPDATE "calendars" 
  SET    "id"=`fn` = 'generate_object_id', 
         `args` = , 
         "type"='XXX',
         /* some other fields */
  WHERE  ( "id" = generate_object_id() 
         OR ( 
            // ...
```

**Comment by FredKSchott** [comment] 2015-06-03 23:34
I was able to reproduce in the PR, @janmeier can you re-open this issue ticket?

As for a fix, so far I don't know enough to fix it myself. ` this.escape()` is getting called with value `{ fn: 'now', args: [] }`, which doesn't pass the check for `if (value && value._isSequelizeMethod)` so it looks like its getting parsed as a string instead. That's about as far as I could get, do you know what behavior should be happening instead?

**Comment by FredKSchott** [comment] 2015-06-04 01:42
I was able to trace the problem back to deepClone removing the special prototype of Utils.fn. Fix has now been submitted with tests here: https://github.com/sequelize/sequelize/pull/3864

**Comment by PyroSA** [comment] 2015-06-04 08:04
Thanks @FredKSchott :+1:
