### ISSUE TITLE
Mapping does not work in WHERE clause

### ISSUE THREAD

**Issue by spimou** [sequelize/sequelize#12271] opened 2020-05-18 15:34 UTC
### What are you doing?

My mapping includes this column 

```
    startTime: {
      field:'signaldate',
      type: Sequelize.DATE
    } ,
```

And my query uses it in the WHERE clause, but I have to cast it.

```
        return Signals.findAll({
          attributes:['startTime'],
          where:  
            Sequelize.where(
             Sequelize.cast(Sequelize.col('signaldate'), 'date'),{[Op.eq]: result} 
            )
        })
```

This is the query created by sequelize
```
SELECT `signaldate` AS `startTime` 
FROM `signals` AS `signals` 
WHERE CAST(`signaldate` AS DATE) = '2020-5-14' ;
```
This works only if I use the original column name in the cast part of the query. 

### What do you expect to happen?

MYSQL does not allow aliases in the WHERE clause, but maybe sequelize can or should, because otherwise, what is the point of mapping? What if I have a couple of casts and have to manually change everyone? There is no mapping. I should be able to use the `startTime` alias in the WHERE cast part, so mapping is also available there. 

### What is actually happening?

Either I use the original column name (no mapping) or I use it (the `startTime') and I get 
```
SequelizeDatabaseError: Unknown column 'startTime' in 'where clause'
```

### Environment

- Sequelize version: 5.21.8 
- Node.js version: 10.16.0 
- Operating System: win 10 pro
- If TypeScript related: TypeScript version: XXX

### How does this problem relate to dialects?

- [ x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment] 2020-05-19 04:44
Duplicate of https://github.com/sequelize/sequelize/issues/10732

`Sequelize.col` is like `Sequelize.literal` currently not aware of model and its attributes, so there is no way for it to covert attribute names. `Sequelize.col` should only be used with column names

**Closed by sushantdhiman** 2020-05-19 04:44 UTC
