### ISSUE TITLE
Raw queries treat where-in parameters as array fields (postgres)

### ISSUE THREAD

**Issue by dmfay** [sequelize/sequelize#3960] opened 2015-06-17 21:00 UTC
This issues completely wrong SQL and subsequently dies with a SequelizeDatabaseError:

```javascript
'use strict';

var Sequelize = require('sequelize');

var sequelize = new Sequelize('test', 'username', 'password', {host: '127.0.0.1', dialect: 'postgres'});

var Team = sequelize.define('Team', {
	name: Sequelize.STRING,
	field: Sequelize.STRING
});

sequelize.sync({force: true}).then(function() {
	return Team.create({
		name: 'a team',
		field: 'whatever'
	}).then(function (team) {
		var query = 'update "Teams" set name = \'new and improved\' where field in (:values)';

		sequelize.query(query, {
			replacements: {values: [team.field]},
			type: sequelize.QueryTypes.BULKUPDATE
		}).then(function () {
			console.log('hi');
		}).catch(function (err) {
			console.log(err);
		});
	});
});
```

The result:
Executing (default): update "Teams" set name = 'new and improved' where field in (ARRAY['whatever'])

It should of course be "where field in('whatever')", but it looks like the array-column support is getting in ahead of that.

**Comment by janmeier** [comment] 2015-06-18 08:22
Duplicate of https://github.com/sequelize/sequelize/issues/1969

**Closed by janmeier** 2015-06-18 08:22 UTC
