### ISSUE TITLE
LIMIT and ORDER inside INCLUDE[]

### ISSUE THREAD

**Issue by asimsohail** [sequelize/sequelize#4081] opened 2015-07-08 22:37 UTC
i have the following heirarchy:

```javascript
User.hasMany(Child);
Child.belongsTo(User);

Child.hasMany(Profile);
Profile.belongsTo(Child);
```

once i have the `User` object loaded, im attempting to load its `Children` along with their `Profiles`.. This works:

```javascript
user.getChildren({
  include: [
    { model: Profile }
  ]
});
```

however, i need to do the following:
1. get ALL `Children` for the user..
2. sort the `Profiles` of each `Child` by `name`..
3. limit the number `Profiles` for each `Child` to 3..

ive tried different permutations of the following but neither works..

```javascript
user.getChildren({
  include: [
    { model: Profile, limit: 3, order: [['name', 'ASC']] }
  ]
});
```

if i move the `limit: 3` outside the `include: []` construct, i end up getting ALL `Profiles` for only three `Children`.. this is not what i want.. i need to get only three `Profiles` for ALL the `Children`.. and i need to order those `Profiles` by `name`..

if i move the `order: [['name', 'ASC']]` outside the `include: []` construct, i get `ER_BAD_FIELD_ERROR: Unknown column 'id DESC' in 'order clause'`..

can someone please tell me the correct way to implement this logic?

the only way i can figure out to achieve that is something like:

```javascript
user.getChildren().then(function(children) {
  user.children = children;
  _.each(children, function(child) {
    child.getProfiles({
      limit: 3,
      order: [['name', 'ASC']]
    });
  });
});
```

but this means potentially lots of sequential SQL calls one after the other.. and ill have to write additional dirty code to ensure that i dont access any `Child` or `Profile` before all `Children` and their `Profiles` have been loaded.. is there a better / more efficient way?

**Comment by janmeier** [comment] 2015-07-09 07:24
Duplicate of https://github.com/sequelize/sequelize/issues/1897

**Closed by janmeier** 2015-07-09 07:24 UTC

**Comment by asimsohail** [comment] 2015-07-09 08:01
hi @janmeier.. youre right.. i found out the linked thread after posting this.. however, there's no workaround mentioned for this.. can you suggest a way to go about this issue?

**Comment by janmeier** [comment] 2015-07-09 08:04
@asimsohail Unfortunately not. As you see in the other issue there has been quite some discussion about how to solve this, but no work done yet. The work required to solve this in a good way is substantial and touches some of the most advanced code in the codebase.

**Comment by asimsohail** [comment] 2015-07-09 08:16
that sucks. =(.. i choose sequelize for my current project after coming across it in an earlier project.. and now after ive developed all the models and the relationships, ive hit this snag and there seems to be no way around it..

**Comment by janmeier** [comment] 2015-07-09 16:48
@asimsohail I see, but unfortunately, no-one has had time to work on it yet.

Perhaps you can speed things along by providing a PR with some test cases (integration or unit)
