### ISSUE TITLE
`findById` does not support `where`

### ISSUE THREAD

**Issue by mikew** [sequelize/sequelize#9710] opened 2018-07-23 14:48 UTC
## What are you doing?

```js
const result = await Model.findById(1, {
  where: {
    somethingElse: 'is this',
  }
})
```

## What do you expect to happen?
The where condition be applied.

## What is actually happening?
The where condition is being overwritten by Sequelize: [See model.js here](https://github.com/sequelize/sequelize/blob/0fe77d6c186cba3a04a687518bdad98e34330fd1/lib/model.js#L1861-L1862)

__Dialect:__ any
__Dialect version:__ any
__Database version:__ any
__Sequelize version:__ any
__Tested with latest release:__ yes

Since this is such an easy fix (`options.where =  options.where || {} `), I'm wondering if this is intentional behaviour.

**Comment by calmdev** [comment] 2018-07-23 15:38
why not use `findOne` if the id isn't unique?

```js
const result = await Model.findOne({ where: { id, somethingElse } });
```

**Comment by sushantdhiman** [comment] 2018-07-23 16:49
Use `findOne` if want extra conditions

Duplicate of https://github.com/sequelize/sequelize/issues/7434

**Closed by sushantdhiman** 2018-07-23 16:49 UTC
