### ISSUE TITLE
`where: { a: col('b') }` produces `"a"` instead of `"a" = "b"`

### ISSUE THREAD

**Issue by gop-aroy** [sequelize/sequelize#7512] opened 2017-04-12 09:38 UTC
Hi everyone :)

I'm having an issue, and I think it's a little problem not handled (but i'm might be wrong). I have this request : 
```
Model.db.client.findAll({
    where: args,
    include: [{
        model: Model.db.project,
        where: Object.assign(Model.querying.project.active),
        include: [{
            model: Model.db.assignment,
            where: Object.assign(Model.querying.assignment.active),
            include: [{
                model: Model.db.person,
                include: [{
                    model: Model.db.imputation,
                    where: {
                        projectId: Sequelize.col('projects.id')
                    }
                }]
            }]
        }]
    }],
    order: [
        ['name'],
        [Model.db.project, 'name'],
        [
            Model.db.project,
            Model.db.assignment,
            Model.db.person,
            Model.db.imputation,
            'year',
        ],
        [
            Model.db.project,
            Model.db.assignment,
            Model.db.person,
            Model.db.imputation,
            'week'
        ]
    ]
});
```
This is generating this SQL query
```
SELECT
  "client"."id",
  "client"."name",
  "client"."createdAt",
  "client"."updatedAt",
  "projects"."id"                                        AS "projects.id",
  "projects"."client_id"                                 AS "projects.clientId",
  "projects"."name"                                      AS "projects.name",
  "projects"."date_from"                                 AS "projects.dateFrom",
  "projects"."date_to"                                   AS "projects.dateTo",
  "projects"."description"                               AS "projects.description",
  "projects"."is_billable"                               AS "projects.isBillable",
  "projects"."createdAt"                                 AS "projects.createdAt",
  "projects"."updatedAt"                                 AS "projects.updatedAt",
  "projects.assignments"."id"                            AS "projects.assignments.id",
  "projects.assignments"."date_from"                     AS "projects.assignments.dateFrom",
  "projects.assignments"."date_to"                       AS "projects.assignments.dateTo",
  "projects.assignments"."createdAt"                     AS "projects.assignments.createdAt",
  "projects.assignments"."updatedAt"                     AS "projects.assignments.updatedAt",
  "projects.assignments"."person_id"                     AS "projects.assignments.personId",
  "projects.assignments"."project_id"                    AS "projects.assignments.projectId",
  "projects.assignments.person"."id"                     AS "projects.assignments.person.id",
  "projects.assignments.person"."email"                  AS "projects.assignments.person.email",
  "projects.assignments.person"."first_name"             AS "projects.assignments.person.firstName",
  "projects.assignments.person"."last_name"              AS "projects.assignments.person.lastName",
  "projects.assignments.person"."max_availability"       AS "projects.assignments.person.maxAvailability",
  "projects.assignments.person"."createdAt"              AS "projects.assignments.person.createdAt",
  "projects.assignments.person"."updatedAt"              AS "projects.assignments.person.updatedAt",
  "projects.assignments.person.imputations"."id"         AS "projects.assignments.person.imputations.id",
  "projects.assignments.person.imputations"."year"       AS "projects.assignments.person.imputations.year",
  "projects.assignments.person.imputations"."week"       AS "projects.assignments.person.imputations.week",
  "projects.assignments.person.imputations"."amount"     AS "projects.assignments.person.imputations.amount",
  "projects.assignments.person.imputations"."project_id" AS "projects.assignments.person.imputations.projectId",
  "projects.assignments.person.imputations"."person_id"  AS "projects.assignments.person.imputations.personId",
  "projects.assignments.person.imputations"."createdAt"  AS "projects.assignments.person.imputations.createdAt",
  "projects.assignments.person.imputations"."updatedAt"  AS "projects.assignments.person.imputations.updatedAt"
FROM "client" AS "client" INNER JOIN "project" AS "projects" ON "client"."id" = "projects"."client_id" AND (
  "projects"."date_to" >= '2017-04-12 08:57:03.450 +00:00' OR "projects"."date_to" IS NULL)
  INNER JOIN "assignment" AS "projects.assignments" ON "projects"."id" = "projects.assignments"."project_id" AND (
    "projects.assignments"."date_to" >= '2017-04-12 08:57:03.438 +00:00' OR "projects.assignments"."date_to" IS NULL)
  LEFT OUTER JOIN "person" AS "projects.assignments.person"
    ON "projects.assignments"."person_id" = "projects.assignments.person"."id"
  INNER JOIN "imputation" AS "projects.assignments.person.imputations"
    ON "projects.assignments.person"."id" = "projects.assignments.person.imputations"."person_id" AND "projects"."id"
ORDER BY "client"."name", "projects"."name", "projects.assignments.person.imputations"."year",
  "projects.assignments.person.imputations"."week";
```

This is a lot to digest… If you spend (too much) time reading this, you'll see that there is a problem with this line (in the last include) :
```
where: {
    projectId: Sequelize.col('projects.id')
}
```
that generates this : `AND "projects"."id"` when it should generate `"projects"."id" = "projects.assignments.person.imputations"."project_id"`

When i add it myself and execute it in my SQL Client, it's working just fine. 

Am I doing it right ?
Thank you in advance for you help.

PS : This error is thrown : 
```
Unhandled rejection SequelizeDatabaseError: argument of AND must be type boolean, not type integer
workload-api    |     at Query.formatError (/usr/app/node_modules/sequelize/lib/dialects/postgres/query.js:357:14)
workload-api    |     at Query.<anonymous> (/usr/app/node_modules/sequelize/lib/dialects/postgres/query.js:88:19)
workload-api    |     at emitOne (events.js:96:13)
workload-api    |     at Query.emit (events.js:188:7)
workload-api    |     at Query.handleError (/usr/app/node_modules/pg/lib/query.js:143:8)
workload-api    |     at Connection.<anonymous> (/usr/app/node_modules/pg/lib/client.js:180:26)
workload-api    |     at emitOne (events.js:96:13)
workload-api    |     at Connection.emit (events.js:188:7)
workload-api    |     at Socket.<anonymous> (/usr/app/node_modules/pg/lib/connection.js:136:12)
workload-api    |     at emitOne (events.js:96:13)
workload-api    |     at Socket.emit (events.js:188:7)
workload-api    |     at readableAddChunk (_stream_readable.js:176:18)
workload-api    |     at Socket.Readable.push (_stream_readable.js:134:10)
workload-api    |     at TCP.onread (net.js:551:20)

```

**Comment by gop-aroy** [comment] 2017-04-12 09:51
I found [a solution](https://github.com/sequelize/sequelize/issues/4414) : 
```
where: Sequelize.where(
    Sequelize.col('projects.assignments.person.imputations.project_id'),
    Sequelize.col('projects.id')
)
```

Is that the correct way to do it ?

**Comment by Cuxs** [comment] 2017-11-08 12:11
I have a similar error, ONLY when there is postgresql in the backend. The request is
```javascript
UserBalance.findAll({
    include: [{
      model: Users,
      where: { user_id: Sequelize.col('User.id') },
    }],
  })
```
This is the query that is launched:

`SELECT "UserBalance"."id", "UserBalance"."balance", "UserBalance"."createdAt", "UserBalance"."updatedAt", "UserBalance"."user_id", "User"."id" AS "User.id", "User"."name" AS "User.name", "User"."secondName" AS "User.secondName", "User"."DNI" AS "User.DNI", "User"."CUIL" AS "User.CUIL", "User"."CBU" AS "User.CBU", "User"."sex" AS "User.sex", "User"."email" AS "User.email", "User"."phone" AS "User.phone", "User"."password" AS "User.password", "User"."address" AS "User.address", "User"."isAdmin" AS "User.isAdmin", "User"."country_id" AS "User.country_id", "User"."investmentProfile_id" AS "User.investmentProfile_id", "User"."createdAt" AS "User.createdAt", "User"."updatedAt" AS "User.updatedAt" FROM "UserBalances" AS "UserBalance" INNER JOIN "Users" AS "User" ON "UserBalance"."user_id" = "User"."id" AND "User"."id";`

And the error:
 **Unhandled rejection SequelizeDatabaseError: argument of AND must be type boolean, not type integer**

I will try with the solution of @gop-aroy

**Comment by Cuxs** [comment] 2017-11-08 12:28
That fix works, but this is something to fix. Thanks @gop-aroy  :)

**Comment by gop-aroy** [comment] 2017-11-08 12:54
My pleasure bro ;)

**Comment by remus32** [comment] 2020-05-08 18:41
This is actually still an issue in v6-beta

**Comment by mariorodriguespt** [comment] 2022-11-11 15:33
Please reopen this issue, this is a common use case.

**Comment by ephys** [comment] 2022-11-11 17:46
To give an update on this issue: the problem isn't specific to includes, it's the default operator that's broken when `col` is used

We have a skipped test for it that we need to fix:

https://github.com/sequelize/sequelize/blob/main/test/unit/sql/where.test.ts#L456-L458

However specifying `Op.eq` explicitly works, so you should be able to write this:

```ts
where: {
  projectId: { [Op.eq]: col('projects.id') }
}
```

We have [a PR](https://github.com/sequelize/sequelize/pull/14020) to fix this but it's been on hold for a long time due to other things needing to be fixed first

**Comment by ephys** [comment] 2023-06-08 08:02
Fixed by https://github.com/sequelize/sequelize/pull/15598 in Sequelize 7

**Closed by ephys** 2023-06-08 08:02 UTC
Labels: type: bug
