### ISSUE TITLE
function date_trunc from PostgreSQL

### ISSUE THREAD

**Issue by makromat** [sequelize/sequelize#3955] opened 2015-06-17 15:55 UTC
Hi guys,

Is possible to add date_trunc function ? I don't know what is wrong but raw queries are not working in my code, so I'm not able to get data from through command like this:

    SELECT count(*), date_trunc('year', "createdAt") AS txn_year FROM tables GROUP BY txn_year

I think date_trunc is really usefull function ....

**Comment by janmeier** [comment] 2015-06-17 15:56
Can you define, 'not working' ? Does it not return the correct result, returns nothing at all? 

Perhaps this is a problem with raw queries - are you using the latest version?

**Comment by makromat** [comment] 2015-06-17 16:10
yes I'm using latest version just 
  
    TypeError: undefined is not a function

**Comment by makromat** [comment] 2015-06-17 17:05
it is working only in my /models/index.js but if I trying to do something like this : 

    var sequelize = require('sequelize');
    exports.getOrdersYearly = function(req, res, sequelize) {

        var sql = 'SELECT COUNT(*) FROM tables';
        sequelize.query(sql).then(function(result){ console.log(result)});
    };

**Comment by janmeier** [comment] 2015-06-17 18:12
undefined is not a function is a javascript error, it has nothing to do with the date_trunc function. At what line do you get that error? Perhaps you are passing something that is not a sequelze instance to the `getOrdersYearly` function

**Comment by makromat** [comment] 2015-06-17 18:55
If I do something like : global.getOrdersYearly ... global function inside index.js where is sequelize connected to the db it is working well, but I wanted it inside my table collector. I think make global function from it is wrong.

**Comment by janmeier** [comment] 2015-06-17 19:13
I'm sorry, but I have no idea what you just said. I can't guess what your code looks like, you'll have to actually show a complete, reproducible sample.

But as I said, you are probably not passing the sequelize instance properly to your function.

It is not enough to just require sequelize in every file where you need it. You must create your instance somewhere, and make sure that it is accessible to everywhere that needs it

**Comment by makromat** [comment] 2015-06-21 09:44
I mean it is working in my index.js file :

    "use strict";
    var fs        = require("fs");
    var path      = require("path");
    var Sequelize = require("sequelize");
    var moment = require('moment');
    var config = require(__dirname + '/../config/secrets').db;
    
    var sequelize = new Sequelize(config.database, config.username, config.password, config.port, config);
    var db        = {};
    
    fs
      .readdirSync(__dirname)
      .filter(function(file) {
        return (file.indexOf(".") !== 0) && (file !== "index.js");
      })
      .forEach(function(file) {
        var model = sequelize["import"](path.join(__dirname, file));
        db[model.name] = model;
      });
    
    Object.keys(db).forEach(function(modelName) {
      if ("associate" in db[modelName]) {
        db[modelName].associate(db);
      }
    });
    
    db.sequelize = sequelize;
    db.Sequelize = Sequelize;
    module.exports = db;

     global.getOrdersMonthly = function(req, res){  

      sequelize.query("").then(function(results){  // sequelize raw query is working only in bottom of :  var sequelize = new Sequelize(...)
    	  res.json(results[0]);
    	});
     };

Now I'm able to access getOrdersMonthly from app.js and it's working... 
But If I'm trying to use sequelize.query("") inside my order.js controller it's not working :

    var sequelize = require('sequelize');
    var _ = require('lodash');
    var async = require('async');
    var crypto = require('crypto');
    var db = require('../models');
    var Order = db.Order;
    var Item = db.Item;
    var secrets = require('../config/secrets');

exports.getOrdersMonthly = function(req, res, sequelize) {

  var sql = 'SELECT COUNT(*) FROM tables';
  sequelize.query(sql).then(function(result){ console.log(result)});  // sequelize throws error 
};

but standard query is working well inside order.js :

exports.getOrders = function(req, res) {
	Order.findAll({
		where: { id: 1 }
	}).then(function(order) {
		res.json(order);
	});
};

Thanks for any help!!!

**Comment by janmeier** [comment] 2015-06-21 09:54
You are still not showing how you invoke the `getOrdersMonthly` function when its not working. __But as I've already said - you are not passing it a proper sequelize instance if the query function is not defined__

This is a general node / required question, please take it to stakc overflow instead :)

Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).

**Closed by janmeier** 2015-06-21 09:54 UTC
