### ISSUE TITLE
Windows Authentication

### ISSUE THREAD

**Issue by Schlickmann** [sequelize/sequelize#10960] opened 2019-05-16 15:47 UTC
Hi guys,

Is there any way to use Windows Authentication to connect to SQL Server?

I am trying to use sequelize-msnodesqlv8 but seems the project is no longer maintained.

It is a requirement for my company. 

Thank you

**Comment by papb** [comment] 2019-07-25 01:11
Duplicate of #11199

**Closed by papb** 2019-07-25 01:11 UTC
