### ISSUE TITLE
Postgres: JSONB sub columns can't make as JSONB 

### ISSUE THREAD

**Issue by haracejacob** [sequelize/sequelize#10599] opened 2019-03-22 08:52 UTC
## What's the problem?
Hello, I have ARRAY type sub field in JSONB field. And I want to querying $contains to ARRAY field. but, sequelize makes nested key to TEXT

#### Data format (db)
```js
{
  foo: {
    bar: ['zoo']
  }
}
```

#### Code
```js
db.findAll(
  where: {
    foo: {
      bar: {
        [Sequelize.Op.contains]: '["zoo"]'
      }
    }
  }
)
```

#### Query
```sql
SELECT *
FROM db AS "DB"
WHERE ("DB"."foo" #>> '{bar}') @> '["zoo"]'
```
And occur `SequelizeDatabaseError: operator does not exist: text @> unknown`

## What are you doing?
I found `CAST` Option and did it.

#### Code
```js
db.findAll(
  where: {
    foo: {
      'bar::jsonb': {
        [Sequelize.Op.contains]: '["zoo"]'
      }
    }
  }
)
```

#### Query
```sql
SELECT *
FROM db AS "DB"
WHERE CAST(("DB"."foo" #>> '{bar}') AS JSONB) @> '["zoo"]'
```
Problem was not occured. but, this query can't use index(except function-based index)

## What do you expect to happen?
So, I want to replace `#>>` with `#>` when use cast statement `::jsonb`.
I fixed `dialects/abstract/query-generator.js` [commit](https://github.com/haracejacob/sequelize/commit/f6f64e5f364961ede49a5fb4ca222a7fd01a3f0b)

And retry.
#### Code
```js
db.findAll(
  where: {
    foo: {
      'bar::jsonb': {
        [Sequelize.Op.contains]: '["zoo"]'
      }
    }
  }
)
```

#### Query
```sql
SELECT *
FROM db AS "DB"
WHERE ("DB"."foo" #> '{bar}') @> '["zoo"]'
```
It's best result to me.

Could you please make options for choose '#>' or '#>>' or '->' or '->>' for JSONB.
Or Do I create PR? if these logic are fine.

__Dialect:__ postgres
__Dialect version:__ 7.8.1
__Database version:__ 11.1
__Sequelize version:__ 5.1

**Comment by papb** [comment] 2020-01-15 01:23
Related: #11671

**Comment by papb** [comment] 2020-01-15 01:24
Actually, do you agree this a duplicate of #11671? Or is there something different?

**Comment by haracejacob** [comment] 2020-01-15 09:57
@papb 
This issue is similar to #11671 but not duplicated.

My opinion is(regardless of the above issue) that when accessing JSONB object fields using nested key in sequelize, It needs to branch the operator to return **TEXT** type(`->>` or `#>>`) or **JSONB** type(`->` or `#>`) depending on the additional operator.

### case(jsonb)
```js
db.findAll(
  where: {
    foo: {
      bar: {
        [Sequelize.Op.contains]: '["zoo"]'
      }
    }
  }
)
```
In this case, contains(`@>`) operator needs jsonb type as left operand type
so, query should be
```sql
SELECT *
FROM db AS "DB"
WHERE "DB"."foo" #> '{bar}' @> '["zoo"]'
```

### case2(text)
```js
db.findAll(
  where: {
    foo: {
      bar: {
        [Sequelize.Op.like]: 'z%'
      }
    }
  }
)
```
In this case, like operator needs text type as left operand type
so, query should be
```sql
SELECT *
FROM db AS "DB"
WHERE "DB"."foo" #>> '{bar}' like 'z%'
```

### case3(uncertain)
```js
db.findAll(
  where: {
    foo: {
      bar: 'zoo'
    }
  }
)
```
Equal is uncertain. because both JSONB type and TEXT type can use equal(`=`) operator.
More discussion is needed in this case.


To use sequelize more effectively with PostgreSQL, it need the above features.
And could you please make options for choose ('#>', '#>>') or ('->', '->>') for accessing JSONB object fields using nested key. Indexes created using one operator do not interoperate with indexes created using the other operator.

**Comment by papb** [comment] 2020-01-16 20:53
Thanks!

> Or Do I create PR?

Please open a PR, that would be great!

**Comment by ephys** [comment] 2023-02-25 11:24
https://github.com/sequelize/sequelize/pull/15598 implements this. The JSON extraction syntax now produces JSON instead of text, so this should just work:

```ts
User.findAll(
  where: {
    foo: {
      bar: {
        [Op.contains]: ['zoo'],
      },
    },
  },
);
```

You can still use the previous text value by writing this:

```ts
User.findAll(
  where: {
    foo: {
      // :unquote is a modifier that "unquotes" JSON.
      // It's equivalent to json_unquote in most dialects, 
      // or the #>> and ->> operators in postgres)
      // The resulting value is TEXT, not JSON
      'bar:unquote': {
        [Op.like]: 'z%'
      }
    }
  }
)
```

**Closed** 2023-03-12 10:09 UTC
Labels: type: feature, dialect: postgres
