### ISSUE TITLE
Password is logged to console when using a transaction 

### ISSUE THREAD

**Issue by jonathansudhakar1** [sequelize/sequelize#10991] opened 2019-05-22 22:50 UTC
## What are you doing?

```js
this.db.transaction({autocommit: false, type: this.db.Transaction.TYPES.EXCLUSIVE, isolationLevel: this.db.Transaction.ISOLATION_LEVELS.SERIALIZABLE}, 
        function (t)
        {.....
```
**To Reproduce**
1. Define a model without specifying the `logging` option so that it uses the default `console.log`
2. Create and run a transaction

## What do you expect to happen?
Database password should not be logged 

## What is actually happening?
Database password is getting logged

Dialect:
- [ ] mysql
- [x] postgres
- [ ] sqlite
- [ ] mssql
- [ ] any

Dialect **pg** version: ^6.4.0
Database version:  9.6.11
Sequelize version: ^4.9.0
Node Version: 6.10
OS: Ubuntu 14.04

Tested with latest release:
- [x] No
- [ ] Yes, specify that version:

**Comment by pradhansidhant** [comment] 2019-07-01 07:27
Hi @jonathansudhakar1

You can go through following link
https://stackoverflow.com/questions/28927836/prevent-sequelize-from-outputting-sql-to-the-console-on-execution-of-query

**Comment by papb** [comment] 2019-07-18 16:26
@jonathansudhakar1 Thanks for submitting this. Can you provide a full reproducible example? You included only part of the code... Thanks!

**Comment by jonathansudhakar1** [comment] 2019-07-18 20:33
@papb All logs coming from transactions have the config object which has the password

**Comment by papb** [comment] 2019-07-24 12:53
@jonathansudhakar1 Still I would like a [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) that I could just copy-paste and see it happening.

**Comment by papb** [comment] 2019-10-10 17:50
I suggest using the [sequelize-sscce repository](https://github.com/papb/sequelize-sscce) to create the SSCCE.

**Comment by ephys** [comment] 2024-03-27 09:39
Because this is for a very old version of Sequelize, and the bug does not ring a bell, nor has a reproducible example been provided, I will close this issue

**Closed by ephys** 2024-03-27 09:39 UTC
Labels: type: bug, status: awaiting response
