### ISSUE TITLE
Promise "catch" vs "onRejected" of "then"

### ISSUE THREAD

**Issue by vinkaga** [sequelize/sequelize#3378] opened 2015-03-19 14:51 UTC
Sequelize documentation uses "catch" pattern with promises as follows
```JavaScript
var Sequelize = require('sequelize')
    , sequelize = new Sequelize('seqex', 'root', 'mysql', {logging: false});

var User = sequelize.define('user', { name: {type:Sequelize.STRING, allowNull:false} });

sequelize.sync({force: true}).then(function () {

    var promise = User.create({}).cancellable();
    promise.then(function() { console.log('success'); });
    promise.catch(function(e) { console.log ('caught error', e); });

});
```
Unfortunately, "catch" isn't part of Promise/A+(https://promisesaplus.com/) spec. Is there a reason why the above pattern is preferable to the Promise/A+ pattern as follows?
```JavaScript
var Sequelize = require('sequelize')
    , sequelize = new Sequelize('seqex', 'root', 'mysql', {logging: false});

var User = sequelize.define('user', { name: {type:Sequelize.STRING, allowNull:false} });

sequelize.sync({force: true}).then(function () {

    var promise = User.create({}).cancellable();
    promise.then(function() { console.log('success'); }, function(err) { console.log('reject error', err)});

});
```

**Comment by janmeier** [comment] 2015-03-19 15:10
Nope, the patterns are equivalent. The benefit comes if you don't want a then callback, only the error. That would have to be written as `then(null, onError)`.

Sometimes we only want to handle the error at a specfic point in the code, while letting another place further up in the chain handle the success. Thus using `catch` is more succint

**Comment by mickhansen** [comment] 2015-03-19 16:17
catch makes the code much cleaner in my opinion, plus it has the sugar of allowing you to have multiple catches per error type.

**Comment by janmeier** [comment] 2015-03-24 14:40
Not a bug, closing

**Closed by janmeier** 2015-03-24 14:40 UTC
