### ISSUE TITLE
Complex where clauses at the top-level with findAndCountAll: no such column

### ISSUE THREAD

**Issue by talmurshidi** [sequelize/sequelize#14551] opened 2022-05-25 21:24 UTC
## Issue Creation Checklist

- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description
- I wrote a sample to explain the issue, I have `Customer`, `Purchase` and `CustomerPurchase`, I used [the Super Many-to-Many relationship](https://sequelize.org/docs/v6/advanced-association-concepts/advanced-many-to-many/#the-best-of-both-worlds-the-super-many-to-many-relationship) and [Complex where clauses at the top-level](https://sequelize.org/docs/v6/advanced-association-concepts/eager-loading/#complex-where-clauses-at-the-top-level)
- I used `findAndCountAll` with `offset` and `limit`.
- no such column: purchases.purchase_id when using `'$purchases.purchase_id$'`

### Models

```
'use strict';
module.exports = (sequelize, DataTypes) => {
    const Customer = sequelize.define(
        'Customer', {
        customer_id: {
            type: DataTypes.INTEGER,
            primaryKey: true,
            autoIncrement: true,
        },
        name: {
            type: DataTypes.TEXT,
            allowNull: true,
        },
    }, {
        tableName: 'customer',
    });

    Customer.associate = function (models) {
        //M:M
        Customer.belongsToMany(models.Purchase, {
            as: 'customerPurchases',
            foreignKey: 'customer_id',
            targetKey: 'purchase_id',
            through: models.CustomerPurchase,
        });
        //1:M
        Customer.hasMany(models.CustomerPurchase, {
            as: 'purchases',
            foreignKey: 'customer_id',
            sourceKey: 'customer_id',
        });
    };
    return Customer;
};
```

```
'use strict';
module.exports = (sequelize, DataTypes) => {
    const Purchase = sequelize.define(
        'Purchase',
        {
            purchase_id: {
                type: DataTypes.INTEGER,
                primaryKey: true,
                allowNull: false,
                autoIncrement: true,
            },
            name: {
                type: DataTypes.TEXT,
                allowNull: false,
            },
        },
        {
            tableName: 'purchase',
        }
    );

    Purchase.associate = function (models) {
        // M:M
        Purchase.belongsToMany(models.Customer, {
            as: 'PurchaseCustomer',
            foreignKey: 'purchase_id',
            targetKey: 'customer_id',
            through: models.CustomerPurchase,
        });

        //1:M
        Purchase.hasMany(models.CustomerPurchase, {
            as: 'customers',
            foreignKey: 'purchase_id',
            sourceKey: 'purchase_id',
        });
    };

    return Purchase;
};
```

```
'use strict';
module.exports = (sequelize, DataTypes) => {
    const CustomerPurchase = sequelize.define(
        'CustomerPurchase',
        {
            customer_id: {
                type: DataTypes.INTEGER,
                primaryKey: true,
                allowNull: false,
            },
            purchase_id: {
                type: DataTypes.INTEGER,
                primaryKey: true,
                allowNull: false,
            },
        },
        {
            tableName: 'customer_purchase',
        }
    );

    CustomerPurchase.associate = function (models) {
        CustomerPurchase.belongsTo(models.Customer, {
            as: 'customer',
            foreignKey: 'customer_id',
            targetKey: 'customer_id'
        });

        CustomerPurchase.belongsTo(models.Purchase, {
            as: 'purchase',
            foreignKey: 'purchase_id',
            targetKey: 'purchase_id'
        });

    };

    return CustomerPurchase;
};
```

### What do you expect to happen?

Customers with purchases based on the condition.

### What is actually happening?

```
  name: 'SequelizeDatabaseError',
  parent: [Error: SQLITE_ERROR: no such column: purchases.purchase_id] {
    errno: 1,
    code: 'SQLITE_ERROR',
    sql: 'SELECT `Customer`.`customer_id`, `Customer`.`name` FROM `customer` AS `Customer` WHERE `purchases`.`purchase_id` = 2 LIMIT 0, 1;'
  },
  original: [Error: SQLITE_ERROR: no such column: purchases.purchase_id] {
    errno: 1,
    code: 'SQLITE_ERROR',
    sql: 'SELECT `Customer`.`customer_id`, `Customer`.`name` FROM `customer` AS `Customer` WHERE `purchases`.`purchase_id` = 2 LIMIT 0, 1;'
  },
  sql: 'SELECT `Customer`.`customer_id`, `Customer`.`name` FROM `customer` AS `Customer` WHERE `purchases`.`purchase_id` = 2 LIMIT 0, 1;',
  parameters: {}
}
```

### Additional context

_[Sample for the bug](https://github.com/talmurshidi/sequelize-top-level-where-clause)_
#### How to run the project?
- Clone the repo `git clone https://github.com/talmurshidi/sequelize-top-level-where-clause.git` 
- Install node packages `npm install`
- Use `npm run watch` CLI and check the results in the terminal.

### Environment

- Sequelize version: v6.20.0
- Node.js version: v16.14.2
- If TypeScript related: TypeScript version:
- Database & Version: sqlite3 v5.0.8
- Connector library & Version: sqlite3 v5.0.8

## Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by wirujs** [comment] 2022-06-14 05:56
Hi, I found the issue just happened recently and my work around is to add `subQuery: false` to that query.

**Comment by talmurshidi** [comment] 2022-06-14 06:17
Hi @wirujs ,
I tried to use `subQuery: false` with `findAndCountAll` but it is not working.

**Comment by Jopchumba** [comment] 2022-06-17 16:28
parent: [Error: SQLITE_ERROR: no such column: purchases.purchase_id]
check if the table was created well its not  a sequel error but a database error.

**Comment by talmurshidi** [comment] 2022-06-18 11:08
@Jopchumba , the table is already created and if I will use `findAll` instead of `findAndCountAll`, the error will not appear.

**Comment by ephys** [comment] 2022-06-18 11:40
Looking at the query in the project, this is a duplicate of https://github.com/sequelize/sequelize/issues/12971

**Closed by ephys** 2022-06-18 11:40 UTC
