### ISSUE TITLE
MSSQL ConnectionError

### ISSUE THREAD

**Issue by theverything** [sequelize/sequelize#3267] opened 2015-03-04 00:05 UTC
I am getting a ConnectionError, which crashes the server, when using sequelize.

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
ConnectionError: Failed to connect to mysever.com:57840 - read ECONNRESET
    at Connection.socketError (/Users/theverything/code/api/node_modules/tedious/lib/connection.js:746:26)
    at Socket.<anonymous> (/Users/theverything/code/api/node_modules/tedious/lib/connection.js:3:59)
    at Socket.emit (events.js:107:17)
    at net.js:451:14
    at process._tickCallback (node.js:355:11)
```

**Comment by janmeier** [comment] 2015-03-04 08:38
Does this happen on the first connection, or on a query. The connection manager should be catching the error, but there is no specific handling for it .. https://github.com/sequelize/sequelize/blob/master/lib/dialects/mssql/connection-manager.js#L50

**Comment by theverything** [comment] 2015-03-04 17:32
It happens after the connection has been open for a little while.

**Comment by mbroadst** [comment] 2015-03-04 18:15
@janmeier hmm looks like we need to maybe catch that error, and release the connection back to the pool maybe?

**Comment by mbroadst** [comment] 2015-03-04 18:18
@theverything if you have some time, perhaps you could add a piece of code in the connection-manager like mysql has here: https://github.com/sequelize/sequelize/blob/master/lib/dialects/mysql/connection-manager.js#L72

tedious has an error event described here: http://pekim.github.io/tedious/api-connection.html#event_error

Otherwise, I'll try to find some time in the next day or two to put this in

**Comment by theverything** [comment] 2015-03-05 00:02
I updated tedious to 1.10 in order to pick up this change https://github.com/pekim/tedious/commit/0806fb95bbff053df510f70cb7d2517457a101b9

Before that change the error didn't have an `error.code`.

I used the following code to catch the error.

```
if (config.pool.handleDisconnects) {
  connection.on('error', function (err) {
  console.log(err);
    if (err.code === 'ESOCKET') {
      console.log('----- Connection lost removing connection from pool -----');
      self.pool.destroy(connection);
    }
  });
}
```

I also put a console.log at the top of the connect method.

```
console.log('---- Connection ----');
```

When the error happens now I can see the `----- Connection lost removing connection from pool -----` followed immediately by `---- Connection ----`. This happens a few times, then the error stops and I see  `---- Connection ----` being logged every second indefinitely until I kill the process.

**Comment by mbroadst** [comment] 2015-03-05 00:28
@theverything sorry I forgot to comment on this earlier, but this was merged earlier today: 317032efd966e1f18520290f042b47e6b1ce4801. It's seems strange that you're running into the constant reconnect behavior.. @ackerdev ran into an issue with connections being left open even after we assumed they were destroyed, I imagine the problem is within the disconnect code [here](https://github.com/sequelize/sequelize/blob/master/lib/dialects/mssql/connection-manager.js#L99). Maybe you can pop some debug messages in there to reveal some broken behavior?

**Comment by theverything** [comment] 2015-03-05 01:53
I did some `console.log`s in the disconnect method and it looks like the `connection.connected` property is always `undefined`.

Which causes the connection to never be closed.

Unless I'm missing something.

**Comment by mbroadst** [comment] 2015-03-05 02:17
@theverything hey can you try the patch in this pr: https://github.com/sequelize/sequelize/pull/3285

**Comment by mbroadst** [comment] 2015-03-05 02:20
@theverything oops, check the update, we didn't catch the error you opened this ticket for in the first place :smile:

**Comment by theverything** [comment] 2015-03-05 02:40
Looks like that patch solves the problem. Thank you @mbroadst !!!!!

**Comment by mbroadst** [comment] 2015-03-05 02:42
@theverything thank you for digging in, glad to know we can wrap these connection issues up :smile:

**Comment by mbroadst** [comment] 2015-03-05 02:43
@mickhansen this can be closed when https://github.com/sequelize/sequelize/pull/3285 is merged

**Closed** 2015-03-05 06:59 UTC

**Comment by douglasjunior** [comment] 2017-06-28 15:23
I have this problem on the `"sequelize": "^4.2.0"` and `"mysql2": "^1.3.5"` . After the connection has been open for a little while. It happens when the connection is idle for a while.

```
{ SequelizeDatabaseError: read ECONNRESET
    at Query.formatError (C:\projetos\NodeJS\aquasafe-webservice\node_modules\sequelize\lib\dialects\mysql\query.js:222:16)
    at Query.connection.query [as onResult] (C:\projetos\NodeJS\aquasafe-webservice\node_modules\sequelize\lib\dialects\mysql\que
ry.js:55:23)
    at Connection._notifyError (C:\projetos\NodeJS\aquasafe-webservice\node_modules\mysql2\lib\connection.js:212:25)
    at Connection._handleFatalError (C:\projetos\NodeJS\aquasafe-webservice\node_modules\mysql2\lib\connection.js:172:14)
    at Connection._handleNetworkError (C:\projetos\NodeJS\aquasafe-webservice\node_modules\mysql2\lib\connection.js:177:8)
    at Socket.g (events.js:292:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1277:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
From previous event:
    at Query.run (C:\projetos\NodeJS\aquasafe-webservice\node_modules\sequelize\lib\dialects\mysql\query.js:44:12)
    at retry (C:\projetos\NodeJS\aquasafe-webservice\node_modules\sequelize\lib\sequelize.js:529:32)
    at C:\projetos\NodeJS\aquasafe-webservice\node_modules\retry-as-promised\index.js:40:21
    at retryAsPromised (C:\projetos\NodeJS\aquasafe-webservice\node_modules\retry-as-promised\index.js:30:10)
    at Promise.try.then.connection (C:\projetos\NodeJS\aquasafe-webservice\node_modules\sequelize\lib\sequelize.js:529:14)
From previous event:
    at Sequelize.query (C:\projetos\NodeJS\aquasafe-webservice\node_modules\sequelize\lib\sequelize.js:526:8)
    at QueryInterface.select (C:\projetos\NodeJS\aquasafe-webservice\node_modules\sequelize\lib\query-interface.js:671:27)
    at Promise.try.then.then.then (C:\projetos\NodeJS\aquasafe-webservice\node_modules\sequelize\lib\model.js:1551:34)
From previous event:
    at Function.findAll (C:\projetos\NodeJS\aquasafe-webservice\node_modules\sequelize\lib\model.js:1548:8)
    at Function.findOne (C:\projetos\NodeJS\aquasafe-webservice\node_modules\sequelize\lib\model.js:1704:17)
    at self.login (C:\projetos\NodeJS\aquasafe-webservice\src\controllers\Users.js:16:11)
    at Layer.handle [as handle_request] (C:\projetos\NodeJS\aquasafe-webservice\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\projetos\NodeJS\aquasafe-webservice\node_modules\express\lib\router\route.js:137:13)
    at req.getValidationResult.then (C:\projetos\NodeJS\aquasafe-webservice\src\validation\Validator.js:17:17)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
  name: 'SequelizeDatabaseError',
  parent:
   { Error: read ECONNRESET
       at exports._errnoException (util.js:1018:11)
       at TCP.onread (net.js:568:26)
     code: 'ECONNRESET',
     errno: 'ECONNRESET',
     syscall: 'read',
     fatal: true,
     sql: 'SELECT ...' },
  original:
   { Error: read ECONNRESET
       at exports._errnoException (util.js:1018:11)
       at TCP.onread (net.js:568:26)
     code: 'ECONNRESET',
     errno: 'ECONNRESET',
     syscall: 'read',
     fatal: true,
     sql: 'SELECT ...' }
```
I tried to decrease the time from the idle pool to 10000, but it did not work.

I went back to the `"sequelize": "^3.30.4"` and `"mysql": "^2.13.0"` and the problem disappeared.

Did the problem come back, or am I doing something wrong? I configured the project using the [sequelize/express-example](https://github.com/sequelize/express-example).
