### ISSUE TITLE
Querying through model attributes in injected getter.

### ISSUE THREAD

**Issue by juanjoLenero** [sequelize/sequelize#3818] opened 2015-05-27 21:45 UTC
Shouldn't it be possible to pass through.where options to an injected many-to-many model accessor just like you can do for many-to-many includes?

Using sequelize v2.1.3.

```javascript
// MODELS
    var Group = sequelize.define('Group', {
        name: sequelize.Sequelize.STRING
    });

    var Person = sequelize.define('Person', {
        name: sequelize.Sequelize.STRING
    });

    var GroupPerson = sequelize.define('GroupPerson', {
        status: sequelize.Sequelize.STRING
    });

// RELATIONS
    Group.belongsToMany(Person, {through: GroupPerson, as: 'Persons'});
    Person.belongsToMany(Group, {through: GroupPerson, as: 'Groups'});

// EXAMPLE
Group
            .create({name: 'Golf'})
            .then(function (golf) {
                Group
                    .create({name: 'Hockey'})
                    .then(function (hockey) {
                        Person
                            .create({name: 'Pedro'})
                            .then(function (pedro) {
                                golf
                                    .addPerson(pedro, {status: 'accepted'})
                                    .then(function () {
                                        return hockey.addPerson(pedro, {status: 'pending'});
                                    })
                                    .then(function () {
                                        // Pedro's groups but only those with status='accepted' in the join model.
                                        return pedro.getGroups({
                                            through: {
                                                where: {status: 'accepted'}
                                            }
                                        });
                                    })
                                    .then(function (acceptedGroups) {
                                        console.log(acceptedGroups);
                                    });
                            });
                    });
            });
```

**Comment by mickhansen** [comment] 2015-05-28 06:45
https://github.com/sequelize/sequelize/blob/master/lib/associations/belongs-to-many.js#L290

Doesn't appear like we look for `through.where` atm, so unfortuneatly not.

**Comment by janmeier** [comment] 2015-07-11 17:41
Duplicate of https://github.com/sequelize/sequelize/issues/3198

**Closed by janmeier** 2015-07-11 17:41 UTC
Labels: feature
