### ISSUE TITLE
Wrong import suggested by Visual Studio Code when using TypeScript

### ISSUE THREAD

**Issue by alecrobertson1** [sequelize/sequelize#14897] opened 2022-08-17 13:50 UTC
## Issue Creation Checklist

- [X] I understand that my issue will be automatically closed if I don't fill in the requested information
- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description

Visual Studio Code suggests to import "sequelize/types", when it should suggest "sequelize".

### Reproducible Example

Here is the link to the SSCCE for this issue:

Ensure sequelize is available as a dependency, reference anything from sequelize package. Note that Visual Studio Code suggests importing from "sequelize/types". 

### What do you expect to happen?

Visual Studio Code should suggest "sequelize" not "sequelize/types".

### What is actually happening?

Visual Studio Code suggests to import "sequelize/types".

### Environment

- Sequelize version: 6.21.3
- Node.js version: 14.19.3
- If TypeScript related: TypeScript version: 4.6.4
- Database & Version: N/A
- Connector library & Version: N/A

## Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I will need guidance.
- [ ] No, I don't have the time, but my company or I are [supporting Sequelize through donations on OpenCollective](https://opencollective.com/sequelize).
- [ ] No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in resolving my issue.

---

*Indicate your interest in the resolution of this issue by adding the 👍 reaction. Comments such as "+1" will be removed.*

**Comment by WikiRik** [comment] 2022-08-17 13:52
Can you include some screenshots or more detailed messages from Visual Studio Code?

**Comment by alecrobertson1** [comment] 2022-08-17 13:52
Note I believe this is an issue with the way Sequelize is setup as other packages do not have this issue. The way Sequelize is setup seems to suggest to Visual Studio Code to import the wrong package.

When creating migrations, this happens and when the migrations are run, sequelize/types cannot be found, so this does have real-world implications. Sequelize should be setup so Visual Studio Code can suggest the correct imports.

**Comment by alecrobertson1** [comment] 2022-08-17 13:53
<img width="550" alt="Screenshot 2022-08-17 at 14 53 01" src="https://user-images.githubusercontent.com/4457688/185151803-52456789-7070-420e-a29a-48d5d8d94ae6.png">

**Comment by WikiRik** [comment] 2022-08-17 15:55
Just as a quick example I opened https://github.com/opencollective/opencollective-api/blob/main/server/lib/restore-sequelize-attributes-on-class.ts in GitHub Codespaces (which uses Visual Studio Code) and the following is what I see.
![image](https://user-images.githubusercontent.com/13023439/185185794-8c2e03f0-2248-4546-9031-4434fbb77e58.png)

How do you import `sequelize` in `@Server/Application/Model/Spaces`?

**Comment by alecrobertson1** [comment] 2022-08-17 16:47
@WikiRik If you remove the import on line 1, what auto import suggestion do you get? I am expecting you will also see the wrong import suggested.

**Comment by WikiRik** [comment] 2022-08-17 18:44
Ah yes, I can reproduce that. The typing does still work though. I guess this is due to the following line in `package.json`;
https://github.com/sequelize/sequelize/blob/ecf49d0102fe0447935b884a1c34c00d294f31db/package.json#L20
But in the `exports` we have the following;
https://github.com/sequelize/sequelize/blob/ecf49d0102fe0447935b884a1c34c00d294f31db/package.json#L22-L37

I'll look into this and see what we can do about it.

**Comment by alecrobertson1** [comment] 2022-08-17 18:45
The typing does work however I’ve had issues with migrations failing because it can’t find the package when the migration gets run. This is with Postgres.

So there is an impact.

**Comment by WikiRik** [comment] 2022-08-17 18:59
Is that fixed by not relying on the auto import but importing from `sequelize` directly?

**Comment by alecrobertson1** [comment] 2022-08-17 19:00
Yes if you manually change the import it works fine.

But I do not believe this should be required, no other packages work in this way.

**Comment by xadamxk** [comment] 2022-08-18 15:22
Dropping by to say my IDE's auto-import settings also defaults to `sequelize-types`.
It isn't breaking anything, but if this could be fixed, that would be great!

**Closed** 2022-08-19 16:32 UTC
Labels: type: typescript, existing workaround

**Comment by WikiRik** [comment] 2022-08-19 18:39
This should be fixed in 6.21.4, can you confirm?

**Comment by WikiRik** [comment] 2022-08-19 18:40
This will be fixed in either 6.21.5 or 6.22.0, but has been merged in the v6 branch
