### ISSUE TITLE
Sqlite dialect ERROR on AUTOINCREMENT id with datatype different then INTEGER.

### ISSUE THREAD

**Issue by ugogiordano87** [sequelize/sequelize#9995] opened 2018-10-05 12:08 UTC
## What are you doing?

The following model definition raises an error when using Sqlite dialect:

```
sequelize.define('User', {
        id: {
            type: DataTypes.SMALLINT,
            allowNull: false,
            primaryKey: true,
            autoIncrement: true
        },
        name: {
            type: DataTypes.STRING(25),
            allowNull: false,
        }, {});
```
while this is working properly: 
```
...       
    id: {
            type: DataTypes.INTEGER(4),
            allowNull: false,
            primaryKey: true,
            autoIncrement: true
        },
...
```
## What do you expect to happen?
It should work both with **INTEGER(length)** and **SMALLINT**.

## What is actually happening?
I got the following error:

    'SQLITE_ERROR: AUTOINCREMENT is only allowed on an INTEGER PRIMARY KEY'

__Dialect:__ mysql (production)/ sqlite (development)
__Dialect version:__ 4.0.2
__Sequelize version:__ 4.39.0

**Comment by sushantdhiman** [comment] 2018-10-05 12:12
Duplicate of https://github.com/sequelize/sequelize/issues/9397 , Already fixed on master.

Next time please check for duplicate issues first :)

**Comment by ugogiordano87** [comment] 2018-10-05 12:37
Well actually [this](https://github.com/sequelize/sequelize/pull/9406/commits/fc0cd9ed7549568ae8b2b35c1386f386a764e9cc) is a fixe for Postgres dialect not for Sqlite.

**Comment by sushantdhiman** [comment] 2018-10-05 12:42
You are right, this is broken for SQLite as well. Would you like you submit an PR @ugogiordano87?

**Comment by ugogiordano87** [comment] 2018-10-05 12:52
Sure, I'm working on it.

**Closed** 2018-10-10 13:38 UTC
Labels: bug, good first issue, sqlite
