### ISSUE TITLE
PostgreSQL NAMEDATALEN limit for aliases

### ISSUE THREAD

**Issue by josser** [sequelize/sequelize#4693] opened 2015-10-20 16:13 UTC
PostgresSQL have limit for identifiers names http://www.postgresql.org/docs/current/static/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS 
which is also applied to 'AS' statements.

Quick test: 
```sql
select 1 as really_long_alias_more_than_63_bytes_long_and_will_be_cut_to_63_bytes
```
 .. will cut alias name to 63 bytes:  
"really_long_alias_more_than_63_bytes_long_and_will_be_cut_to_63"

In really deep findAll / find with include: { .. include: { ,... { include: ... }}  } sequelize will produce very long aliases which will be truncated to 63 bytes long. 

Thanks and sorry for my bad english :(

**Comment by janmeier** [comment] 2015-10-20 16:17
Duplicate of https://github.com/sequelize/sequelize/issues/2084

**Closed by janmeier** 2015-10-20 16:17 UTC
