### ISSUE TITLE
Creating with existing association.

### ISSUE THREAD

**Issue by iwaduarte** [sequelize/sequelize#11105] opened 2019-06-24 01:35 UTC
This is a very important feature that has been request all around in forums,channels and here and still as v5 not implemented.

**Describe the solution you'd like**
The ability to create and associate with existing data instead to rely on set or add.
i.e `User.create({name: 'Sequelize', versions:[1,2,3,4,5]})` 

**Why should this be in Sequelize**
https://github.com/sequelize/sequelize/issues/5583
https://stackoverflow.com/questions/51952379/sequelize-create-instance-with-existing-association
https://stackoverflow.com/questions/38421078/sequelize-create-with-existing-association

**Describe alternatives you've considered**
The add and set alternatives are way more verbose and very different than an "easy-to-use" approach especially in cases where multiple associations are needed

`User.create({name:'Sequelize', details:'easy-to-use orm', versions:[1,2,3,4,5], enviroments:[1,2,3,4,5]})`
`// objects with ASSOCIATIONS predefined`
**very helpful in** `User.bulkCreate([obj1WithAssoc,obj2WithAssoc,obj2WithAssoc]).then(response => response);`

instead of:

**this is far from optimal or easy IMO**
`User.create(...).then(user => {
Promise.all ([user.addX([..])
                    user.addY([..])
                    user.addZ([..])]. then()})`

Would you guys consider this?

**Comment by papb** [comment] 2019-07-25 23:23
Duplicate of #5325

**Closed by papb** 2019-07-25 23:23 UTC
Labels: type: feature

**Comment by iwaduarte** [comment] 2020-12-04 17:25
@papb What exactly is the workaround ? My issue is just to avoid the use of sets.

**Comment by iwaduarte** [comment] 2020-12-04 17:26
Maybe if I create a PR ? @papb
