### ISSUE TITLE
getMigrator

### ISSUE THREAD

**Issue by stephenhu** [sequelize/sequelize#4281] opened 2015-08-09 05:45 UTC
seems the documentation is a bit vague or outdated, seems the sequelize.getMigrator call fails with "undefined is not a function".  searching through the sequelize code, i could not find this function call, i found this in the sequelize-cli code as a gulp task, but it's not accessible programmatically, in other words, i cannot require("sequelize-cli") in my code to leverage this.

basically i am trying to create a project that leverages a sqlite3 database, and i'm trying to create an instance by running migrations as per your instructions here "about programmatic migrations". 

http://sequelize.readthedocs.org/en/rtd/docs/migrations/

i assume i need to re-invent the wheel and create an umzug task?

**Comment by janmeier** [comment] 2015-08-09 10:58
Duplicate of https://github.com/sequelize/sequelize/issues/3926#issuecomment-129127151

**Closed by janmeier** 2015-08-09 10:58 UTC
