### ISSUE TITLE
Add a cassandra dialect

### ISSUE THREAD

**Issue by kimgeorgesb** [sequelize/sequelize#5563] opened 2016-03-10 03:52 UTC
Adding support for a cassandra dialect has been discussed by the official nodejs driver team:
[Datastax NODEJS-144 Issue](https://datastax-oss.atlassian.net/browse/NODEJS-144)

There's currently no mature ORM's for cassandra and it's a major hurdle to adoption. The core functionality of sequelize solves many of the issues with the existing driver.

**Comment by mickhansen** [comment] 2016-03-10 08:31
We're not looking to support any non SQL DBs.
Most of our codebase is built around generating SQL queries.

**Comment by mickhansen** [comment] 2016-03-10 08:32
Ah it looks like Cassandra has some pseudo-sql, maybe it can work.

**Comment by janmeier** [comment] 2016-03-10 08:44
Yeah, it looks to me like CQL is close enough to SQL that we could integrate it into sequelize without too many changes. 

We would love to provide help and advice for creating a cassandra dialect, but no-one from the core team has time to do it

**Comment by kimgeorgesb** [comment] 2016-03-10 11:01
Yeah after looking at the other ORM solutions available they mostly all follow the MongoDB approach of making the inserts look like documents however the cassandra database structure is much closer to a relational db than a document based NoSQL db  in my opinion. After using the official drivers for a week I got really frustrated. Simple stuff like converting from snake case to camel case is a real pain, managing schema migration is a huge pain. Reading the functionality of sequelize it seems to solve a lot of the frustrating issues.

**Comment by kimgeorgesb** [comment] 2016-03-10 11:05
That being said I'd like to work on it, I forked 3.19.3 but should I work in a branch instead so you can pay attention to what I'm doing?

**Comment by janmeier** [comment] 2016-03-10 11:08
Did you fork it on github? It doesn't show up on github. 

It doesn't matter what branch you work on, github hos no problem showing diffs between different repos / branches

**Comment by kimgeorgesb** [comment] 2016-03-10 11:11
I forked it to my organizations repos
https://github.com/sustainablebasis/sequelize/tree/feat-cassandra-dialect

**Comment by kimgeorgesb** [comment] 2016-03-11 12:45
I had a preliminary scan of the code base and this is what I think needs to be done to achieve this feature:

https://github.com/sustainablebasis/sequelize/blob/feat-cassandra-dialect/CQLPROPOSAL.md

Can you guys take a look and let me know if I'm completely off-base with anything.

**Comment by mickhansen** [comment] 2016-03-12 08:13
`/test/unit/cql`

Ideally we would just expand the current tests to match for cassandra aswell.

**Comment by janmeier** [comment] 2016-06-20 13:45
@kimgeorgesb Feel free to continue work and ping us when you have questions, but since this is not a bug report I'll close it - Trying to keep the number of open issues down

**Closed** 2016-06-20 13:44 UTC
Labels: discussion, feature

**Comment by nivapo** [comment] 2016-11-20 06:18
Supporting cassandra dialect is a brilliant idea.Are you planning to bring cassandra support in the distribution.

**Comment by janmeier** [comment] 2016-11-20 07:49
@nivapo the short answer is no. It would have to come from an outside contributor, preferably also someone who would pledge to maintain it after it was merged. 
The core contributors simply don't have the time required or any experience with Cassandra

**Comment by bhaveshgohel** [comment] 2020-10-09 06:25
Hi guys, sorry to bother.
Any cahances we could get Sequelize + Cassandra working in 2020?

Thank you. :pray:

**Comment by vasuchawla** [comment] 2021-02-09 09:35
or maybe in 2021?

**Comment by o-zoaiter-alpha** [comment] 2022-01-26 13:43
or maybe in 2022 ?!

**Comment by ephys** [comment] 2022-01-26 13:55
It's unlikely it's going to be implemented in Sequelize Core. But we're opening the ability to create new dialects so third parties can create implement own.

**Comment by wouterdoublebyte** [comment] 2023-03-28 17:23
2023 The Year??
