### ISSUE TITLE
close() not closing connections?

### ISSUE THREAD

**Issue by ackerdev** [sequelize/sequelize#3216] opened 2015-02-24 19:12 UTC
It seems that Sequelize.prototype.close is not properly terminating all connections. This may be an MSSQL-dialect specific problem.

When executing the following code, the node process does not exit automatically and a connection can be seen still open on the SQL Server.
```js
var Sequelize = require('sequelize');
var sequelize = new Sequelize(/* ... */);

sequelize.query('SELECT 1', { raw: true })
  .then(function(results) {
    /* do something with results */
    sequelize.close();
  });
```

Version: 2.0.3
Dialect: MSSQL

**Comment by janmeier** [comment] 2015-02-25 09:13
There is no dialect specific code for closing connections - sequelize.close simply drains the pool and forces all open connections to close. 

Does the process hang indefinitely, or just for 30 seconds or so?

**Comment by ackerdev** [comment] 2015-02-25 14:57
It appears to hang indefinitely.

With some fiddling in generic-pool.js I enabled logging and it

**Comment by mbroadst** [comment] 2015-03-05 02:43
@mickhansen this can be closed when https://github.com/sequelize/sequelize/pull/3285 is merged

**Closed** 2015-03-05 06:59 UTC

**Comment by shernshiou** [comment] 2015-03-24 17:32
I still face this problem after upgrading to 2.0.5
The connection waited until like 10 seconds before it close down. I have to manually close the connection.

```
var Transactions = require('./models/mssql').Transactions
  , sequelize = require('./models/mssql').sequelize;

Transactions.find(432)
.then(function (transactions) {
  console.log(transactions.get({ plain: true }));
  //sequelize.close();
})
.catch(function (err) {
  console.log(err);
});
```

**Comment by janmeier** [comment] 2015-03-24 19:37
@shernshiou I'm not sure why this is an issue :)?

I just did a test, and the reason for the apearent 'hang' is that process.onexit is not triggered before after 10-15 seconds - this is probably related to pooling, but there is nothing we can do about it

**Comment by mickhansen** [comment] 2015-03-24 19:40
@shernshiou are you expecting it to work without close() or are you saying it doesnt work with close() either?

If you don't want to wait for the pool to drain: use close - We're not changing pooling semantics for cli script usecases.

**Comment by shernshiou** [comment] 2015-03-25 01:26
Thanks @janmeier @mickhansen . I am expecting it to close immediately after query like postgresql and sqlite counterparts. If thats the case, I will manually close it then.

**Comment by cly19891215** [comment] 2015-04-09 07:01
@shernshiou  I face the same problem. Could you show me how to manually close connection immediately after each query?

**Comment by janmeier** [comment] 2015-04-09 07:07
@cly19891215 You can close all open connections on a sequelize instance by calling `sequelize.close`. However, that will completely close all connections, and you wont be able to use the sequelize instance anymore

**Comment by cly19891215** [comment] 2015-04-09 07:10
@janmeier Is there a way to just close the current query connection while not close all connections?

**Comment by janmeier** [comment] 2015-04-09 07:12
Nope that is not possible.

Why do you want to do that though? Sequelize uses connection pooling so there's no reason to force a connection to close, since that would prevent it from being used by the next query

**Comment by cly19891215** [comment] 2015-04-09 07:17
@janmeier Usually Sequelize can handle connections well, but our mysql server do not return timeout for idle connections, it causes connection leak...

**Comment by mickhansen** [comment] 2015-04-09 07:19
@cly19891215 the pool should automatically be releasing idle connections after the idle timeout setting.

**Comment by janmeier** [comment] 2015-04-09 07:19
So when a connection is idle for too long it is never released by mysql? 

you can lower `pool.maxIdleTime`to ensure that connections are released (closed) faster http://docs.sequelizejs.com/en/latest/api/sequelize/

**Comment by cly19891215** [comment] 2015-04-09 07:33
@janmeier  I set pool: {        maxIdleTime: 1    }, but it doesn't work either. If I set dialectOptions: {connectTimeout: 1}, sometimes sequelize catch 'ETIMEOUT' error.

**Comment by cly19891215** [comment] 2015-04-09 07:36
Could I manually close connection for every commit ?

**Comment by janmeier** [comment] 2015-04-09 07:39
`connectionTimeout` is 

>The milliseconds before a timeout occurs during the initial connection to the MySQL server

So that shouldn't be related to what you are trying to do. The reason you get an `ETIMEOUT` with that option is that the server is taking too long to connect

And no, you can't access single connections. The purpose of an ORM is to abstract that kind of stuff away, so we won't expose those kind of details from sequelize. 
On top of that I'm still not quite sure why you want to do that. How are connections being leaked exactly?

**Comment by cly19891215** [comment] 2015-04-09 09:53
@janmeier because tcp connection is ESTABLISHED status, and it's increase with sequelize query.

**Comment by janmeier** [comment] 2015-04-09 11:13
@cly19891215 But when the connection becomes idle for too long it will be closed and so will the TCP connection. That happens automatically, and you don't have to do anything about it

**Comment by cly19891215** [comment] 2015-04-10 02:14
@janmeier The problem is, even if I config the config.pool =  pool: { maxConnections: 10,    minConnections: 0,  maxIdleTime: 10  }, a lot of tcp connections keep status 'ESTABLISHED', and reach the system FD limit about 1000. Then I cannot query any data from mysql.

**Comment by janmeier** [comment] 2015-04-10 06:46
So you are saying that tcp connections are not being properly released by node-mysql / sequelize? I have never heard of anything similar so that sounds very weird. 

Can you perhaps provide some kind of test case to replicate the problem? Preferably in a new issue

**Comment by cly19891215** [comment] 2015-04-10 11:22
@janmeier @mickhansen  Thanks for your responses.

By adding debug log, I figure out the problem is caused by node-mysql client.end() never calls callback function, so connections are always hang. That means our MySQL server is not forwarding the ending FIN-ACK handshakes. 

In the function ConnectionManager.prototype.disconnect, I replace the connection.end() with  connection.destroy(). All the connections are released correctly. However, it's not a graceful ending.

**Comment by janmeier** [comment] 2015-04-10 11:29
Seems like you need to open an issue with https://github.com/felixge/node-mysql/, if you can create a self contained example.

Calling `connection.destroy` is not an option for sequelize, we want to close the connection as cleanly as possibel

**Comment by jhansen-tt** [comment] 2015-04-24 19:18
I'm seeing the same issue using postgres here so I don't think it's a db-specific issue.

**Comment by janmeier** [comment] 2015-04-24 19:19
@jhansen-tt Please describe your issue in more detail then - What's the specific issues that you are seing?

**Comment by jhansen-tt** [comment] 2015-04-24 19:22
This is what my process._getActiveHandles() returns about 1 second after I call sequelize.close():

[ { _connecting: false,
    _hadError: false,
    _handle:
     { fd: 19,
       reading: true,
       owner: [Circular],
       onread: [Function: onread],
       onconnection: null,
       writeQueueSize: 0 },
    _parent: null,
    _host: 'db-server',
    _readableState:
     { objectMode: false,
       highWaterMark: 16384,
       buffer: [],
       length: 0,
       pipes: null,
       pipesCount: 0,
       flowing: true,
       ended: false,
       endEmitted: false,
       reading: true,
       sync: false,
       needReadable: true,
       emittedReadable: false,
       readableListening: false,
       defaultEncoding: 'utf8',
       ranOut: false,
       awaitDrain: 0,
       readingMore: false,
       decoder: null,
       encoding: null,
       resumeScheduled: false },
    readable: true,
    domain: null,
    _events:
     { end: [Object],
       finish: [Function: onSocketFinish],
       _socketEnd: [Function: onSocketEnd],
       connect: [Object],
       data: [Function],
       error: [Function],
       close: [Function],
       drain: [Function] },
    _maxListeners: undefined,
    _writableState:
     { objectMode: false,
       highWaterMark: 16384,
       needDrain: false,
       ending: false,
       ended: false,
       finished: false,
       decodeStrings: false,
       defaultEncoding: 'utf8',
       length: 0,
       writing: false,
       corked: 0,
       sync: false,
       bufferProcessing: false,
       onwrite: [Function],
       writecb: null,
       writelen: 0,
       bufferedRequest: null,
       lastBufferedRequest: null,
       pendingcb: 0,
       prefinished: false,
       errorEmitted: false },
    writable: true,
    allowHalfOpen: false,
    destroyed: false,
    bytesRead: 1965,
    _bytesDispatched: 14,
    _pendingData: null,
    _pendingEncoding: '',
    read: [Function],
    _consuming: true,
    _idleNext: null,
    _idlePrev: null,
    _idleTimeout: -1 },
  { '0': [Function: listOnTimeout],
    _idleNext: [Circular],
    _idlePrev: [Circular],
    msecs: 500 } ]

I'm not sure what else to try to give more feedback.

**Comment by janmeier** [comment] 2015-04-24 19:25
Sorry if I'm being completely ignorant here, but I have no idea what `_getActiveHandles` does, and its not in the public API.

What are your pool settings?
Does the process seem to hang indefinitely?

**Comment by jhansen-tt** [comment] 2015-04-24 19:27
_getActiveHandles is a way to show the processes that are keeping node from shutting down.  It's definitely a sequelize process, so there's got to be an issue in sequelize that is not shutting down.

I'm using default pool settings.  Should I try something else?  The process hangs for probably a couple minutes, then exits.

**Comment by janmeier** [comment] 2015-04-24 19:35
Hmm, can you try setting `pool.log` to true, and see when pool.drain and destroyAllNow are called?

**Comment by janmeier** [comment] 2015-04-24 19:38
Actually, it seems we are not passing that parameter down - try going into dialects/abstract/connection-manager and setting log: true manually there around line 80

**Comment by jhansen-tt** [comment] 2015-04-24 19:40
These show up right when I call close:

INFO pool sequelize-connection - draining
INFO pool sequelize-connection - force destroying all objects

But the process still lingers with the node.js handles given above.  I'm still waiting to see if anything else prints when it finally closes...

**Comment by janmeier** [comment] 2015-04-24 19:46
force destroying should be the last thing that's printed.

From what I can see its not sequelize objects, but pg connection objects that are preventing the process from shutting down.

Not sure what more we can do - we are calling `.end` on all connections, which should close them immediately. 

Does the same happen if you use the pg library directly?

**Comment by jhansen-tt** [comment] 2015-04-24 19:59
This also happens when I use pg directly... I guess I'll have to take it up with them.  Funny how both db libraries would have a very similar issue.

**Comment by omeryttnc** [comment] 2024-08-30 00:46
i am still having same issue is there anyone found a solution

**Comment by joshsmonta** [comment] 2025-02-13 08:28
This issue still seems to be a problem.
