### ISSUE TITLE
[Hook] Can't set variable value of hook afterCreate

### ISSUE THREAD

**Issue by tindecken** [sequelize/sequelize#9733] opened 2018-07-28 15:27 UTC
Can't set variable value of hook afterCreate

## What are you doing?

I have Model: Category as below:
```js
'use strict';

module.exports = (sequelize, DataTypes) => {
  var Category = sequelize.define('Category', {
    name: {
      type: DataTypes.STRING,
      allowNull: false,
      unique: true
    },
    description: DataTypes.STRING,
    type: {
      type: DataTypes.STRING,
      allowNull: true,
      defaultValue: 'Category'
    },
    status: {
      type: DataTypes.ENUM('NORUN', 'PASS', 'FAIL', 'READYTORUN','RUNNING', 'PARTIAL'),
      defaultValue: 'NORUN',
      allowNull: false
    },
    refId: {
      type: DataTypes.STRING,
      allowNull: true,
      defaultValue: "category_"
    }
  },{ 
    underscored: true, freezeTableName: true 
  });
  Category.afterCreate((category, options) => {
    console.log('------------------------------START--------------------------------------')
    console.log('ID', category.id)
    console.log('RefId', category.refId)
    category.refId = "category_" + category.id
    console.log('------------------------------END-------------------------------------')
  })
  Category.associate = function(models) {
    Category.hasMany(models.TestSuite, {as: 'TestSuite', onDelete: 'cascade'})
  };
  return Category;
};
```
## What do you expect to happen?
RefId = 'category_' + id

![1](https://user-images.githubusercontent.com/4727197/43357980-5b03a16a-9282-11e8-9bf3-7f3577198b81.png)

## What is actually happening?
Can't automatic set refId as expectation

![2](https://user-images.githubusercontent.com/4727197/43357984-6132474e-9282-11e8-868f-3a5a7edda0ea.png)

__Dialect: postgres
__Dialect version:__ XXX
__Database version: PostgreSQL 10.3, compiled by Visual C++ build 1800, 64-bit
__Sequelize version: 4.37.6
__Tested with latest release: Yes - 4.38.0

**Comment by sushantdhiman** [comment] 2018-07-30 15:36
`afterCreate` create means it will return record after creating it, so if you change anything in this hook it wont matter as this hook is executed after record has been created.

At the time of actual create you are not passing `refId` any value, so default `category_` is used.

Looks like you need `category.id` to generate `refId`, so this can't be achieved in both before and after hook. I suggest a custom method which you should call after `category` is created. Also `refId` just look duplicate of what `categeory.id` with a prefix.

I suggest rethink your approach, you are trying to implement some sort of FK relationship with custom valued string based keys with poor normalization, I would suggest to just go with plain simple auto incremented integer and link `category.id` with other table

--------------------------------------
--------------------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396

**Closed by sushantdhiman** 2018-07-30 15:36 UTC
