### ISSUE TITLE
Not able to generate query with nested where clause

### ISSUE THREAD

**Issue by rjmunhoz** [sequelize/sequelize#8028] opened 2017-07-28 21:04 UTC
## What you are doing?
I've got a database with entities that follow this hierarchy:
Exam -> Localizer -> Location -> Company -> Group

They are defined as follows:

Exam
```js
module.exports = (sequelize, DataTypes) => {
  const Exam = sequelize.define('Exam', {
    id: {
      type: DataTypes.INTEGER,
      field: 'cd_contas_nota_exame',
      primaryKey: true
    },
    execution_date: {
      type: DataTypes.DATE,
      field: 'dt_exame'
    },
    creation_date: {
      type: DataTypes.DATE,
      field: 'dt_insercao'
    }
  }, {
    tableName: 'tb_contas_nota_exame',
    timestamps: false
  })

  Exam.associate = models => {
    Exam.belongsTo(models.Localizer, {
      as: 'localizer',
      foreignKey: 'cd_lotacao',
      timestamps: false
    })
  }

  return Exam
}
```

Localizer
```js
module.exports = (sequelize, DataTypes) => {
  const Localizer = sequelize.define('Localizer', {
    id: {
      type: DataTypes.INTEGER,
      field: 'cd_lotacao',
      primaryKey: true
    }
  }, {
    tableName: 'tb_lotacao',
    timestamps: false
  })

  Localizer.associate = models => {
    Localizer.belongsTo(models.Location, {
      as: 'location',
      foreignKey: 'cd_localidade',
      timestamps: false
    })
  }

  return Localizer
}
```

Location
```js
module.exports = (sequelize, DataTypes) => {
  const Location = sequelize.define('Location', {
    id: {
      type: DataTypes.INTEGER,
      field: 'cd_localidade',
      primaryKey: true
    },
    description: {
      type: DataTypes.STRING,
      field: 'ds_localidade'
    }
  }, {
    tableName: 'tb_localidade',
    timestamps: false
  })

  Location.associate = models => {
    Location.belongsTo(models.Company, {
      as: 'company',
      foreignKey: 'cd_pessoa',
      timestamps: false
    })

    Location.hasMany(models.Localizer, {
      as: 'localizer',
      foreignKey: 'cd_localidade',
      timestamps: false
    })
  }

  return Location
}
```

Company
```js
module.exports = (sequelize, DataTypes) => {
  const Company = sequelize.define('Company', {
    id: {
      type: DataTypes.INTEGER,
      field: 'cd_pessoa',
      primaryKey: true
    },
    name: {
      type: DataTypes.STRING,
      field: 'nm_razao_social'
    },
    cnpj: {
      type: DataTypes.STRING,
      field: 'nr_cnpj'
    }
  }, {
    tableName: 'tb_pessoa_juridica',
    timestamps: false
  })

  Company.associate = models => {
    Company.belongsToMany(models.Group, {
      as: 'group',
      through: 'tb_pessoa_cliente',
      foreignKey: 'cd_pessoa',
      timestamps: false
    })

    Company.hasMany(models.Location, {
      as: 'locations',
      foreignKey: 'cd_pessoa',
      timestamps: false
    })
  }

  return Company
}
```

Group
```js
module.exports = (sequelize, DataTypes) => {
  const Group = sequelize.define('Group', {
    id: {
      type: DataTypes.INTEGER,
      field: 'cd_cliente',
      primaryKey: true
    },
    name: {
      type: DataTypes.STRING,
      field: 'nm_cliente'
    }
  }, {
    tableName: 'tb_cliente',
    timestamps: false
  })

  Group.associate = models => {
    Group.belongsToMany(models.Company, {
      as: 'companies',
      through: 'tb_pessoa_cliente',
      foreignKey: 'cd_cliente',
      timestamps: false
    })
  }

  return Group
}
```

## What do you expect to happen?
When I query the Exam model as shown below, it generates something like

```sql
SELECT *
FROM tb_contas_nota_exame Exam
  JOIN tb_lotacao Localizer ON Exam.cd_lotacao = Localizer.cd_lotacao
  JOIN tb_localidade Location ON Localizer.cd_localidade = Location.cd_localidade
  JOIN tb_pessoa_cliente ON Location.cd_pessoa = tb_pessoa_cliente.cd_pessoa
  JOIN tb_cliente [Group] ON tb_pessoa_cliente.cd_cliente = [Group].cd_cliente
WHERE [Group].cd_cliente = 1
```

Of course, with column names, `LEF OUTER JOIN`s and everything

## What is actually happening?
When I query the Exams model with

```js
const query = {
    limit,
    offset,
    include: [{
      model: db.Guide,
      as: 'guide'
    }, {
      model: db.Worker,
      as: 'worker'
    }, {
      model: db.ExamDomain,
      as: 'domain'
    }, {
      model: db.Localizer,
      as: 'localizer',
      include: [{
        model: db.Location,
        as: 'location',
        include: [{
          model: db.Company,
          as: 'company',
          include: [{
            model: db.Group,
            as: 'group'
          }]
        }]
      }]
    }]
  }

query.where = { '$localizer.location.company.group.cd_cliente$': 1 }

return db.Exam.findAll(query)
```

It generates

```sql
SELECT
  [Exam].*,
  [guide].[cd_prontuario]                                               AS [guide.id],
  [guide].[cd_tipo_exame_medico]                                        AS [guide.type],
  [worker].[cd_contas_colaborador]                                      AS [worker.id],
  [worker].[ds_pessoa]                                                  AS [worker.name],
  [domain].[cd_exame]                                                   AS [domain.id],
  [domain].[ds_exame]                                                   AS [domain.examClass],
  [localizer].[cd_lotacao]                                              AS [localizer.id],
  [localizer].[cd_localidade]                                           AS [localizer.cd_localidade],
  [localizer->location].[cd_localidade]                                 AS [localizer.location.id],
  [localizer->location].[ds_localidade]                                 AS [localizer.location.description],
  [localizer->location].[cd_pessoa]                                     AS [localizer.location.cd_pessoa],
  [localizer->location->company].[cd_pessoa]                            AS [localizer.location.company.id],
  [localizer->location->company].[nm_razao_social]                      AS [localizer.location.company.name],
  [localizer->location->company].[nr_cnpj]                              AS [localizer.location.company.cnpj],
  [localizer->location->company->group].[cd_cliente]                    AS [localizer.location.company.group.id],
  [localizer->location->company->group].[nm_cliente]                    AS [localizer.location.company.group.name],
  [localizer->location->company->group->tb_pessoa_cliente].[cd_pessoa]  AS [localizer.location.company.group.tb_pessoa_cliente.cd_pessoa],
  [localizer->location->company->group->tb_pessoa_cliente].[cd_cliente] AS [localizer.location.company.group.tb_pessoa_cliente.cd_cliente]
FROM (SELECT TOP 100 PERCENT
        [Exam].[cd_contas_nota_exame] AS [id],
        [Exam].[dt_exame]             AS [execution_date],
        [Exam].[dt_insercao]          AS [creation_date],
        [Exam].[cd_prontuario],
        [Exam].[cd_contas_colaborador],
        [Exam].[cd_exame],
        [Exam].[cd_lotacao]
      FROM (SELECT TOP 1 *
            FROM (SELECT
                    ROW_NUMBER()
                    OVER (
                      ORDER BY [cd_contas_nota_exame] ) AS row_num,
                    *
                  FROM [tb_contas_nota_exame] AS [Exam]) AS [Exam]
            WHERE row_num > 1) AS [Exam]
      WHERE [localizer->location->company->group].[cd_cliente] = 1) AS [Exam]
  LEFT OUTER JOIN [tb_contas_prontuario] AS [guide]
    ON [Exam].[cd_prontuario] = [guide].[cd_prontuario]
  LEFT OUTER JOIN [tb_contas_colaborador] AS [worker]
    ON [Exam].[cd_contas_colaborador] = [worker].[cd_contas_colaborador]
  LEFT OUTER JOIN [tb_cred_exames_amb] AS [domain]
    ON [Exam].[cd_exame] = [domain].[cd_exame]
  LEFT OUTER JOIN [tb_lotacao] AS [localizer]
    ON [Exam].[cd_lotacao] = [localizer].[cd_lotacao]
  LEFT OUTER JOIN [tb_localidade] AS [localizer->location]
    ON [localizer].[cd_localidade] = [localizer->location].[cd_localidade]
  LEFT OUTER JOIN [tb_pessoa_juridica] AS [localizer->location->company]
    ON [localizer->location].[cd_pessoa] = [localizer->location->company].[cd_pessoa]
  LEFT OUTER JOIN ([tb_pessoa_cliente] AS [localizer->location->company->group->tb_pessoa_cliente] INNER JOIN
    [tb_cliente] AS [localizer->location->company->group]
      ON [localizer->location->company->group].[cd_cliente] =
         [localizer->location->company->group->tb_pessoa_cliente].[cd_cliente])
    ON [localizer->location->company].[cd_pessoa] = [localizer->location->company->group->tb_pessoa_cliente].[cd_pessoa]
```

Wich gives me `The multi-part identifier \"localizer->location->company->group.cd_cliente\" could not be bound.`, that is correct, since, in the scope this identifier is used, it does not exist

__Dialect:__ mssql
__Database version:__ Microsoft SQL Server 2008 (SP3) - 10.0.5538.0
__Sequelize version:__ 4.4.2

**Comment by lerit** [comment] 2018-03-26 02:55
yes,i face same problem in microsoft sql server

**Comment by sushantdhiman** [comment] 2018-04-11 04:17
Duplicate of #8475

**Closed by sushantdhiman** 2018-04-11 04:17 UTC
Labels: bug, mssql
