### ISSUE TITLE
[Bug] Ordering when filtering on embedded objects with belongsToMany association

### ISSUE THREAD

**Issue by porzioj** [sequelize/sequelize#6621] opened 2016-09-22 13:44 UTC
Hi guys,

I don't really know if it is a bug or my way to use Sequelize which is not good but let's see if someone can help me :-).
I have a structure defined as follow:

- Procedure
    - Patient (belongsTo)
        - Clinic (belongsTo)
    - Document (belongsToMany)

So using the get method (with structure described in include, with filtering on clinic id) it is not possible to get my list ordered by patient's name.
If I remove the filter everything run well.
Please find the test case: 

```js
var Sequelize = require('sequelize');

var USER = 'YOUR_USER';
var PASSWD = 'YOUR_PASSWD';
var DB_NAME = 'YOUR_DBNAME';
var HOST = "YOUR_HOSTNAME";

describe('Bug when filtering with include', function() {

    var self=this;

    self._createStructure=function () {

        self.Clinic = self.sequelize.define('Clinic', {
            label: Sequelize.STRING
        });

        self.Patient = self.sequelize.define('Patient', {
            firstname: Sequelize.STRING
        });

        self.Procedure = self.sequelize.define('Procedure', {
            name: Sequelize.STRING
        });

        self.Document = self.sequelize.define('Document', {
            name: Sequelize.STRING
        });

        self.Procedure.belongsTo(
            self.Patient
        );

        self.Patient.belongsTo(
            self.Clinic
        );

        self.Procedure.belongsToMany(
            self.Document, {
                through: 'procedures_has_documents'
            }
        );

        self.Document.belongsToMany(
            self.Procedure, {
                through: 'procedures_has_documents'
            }
        );
    };

    self._populateDatas = function (done) {
        self.Clinic.create({
            name:"Clinic Death Star"
        }).then(function (clinic2) {
            self.Patient.create({
                firstname: "John",
                lastname: "Doe",
                "clinic_id": clinic2.id
            }).then(function (patient2) {
                self.Procedure.create({
                    name: "MyFirstProcedure"
                }).then(function (procedure1) {
                    procedure1.setPatient(patient2);
                    done();
                });
            });
        });
    };

    before(function(done) {
        self.sequelize = new Sequelize(
            DB_NAME,
            USER,
            PASSWD,
            {
                "host": HOST,
                "dialect":"mysql",
                "logging":false
            }
        );

        self._createStructure();

        self.options={
            include:[
                {
                    model : self.Patient,
                    as: "Patient",
                    include: [{
                        where: {id:{$in:[2]}},
                        model: self.Clinic,
                        as: "Clinic"
                    }]
                },
                {
                    model : self.Document
                }
            ]
        };

        self.sequelize.sync({ force: true }).then(function() {
            self._populateDatas(done);
        });
    });

    it('should sort by Procedure -> name without limit', function(done) {
        self.Procedure.findAll({
            order:"name",
            limit:6,
            include:self.options.include
        }).then(function () {
            done();
        }, function (error) {
            console.log(error);
        });
    });

    it('should sort by Procedure -> name with limit', function(done) {
        self.Procedure.findAll({
            order:"name",
            limit:6,
            include:self.options.include
        }).then(function () {
            done();
        }, function (error) {
            console.log(error);
        });
    });

    it('should sort by Procedure -> Patient -> Clinic -> label without limit', function(done) {
        self.Procedure.findAll({
            order:[[self.Patient,self.Clinic,"label","ASC"]],
            include:self.options.include
        }).then(function () {
            done();
        }, function (error) {
            console.log(error);
        });
    });

    it('should sort by Procedure -> Patient -> Clinic -> label with limit', function(done) {
        self.Procedure.findAll({
            order:[[self.Patient,self.Clinic,"label","ASC"]],
            limit:6,
            include:self.options.include
        }).then(function () {
            done();
        }, function (error) {
            console.log(error);
        });
    });

    it('if should sort by Procedure -> Patient -> firstname without limit', function(done) {
        self.Procedure.findAll({
            order:[[self.Patient,"firstname","DESC"]],
            include:self.options.include
        }).then(function () {
            done();
        }, function (error) {
            console.log(error);
        });
    });

    it('if should sort by Procedure -> Patient -> firstname with limit', function(done) {
        self.Procedure.findAll({
            order:[[self.Patient,"firstname","DESC"]],
            limit:6,
            include:self.options.include
        }).then(function () {
            done();
        }, function (error) {
            console.log(error);
        });
    });
});
```

Do not hesitate if you need more information from my side.

Thanks in advance for you help.

__Dialect:__ mysql
__Database version:__ XXX
__Sequelize version:__ 3.24.3

**Comment by felixfbecker** [comment] 2016-09-22 13:50
The expected behavior is clear, but what is the actual behavior? An error?

**Comment by porzioj** [comment] 2016-09-22 14:04
For now the test "if should sort by Procedure -> Patient -> firstname with limit" is failing:
```js
{ [SequelizeDatabaseError: ER_BAD_FIELD_ERROR: Unknown column 'Patient.firstname' in 'order clause']
  name: 'SequelizeDatabaseError',
  message: 'ER_BAD_FIELD_ERROR: Unknown column \'Patient.firstname\' in \'order clause\'',
  parent: 
   { [Error: ER_BAD_FIELD_ERROR: Unknown column 'Patient.firstname' in 'order clause']
     code: 'ER_BAD_FIELD_ERROR',
     errno: 1054,
     sqlState: '42S22',
     index: 0,
     sql: 'SELECT `Procedure`.*, `Patient.Clinic`.`id` AS `Patient.Clinic.id`, `Patient.Clinic`.`label` AS `Patient.Clinic.label`, `Patient.Clinic`.`createdAt` AS `Patient.Clinic.createdAt`, `Patient.Clinic`.`updatedAt` AS `Patient.Clinic.updatedAt`, `Documents`.`id` AS `Documents.id`, `Documents`.`name` AS `Documents.name`, `Documents`.`createdAt` AS `Documents.createdAt`, `Documents`.`updatedAt` AS `Documents.updatedAt`, `Documents.procedures_has_documents`.`createdAt` AS `Documents.procedures_has_documents.createdAt`, `Documents.procedures_has_documents`.`updatedAt` AS `Documents.procedures_has_documents.updatedAt`, `Documents.procedures_has_documents`.`ProcedureId` AS `Documents.procedures_has_documents.ProcedureId`, `Documents.procedures_has_documents`.`DocumentId` AS `Documents.procedures_has_documents.DocumentId` FROM (SELECT `Procedure`.`id`, `Procedure`.`name`, `Procedure`.`createdAt`, `Procedure`.`updatedAt`, `Procedure`.`PatientId`, `Patient`.`id` AS `Patient.id`, `Patient`.`firstname` AS `Patient.firstname`, `Patient`.`createdAt` AS `Patient.createdAt`, `Patient`.`updatedAt` AS `Patient.updatedAt`, `Patient`.`ClinicId` AS `Patient.ClinicId` FROM `Procedures` AS `Procedure` LEFT OUTER JOIN `Patients` AS `Patient` ON `Procedure`.`PatientId` = `Patient`.`id` LIMIT 6) AS `Procedure` INNER JOIN `Clinics` AS `Patient.Clinic` ON `Patient.ClinicId` = `Patient.Clinic`.`id` AND `Patient.Clinic`.`id` IN (2) LEFT OUTER JOIN (`procedures_has_documents` AS `Documents.procedures_has_documents` INNER JOIN `Documents` AS `Documents` ON `Documents`.`id` = `Documents.procedures_has_documents`.`DocumentId`) ON `Procedure`.`id` = `Documents.procedures_has_documents`.`ProcedureId` ORDER BY `Patient`.`firstname` DESC;' },
  original: 
   { [Error: ER_BAD_FIELD_ERROR: Unknown column 'Patient.firstname' in 'order clause']
     code: 'ER_BAD_FIELD_ERROR',
     errno: 1054,
     sqlState: '42S22',
     index: 0,
     sql: 'SELECT `Procedure`.*, `Patient.Clinic`.`id` AS `Patient.Clinic.id`, `Patient.Clinic`.`label` AS `Patient.Clinic.label`, `Patient.Clinic`.`createdAt` AS `Patient.Clinic.createdAt`, `Patient.Clinic`.`updatedAt` AS `Patient.Clinic.updatedAt`, `Documents`.`id` AS `Documents.id`, `Documents`.`name` AS `Documents.name`, `Documents`.`createdAt` AS `Documents.createdAt`, `Documents`.`updatedAt` AS `Documents.updatedAt`, `Documents.procedures_has_documents`.`createdAt` AS `Documents.procedures_has_documents.createdAt`, `Documents.procedures_has_documents`.`updatedAt` AS `Documents.procedures_has_documents.updatedAt`, `Documents.procedures_has_documents`.`ProcedureId` AS `Documents.procedures_has_documents.ProcedureId`, `Documents.procedures_has_documents`.`DocumentId` AS `Documents.procedures_has_documents.DocumentId` FROM (SELECT `Procedure`.`id`, `Procedure`.`name`, `Procedure`.`createdAt`, `Procedure`.`updatedAt`, `Procedure`.`PatientId`, `Patient`.`id` AS `Patient.id`, `Patient`.`firstname` AS `Patient.firstname`, `Patient`.`createdAt` AS `Patient.createdAt`, `Patient`.`updatedAt` AS `Patient.updatedAt`, `Patient`.`ClinicId` AS `Patient.ClinicId` FROM `Procedures` AS `Procedure` LEFT OUTER JOIN `Patients` AS `Patient` ON `Procedure`.`PatientId` = `Patient`.`id` LIMIT 6) AS `Procedure` INNER JOIN `Clinics` AS `Patient.Clinic` ON `Patient.ClinicId` = `Patient.Clinic`.`id` AND `Patient.Clinic`.`id` IN (2) LEFT OUTER JOIN (`procedures_has_documents` AS `Documents.procedures_has_documents` INNER JOIN `Documents` AS `Documents` ON `Documents`.`id` = `Documents.procedures_has_documents`.`DocumentId`) ON `Procedure`.`id` = `Documents.procedures_has_documents`.`ProcedureId` ORDER BY `Patient`.`firstname` DESC;' },
  sql: 'SELECT `Procedure`.*, `Patient.Clinic`.`id` AS `Patient.Clinic.id`, `Patient.Clinic`.`label` AS `Patient.Clinic.label`, `Patient.Clinic`.`createdAt` AS `Patient.Clinic.createdAt`, `Patient.Clinic`.`updatedAt` AS `Patient.Clinic.updatedAt`, `Documents`.`id` AS `Documents.id`, `Documents`.`name` AS `Documents.name`, `Documents`.`createdAt` AS `Documents.createdAt`, `Documents`.`updatedAt` AS `Documents.updatedAt`, `Documents.procedures_has_documents`.`createdAt` AS `Documents.procedures_has_documents.createdAt`, `Documents.procedures_has_documents`.`updatedAt` AS `Documents.procedures_has_documents.updatedAt`, `Documents.procedures_has_documents`.`ProcedureId` AS `Documents.procedures_has_documents.ProcedureId`, `Documents.procedures_has_documents`.`DocumentId` AS `Documents.procedures_has_documents.DocumentId` FROM (SELECT `Procedure`.`id`, `Procedure`.`name`, `Procedure`.`createdAt`, `Procedure`.`updatedAt`, `Procedure`.`PatientId`, `Patient`.`id` AS `Patient.id`, `Patient`.`firstname` AS `Patient.firstname`, `Patient`.`createdAt` AS `Patient.createdAt`, `Patient`.`updatedAt` AS `Patient.updatedAt`, `Patient`.`ClinicId` AS `Patient.ClinicId` FROM `Procedures` AS `Procedure` LEFT OUTER JOIN `Patients` AS `Patient` ON `Procedure`.`PatientId` = `Patient`.`id` LIMIT 6) AS `Procedure` INNER JOIN `Clinics` AS `Patient.Clinic` ON `Patient.ClinicId` = `Patient.Clinic`.`id` AND `Patient.Clinic`.`id` IN (2) LEFT OUTER JOIN (`procedures_has_documents` AS `Documents.procedures_has_documents` INNER JOIN `Documents` AS `Documents` ON `Documents`.`id` = `Documents.procedures_has_documents`.`DocumentId`) ON `Procedure`.`id` = `Documents.procedures_has_documents`.`ProcedureId` ORDER BY `Patient`.`firstname` DESC;' }
```

**Comment by felixfbecker** [comment] 2016-09-22 14:48
Could this be a duplicate of https://github.com/sequelize/sequelize/issues/6420?

**Comment by porzioj** [comment] 2016-09-22 15:46
Maybe it is linked in some points: 

- In 6621 case removing the where clause solve the problem, it does not in 6420.
- In both case removing limit option solve the problem 

I found some interesting things analyzing the #6420, I will put that on it.

**Comment by felixfbecker** [comment] 2016-09-22 16:06
I did not try to remove the `where` because my query would be useless without `where`, so I think it is the same bug.

**Comment by porzioj** [comment] 2016-09-22 16:10
I agree, in my case too removing the were would be useless, the goal was just to try to to point what could be the problem :-)
In any case I think you can merge this bug in #6420 as it looks like the same issue.

**Closed** 2016-09-22 16:17 UTC
Labels: duplicate
