### ISSUE TITLE
Sequelize hangs on new connect / support node 14

### ISSUE THREAD

**Issue by glassdimlygr** [sequelize/sequelize#12274] opened 2020-05-18 20:15 UTC
## Issue Description
When using node `14`, sequelize connection to postresql database hangs because `lib/connection.js` fails to emit event  with `this.emit('connect')`, a function derived from nodejs core `events` library.

### Workaround
Downgrade to node `12`.

### Proposed solution
(Eventually) upgrade `lib/connection.js` to support node `14`

**Comment by sushantdhiman** [comment] 2020-05-19 04:38
Please follow the issue template next time, Duplicate of https://github.com/sequelize/sequelize/issues/12158

**Closed by sushantdhiman** 2020-05-19 04:38 UTC
