### ISSUE TITLE
Timestamp format

### ISSUE THREAD

**Issue by helloqhx** [sequelize/sequelize#6755] opened 2016-10-26 08:11 UTC
Where to set the timestamp format function, when i select with **raw** option, it is not my want format.
any one can help?

**Comment by helloqhx** [comment] 2016-10-26 08:12
I found some walk around solutions. But I think it should be config in the model or other places.

**Comment by janmeier** [comment] 2016-10-26 09:10
Timestamps are converted to javascript dates - This is done by the underlying driver, not by sequelize.

When you console.log a date you will _ALWAYS_  see it in your local timezone. Thats just how v8 works.

Please be more specific. What data do you have in the database, what code do you run, what do you expect to see, and what do you actually see? (basically what the template you removed told you do do :) )

**Comment by helloqhx** [comment] 2016-10-26 10:07
@janmeier 
I know timestamps are all converted to Dates. I mean when I select rows from db with the RAW option, I want a configuration that can help me format the date. Instead this stuff must be done in myself.

**Comment by janmeier** [comment] 2016-10-26 10:35
Please show a concrete example ( [SSCCE](HTTP://SSCCE.ORG/))

**Comment by felixfbecker** [comment] 2016-10-26 10:47
Formatting dates is out of scope for an ORM - we give you a `Date` object and you can format it with libraries like http://momentjs.com/ if you wish.

**Closed by felixfbecker** 2016-10-26 10:47 UTC

**Comment by damianobarbati** [comment] 2017-11-01 12:40
@felixfbecker I'm seeing different behaviour between sqlite and postgres probably caused by underlying drivers/adapters.
When querying sqlite I get timestamps as "string" but on postgres I get "Date" objects: how can I keep it consistent and always have just strings? Getter methods?

**Comment by ccrsky** [comment] 2019-03-07 11:39
> @janmeier
> I know timestamps are all converted to Dates. I mean when I select rows from db with the RAW option, I want a configuration that can help me format the date. Instead this stuff must be done in myself.

you can hack it
```js
Sequelize.DataTypes.mysql.DATE.parse = function parse(value, options) {
  value = value.string();
  if (value === null) {
    return value;
  }
  return new Date(value);
};
```
