### ISSUE TITLE
Sequelize returns a string for decimal types

### ISSUE THREAD

**Issue by raz3r** [sequelize/sequelize#8019] opened 2017-07-27 13:28 UTC
I have a simple model with a DECIMAL column. Whenever I query that model the column is returned as a string rather than a float. Thing is, I am not sure whether the issue is on ExpressJS side (res.json()) or on Sequelize side. Or maybe there's something else I am not aware of.

```js
app.get('/test/list/do', function(req, res) {
	models.test.findAll().then(function(tests) {
		res.json(tests);
	});
});
```

I am using the latest version of Sequelize and ExpressJS along with MySQL 5.7.

**EDIT: I tried logging the model directly in Node and the field was already converted to a string before sending it out. So it must be Sequelize.**

I understand it's probably due to precision issues but I would like to know if there's a away to get a number regardless.

**Comment by andrewmunro** [comment] 2017-07-27 16:39
I have just updated to the latest version of sequelize and started having the same issue. It's returning strings for my decimal data types.

**Comment by andrewmunro** [comment] 2017-07-27 16:50
Seems like upgrading from 3.30.4 to 4.0.0 caused this. Either something in the sequelize 4.0 release or possibly due to switching the dependency from mysql to mysql2?

**Comment by nerdlibfront** [comment] 2017-07-31 09:15
Same here with the current releases of Sequelize (4.4.2) and mysql2 (1.3.6)

**Comment by nerdlibfront** [comment] 2017-07-31 09:22
This is an issue with mysql2 returning decimals as a string to preserve precision:
https://github.com/sequelize/sequelize/issues/7465

If you are sure that your data won't run into precision issues you can set 
`dialectOptions: { decimalNumbers: true }`
when instantiating sequelize.

**Comment by raz3r** [comment] 2017-07-31 13:48
Thank you, that solved my issue 👍

**Comment by andrewmunro** [comment] 2017-07-31 14:01
Fixed for me too. Suggest this workaround is added to here http://docs.sequelizejs.com/manual/tutorial/upgrade-to-v4.html

**Comment by kingjerod** [comment] 2018-02-20 23:34
Setting `dialectOptions: { decimalNumbers: true }` doesn't seem to work for Postgres. Is this a MySQL2 only option?

**Comment by kingjerod** [comment] 2018-04-03 18:25
@deejbee The solution I found:
```
import * as pg from "pg";
// setup your Sequelize instance
pg.types.setTypeParser(1700, parseFloat);
```

1700 corresponds to the Decimal type. Using parseFloat like this is only safe if you know your numbers will be within the valid float range.

**Comment by deejbee** [comment] 2018-04-03 19:19
Thanks for the the quick reply @kiddouk.  I'm not too sure where that code should go though.  I tried it before and after this and several other places but it didn't effect the result so not sure what I'm missing :
```

var sequelize = new Sequelize({
	host: 'localhost',
..etc
});
```

**Comment by deejbee** [comment] 2018-04-04 05:57
Ah,  I'm using 4.37.4 and the fix no longer works.  Am now going through the changes to see why...

**Comment by deejbee** [comment] 2018-04-25 14:53
I finally found a way and ended up doing this with the latest (4.37.6)

`Sequelize.postgres.DECIMAL.parse = function (value) {
	return parseFloat(value);
};`

using setTypeParser() had no effect.

Since I know all my values are currency style decimals there hopefully won't be a problem losing any precision.

**Comment by hellznrg** [comment] 2018-09-21 02:40
Who thought that returning a number as a string was a great idea? "Lets break functionality for millions of projects in order to make a workaround for one random person who cares about the 25th digit after the decimal point." Yep... ok then

**Comment by hellznrg** [comment] 2018-09-21 02:54
This is obviously a problem in Javascript, which doesn't have a decimal type. People who care that much about the zillionth digit after the decimal point will anyway do the conversion to string on the db server end as a workaround. At some point, Decimal may make it into the javascript spec. Until then, lets please leave numbers as numbers and strings as strings.

**Comment by abimelex** [comment] 2018-09-25 14:21
Can't believe this issue is closed. There NEEDS to be an option to get plain decimal numbers also in postgres.

**Comment by nuance-heramb** [comment] 2018-10-25 03:30
As a temporary fix, defining a custom setter also works. It isnt ideal by any means but it works for now!

`
'quantity'     : {
      'type'     : DataTypes.DECIMAL(10, 2),
      'allowNull': true,
      get() { return parseFloat(this.getDataValue('quantity')); }
    }
`

**Comment by weagle08** [comment] 2019-02-01 04:20
Why is this closed? the workarounds are less than ideal for postgres

**Comment by papb** [comment] 2019-08-21 02:11
> Why is this closed? the workarounds are less than ideal for postgres

No idea...

--------

**Suggested workaround**

```js
sequelize.define("user", {
  foo: {
    type: Sequelize.DECIMAL,
    get() {
      // Workaround until sequelize issue #8019 is fixed
      const value = this.getDataValue('foo');
      return value === null ? null : parseFloat(value);
    }
  }
});
```

@everyone If the above workaround is not enough for any of you, please let me know!

**Comment by papb** [comment] 2019-08-21 02:15
Here is a SSCCE for this issue:

```js
const user = sequelize.define("user", { foo: Sequelize.DECIMAL });
(async () => {
  await sequelize.sync({ force: true });
  await user.create({ foo: 12.34 });
  console.log(typeof (await user.findOne()).foo); // string
})();
```

**Comment by maxim-danilov** [comment] 2019-11-28 22:29
How do you guys solve this issue? (postgres)
a) using float instead of decimal for currency is not correct
b) the custom getter can reduce the performance
c) using parseFloat for each math operation makes the code dirty

**Comment by zgr024** [comment] 2020-03-09 05:40
Any fix for Postgres or is this still ongoing?

**Comment by crascher** [comment] 2020-04-11 08:28
Also a problem for me, have mainly decimals in use like this: DataTypes.DECIMAL(10, 2)

My workaround is as mentioned:
Sequelize.postgres.DECIMAL.parse = function (value) { return parseFloat(value); };

Would be nice to have something like this: https://github.com/sequelize/sequelize/issues/4893#issuecomment-171592939

**Comment by Smmw** [comment] 2020-04-12 01:55
@papb just letting you know, when you use `{raw: true}` you getter function you mentioned is no longer work.

`Sequelize version: 5.21.6`

**Comment by Leithal3** [comment] 2020-05-06 04:31
I would back up @EyePulp and recommend anyone running into this issue to have a look at the related issue https://github.com/sequelize/sequelize/issues/9074#issue-298501356 .

That was where I was finally able to find a workaround that works for me at this point in time. If using TypeScript have a look at the following comment - https://github.com/sequelize/sequelize/issues/9074#issuecomment-624433890

Currently working on Sequelize v5.21

**Comment by gorydev** [comment] 2020-08-14 21:15
using Sequelize.cast(val, 'float') worked for me in postgres and sequelize v5.21.10

**Comment by LuigiMaestrelli** [comment] 2020-08-20 00:11
I'm running Sequelize v6.3.4 and still facing this issue...
For now, this solution is working, but a better and more permanent one will be greate.

> Also a problem for me, have mainly decimals in use like this: DataTypes.DECIMAL(10, 2)
> 
> My workaround is as mentioned:
> Sequelize.postgres.DECIMAL.parse = function (value) { return parseFloat(value); };

**Comment by mariusa** [comment] 2020-08-28 11:49
Same issue with DOUBLE, sequelize 6.x

**Comment by ruankotovich** [comment] 2020-10-23 20:07
> Same issue with DOUBLE, sequelize 6.x

Have you encontered some solution? I am currently using sequelize 5.22.3 and its working just fine.

**Comment by oyanezm** [comment] 2020-12-22 20:31
> > Why is this closed? the workarounds are less than ideal for postgres
> 
> No idea...
> 
> **Suggested workaround**
> 
> ```js
> sequelize.define("user", {
>   foo: {
>     type: Sequelize.DECIMAL,
>     get() {
>       // Workaround until sequelize issue #8019 is fixed
>       const value = this.getDataValue('foo');
>       return value === null ? null : parseFloat(value);
>     }
>   }
> });
> ```
> 
> If the above workaround is not enough for any of you, please let me know!

an extra sugar on this
```ts
get(...args) {
  const value = this.getDataValue(args[0]);
  return value === null ? null : parseFloat(value);
}
```

**Comment by Renan04lima** [comment] 2021-07-21 15:35
if anyone uses `sequelize-typescript` and postgreSQL this is useful <https://www.npmjs.com/package/sequelize-typescript#accessors>

I resolve like this
```ts
@Column
get price(): number {
  return parseFloat(`${this.getDataValue('price')}`);
}

set price(value: number) {
  this.setDataValue('price', value);
}
```
I hope this helped anyone

**Comment by RayKorenRedDot** [comment] 2021-07-28 21:54
Note that this is an issue in version 6.6.2 .
Jest Tests passed with the workaround mentioned above.

**Comment by GautheyValentin** [comment] 2021-11-22 00:05
> if anyone uses `sequelize-typescript` and postgreSQL this is useful https://www.npmjs.com/package/sequelize-typescript#accessors
> 
> I resolve like this
> 
> ```ts
> @Column
> get price(): number {
>   return parseFloat(`${this.getDataValue('price')}`);
> }
> 
> set price(value: number) {
>   this.setDataValue('price', value);
> }
> ```
> 
> I hope this helped anyone

Care, add a check for null value
```ts
  @Column(DataType.DECIMAL(10, 2))
  get price(): number {
    const value = this.getDataValue('price');
    return value === null ? null : parseFloat(value);
  }

  set price(value: number) {
    this.setDataValue('price', value);
  }
```

**Comment by ephys** [comment] 2022-01-06 17:03
I'm collecting Data regarding how to support choosing how a type is represented in JS.

This is what it currently looks like: https://gist.github.com/ephys/50a6a05be7322c64645be716fea6186a#support-for-alternative-js-types

**Comment by ephys** [comment] 2022-04-16 17:14
Removing the `breaking change` label because `DataTypes.DECIMAL` will continue returning strings by default but we plan on letting you choose to unsafely cast it to number if you choose to with https://github.com/sequelize/sequelize/issues/14296

**Comment by ephys** [comment] 2022-10-06 17:48
I'm closing in favor of https://github.com/sequelize/sequelize/issues/14296

**Closed by ephys** 2022-10-06 17:48 UTC
Labels: type: feature, existing workaround

**Comment by riosje** [comment] 2022-10-17 13:22
## For those who still arrives here looking for some solution and information as sequelize version `"^6.3.5"` this is still happening ##

### **MYSQL SOLUTION**
If you're using **MYSQL** all what you need is specify this option in `dialectOptions` parameter:
> dialectOptions: { decimalNumbers: true }

you can find more information here in the [API documentation](https://sequelize.org/api/v6/class/src/sequelize.js~sequelize#instance-constructor-constructor)

---------------------------------------------------------------------------------------------------------
### **Postgresql SOLUTION**

The above solution **doesn't work with Postgresql** so far you have 2 options to workaround this:

**1. Creeate a getter function within each field on every model.**

> **Suggested workaround**
> 
> ```js
> sequelize.define("user", {
>   foo: {
>     type: Sequelize.DECIMAL,
>     get() {
>       // Workaround until sequelize issue #8019 is fixed
>       const value = this.getDataValue('foo');
>       return value === null ? null : parseFloat(value);
>     }
>   }
> });
> ```

**2. Modify the Sequelize datatype in the application bootstrap using a hook.**

```js
const sequelize = new Sequelize(config.configPGSQL.database, config.configPGSQL.username, config.configPGSQL.password, {
  host: config.configPGSQL.host,
  dialect: config.configPGSQL.dialect,
  port: config.configPGSQL.port,
  logging: config.configPGSQL.logging,
  pool: config.configPGSQL.pool,
  dialectOptions: config.configPGSQL.dialectOptions,
  hooks: {
    beforeConnect() {
      console.log("beforeConnect");
      const cloneType = function (t, parseFn) {
        const clone = {};
        for (const name of Object.getOwnPropertyNames(t)) {
          clone[name] = t[name];
        }
        (clone.key = t.key), (clone.types = t.types), (clone.parse = parseFn);
        return clone;
      };
      const dTypes = {
        DECIMAL: cloneType(Sequelize.DataTypes.postgres.DECIMAL, parseFloat),
        INTEGER: cloneType(Sequelize.DataTypes.postgres.INTEGER, v => parseInt(v, 10)),
        BIGINT: cloneType(Sequelize.DataTypes.postgres.BIGINT, v => parseInt(v, 10)),
      };
      this.connectionManager.refreshTypeParser(dTypes);
    },
  },
});
```

[hooks documentation](https://sequelize.org/docs/v6/other-topics/hooks/#default-hooks-on-sequelize-constructor-options)

**Comment by riosje** [comment] 2022-10-17 16:10
Hi @ephys thanks for comment on this and all the effort you put on this awesome project.
as far as I can see there is a lot of confusion over this topic, but here my comments:
your suggestion of use **_DOUBLE_** instead of **_DECIMAL_** works pretty well, sequelize returns the data type as expected (_number_), this works while you don't need a fixed decimal LENGTH.

for example  this approach `DataTypes.DOUBLE(18,4)` PostgresSQL does not support 'DOUBLE PRECISION' with LENGTH, there is where the DECIMAL data type becomes important.

There is multiple discussions on stack over flow where encourage people not to use FLOAT for financial operations, instead of that they suggest the usage of DECIMAL data types.

Maybe all of us who ended up here in this issue trying to bring support to DECIMAL data type on sequelize, have a wrong design of the software or perhaps we have misunderstanding of programming data structures.

Anyway, thank you again @ephys for taking the time and document all those workarounds and POCs, even to answer all those issue comments

**Comment by ephys** [comment] 2022-10-17 22:02
What you said about numeric amounts is exactly what I mean :) you should not use float or double to store numeric amounts, but the JavaScript number type *is* a double (both the SQL double, float, and real, as well as the JS number type are IEEE 754 floating point numbers).

You definitely should use either integers or decimals for that. But representing decimals using the JS number type will lead to the same imprecision issues as if you stored them as doubles in the database.

JavaScript doesn't have a decimal type, so we return them as strings to prevent any loss of precision. You can then use libraries like bigdecimal to handle them

Similarly, not all bigints values can be represented by the JS number type. Which is why for now they're returned as strings too. Now that JS does support bigints, we're planning on returning them as bigints instead (in the next major release)

**Comment by DavFeng1** [comment] 2023-05-30 21:34
> Keep in mind that `number` is not capable of safely representing `DECIMAL` or `BIGINT` (which is why we won't enable this by default). Another way of fixing your issue is to use `DataTypes.INTEGER` and `DataTypes.DOUBLE` instead.

Does this mean that using `DataType.DOUBLE` is supposed to give `number` at runtime? I'm running into the same issue (getting a string) when using `DataType.DOUBLE` (i'm using sequelize-typescript)

**Comment by ephys** [comment] 2023-05-31 06:37
Yes `DataType.DOUBLE` should produce a `number`. If you're getting a string, there might be a bug (In which case I encourage you to open a new bug report with a reproducible example if you can)

**Comment by DavFeng1** [comment] 2023-06-30 11:01
I've opened the issue w/ sequelize-typescript https://github.com/sequelize/sequelize-typescript/issues/1680

**Comment by aboucodeur** [comment] 2023-08-15 16:37
> Supprimer l' `breaking change`étiquette car `DataTypes.DECIMAL`diffusée à renvoyer des chaînes par défaut, mais nous prévoyons de vous laisser choisir de le convertir de manière non sécurisée en nombre si vous le souhaitez avec [# 14296](https://github.com/sequelize/sequelize/issues/14296)

C'ets dangereux pouvoir gerer le types soit surtout avec des valeurs monetaires qui est le nerd de la geurre des developpeur LE DECIMAL de sequeelize => NUMERIC a postgresql . Donner le choix peut jouer sur #performances

**Comment by aboucodeur** [comment] 2023-08-15 16:49
Simple solution enjoy :
```js
// curious sql :SELECT oid,typname FROM pg_type where typname ilike '%numeric%';
const PG_NUMERIC_CODE = 1700
require("pg").types.setTypeParser(PG_NUMERIC_CODE, value => parseFloat(value))
```

**Comment by aboucodeur** [comment] 2023-08-15 17:04
I build a saas stock management app i'm very fan of postgresql example : 
```js
compte.solde += 20000.88 // client side float (like react)
// DataTypes.DECIMAL(val,len) like string
// bug is : 60002.6720000.89
// Solution just using parser and typeof() to know types 

```
