### ISSUE TITLE
Sequelize won't connect to Postgres database with node v14.40

### ISSUE THREAD

**Issue by GoudekettingRM** [sequelize/sequelize#12393] opened 2020-06-19 20:38 UTC
## Issue Description
I setup a new development environment and installed the everything new, including sequelize and node. I cloned my repo from github (that ran on my old setup), but with the latest installs in did not connect to the database. 

### What are you doing?
I am running an Node.js/Express.js server with Sequelize and PostgreSQL database. Running the server using `node index.js` starts the server like it should, but the async methods on my `Sequelize` instance are not doing anything. 

**Here is the link to the SSCCE for this issue:** I have not created an SSCCE, but can do that later. I just wanted to make sure this gets reported. If this is an unknown issue, I can create an SSCCE. I can also include the link to my repo if useful. 

Below is the minimized setup that I am running. 

```js
// index.js
const express = require("express");
const Sequelize = require('sequelize');

const app = express();
const port = process.env.PORT || 4000;

const databaseUrl = process.env.DATABASE_URL || 'postgres://postgres:secret@localhost:5432/postgres';
const db = new Sequelize(databaseUrl);

async function syncDB() {
  try {
    await db.sync({ force: false });
    console.log('Database connected');
  } catch (error) {
    console.error('error synching database', error);
  }
}
syncDB();

function onListen() {
  console.log(`Listening on port ${port}!`);
}

app.listen(port, onListen);
```

### What do you expect to happen?

Running this code on my old machine would log `Listening on port 4000` and `Database connected` and the corresponding SQL statements.

### What is actually happening?

It only logs `Listening on port 4000`.

### Environment

- Sequelize version: 5.21.13 
- Node.js version: v14.4.0 
- Operating System: Mac OS Catalina 10.15.5

**Important to note that if I switch to node lts (v12.18.1), everything works perfectly.**

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [x] I don't know, I was using Postgres via docker (version 19.03.8, build afacb8b) and pg@8.2.1

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.
- [x] Yes, but I think it will be a very big thing to solve and I'm not sure if I have the time and I also wouldn't know how to start, but if you have some other small thing that a newcomer like me could help with, I'd be open for that too.

**Comment by sushantdhiman** [comment] 2020-06-20 04:52
Duplicate of https://github.com/sequelize/sequelize/issues/12158

**Closed by sushantdhiman** 2020-06-20 04:52 UTC

**Comment by Homitag14** [comment] 2021-01-11 18:36
Please refer to this link.
https://stackoverflow.com/questions/58965011/sequelizeconnectionerror-self-signed-certificate

**Comment by way2mohsun** [comment] 2021-01-11 18:37
please refer to this link.
https://stackoverflow.com/questions/58965011/sequelizeconnectionerror-self-signed-certificate
