### ISSUE TITLE
sync({alter: true}) throws "Too many keys specified"

### ISSUE THREAD

**Issue by aljorhythm** [sequelize/sequelize#9653] opened 2018-07-12 08:28 UTC
This issue is related to #9536

## What are you doing?

```js
await sequelize.sync({ alter: true, force: false });
```

## What do you expect to happen?

Sequelize to sync successfully.

## What is actually happening?

I get this error: ``` SequelizeDatabaseError: Too many keys specified; max 64 keys allowed ```. This happens I guess after 64 times of restarting the application.

## How did I workaround

There are few things that I can do

1. set `force: true`. This is not practical for production environment
2. set `alter: false`. This is not practical when my definitions change
3. set MYSQL key limit, which is makes it hard for cross platform compatibility
4. delete all tables, which defeats the point of use `alter`.
I guess alter creates some indexes which make

__Dialect:__ mysql
__Database version:__ XXX
__Sequelize version:__ 4.37.10
__Tested with latest release:__ Yes (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by te-online** [comment] 2018-08-02 11:47
Having the same issue here with 4.38.0

**Comment by Maples7** [comment] 2018-08-07 06:07
same too.

**Comment by mcampbellr** [comment] 2018-08-21 19:39
Same here, Any update?

**Comment by wilian746** [comment] 2018-09-09 16:37
I have it's problem too, please someone help us!!

**Comment by aircloud** [comment] 2018-09-24 15:38
same too.

**Comment by lukasim** [comment] 2018-11-27 10:11
Is there any solution to this problem, which does not require removing the database after every 64 changes?

**Comment by HighSoftWare96** [comment] 2018-12-03 14:39
I have the same problem. I think this is a serious bug of this repo. Please consider to fix this.

**Comment by cribcutkiran** [comment] 2019-01-11 17:41
Here's workaround that seems to fix it. If you use the approach documented [here](http://docs.sequelizejs.com/manual/tutorial/models-definition.html#indexes), it maintains the same index rather than adding a new one each time sequelize syncs. So instead of:
`sequelize.define('user', {email: {type: Sequelize.STRING, unique:true}})`
use `sequelize.define('user', {email: Sequelize.STRING}, {indexes:[{unique:true, fields['email']}]})`

**Comment by jslok** [comment] 2019-07-10 23:32
This problem still exists. The workaround mentioned above seems to work but from what I can tell cannot be used if you want multiple columns to have unique keys.

**Comment by papb** [comment] 2019-07-23 19:02
> cannot be used if you want multiple columns to have unique keys.

Hi @jslok can you please provide a [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) for this?

**Comment by jslok** [comment] 2019-07-24 05:34
Nevermind I was wrong about that. I did not have it setup correctly.

**Comment by willsgh** [comment] 2019-08-01 11:15
The approach suggested by @cribcutkiran works for me, working with a MySQL database.
Additionally, I used MySQL Workbench to delete the additional indexes created. Running sync repeatedly after that only creates a single instance of each index.

for multiple columns with unique keys, 
sequelize.define(
'user', 
{
email: Sequelize.STRING,
username: Sequelize.STRING
}, 
{
indexes:[
{unique:true, fields: ['email']},
{unique:true, fields:['username]}
]
})

**Comment by codextech** [comment] 2020-07-17 18:23
old sequelize use **email:{type: Sequelize.STRING, unique: true}**
Now, **email:{type: Sequelize.STRING, unique:'email'}**
this will fix the issue.

**Comment by jaimeagudo** [comment] 2020-08-12 16:24
Still seeing this at `sequelize": "^5.19.0 `

**Comment by hoangkakaha** [comment] 2020-08-16 04:47
Same here, but I thought it occur in sequelize-typescript only. May this bug still existed in all version.

**Comment by Bitha007** [comment] 2020-09-21 10:22
How to fix this in databse

**Comment by AlexanderProd** [comment] 2021-01-14 12:05
Still getting it.

**Comment by theprometeus** [comment] 2021-01-14 17:18
> old sequelize use **email:{type: Sequelize.STRING, unique: true}**
> Now, **email:{type: Sequelize.STRING, unique:'email'}**
> this will fix the issue.

This is not a solution for the issue.

If we can use the "true" value to make Sequelize handle the keys automatically, why would we need then to type the key name instead?

Also I'm still having this issue too, it's almost making 3 years.
My workaround is to reset the database every time I update it; it's a very expensive task.

**Comment by hoangkakaha** [comment] 2021-01-15 04:55
> > old sequelize use **email:{type: Sequelize.STRING, unique: true}**
> > Now, **email:{type: Sequelize.STRING, unique:'email'}**
> > this will fix the issue.
> 
> This is not a solution for the issue.
> 
> If we can use the "true" value to make Sequelize handle the keys automatically, why would we need then to type the key name instead?
> 
> Also I'm still having this issue too, it's almost making 3 years.
> My workaround is to reset the database every time I update it; it's a very expensive task.

I think u should write migration to fix database, stop using auto sync database :D

**Comment by renshenhe** [comment] 2021-01-22 01:08
Looks like @papb has more time now! Hopefully this is something on his list.

**Comment by theprometeus** [comment] 2021-02-17 05:23
> > > old sequelize use **email:{type: Sequelize.STRING, unique: true}**
> > > Now, **email:{type: Sequelize.STRING, unique:'email'}**
> > > this will fix the issue.
> > 
> > 
> > This is not a solution for the issue.
> > If we can use the "true" value to make Sequelize handle the keys automatically, why would we need then to type the key name instead?
> > Also I'm still having this issue too, it's almost making 3 years.
> > My workaround is to reset the database every time I update it; it's a very expensive task.
> 
> I think u should write migration to fix database, stop using auto sync database :D

This feature is useful when in development stage.
It's very expensive to migrate the entire database every time something is changing when you're still developing / designing de database :/

**Comment by Klock85** [comment] 2021-03-13 17:22
Still an issue - March '21 in version ^6.5.0

**Comment by angieEncoded** [comment] 2021-04-07 13:30
Still doing it in April on "^6.6.2". I thought I was just doing something wrong with the config but I see this is something the package just does. I hope that there can be a fix for this soon. It has been many years for an inelegant bug like this to exist.

**Comment by siamakdev24** [comment] 2021-04-12 07:40
hi everyone , you can export your database and then edit it and find AlTER in each tables then remove extra fields like : (email_1, user_1, ...) then save and import again your database , you will see issue solved

**Comment by angieEncoded** [comment] 2021-04-12 11:18
Until ~60 more saves, which I think is where this discussion ended up. Yes, the extra keys can be removed by altering them out or dropping and starting over, but the actual problem remains of the system creating the key over and over and it not being very intuitively documented why there is this behavior.

In mariadb and sequelize ^6.6.2 this solution is working
> Now, email:{type: Sequelize.STRING, unique:'email'}

but as others have said, it's not intuitive to have to do this.

**Comment by erfunath** [comment] 2021-04-20 22:01
> In mariadb and sequelize ^6.6.2 this solution is working
> 
> > Now, email:{type: Sequelize.STRING, unique:'email'}
> 
> but as others have said, it's not intuitive to have to do this.

This also works for me. Perhaps a docs update is in order if this isn't already in there.

**Comment by enricodevita** [comment] 2021-11-03 18:06
You have to go in mysql and drop duplicate indexes in models with some unique keys after errors "Too many keys specified" occurs without drop nothing more.

To evitate that error occurs again it's opportune to define unique field like this with the name of index:
 email: { type: Sequelize.STRING, allowNull: false, unique: 'email'},

**Comment by SylvainLeDEV** [comment] 2022-01-18 09:58
> You have to go in mysql and drop duplicate indexes in tables / models with some unique keys after errors "Too many keys specified" occurs without drop entire database.
> 
> To evitate that error occurs again it's opportune to define unique field like this with the name of index: ` email: { type: Sequelize.STRING, allowNull: false, unique: 'email'}` so sequelize don't create a new index name at every alter table.

 i thank you for your answer !

**Comment by Ligengxin96** [comment] 2022-03-01 07:50
`sequelize-typescript` solution

Error code
```ts
  @AllowNull(false)
  @Column({
    type: DataType.STRING(36),
    unique: true, // delete this line
  })
  cdkey: string;
  ```

Correct code
```ts
  @Unique({ name: 'cdkey_unique', msg: 'cdkey_should_be_unique' }) // add this line
  @AllowNull(false)
  @Column({
    type: DataType.STRING(36),
  })
  cdkey: string;
  ```

**Comment by zachshattuck** [comment] 2022-05-04 04:19
Still an issue in ^6.19.0

**Comment by ephys** [comment] 2022-05-20 11:53
Consider 👍🏼 the initial post as we often [sort by the thumbs up emoji](https://github.com/sequelize/sequelize/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) to determine what needs to be prioritized.

**Comment by ekotyoo** [comment] 2022-06-07 04:03
Still an issue in ^6.20.1

**Comment by esraa00** [comment] 2022-07-03 07:23
still an issue

**Comment by ephys** [comment] 2022-07-03 10:47
I believe this is fixed in [Sequelize 7.0.0-alpha.14](https://github.com/sequelize/sequelize/releases/tag/v7.0.0-alpha.14), we have a bunch of tests to ensure indexes are not re-created by alter if they already exist: https://github.com/sequelize/sequelize/blob/main/test/integration/model/sync.test.js#L180

PR: https://github.com/sequelize/sequelize/pull/14619

**Closed by ephys** 2022-07-03 10:47 UTC
Labels: type: bug, status: understood, existing workaround

**Comment by lokeshkumar26** [comment] 2022-07-16 11:21
Use unique: 'compositeIndex'   if u have two column with same name,                                                                                    
  email: {
      type: DataTypes.STRING,
      allowNull: false,
      unique: 'compositeIndex'
    },                    
Check at offical docs https://sequelize.org/docs/v6/core-concepts/model-basics/#column-options

**Comment by varundeva** [comment] 2023-02-15 16:14
> You have to go in mysql and drop duplicate indexes in tables / models with some unique keys after errors "Too many keys specified" occurs without drop entire database.
> 
> To evitate that error occurs again it's opportune to define unique field like this with the name of index: ` email: { type: Sequelize.STRING, allowNull: false, unique: 'email'}` so sequelize don't create a new index name at every alter table.

Thank You for this information. 
issue resolved.

**Comment by gnubyte** [comment] 2023-05-22 02:34
I had to drop my database table, let it get recreated and then import the DB.

**Comment by ArtonRamadani** [comment] 2024-07-01 08:00
this problem occurs since you have synced your models multiple times therefore creating multiple indexes for the same fields, 

what you need to do to confirm this is to run the commands :

1) 
`SHOW INDEX FROM yout_table_name;`

this should confirm to you that you have multiple indexes for the same fields, and to be able to delete them you need to run 


`-- Step 1: Query to list all indexes on your_table_name table
SELECT INDEX_NAME
FROM INFORMATION_SCHEMA.STATISTICS
WHERE TABLE_SCHEMA = 'your_database_name'
  AND TABLE_NAME = 'your_table_name';

-- Step 2: Generate and execute DROP INDEX statements for each index
-- Note: Replace 'your_database_name' with the actual name of your database.

SET @tableName = 'your_table_name';
SET @schemaName = 'your_database_name';

-- Generate DROP INDEX statements and output
SELECT CONCAT('DROP INDEX ', INDEX_NAME, ' ON ', @tableName, ';') AS drop_statement
FROM INFORMATION_SCHEMA.STATISTICS
WHERE TABLE_SCHEMA = @schemaName
  AND TABLE_NAME = @tableName;
`


this command should give you the commands you need to run to drop the indexes on that table like in the following picture

![image](https://github.com/sequelize/sequelize/assets/60104374/e2c07490-46c0-4000-a8f5-b67be0111380)

copy and paste them and you should be good to go!

**_command will not be executed if you try to drop the PRIMARY INDEX._**
