### ISSUE TITLE
Add `Model.exists()` to allow efficient checking of at least one matching row

### ISSUE THREAD

**Issue by c-oreills** [sequelize/sequelize#17300] opened 2024-05-02 11:16 UTC
### Describe the feature you'd like to see implemented
Add a new `exists` method on model, taking the same parameters as `findOne`, which returns a boolean of whether at least one matching row exists in the database.

Example usage:
```
await User.create({ name: 'Alice' });

await User.exists({ name: 'Alice' }); // true
await User.exists({ name: 'Bob' }); // false
```

Under the hood this would execute a count query limited to 1 and coerce to a boolean, so that it's efficient on the database and network.

### Describe why you would like this feature to be added to Sequelize

This is a convenience method. I recently needed this to avoid O(NM) complexity in a check. I ended up using `findOne` instead and checking for a null, but didn't need the resulting model instance.

The limit of 1 is more efficient for large queries.

The API mirrors a Django's [QuerySet.exists](https://docs.djangoproject.com/en/5.0/ref/models/querysets/#django.db.models.query.QuerySet.exists) 

### Is this feature dialect-specific?

- [x] No. This feature is relevant to Sequelize as a whole.
- [ ] Yes. This feature only applies to the following dialect(s): 

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I will need guidance.
- [ ] No, I don't have the time, but my company or I are [supporting Sequelize through donations on OpenCollective](https://opencollective.com/sequelize).
- [ ] No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in implementing my feature.

---

_Indicate your interest in the addition of this feature by adding the 👍 reaction. Comments such as "+1" will be removed._

**Comment by WikiRik** [comment] 2024-10-25 08:28
Duplicate of https://github.com/sequelize/sequelize/issues/10187

**Closed** 2024-10-25 08:36 UTC
Labels: type: feature, pending-approval
