### ISSUE TITLE
Migration addColumn with references does not create foreign key

### ISSUE THREAD

**Issue by JSteunou** [sequelize/sequelize#2943] opened 2015-01-15 11:20 UTC
Maybe I'm doing it wrong, or it's a missing feature on purpose, but, reading the documentation a lot and not finding a response, I started to think that might be a bug.

Using 2.0.0-rc7, I have a migration script with something like this

```
migration.addColumn('user', 'pet_id', {
    type: DataTypes.INTEGER(11),
    allowNull: false,
    field: 'pet_id',
    references: 'pet',
    onUpdate: 'cascade',
    onDelete: 'restrict'
});
```

and it just fire a 

```
ALTER TABLE `user` ADD `pet_id` INTEGER(11) NOT NULL REFERENCES `pet` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
```

How can I add constraint on foreign key?

**Comment by JSteunou** [comment] 2015-01-15 11:27
Might found a good answer why it does not add foreign key: because I'm using InnoDB Engine!
http://dba.stackexchange.com/questions/14070/using-foreign-key-and-references-for-on-delete-cascade-in-mysql

**Comment by jlamberg** [comment] 2015-03-13 14:06
I noticed the same while trying to migrate a table to have a new column with a foreign key constraint.

I don't know if you already knew it (I've tested it at least in later 2.0.0-rc versions) but you can add a foreign key constraint when you do a migration that creates a new table:

    migration.createTable("Workshifts", {
      ...
      employee_id: {
        type: DataTypes.INTEGER,
        references: 'Employees',
        referencesKey: 'id',
        onUpdate: 'CASCADE',
        onDelete: 'RESTRICT'
      },
      ...
    });

The above results in the  following:

    > show create table Workshifts;

    CREATE TABLE `Workshifts` (
      ...
      `employee_id` int(11) DEFAULT NULL,
      KEY `employee_id` (`employee_id`),
      CONSTRAINT `workshifts_ibfk_1` FOREIGN KEY (`employee_id`) REFERENCES `Employees` (`id`) ON UPDATE CASCADE
    ) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8

**Comment by jlamberg** [comment] 2015-03-17 14:41
I ended up using raw SQL to add a new column with a foreign key reference in a migration as I could not go back and change old migrations (which is wrong, anyway :).

    var sql = "ALTER TABLE `Workshifts`" +
      " ADD COLUMN `location_id` INTEGER DEFAULT NULL" +
      ", ADD FOREIGN KEY (`location_id`) REFERENCES `Locations` (`id`)" +
      " ON UPDATE CASCADE ON DELETE RESTRICT";

    migration.sequelize.query(sql, {
      type: migration.sequelize.QueryTypes.RAW
    });
    done();

For the undo-part (down function) of the migration, remember to drop the foreign key constraint first and then the column itself, otherwise it won't work (or at least not in MySQL that I'm using in this project).

Note that Sequelize automatically generates a foreign key constraint identifier that needs to be used to drop the constraint. (Currently, one can't provide the identifier anyway, AFAIK.) So, run the migration up first and then look up the constraint identifier manually and add it to the migration file. 

In my case, the down function looks like this:

    var sql = "ALTER TABLE `Workshifts`" +
      " DROP FOREIGN KEY `workshifts_ibfk_2`, DROP COLUMN `location_id`";

    migration.sequelize.query(sql, {
      type: migration.sequelize.QueryTypes.RAW
    });
    done();


The setup I use is: Sequelize [Node: 0.10.35, CLI: 1.4.0, ORM: 2.0.4].

**Comment by BridgeAR** [comment] 2015-05-31 13:32
Duplicate of #966

**Closed** 2015-05-31 13:49 UTC
