### ISSUE TITLE
MSSQL: Cannot read property 'msg' of undefined - when trying to insert a duplicated value with unique constraint

### ISSUE THREAD

**Issue by damianofusco** [sequelize/sequelize#3928] opened 2015-06-13 13:44 UTC
Table User has a unique constraint on [name] column.
When i try to insert the same value for the second time, I get this:

Executing (default): INSERT INTO [dbo].[User] ([name],[dateCreated]) OUTPUT INSERTED.* VALUES ('myuser','2015-06-13 13:39:44.419 +00:00');

../node_modules/sequelize/lib/dialects/mssql/query.js:177
    if (!!uniqueKey.msg) message = uniqueKey.msg;
                   ^
TypeError: Cannot read property 'msg' of undefined

**Comment by janmeier** [comment] 2015-06-14 12:41
Can you create a small test case?

**Comment by renak** [comment] 2015-07-21 00:00
I got this error because the database table had a unique index on certain columns, and I was trying to insert duplicate records. Modifying the index fixed the issue.

**Comment by janmeier** [comment] 2015-07-21 06:10
@renak Test-case :)?

**Comment by renak** [comment] 2015-07-21 16:47
@janmeier - To test: 
 - Create a db table in SQL Server with an auto-increment id field, and two additional fields. 
 - Create a Unique, Non-Clustered index on the 2 additional fields. 
 - Using sequelize, execute an insert on the table twice, both times with the same data.

Result:
The console outputs an error, which is correct because the index that is setup requires that the fields are unique. However, it seems that the error thrown from the database is not caught correctly in sequelize if it's getting "undefined". See the error description that damianofusco reported.

**Comment by janmeier** [comment] 2015-07-21 19:28
Cannot reproduce. This should be fixed on latest master https://github.com/sequelize/sequelize/blob/master/lib/dialects/mssql/query.js#L177, please comment with a testcase (in sequelize) if it isn't

**Closed by janmeier** 2015-07-21 19:28 UTC
Labels: bug
