### ISSUE TITLE
Bind throw an error

### ISSUE THREAD

**Issue by ks-s-a** [sequelize/sequelize#5727] opened 2016-04-11 12:19 UTC
## What you are doing?

I want to check a bind construction mechanism, but I got an error.

I'v already tried to use array bind syntax, it produce the same error.

```js
const i = '1 or 1 = 1';

sequelize.query('select id from "Apps" where id = ' + i)
    .spread(results => console.log('arguments is: ', results));

sequelize
    .query('select id from "Apps" where id = $a', {
      bind: {
        a: i,
      }
    })
    .spread(results => console.log('arguments is: ', results));

```

## What do you expect to happen?
I wanted the same results for the both snippets of code.

## What is actually happening?
Second query throw an error: 
{ [SequelizeDatabaseError: syntax error at or near "$"]
  name: 'SequelizeDatabaseError',
  message: 'syntax error at or near "$"',
  parent: 
   { [error: syntax error at or near "$"]
     name: 'error',
     length: 83,
     severity: 'ERROR',
     code: '42601',
     detail: undefined,
     hint: undefined,
     position: '34',
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: undefined,
     table: undefined,
     column: undefined,
     dataType: undefined,
     constraint: undefined,
     file: 'scan.l',
     line: '1053',
     routine: 'scanner_yyerror',
     sql: 'select id from "Apps" where id = $a' },
  original: 
   { [error: syntax error at or near "$"]
     name: 'error',
     length: 83,
     severity: 'ERROR',
     code: '42601',
     detail: undefined,
     hint: undefined,
     position: '34',
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: undefined,
     table: undefined,
     column: undefined,
     dataType: undefined,
     constraint: undefined,
     file: 'scan.l',
     line: '1053',
     routine: 'scanner_yyerror',
     sql: 'select id from "Apps" where id = $a' },
  sql: 'select id from "Apps" where id = $a' }

Output: JSON
__Dialect:__ postgres
__Database version:__ psql (PostgreSQL) 9.4.5
__Sequelize version:__ 3.4.1

**Comment by janmeier** [comment] 2016-04-15 21:16
Cannot reproduce this one the latest version - however it throws ` invalid input syntax for integer: "1 or 1 = 1"` instead - which makes sense since $a uses an actual bind parameter (database driver parameter binding as opposed to putting the value inside the string) and postgres tries to validate the input as an integer.

Going to close this, please reopen if you still have issues on the latest version

**Closed by janmeier** 2016-04-15 21:16 UTC
