### ISSUE TITLE
Declare types to match ESM usage

### ISSUE THREAD

**Issue by JacobLey** [sequelize/sequelize#13132] opened 2021-03-22 16:36 UTC
## Issue Description

Current typings are emitted such that something like:
```
import { where } from 'sequelize';
where()
```
_appears_ to be entirely valid code.

While that is the case with Transpiled code (e.g. the above becomes something like:
```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const sequelize_1 = require("sequelize");
sequelize_1.where();
```
in a commonjs module)

it is not valid when using native ESM (`"type":"module"`), which will result in the following error:
```
import { where } from 'sequelize';
         ^^^^^
SyntaxError: Named export 'where' not found. The requested module 'sequelize' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'sequelize';
const { where } = pkg;
```

### What was unclear/insufficient/not covered in the documentation

Current typings encourage the usage of named exports from Sequelize https://sequelize.org/master/manual/typescript.html and similarly internally https://github.com/sequelize/sequelize/blob/main/types/test/where.ts

This documentation infers a commonjs environment, and is not compatible with ESM.

### If possible: Provide some suggestion on how we can enhance the docs

There are 3 general approaches I can think of:

1) Change all named exports in [index.d.ts](https://github.com/sequelize/sequelize/blob/main/types/index.d.ts) to `export type` to encourage usage of the default export. This would most likely be a breaking change for people that use commonjs typescript (probably 95%) but would result in the most "correct" typings
2) Add footnote to documentation saying something like "If you use ESM, only use the default export", which would be enough to "support it" but I think it would be confusing to technically have two different usages
3) Actually export named values. While this would actually be the best, there are a _lot_ of exports and would require actual JS changes, which overall would require a lot more work.

### Additional context

Originally brought up here: https://github.com/sequelize/sequelize/pull/12921#discussion_r598869811

I use Sequelize with ESM/Typescript and have run into this issue before. 

using something like
```
import Sequelize, { Transaction } from 'sequelize';
const { Model }

class Foo extends Model {}...

export const async withTransaction(transaction?: Transaction): Promise<Foo> => Foo.findOne({ transaction })
```
has worked for me (e.g. use default export for Javascript values, named exports for types)

### Is this issue dialect-specific?

- [X] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [X] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by ephys** [comment] 2021-11-03 09:31
This is still an issue. We have to create an intermediary file to be able to `import` sequelize without losing typings: https://github.com/ephys/modpack-maker/blob/main/api/src/esm-compat/sequelize-esm.ts

Best solution is to fully convert the codebase to ESM, and transpile to CommonJS to support both versions without breaking changes. (See conditional exports https://nodejs.org/api/packages.html#conditional-exports)

**Comment by armellarcier** [comment] 2021-11-09 07:00
How comes this did not reopen?

**Comment by WikiRik** [comment] 2021-11-09 09:09
The bot does not reopen things automatically, but seeing as this is still an issue I will reopen it.

**Comment by armellarcier** [comment] 2021-11-09 23:16
It seems the bot does reopen issues though

**Comment by WikiRik** [comment] 2021-11-09 23:18
It only removes the stale label if the issue is still open, I manually opened this one

**Comment by information-security** [comment] 2021-11-19 04:11
Apart from enhancements of the documentation, are there going to be any fix (like what @ephys suggested) merged into the `sequelize` or should we start modifying our codebase?

**Comment by WikiRik** [comment] 2021-11-19 09:45
Fully converting the codebase to ESM will take some time, so not sure how feasible that is for now. We are planning on rewriting the codebase in TypeScript, and we'll take the ESM usages into account for that as well

**Closed** 2021-12-12 11:39 UTC
Labels: type: docs
