### ISSUE TITLE
how to use Stream of sequelize? not support？

### ISSUE THREAD

**Issue by 119786155** [sequelize/sequelize#4286] opened 2015-08-10 01:26 UTC
http://stackoverflow.com/questions/28787889/how-can-i-set-up-sequelize-js-to-stream-data-instead-of-a-promise-callback/28876877

**Comment by janmeier** [comment] 2015-08-10 12:35
Duplicate of https://github.com/sequelize/sequelize/issues/2454

**Closed by janmeier** 2015-08-10 12:35 UTC
