### ISSUE TITLE
Errors are not handled on unkown data types in migratios files

### ISSUE THREAD

**Issue by ArtistNeverStop** [sequelize/sequelize#9749] opened 2018-07-31 19:42 UTC
## What are you doing?

Sequelize must trow an error of not suported data types  when runing the migrations files , currently is just trowing a [ERROR: Cannot read property 'toString' of undefined] in the sequelize\lib\dialects\mssql\connection-manager.js:70:26 file 
```js
'use strict';
module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.createTable('Clients', {
      id: {
        allowNull: false,
        autoIncrement: true,
        primaryKey: true,
        type: Sequelize.INTEGER
      },
      name: {
        allowNull: true,
        type: Sequelize.STRING
      },
      client_id: {
        allowNull: true,
        type: Sequelize.STRING
      },
      secret: {
        allowNull: true,
        type: Sequelize.SRTING
      },
      createdAt: {
        allowNull: false,
        type: Sequelize.DATE
      },
      updatedAt: {
        allowNull: false,
        type: Sequelize.DATE
      }
    });
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.dropTable('Clients');
  }
};
```

## What do you expect to happen?
Because the above migration has a typo in the secret field : (it is SRTING instead of STRING)
I expect Sequelize to trow a NON SUPORTED DATA TYPE exception or something 

## What is actually happening?
But instead i got this ERROR: Cannot read property 'toString' of undefined] 
[ERROR: Cannot read property 'toString' of undefined] in the sequelize\lib\dialects\mssql\connection-manager.js:70:26 file 

mssql 
__Dialect version:__ 2.6.4
__Sequelize version:__ 4.38.0

I suggest either to  import the data types individualy from the Sequelize library or to validate thhe dta types and throw an UNSOPORTED Exception 

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment] 2018-08-01 05:57
Duplicate of https://github.com/sequelize/cli/issues/222

**Closed by sushantdhiman** 2018-08-01 05:57 UTC
