### ISSUE TITLE
PostgreSQL migrations should be transactional

### ISSUE THREAD

**Issue by d11wtq** [sequelize/sequelize#2114] opened 2014-08-04 12:52 UTC
PostgreSQL supports transactions on DDL, meaning you can wrap your migrations in a transaction and if something goes wrong, all schema changes will be rolled back, leaving you in a clean state. Without this, you end up having to clean up half-performed migrations by hand, if you accidentally make a typo in a migration.

**Comment by sushantdhiman** [comment] 2016-05-30 09:48
Duplicate of #1882 @janmeier

**Comment by janmeier** [comment] 2016-05-30 09:51
Indeed it is, fanx!

**Closed by janmeier** 2016-05-30 09:51 UTC
Labels: feature
