### ISSUE TITLE
Models with schema containing a "$" character fail to create or update records.

### ISSUE THREAD

**Issue by arnaudForestAdmin** [sequelize/sequelize#11320] opened 2019-08-14 14:58 UTC
## What are you doing?
On a simple table (columns id, name) attached to a schema containing a "$" character, I try to create or update records.

```js
module.exports = (sequelize, DataTypes) => {
  const User = sequelize.define('user', {
    name: { type: DataTypes.STRING },
  }, {
    schema: 'point-prisma$dev',
    tableName: 'users',
    timestamps: false,
  });

  User.associate = () => {
  };
};
```

**To Reproduce**
This error happens in v5 (v5.14) and not in v4 (v4.43).

1. Create a database schema with a name containing a "$" character (for instance "point-prisma$dev")
2. Create a table and attach it the created schema
3. `find` function should work well but not `create` / `update`
4. For create/update you should see this error:
```
Named bind parameter "$dev" has no value in the given object.
```
Something wrong happen in `formatBindParameters` function in `lib/dialects/abstract/query.js`

## What do you expect to happen?
The create / update actions should create or update the record.

## What is actually happening?
Internal error:
```
Named bind parameter "$dev" has no value in the given object.
```

## Environment
Dialect:
- [ ] mysql
- [x] postgres
- [ ] sqlite
- [ ] mssql
- [ ] any
Database version: 9.5
Sequelize version: 5.14
Node Version: 11.14
OS: OSX
Tested with latest release:
- [ ] No
- [x] Yes, specify that version: 5.14

**Comment by papb** [comment] 2019-08-14 17:31
Can you please test this with another dialect? This is important to know whether the problem is dialect-specific or not.

You can instantiate an in-memory SQLite instance very easily:

1. `npm install sqlite3`
2. `new Sequelize('sqlite::memory:')`

**Comment by arnaudbesnier** [comment] 2019-08-21 16:01
Hi @papb
Thanks for your response.
I tried to test on a minimal SQLite configuration.

### Context
With the same model configuration (described above) and the following table configuration with SQLite:
<img width="636" alt="Screenshot 2019-08-21 at 17 57 44" src="https://user-images.githubusercontent.com/664261/63447943-3bfd0e80-c43d-11e9-9163-bb19511948a3.png">

### Result
I can create records without errors. And the object created are well persisted in my sqlite file.

### Conclusion
So the issue is clearly "dialect-specific".

**Comment by papb** [comment] 2019-08-21 21:28
Thanks! Can you please post the generated SQL for the postgres case?

**Comment by arnaudbesnier** [comment] 2019-08-22 06:35
In v4, working case, it is fine:
```sql
UPDATE "point-prisma$dev"."users" SET "name"='yeah' WHERE "id" = 1;`
```

In v5, the error happens during the SQL query generation so the SQL is not really generated nor run/logged. Here is the error (as presented in the issue description):
`Named bind parameter "$dev" has no value in the given object`

**Comment by papb** [comment] 2019-08-22 20:21
@arnaudbesnier Ah, ok!

**Comment by AbhiSivaprasad** [comment] 2019-09-18 15:52
Is there any update or workaround for this if you can't remove '$' from schema name?

**Comment by sushantdhiman** [comment] 2020-05-14 07:32
Fixed with https://github.com/sequelize/sequelize/pull/12250

**Closed by sushantdhiman** 2020-05-14 07:32 UTC
Labels: Great SSCCE, dialect: postgres, status: understood, type: bug
