### ISSUE TITLE
Get different data from Model when is found

### ISSUE THREAD

**Issue by juliocanares** [sequelize/sequelize#3339] opened 2015-03-13 06:20 UTC
Hi guys its possible get different data from model ?

I want make this

I have 1 model called Client , that is a User but with privilege of a client , then i saving the UserId in Client table.

Client Model

```javascript
var Client = sequelize.define('Client', {
     UserId: DataTypes.INTEGER
});
```
User Model

```javascript
var User = sequelize.define('User',
    {
        name: DataTypes.STRING,
        email: DataTypes.STRING
        privilege: DataTypes.STRING
    }, {
        hooks: {
            afterCreate: function (user, options) {
                var values = {UserId: user.id};
                switch (user.privilege) {
                    case "Client":
                        return global.db.Client.create(values);
                        break;
                }
            }
        }
    }
);
```

Then i want that when obtain the data of the Client really to show the data of the user.

```javascript
global.db.Client.find(1).then(function(client){
  console.log(client.toJSON()) // {name:'user','user@gmail.com','Client'}
})
```

thanks :dancers:

**Comment by mickhansen** [comment] 2015-03-13 08:19
Well you could use a beforeFind hook on Client to add the needed User include and then you could overload toJSON() or similar.

**Comment by janmeier** [comment] 2015-03-24 14:41
Not a bug or feature request, closing

**Closed by janmeier** 2015-03-24 14:41 UTC
