### ISSUE TITLE
Model field names truncated on multi-level includes

### ISSUE THREAD

**Issue by teagup** [sequelize/sequelize#4158] opened 2015-07-20 20:42 UTC
Considering I have the following relationships setup:
```coffeescript
db.Invoice.hasMany db.InvoiceLineItem
db.InvoiceLineItem.belongsTo db.Invoice

db.InvoiceLineItem.hasMany db.InvoiceLineItemAdjustment
db.InvoiceLineItemAdjustment.belongsTo db.InvoiceLineItem

db.InvoiceLineItemAdjustment.belongsTo db.LineItemAdjustmentType
db.LineItemAdjustmentType.hasMany db.InvoiceLineItemAdjustment
```

When I try to run the following query:
```coffeescript
db.Invoice.findAll
  where:
    id: 1
    is_active: true
  include: [
    model: db.InvoiceLineItem
    include: [
      model: db.InvoiceLineItemAdjustment
      include: [
        db.LineItemAdjustmentType
      ]
    ]
  ]
```

The returned result has truncated fields in each InvoiceLineItemAdjustment's dataValue, with the following printed when logging each InvoiceLineItemAdjustment's dataValue:
```
{
  invoice_id: 1,
  invoice_line_item_i: 1,
  adjustment_amount: 4,
  adjustment_percenta: null,
  user_coupon_code_id: null,
  is_active: true,
  LineItemAdjustmentT: 'damage'
}
```

I have attempted aliasing the LineItemAdjustmentType using an 'as', with still no luck. When I try loading running the following query:
```coffeescript
db.InvoiceLineItem.findAll
  where:
     invoice_id: 1
     is_active: true
  include: [
    model: db.InvoiceLineItemAdjustment
    include: [
      db.LineItemAdjustmentType
    ]
  ]
```

The returned result for each InvoiceLineItemAdjustment's dataValue is as expected:
```
{
  invoice_id: 1,
  invoice_line_item_item_id: 1,
  adjustment_amount: 4,
  adjustment_percentage: null,
  user_coupon_code_id: null,
  is_active: true,
  LineItemAdjustmentType: {
    dataValues: {
      id: 3,
      description: 'Damage',
      lookup_key: 'damage',
      is_active: true
    }
  }
}
```

I am not quite sure what is causing this issue, but it severely impacts the query performance for running complex queries with multi-level includes, because it essentially means I have to run the nested includes in separate queries. I've tested on the most recent version: 3.4.1. I'm wondering if anyone else has encountered this issue, and if there is a fix in the works for it. Thanks in advance!

**Comment by mickhansen** [comment] 2015-07-20 21:01
What dialect are you using?

**Comment by teagup** [comment] 2015-07-20 21:04
I am using the postgres dialect.

**Comment by mickhansen** [comment] 2015-07-20 21:22
That's odd, i've had some pretty long column names, but i guess not that long :)
There's no easy fix, a workaround could be to name your models with an acronym but retain the long table name.

**Comment by janmeier** [comment] 2015-07-20 21:36
Duplicate of #2084 

Your talked about minifying identifiers yourself previously @mickhansen ;-) 

Not sure it's a viable scheme though... It's not easy to debug at least 
I think the best solution would be to use include separate when the identifier becomes too long

**Closed by janmeier** 2015-07-20 21:36 UTC

**Comment by teagup** [comment] 2015-07-20 21:43
Ok, I suppose I can try renaming the model definitions to acronyms, although I don't feel it fully addresses the issue as it leads to less legible code if all my model names are acronyms. You mention there's no easy fix for the bug, but it seems like a fairly important feature to not have model names tied to the number of nested includes you can have. Where does the problem stem from? I would like to look into it more to see if I could contribute a fix.

**Comment by janmeier** [comment] 2015-07-20 22:04
@teagup in the issue I linked you'll see that postgres has a max length of 63 characters for identifiers. Sequelize prefixes nested included with the names of the parent models for easier deduplication - which means we pretty quickly hit that limit. 

The only fix now is to convert model names into something shorter - eg `user.projects.tasks` - > `a.b.c`. But that leads to a lot less readable queries, and might also introduce bugs. The include + deduplication code is complicated enough already :-). 

I think the best fix would be to split the query onto several queries when the identifiers become too long. That's what `include.separate` does. But it's not implemented yet :-). 

Using separate includes when there are many nested includes could also give a performance boost, since deduplication in javascript is CPU heavy

**Comment by simonv3** [comment] 2016-08-02 15:43
Hey @janmeier, is `include.separate` implemented yet?

**Comment by janmeier** [comment] 2016-08-02 20:35
For hasMany yes :)

**Comment by simonv3** [comment] 2016-08-02 22:45
Do you know if it will be implemented for other association types?

**Comment by faceleg** [comment] 2016-08-02 23:37
Are there docs for include.separate?

**Comment by simonv3** [comment] 2016-08-02 23:46
@faceleg have a look in http://docs.sequelizejs.com/en/latest/api/model/#findalloptions-promisearrayinstance, in the options it mentions it (easiest is doing find on that page)

**Comment by moseleyi** [comment] 2018-04-19 16:48
Thanks @simonv3 for the link, saved my life. All my column names once returned from Sequelize have been truncated to 5 characters (It was 4 levels deep in my GraphQL query) and this solved the problem and also allowed me to split the queries up a bit (my Cartesian product was getting out of hand

**Comment by vaulstein** [comment] 2021-12-01 15:40
**separate** all works if **hasMany** is used, for **belongsToMany** the only option is to lazy load

**Comment by chornbe** [comment] 2022-05-18 20:37
I just spent two days rewriting a metric shit tonne of code because of this. Wrote all my APIs, wrote enough testing GUI code to verify usage, started loading data, whammo, crash and burn and absolutely unreliable data. I'm truly not sure which is worse; the asinine PostgreSQL limit, or the Sequelize documentation on the separate:true workaround that is clearly not fully implemented. I don't understand how hasOne isn't remarkably easy to implement compared to all other join types, and wasn't the basis for hasMany when putting this feature in. 

I'm sure I'd just end up pissing off a lot of people, but if you ever want a guy with decades of experience who knows how important APIs are to help you guide this product to commercial-quality viability, we can talk. I like Sequelize, but I hate bumping up against its fairly easy-to-hit limits once you move beyond basic CRUD. (sigh) 

For this issue, I'm just back to doing single-table selects and gluing the final model together myself before finalizing the REST calls. Makes everything four times longer than it needs to be, more prone to fragility (well, I guess not really), and more to change later when you invariably, yet again, change existing API calls like you've been wont to do (which is, in my decades of experience, a fire-immediately offense). 

Yes, I'm being whiney; I just lost a couple days thanks to this, and it's not the first time Sequelize has created a similar mess, not by a long shot.

**Comment by ephys** [comment] 2022-05-18 21:09
You can try using [minifyAliases](https://sequelize.org/api/v7/interfaces/options#minifyAliases) to resolve that issue, but it has [its own issues](https://github.com/sequelize/sequelize/issues?q=is%3Aissue+is%3Aopen+minifyAliases), and is a global option instead of a per-query option.

Other than that, I understand that you're frustrated. Sequelize does have a good few very long standing issues that have been open for years. Sequelize isn't a commercial project and receives very little financing. That means it's maintained by a small group of volunteers that are working on it for (almost) free in the time we can spare outside of our day jobs.

We're always open to more people helping, even if it's just one PR that fixes that problem that is causing you trouble. That's how most of us ended up working on it. We use it professionally, and we needed it to be better.

I've used the project for a while but I've only been working on it for 6 months so I'm curious about what you mean by:
> change existing API calls like you've been known to do

**Comment by httpiga** [comment] 2022-05-19 06:52
@chornbe I know that feel bro https://bit.ly/3lr9h4u

**Comment by chornbeRecurve** [comment] 2022-10-21 03:32
This is still a HUGE problem, a STUPID problem, and I want to just find a commercial library that does this where the people writing and maintaining it have a financial, vested interest in making it work right. I WANT TO GIVE MONEY TO SOMEONE WHO WRITES LIBRARIES BECAUSE OPEN SOURCE ALWAYS FALLS SHORT OF GOOD, COMPLETE, WELL-TESTED IMPLEMENTATIONS.

**Comment by jaypkanhasoft** [comment] 2022-12-30 10:16
Hello everyone, here is the perfect solution:

```
include: [
                    {
                      separate: true,
                      model: Model,
                    },
              ]
```
 - Add separate: true while including.

**Comment by andretti1977** [comment] 2023-02-14 18:35
just came here with the same problem...very strange this is still an issue

**Comment by ephys** [comment] 2023-03-02 21:54
It's always going to be a limitation, but in a future update you'll be able to minify aliases per-query (https://github.com/sequelize/sequelize/pull/15394), and Sequelize will throw if it detects a broken alias to tell you to enable `minifyAliases` (https://github.com/sequelize/sequelize/issues/15362)

**Comment by Abdul-Manan-456** [comment] 2023-10-06 10:34
> Hello everyone, here is the perfect solution:
> 
> ```
> include: [
>                     {
>                       separate: true,
>                       model: Model,
>                     },
>               ]
> ```
> 
> * Add separate: true while including.

Yes it works for me
