### ISSUE TITLE
Getters getting called when they're not required... [probable bug]

### ISSUE THREAD

**Issue by EdwardGonzalez** [sequelize/sequelize#4825] opened 2015-11-08 04:30 UTC
Since I didn't have the JSON.parse functionability around a try and catch because my field in my model is defined as:

```javascript
	type:Sequelize.TEXT,
	defaultValue:"{}",
	get:function(){
		return JSON.parse(this.getDataValue('appMetadata'));
	},
	set:function(value){
		this.setDataValue('appMetadata',JSON.stringify(value));
	}
```

which indeed means that I'm supposed to provide a valid object every time and that such cannot be null (unless you give some weird circular element and make it crash) so I expected it to work properly however in one of my parts once I do.

```javascript
this.models.User.findAll({'attributes':['ID']}).then(function(users){
    users.map(function(user){
        return user.toJSON();
    });
});
````

I get the awful bug of [SyntaxError: Unexpected token u] which indeed means that my JSON.parse function is being called with undefined, but my question is why, I only want the id attribute, it's calling my getter to get something I don't want to get because it doesn't even exist.

However I can think of several technical reasons for this, such that it's a protocol that gets all the dataValues in your instance and that it's allowed to set those values and re-get them again, anyway, I'm going to fix the setters and getters because if someone changes it to invalid JSON in plain text my server won't work, but I'm not sure what to think about this problem.

But I just don't know why undefined, since there's no undefined in the database; so that should mean I wouldn't actually call that value and I don't want anything with it, unless I'm a bit weird and I want to apply setters to update, but then you'd have a value that should not be undefined; and thus able to know that you should call the getter.

Just saying, I got confused with that and took me a while to understand, but it's up to you at the end :) it's a nice library anyway.

**Comment by janmeier** [comment] 2015-11-09 07:37
Duplicate of https://github.com/sequelize/sequelize/issues/4632 - custom getters are always called

**Closed by janmeier** 2015-11-09 07:37 UTC
