### ISSUE TITLE
snake_case to camelCase with `field` creates woefully long queries

### ISSUE THREAD

**Issue by heisian** [sequelize/sequelize#9246] opened 2018-03-28 02:10 UTC
## What are you doing?
My tables use `snake_case` columns, and I use `field` in my model definitions to convert them to `camelCase`. The problem occurs when eager-loading several nested associations like so:
```js
// Psuedo-code
MyModel.addScope('defaultScope', {
  include: [
    Model1,
    Model2,
    Model3,
    {
      model: Model4,
      include: [
        Model5,
        Model6,
        Model7,
        {
          model: Model8,
          include: [
            Model9
          ]
        }
      ]
    }
  ]
}, {
  override: true
})
```

## What do you expect to happen?
I expected `snake_case` to `camelCase` conversion to occur in the application/ORM layer, not the database layer.

Because conversion is done in the database layer, Sequelize ends up generating a ridiculously long and inefficient query:
```sql
SELECT
   "User".*,
   "Emails"."id" AS "Emails.id",
   "Emails"."user_id" AS "Emails.userId",
   "Emails"."email" AS "Emails.email",
   "Emails"."verified" AS "Emails.verified",
   "Emails"."primary" AS "Emails.primary",
   "Emails"."created_at" AS "Emails.createdAt",
   "Emails"."updated_at" AS "Emails.updatedAt",
   "Emails"."deleted_at" AS "Emails.deletedAt",
   "Emails"."user_id" AS "Emails.user_id",
   "Identity"."id" AS "Identity.id",
   "Identity"."user_id" AS "Identity.userId",
   "Identity"."birth_name_first" AS "Identity.birthNameFirst",
   "Identity"."birth_name_middle" AS "Identity.birthNameMiddle",
   "Identity"."birth_name_last" AS "Identity.birthNameLast",
   "Identity"."birth_date" AS "Identity.birthDate",
   "Identity"."birth_gender" AS "Identity.birthGender",
   "Identity"."birth_country" AS "Identity.birthCountry",
   "Identity"."created_at" AS "Identity.createdAt",
   "Identity"."updated_at" AS "Identity.updatedAt",
   "Identity"."deleted_at" AS "Identity.deletedAt",
   "Identity"."user_id" AS "Identity.user_id",
   "Identity -> Profiles"."id" AS "Identity.Profiles.id",
   "Identity -> Profiles"."identity_id" AS "Identity.Profiles.identityId",
   "Identity -> Profiles"."name_first" AS "Identity.Profiles.nameFirst",
   "Identity -> Profiles"."name_middle" AS "Identity.Profiles.nameMiddle",
   "Identity -> Profiles"."name_last" AS "Identity.Profiles.nameLast",
   "Identity -> Profiles"."gender" AS "Identity.Profiles.gender",
   "Identity -> Profiles"."height" AS "Identity.Profiles.height",
   "Identity -> Profiles"."weight" AS "Identity.Profiles.weight",
   "Identity -> Profiles"."status_citizen" AS "Identity.Profiles.statusCitizen",
   "Identity -> Profiles"."status_permanent_resident" AS "Identity.Profiles.statusPermanentResident",
   "Identity -> Profiles"."status_green_card_number" AS "Identity.Profiles.statusGreenCardNumber",
   "Identity -> Profiles"."status_months_in_us" AS "Identity.Profiles.statusMonthsInUS",
   "Identity -> Profiles"."drivers_license_state" AS "Identity.Profiles.driversLicenseState",
   "Identity -> Profiles"."drivers_license_number" AS "Identity.Profiles.driversLicenseNumber",
   "Identity -> Profiles"."created_at" AS "Identity.Profiles.createdAt",
   "Identity -> Profiles"."updated_at" AS "Identity.Profiles.updatedAt",
   "Identity -> Profiles"."deleted_at" AS "Identity.Profiles.deletedAt",
   "Identity -> Profiles"."identity_id" AS "Identity.Profiles.identity_id",
   "Identity -> Profiles -> MedicalHistory"."id" AS "Identity.Profiles.MedicalHistory.id",
   "Identity -> Profiles -> MedicalHistory"."profile_id" AS "Identity.Profiles.MedicalHistory.profileId",
   "Identity -> Profiles -> MedicalHistory"."declared_health" AS "Identity.Profiles.MedicalHistory.declaredHealth",
   "Identity -> Profiles -> MedicalHistory"."declared_tobacco" AS "Identity.Profiles.MedicalHistory.declaredTobacco",
   "Identity -> Profiles -> MedicalHistory"."tobacco" AS "Identity.Profiles.MedicalHistory.tobacco",
   "Identity -> Profiles -> MedicalHistory"."tobacco_type" AS "Identity.Profiles.MedicalHistory.tobaccoType",
   "Identity -> Profiles -> MedicalHistory"."tobacco_last_used" AS "Identity.Profiles.MedicalHistory.tobaccoLastUsed",
   "Identity -> Profiles -> MedicalHistory"."tobacco_per_day" AS "Identity.Profiles.MedicalHistory.tobaccoPerDay",
   "Identity -> Profiles -> MedicalHistory"."tobacco_per_month" AS "Identity.Profiles.MedicalHistory.tobaccoPerMonth",
   "Identity -> Profiles -> MedicalHistory"."marijuana" AS "Identity.Profiles.MedicalHistory.marijuana",
   "Identity -> Profiles -> MedicalHistory"."marijuana_details" AS "Identity.Profiles.MedicalHistory.marijuanaDetails",
   "Identity -> Profiles -> MedicalHistory"."family_history" AS "Identity.Profiles.MedicalHistory.familyHistory",
   "Identity -> Profiles -> MedicalHistory"."family_history_details" AS "Identity.Profiles.MedicalHistory.familyHistoryDetails",
   "Identity -> Profiles -> MedicalHistory"."pregnant" AS "Identity.Profiles.MedicalHistory.pregnant",
   "Identity -> Profiles -> MedicalHistory"."pregnant_details" AS "Identity.Profiles.MedicalHistory.pregnantDetails",
   "Identity -> Profiles -> MedicalHistory"."prescriptions" AS "Identity.Profiles.MedicalHistory.prescriptions",
   "Identity -> Profiles -> MedicalHistory"."prescriptions_details" AS "Identity.Profiles.MedicalHistory.prescriptionsDetails",
   "Identity -> Profiles -> MedicalHistory"."hiv_aids" AS "Identity.Profiles.MedicalHistory.hivAids",
   "Identity -> Profiles -> MedicalHistory"."hiv_aids_details" AS "Identity.Profiles.MedicalHistory.hivAidsDetails",
   "Identity -> Profiles -> MedicalHistory"."circulatory_disorder" AS "Identity.Profiles.MedicalHistory.circulatoryDisorder",
   "Identity -> Profiles -> MedicalHistory"."circulatory_disorder_details" AS "Identity.Profiles.MedicalHistory.circulatoryDisorderDetails",
   "Identity -> Profiles -> MedicalHistory"."endocrine_disorder" AS "Identity.Profiles.MedicalHistory.endocrineDisorder",
   "Identity -> Profiles -> MedicalHistory"."endocrine_disorder_details" AS "Identity.Profiles.MedicalHistory.endocrineDisorderDetails",
   "Identity -> Profiles -> MedicalHistory"."ent_disorder" AS "Identity.Profiles.MedicalHistory.entDisorder",
   "Identity -> Profiles -> MedicalHistory"."ent_disorder_details" AS "Identity.Profiles.MedicalHistory.entDisorderDetails",
   "Identity -> Profiles -> MedicalHistory"."neurological_disorder" AS "Identity.Profiles.MedicalHistory.neurologicalDisorder",
   "Identity -> Profiles -> MedicalHistory"."neurological_disorder_details" AS "Identity.Profiles.MedicalHistory.neurologicalDisorderDetails",
   "Identity -> Profiles -> MedicalHistory"."oncological_disorder" AS "Identity.Profiles.MedicalHistory.oncologicalDisorder",
   "Identity -> Profiles -> MedicalHistory"."oncological_disorder_details" AS "Identity.Profiles.MedicalHistory.oncologicalDisorderDetails",
   "Identity -> Profiles -> MedicalHistory"."orthopedic_disorder" AS "Identity.Profiles.MedicalHistory.orthopedicDisorder",
   "Identity -> Profiles -> MedicalHistory"."orthopedic_disorder_details" AS "Identity.Profiles.MedicalHistory.orthopedicDisorderDetails",
   "Identity -> Profiles -> MedicalHistory"."psychological_disorder" AS "Identity.Profiles.MedicalHistory.psychologicalDisorder",
   "Identity -> Profiles -> MedicalHistory"."psychological_disorder_details" AS "Identity.Profiles.MedicalHistory.psychologicalDisorderDetails",
   "Identity -> Profiles -> MedicalHistory"."reproductive_disorder" AS "Identity.Profiles.MedicalHistory.reproductiveDisorder",
   "Identity -> Profiles -> MedicalHistory"."reproductive_disorder_details" AS "Identity.Profiles.MedicalHistory.reproductiveDisorderDetails",
   "Identity -> Profiles -> MedicalHistory"."respiratory_disorder" AS "Identity.Profiles.MedicalHistory.respiratoryDisorder",
   "Identity -> Profiles -> MedicalHistory"."respiratory_disorder_details" AS "Identity.Profiles.MedicalHistory.respiratoryDisorderDetails",
   "Identity -> Profiles -> MedicalHistory"."vascular_disorder" AS "Identity.Profiles.MedicalHistory.vascularDisorder",
   "Identity -> Profiles -> MedicalHistory"."vascular_disorder_details" AS "Identity.Profiles.MedicalHistory.vascularDisorderDetails",
   "Identity -> Profiles -> MedicalHistory"."prior_patient" AS "Identity.Profiles.MedicalHistory.priorPatient",
   "Identity -> Profiles -> MedicalHistory"."prior_patient_details" AS "Identity.Profiles.MedicalHistory.priorPatientDetails",
   "Identity -> Profiles -> MedicalHistory"."pending_tests" AS "Identity.Profiles.MedicalHistory.pendingTests",
   "Identity -> Profiles -> MedicalHistory"."pending_tests_details" AS "Identity.Profiles.MedicalHistory.pendingTestsDetails",
   "Identity -> Profiles -> MedicalHistory"."special_tests" AS "Identity.Profiles.MedicalHistory.specialTests",
   "Identity -> Profiles -> MedicalHistory"."special_tests_details" AS "Identity.Profiles.MedicalHistory.specialTestsDetails",
   "Identity -> Profiles -> MedicalHistory"."substance_use" AS "Identity.Profiles.MedicalHistory.substanceUse",
   "Identity -> Profiles -> MedicalHistory"."substance_use_details" AS "Identity.Profiles.MedicalHistory.substanceUseDetails",
   "Identity -> Profiles -> MedicalHistory"."substance_treatment" AS "Identity.Profiles.MedicalHistory.substanceTreatment",
   "Identity -> Profiles -> MedicalHistory"."substance_treatment_details" AS "Identity.Profiles.MedicalHistory.substanceTreatmentDetails",
   "Identity -> Profiles -> MedicalHistory"."transfusion" AS "Identity.Profiles.MedicalHistory.transfusion",
   "Identity -> Profiles -> MedicalHistory"."transfusion_details" AS "Identity.Profiles.MedicalHistory.transfusionDetails",
   "Identity -> Profiles -> MedicalHistory"."weight_change" AS "Identity.Profiles.MedicalHistory.weightChange",
   "Identity -> Profiles -> MedicalHistory"."weight_change_details" AS "Identity.Profiles.MedicalHistory.weightChangeDetails",
   "Identity -> Profiles -> MedicalHistory"."profile_id" AS "Identity.Profiles.MedicalHistory.profile_id",
   "Identity -> Profiles -> InsuranceHistory"."id" AS "Identity.Profiles.InsuranceHistory.id",
   "Identity -> Profiles -> InsuranceHistory"."profile_id" AS "Identity.Profiles.InsuranceHistory.profileId",
   "Identity -> Profiles -> InsuranceHistory"."existing_coverage" AS "Identity.Profiles.InsuranceHistory.existingCoverage",
   "Identity -> Profiles -> InsuranceHistory"."existing_coverage_carriers" AS "Identity.Profiles.InsuranceHistory.existingCoverageCarriers",
   "Identity -> Profiles -> InsuranceHistory"."other_coverage" AS "Identity.Profiles.InsuranceHistory.otherCoverage",
   "Identity -> Profiles -> InsuranceHistory"."other_coverage_details" AS "Identity.Profiles.InsuranceHistory.otherCoverageDetails",
   "Identity -> Profiles -> InsuranceHistory"."expense_declined" AS "Identity.Profiles.InsuranceHistory.expenseDeclined",
   "Identity -> Profiles -> InsuranceHistory"."expense_declined_details" AS "Identity.Profiles.InsuranceHistory.expenseDeclinedDetails",
   "Identity -> Profiles -> InsuranceHistory"."undergone_health_exams" AS "Identity.Profiles.InsuranceHistory.undergoneHealthExams",
   "Identity -> Profiles -> InsuranceHistory"."profile_id" AS "Identity.Profiles.InsuranceHistory.profile_id",
   "Identity -> Profiles -> OccupationalHistory"."id" AS "Identity.Profiles.OccupationalHistory.id",
   "Identity -> Profiles -> OccupationalHistory"."profile_id" AS "Identity.Profiles.OccupationalHistory.profileId",
   "Identity -> Profiles -> OccupationalHistory"."self_employed" AS "Identity.Profiles.OccupationalHistory.selfEmployed",
   "Identity -> Profiles -> OccupationalHistory"."net_annual_income" AS "Identity.Profiles.OccupationalHistory.netAnnualIncome",
   "Identity -> Profiles -> OccupationalHistory"."gross_annual_income" AS "Identity.Profiles.OccupationalHistory.grossAnnualIncome",
   "Identity -> Profiles -> OccupationalHistory"."occupation_details" AS "Identity.Profiles.OccupationalHistory.occupationDetails",
   "Identity -> Profiles -> OccupationalHistory"."profile_id" AS "Identity.Profiles.OccupationalHistory.profile_id",
   "Identity -> Profiles -> CriminalHistory"."id" AS "Identity.Profiles.CriminalHistory.id",
   "Identity -> Profiles -> CriminalHistory"."profile_id" AS "Identity.Profiles.CriminalHistory.profileId",
   "Identity -> Profiles -> CriminalHistory"."felony" AS "Identity.Profiles.CriminalHistory.felony",
   "Identity -> Profiles -> CriminalHistory"."felony_details" AS "Identity.Profiles.CriminalHistory.felonyDetails",
   "Identity -> Profiles -> CriminalHistory"."probation" AS "Identity.Profiles.CriminalHistory.probation",
   "Identity -> Profiles -> CriminalHistory"."probation_details" AS "Identity.Profiles.CriminalHistory.probationDetails",
   "Identity -> Profiles -> CriminalHistory"."vehicular" AS "Identity.Profiles.CriminalHistory.vehicular",
   "Identity -> Profiles -> CriminalHistory"."vehicular_details" AS "Identity.Profiles.CriminalHistory.vehicularDetails",
   "Identity -> Profiles -> CriminalHistory"."profile_id" AS "Identity.Profiles.CriminalHistory.profile_id",
   "Identity -> Profiles -> PersonalHistory"."id" AS "Identity.Profiles.PersonalHistory.id",
   "Identity -> Profiles -> PersonalHistory"."profile_id" AS "Identity.Profiles.PersonalHistory.profileId",
   "Identity -> Profiles -> PersonalHistory"."aviation" AS "Identity.Profiles.PersonalHistory.aviation",
   "Identity -> Profiles -> PersonalHistory"."aviation_details" AS "Identity.Profiles.PersonalHistory.aviationDetails",
   "Identity -> Profiles -> PersonalHistory"."bankruptcy" AS "Identity.Profiles.PersonalHistory.bankruptcy",
   "Identity -> Profiles -> PersonalHistory"."bankruptcy_details" AS "Identity.Profiles.PersonalHistory.bankruptcyDetails",
   "Identity -> Profiles -> PersonalHistory"."extreme_sports" AS "Identity.Profiles.PersonalHistory.extremeSports",
   "Identity -> Profiles -> PersonalHistory"."extreme_sports_details" AS "Identity.Profiles.PersonalHistory.extremeSportsDetails",
   "Identity -> Profiles -> PersonalHistory"."foreign_travel" AS "Identity.Profiles.PersonalHistory.foreignTravel",
   "Identity -> Profiles -> PersonalHistory"."foreign_travel_details" AS "Identity.Profiles.PersonalHistory.foreignTravelDetails",
   "Identity -> Profiles -> PersonalHistory"."military" AS "Identity.Profiles.PersonalHistory.military",
   "Identity -> Profiles -> PersonalHistory"."military_details" AS "Identity.Profiles.PersonalHistory.militaryDetails",
   "Identity -> Profiles -> PersonalHistory"."profile_id" AS "Identity.Profiles.PersonalHistory.profile_id",
   "Identity -> Profiles -> ProfileRequirements"."id" AS "Identity.Profiles.ProfileRequirements.id",
   "Identity -> Profiles -> ProfileRequirements"."profile_id" AS "Identity.Profiles.ProfileRequirements.profileId",
   "Identity -> Profiles -> ProfileRequirements"."admin_id" AS "Identity.Profiles.ProfileRequirements.adminId",
   "Identity -> Profiles -> ProfileRequirements"."reason" AS "Identity.Profiles.ProfileRequirements.reason",
   "Identity -> Profiles -> ProfileRequirements"."details" AS "Identity.Profiles.ProfileRequirements.details",
   "Identity -> Profiles -> ProfileRequirements"."resolution" AS "Identity.Profiles.ProfileRequirements.resolution",
   "Identity -> Profiles -> ProfileRequirements"."resolution_admin_id" AS "Identity.Profiles.ProfileRequirements.resolutionAdminId",
   "Identity -> Profiles -> ProfileRequirements"."created_at" AS "Identity.Profiles.ProfileRequirements.createdAt",
   "Identity -> Profiles -> ProfileRequirements"."updated_at" AS "Identity.Profiles.ProfileRequirements.updatedAt",
   "Identity -> Profiles -> ProfileRequirements"."deleted_at" AS "Identity.Profiles.ProfileRequirements.deletedAt",
   "Identity -> Profiles -> ProfileRequirements"."profile_id" AS "Identity.Profiles.ProfileRequirements.profile_id",
   "Identity -> Profiles -> ProfileRequirements"."resolution_admin_id" AS "Identity.Profiles.ProfileRequirements.resolution_admin_id",
   "Identity -> SSN"."id" AS "Identity.SSN.id",
   "Identity -> SSN"."identity_id" AS "Identity.SSN.identityId",
   "Identity -> SSN"."encrypted_value" AS "Identity.SSN.encrypted_value",
   "Identity -> SSN"."transunion_attempts" AS "Identity.SSN.transunion_attempts",
   "Identity -> SSN"."transunion_verified" AS "Identity.SSN.transunion_verified",
   "Identity -> SSN"."transunion_details" AS "Identity.SSN.transunion_details",
   "Identity -> SSN"."prefill_status" AS "Identity.SSN.prefill_status",
   "Identity -> SSN"."prefill_attempts" AS "Identity.SSN.prefill_attempts",
   "Identity -> SSN"."created_at" AS "Identity.SSN.createdAt",
   "Identity -> SSN"."updated_at" AS "Identity.SSN.updatedAt",
   "Identity -> SSN"."deleted_at" AS "Identity.SSN.deletedAt",
   "Identity -> SSN"."created_at" AS "Identity.SSN.created_at",
   "Identity -> SSN"."updated_at" AS "Identity.SSN.updated_at",
   "Identity -> SSN"."deleted_at" AS "Identity.SSN.deleted_at",
   "Identity -> SSN"."identity_id" AS "Identity.SSN.identity_id",
   "Identity -> PhoneNumbers"."id" AS "Identity.PhoneNumbers.id",
   "Identity -> PhoneNumbers"."identity_id" AS "Identity.PhoneNumbers.identityId",
   "Identity -> PhoneNumbers"."number" AS "Identity.PhoneNumbers.number",
   "Identity -> PhoneNumbers"."verified" AS "Identity.PhoneNumbers.verified",
   "Identity -> PhoneNumbers"."identity_id" AS "Identity.PhoneNumbers.identity_id",
   "Identity -> Addresses"."id" AS "Identity.Addresses.id",
   "Identity -> Addresses"."identity_id" AS "Identity.Addresses.identityId",
   "Identity -> Addresses"."type" AS "Identity.Addresses.type",
   "Identity -> Addresses"."street1" AS "Identity.Addresses.street1",
   "Identity -> Addresses"."street2" AS "Identity.Addresses.street2",
   "Identity -> Addresses"."locality" AS "Identity.Addresses.locality",
   "Identity -> Addresses"."region" AS "Identity.Addresses.region",
   "Identity -> Addresses"."postal_code" AS "Identity.Addresses.postalCode",
   "Identity -> Addresses"."country" AS "Identity.Addresses.country",
   "Identity -> Addresses"."identity_id" AS "Identity.Addresses.identity_id",
   "Groups"."id" AS "Groups.id",
   "Groups"."name" AS "Groups.name",
   "Groups"."type" AS "Groups.type",
   "Groups"."created_at" AS "Groups.created_at",
   "Groups"."updated_at" AS "Groups.updated_at",
   "Groups -> UsersGroups"."user_id" AS "Groups.UsersGroups.userId",
   "Groups -> UsersGroups"."group_id" AS "Groups.UsersGroups.groupId",
   "Groups -> UsersGroups"."role" AS "Groups.UsersGroups.role",
   "Groups -> UsersGroups"."group_id" AS "Groups.UsersGroups.group_id",
   "Groups -> UsersGroups"."user_id" AS "Groups.UsersGroups.user_id" 
FROM
   (
      SELECT
         "User"."id",
         "User"."lead_id" AS "leadId",
         "User"."password",
         "User"."password_change_required" AS "passwordChangeRequired",
         "User"."client_data" AS "clientData",
         "User"."object_id" AS "objectId",
         "User"."referrer_object_id" AS "referrerObjectId",
         "User"."created_at" AS "createdAt",
         "User"."updated_at" AS "updatedAt",
         "User"."deleted_at" AS "deletedAt" 
      FROM
         "Users" AS "User" 
      WHERE
         (
            "User"."deleted_at" > '2018-03-28 01:23:51.911 +00:00' 
            OR "User"."deleted_at" IS NULL
         )
         AND 
         (
            SELECT
               "user_id" 
            FROM
               "Emails" AS "Emails" 
            WHERE
               (
                  "Emails"."user_id" = "User"."id" 
                  AND 
                  (
("Emails"."deleted_at" > '2018-03-28 01:23:51.911 +00:00' 
                     OR "Emails"."deleted_at" IS NULL) 
                     AND "Emails"."email" = '0172wink@gmail.com'
                  )
               )
               LIMIT 1 
         )
         IS NOT NULL LIMIT 1
   )
   AS "User" 
   INNER JOIN
      "Emails" AS "Emails" 
      ON "User"."id" = "Emails"."user_id" 
      AND 
      (
("Emails"."deleted_at" > '2018-03-28 01:23:51.911 +00:00' 
         OR "Emails"."deleted_at" IS NULL) 
         AND "Emails"."email" = '0172wink@gmail.com'
      )
   LEFT OUTER JOIN
      "Identities" AS "Identity" 
      ON "User"."id" = "Identity"."user_id" 
      AND 
      (
         "Identity"."deleted_at" > '2018-03-28 01:23:51.911 +00:00' 
         OR "Identity"."deleted_at" IS NULL
      )
   LEFT OUTER JOIN
      "Profiles" AS "Identity -> Profiles" 
      ON "Identity"."id" = "Identity -> Profiles"."identity_id" 
      AND 
      (
         "Identity -> Profiles"."deleted_at" > '2018-03-28 01:23:51.911 +00:00' 
         OR "Identity -> Profiles"."deleted_at" IS NULL
      )
   LEFT OUTER JOIN
      "Medical_Histories" AS "Identity -> Profiles -> MedicalHistory" 
      ON "Identity -> Profiles"."id" = "Identity -> Profiles -> MedicalHistory"."profile_id" 
   LEFT OUTER JOIN
      "Insurance_Histories" AS "Identity -> Profiles -> InsuranceHistory" 
      ON "Identity -> Profiles"."id" = "Identity -> Profiles -> InsuranceHistory"."profile_id" 
   LEFT OUTER JOIN
      "Occupational_Histories" AS "Identity -> Profiles -> OccupationalHistory" 
      ON "Identity -> Profiles"."id" = "Identity -> Profiles -> OccupationalHistory"."profile_id" 
   LEFT OUTER JOIN
      "Criminal_Histories" AS "Identity -> Profiles -> CriminalHistory" 
      ON "Identity -> Profiles"."id" = "Identity -> Profiles -> CriminalHistory"."profile_id" 
   LEFT OUTER JOIN
      "Personal_Histories" AS "Identity -> Profiles -> PersonalHistory" 
      ON "Identity -> Profiles"."id" = "Identity -> Profiles -> PersonalHistory"."profile_id" 
   LEFT OUTER JOIN
      "Profile_Requirements" AS "Identity -> Profiles -> ProfileRequirements" 
      ON "Identity -> Profiles"."id" = "Identity -> Profiles -> ProfileRequirements"."profile_id" 
      AND 
      (
         "Identity -> Profiles -> ProfileRequirements"."deleted_at" > '2018-03-28 01:23:51.911 +00:00' 
         OR "Identity -> Profiles -> ProfileRequirements"."deleted_at" IS NULL
      )
   LEFT OUTER JOIN
      "SSNs" AS "Identity -> SSN" 
      ON "Identity"."id" = "Identity -> SSN"."identity_id" 
      AND 
      (
         "Identity -> SSN"."deleted_at" > '2018-03-28 01:23:51.911 +00:00' 
         OR "Identity -> SSN"."deleted_at" IS NULL
      )
   LEFT OUTER JOIN
      "Phone_Numbers" AS "Identity -> PhoneNumbers" 
      ON "Identity"."id" = "Identity -> PhoneNumbers"."identity_id" 
   LEFT OUTER JOIN
      "Addresses" AS "Identity -> Addresses" 
      ON "Identity"."id" = "Identity -> Addresses"."identity_id" 
   LEFT OUTER JOIN
      (
         "Users_Groups" AS "Groups -> UsersGroups" 
         INNER JOIN
            "Groups" AS "Groups" 
            ON "Groups"."id" = "Groups -> UsersGroups"."group_id"
      )
      ON "User"."id" = "Groups -> UsersGroups"."user_id";
```

This query can run from the `psql` command line in about ~22ms, but from a remote client can take up to 300ms, which I imagine is due to the network transfer time of sending such a long-ass query.

__Dialect:__ postgres
__Dialect version:__ 10.1
__Database version:__ 10.1
__Sequelize version:__ latest
__Tested with latest release:__ Yes

**Comment by sushantdhiman** [comment] 2018-03-28 04:40
Duplicate of https://github.com/sequelize/sequelize/issues/5708

**Closed by sushantdhiman** 2018-03-28 04:40 UTC
