### ISSUE TITLE
[5.0.0-beta.14] Generate UUIDV4 in the database

### ISSUE THREAD

**Issue by StefanFeederle** [sequelize/sequelize#10124] opened 2018-11-05 15:34 UTC
## What are you doing?

I'm trying to generate default UUIDs inside the database.
Postgres has a [pgcrypto ](https://www.postgresql.org/docs/9.4/static/pgcrypto.html) module to generate UUIDs. I can't do it in application code because we need to use a consistent UUID algorithm across different client languages.
This doesn't seem to be possible with sequelize right now:
```js
sequelize.define('part', {
	// more columns
	reference: {
	   type: Sequelize.DataTypes.UUID,
	   allowNull: false,
       unique: true,
	   defaultValue: Sequelize.literal('gen_random_uuid()'),
	},
});
```
```js
models.Part.bulkCreate(args.input.parts, { returning: true })
```

## What do you expect to happen?
* A column is created with gen_random_uuid() as its default value on the db-side
* Inserts without a `reference` field use the db method and return the UUID that was created by the db
* Inserts with a `reference` field use the value provided

## What is actually happening?
The insert is working correctly but does return an instance of Sequelize.literal() instead of the generated uuid.

_Output, either JSON or SQL_
`
INSERT INTO "parts" ("id","order_name","order_id","step_id","drawing","pos","quantity","comment","contour_exists","state","width","length","height","weight","identifier","created_at","updated_at") VALUES (DEFAULT,'Messeständer MC300',200552,80,'1800 437 00','4',2,'Plasmat.12x200x200 Knoten',false,'open','200','200','12','8',gen_random_uuid(),'2018-11-05 15:30:01.729 +00:00','2018-11-05 15:30:01.729 +00:00') RETURNING *;
`
![image](https://user-images.githubusercontent.com/11903965/48007536-26219580-e118-11e8-918a-82ef9a2de6e0.png)

__Dialect:__ postgres
__Dialect version:__ 7.5.0
__Database version:__ 11
__Sequelize version:__ 5.0.0-beta.14
__Tested with latest release:__ Yes

**Comment by sushantdhiman** [comment] 2018-11-05 17:03
Duplicate of https://github.com/sequelize/sequelize/issues/9151

**Closed by sushantdhiman** 2018-11-05 17:03 UTC
