### ISSUE TITLE
update method tries to insert null when receiving undefined 

### ISSUE THREAD

**Issue by jony89** [sequelize/sequelize#7056] opened 2016-12-29 21:22 UTC
## What you are doing?

I map some request to Sequelize model : 

```js
        var model = {
            title: req.body.title,
            description: req.body.description
        };
        models.job.update(model, {..}).then(() => {})
```

let say that req.body.title is undefined and req.body.description has value.
In the model, `title` cant be null.
For some reason sequelize tries to insert null to the title although it is undefined, resulting in getting the following error : 

> err.stack SequelizeValidationError: notNull Violation: title cannot be null

this happens probably because  model.hasOwnProperty('title') returns true, but yet, model.title is `undefined` and not `null`
## What do you expect to happen?

I think that in that case, when a field is undefined, Sequelize should not try to insert null into it (the title field) and just ignore it 

## What is actually happening?

i get an error : 

> err.stack SequelizeValidationError: notNull Violation: title cannot be null

I think we should insert null only when someone specifically specify that this field is null. 

__Dialect:__ mysql 
__Database version: 5.7.9
__Sequelize version: 3.28.0

**Comment by jony89** [comment] 2016-12-30 09:27
if i add :

```
  //remove undefined values
  Object.keys(values).forEach(function(key) {
    if (values[key] === undefined) {
      delete values[key];
    }
  }); 
```

at models.js after the comment :

> // Remove values that are not in the options.fields

it works well, I think we should insert null only when someone specifically specify that this field is null.

**Comment by jony89** [comment] 2017-01-07 15:18
any help?

**Comment by jony89** [comment] 2017-01-17 19:42
@sushantdhiman  could u help here? someone? :S

**Comment by jony89** [comment] 2017-01-24 09:02
if i add :

```js
  //remove undefined values
  Object.keys(values).forEach(function(key) {
    if (values[key] === undefined) {
      delete values[key];
    }
  }); 
```

at ./lib/models.js after the comment :

> // Remove values that are not in the options.fields

it works well, is this a possible solution ? should i create a PR?

**Comment by jony89** [comment] 2017-01-30 21:25
I've done few more testing and I found out that if the field allowed to have nulls, and i try to update with value undefined it actually skips it as desired.

This actually supports my claim.. but it gives a different approach, maybe the problem is only with the validation ? 

If it is skipped, then why the validation checks for undefined as well : 

>   if (rawAttribute.allowNull === false && ((value === null) || (value === undefined))) {
>     error = new sequelizeError.ValidationErrorItem(field + ' cannot be null', 'notNull Violation', field, value);
>     this.errors.push(error);
>   }

could be 

>   if (rawAttribute.allowNull === false && value === null) {
>     error = new sequelizeError.ValidationErrorItem(field + ' cannot be null', 'notNull Violation', field, value);
>     this.errors.push(error);
>   }

**further more**, if i remove that validation, everything works as magic. sequelize doesnt try to insert null/undefined to the field and just skips it.

**Comment by agalazis** [comment] 2017-03-14 22:40
that's true  the only way to  keep a value is to reinsert this sounds weird for an update especially foe people who are used to update just the field they want . @mickhansen  your input is appreciated.

**Comment by jony89** [comment] 2017-05-30 09:39
reproduced on sequelize v4 as well

**Comment by jony89** [comment] 2017-07-31 22:00
this issue still need to be fixed.

**Comment by jony89** [comment] 2017-09-30 16:33
please reopen this, still need to be resolved.

**Comment by sushantdhiman** [comment] 2017-09-30 16:35
I assume can be reproduced on master

**Comment by jony89** [comment] 2017-09-30 16:40
Didn't retest it for a while, but yeah

**Comment by gabegorelick** [comment] 2017-10-17 15:14
This behavior is fairly consistent throughout Sequelize; e.g. 
```js
Model.findAll({where: {foo: undefined}});
```

will run `SELECT ... WHERE foo IS NULL`. I personally find this inconvenient as it means I need to remove undefined values from my where options, but if that's the decision Sequelize has made then present-but-`undefined` values should be treated as NULL everywhere. Otherwise, it would probably require a major version bump to change this behavior.

**Comment by jony89** [comment] 2017-10-23 11:21
@gabegorelick , that is not correct.

As I shown above, there is different behaviour between nullable props and non-nullable props.

> I've done few more testing and I found out that if the field allowed to have nulls, and i try to update with value undefined it actually skips it as desired.
> 
> This actually supports my claim..

**Comment by millermatt** [comment] 2018-02-23 21:16
Until this is fixed there is no way to update fields in a record without also setting all of the non-null field values, even if those are not changing.

**Comment by writebeat** [comment] 2018-05-29 21:37
This is still an issue on v4

**Comment by writebeat** [comment] 2018-05-29 22:39
Workaround is to set the `fields` option on the update function to `Object.keys(req.body)`, worked for me, at least.

**Comment by schester44** [comment] 2018-06-09 04:48
@writebeat that seems to work. You can be a bit more verbose and spread only specific columns as well.

something like:
```

appointment.update({
            ...input.employeeId && { employeeId: input.employeeId },
            ...input.locationId && { locationId: input.locationId },
            ...input.startTime && { startTime: input.startTime },
            ...input.checkinTime && { checkinTime: input.checkinTime },
            ...input.endedTime && { endedTime: input.endedTime }
        })
```

**Comment by gabegorelick** [comment] 2018-06-20 15:11
May be resolved by #9548.

**Comment by Alexsey** [comment] 2018-06-20 15:58
No, it would not be resolved with #9548 because that one is only about `undefined` in `where` and here we have `undefined` in update object

**Comment by jony89** [comment] 2018-06-21 06:22
I've created a PR for this a while ago : https://github.com/sequelize/sequelize/pull/7167
I'm pretty sure this is the correct solution, yet it was for v3 and the test did not pass, need to give it some more time. I'll try to redo it this weekend.

**Closed** 2018-06-24 15:44 UTC
Labels: bug

**Comment by 1valdis** [comment] 2018-09-16 10:58
This is still an issue for me on v4.38.1. When we'd expect a fix?

**Comment by jony89** [comment] 2018-09-16 11:32
Can u share some code ? This should be fixed. it is tested manual+unit tests.

**Comment by 1valdis** [comment] 2018-09-16 15:35
Here you go. I have a User model with field 'name' on it:
```javascript
module.exports = (sequelize, types) => {
  const User = sequelize.define(
    'user',
    {
      // some fields...
      name: {
        type: types.STRING,
        allowNull: false,
        validate: {
          notEmpty: {
            msg: 'Name cannot be empty'
          }
        }
      },
      // some other fields...
    }, /* some options... */
  )

  return User
}
```
I `import` it to Sequelize. I have an api route to edit a user. It looks like this:
```javascript
exports.editMe = async (req, res) => {
    //assume that req.body is empty object here
    req.body.name = undefined
    //if I uncomment next line, it works as expected, not trying to insert null
    //delete req.body.name
    console.log(req.body) // {name: undefined}
    await user.update(req.body) // SequelizeValidationError: notNull Violation: user.name cannot be null
}
```
