### ISSUE TITLE
intermittent connection hanging with no errors using .authenticate()

### ISSUE THREAD

**Issue by nickr-davey** [sequelize/sequelize#12363] opened 2020-06-10 23:18 UTC
## Intermittent connection hanging with no errors using .authenticate()

I am using lambda functions and RDS postgres 10.6

Using both v4 and v5 and pg 7+ and 8+ I get an issue where sometimes the connection is never established I think. It seeems to just hang in the authenticate() function where it is not returning an error or resolving. 
I have gone through the other issues where people were running into this issue on v4 so I updated to v5 but I still see the same problem. When it happens once it wont get out of this state until and new instance of the function is created. It is really hard to debug when there are no errors happening and my function will just timeout.

It makes no difference using context.callbackWaitsForEmptyEventLoop = false; or increasing or decreasing the idle time.

#### I never see - executing (default): SELECT 1+1 AS result. when this happens so I am not sure what is happening is it isn't trying to see if it is connected.

`
  sequelize = new Sequelize(database, username, password, {
    host: host,
    dialect: "postgres",
    pool: { max: 1, min: 0, idle: 1000 },
    logging: console.log,
  
  });

.........

  try {
    await sequelize.authenticate();
      console.log("Connection established");
    }
    return sequelize;
  } catch (error) {
    console.error("--------------  database error:", error);
    throw error;
  }
`

### Is this issue dialect-specific?
- [x] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time but I don't know how to start, I would need guidance.

**Comment by sushantdhiman** [comment] 2020-06-11 04:24
Duplicate of https://github.com/sequelize/sequelize/issues/12158

Follow the template next time

**Closed by sushantdhiman** 2020-06-11 04:24 UTC

**Comment by nickr-davey** [comment] 2020-06-11 04:27
Not a duplicate as we are using node 12.x also same thing happens with node 10.x , 
and filled out the template as well.

**Comment by sushantdhiman** [comment] 2020-06-11 04:39
@nickr-davey Then reopen issue by properly following template, you missed versions, dialect and reproduction code etc. Spend some time to properly present your use case, see examples from other open issues

**Comment by marcogrcr** [comment] 2020-08-26 20:55
For people experiencing issues in AWS Lambda, I have created a pull request that documents how to properly configure `sequelize` for Lambda. Hopefully you'll be able to see it in <https://sequelize.org/master/manual/aws-lambda.html> once it gets merged. In the meantime, please check #12642 out and provide feedback if you find any inaccuracies or space for improvement.
