### ISSUE TITLE
Deprecated use of custom inspect function `DEP0079`

### ISSUE THREAD

**Issue by SimonSchick** [sequelize/sequelize#10104] opened 2018-10-31 13:19 UTC
## What are you doing?
```require('sequelize')```

## What do you expect to happen?

No warning.

## What is actually happening?

```> (node:94309) [DEP0079] DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated```

This has been deprecated since 8.7.0

**Comment by sushantdhiman** [comment] 2018-10-31 13:21
Duplicate of https://github.com/sequelize/sequelize/issues/9801 , but will keep this open

**Comment by SimonSchick** [comment] 2018-10-31 13:29
i forgot to post the link, sorry: https://nodejs.org/api/deprecations.html#deprecations_dep0079_custom_inspection_function_on_objects_via_inspect

**Comment by SimonSchick** [comment] 2018-10-31 13:33
@sushantdhiman on that note, you probably want to increment the minimum node version for v5 to something like `6.14` to ensure that all node v6 features we are using are available.

For instance, using the custom inspector symbols requires at least v6.6.0

**Closed** 2020-05-17 09:50 UTC
Labels: breaking change, status: understood, type: other
