### ISSUE TITLE
setAssociations() and scope delete all associations...

### ISSUE THREAD

**Issue by Ndrou** [sequelize/sequelize#8954] opened 2018-01-26 12:53 UTC
## What are you doing?

I have 2 tables, and a many to many association. I used scope to organize my associations.

When i do a setAssociation() (scoped association), i tried to use the setxxxx() function on the 2 scoped associations consecutively.

## What do you expect to happen?
The 2 scoped associations should'nt delete other scoped associations before add... 

## What is actually happening?

It deletes all the other associated records (not in scope).

Below a part of my model associations :
```js
db.company.belongsToMany(db.taxonomy, {
    through: db.companyTaxonomy,
});
db.company.belongsToMany(db.taxonomy, {
    through: db.companyTaxonomy,
    as: 'skills',
    scope: {
        vocabularyId: 'company_skills',
    },
});
db.company.belongsToMany(db.taxonomy, {
    through: db.companyTaxonomy,
    as: 'certifications',
    scope: {
        vocabularyId: 'company_certifications',
    },
});
```

And when i do a delete : 
```js
await data.setCertifications(certifications);
await data.setSkills(skills);
```

`setCertifications` delete all association records between my company and my taxonomies.
`setSkills` delete all association records between my company and my taxonomies.

So, the certifications are never setted.

__Dialect:__ mysql2
__Dialect version:__ 1.4.2
__Database version:__ 5.7.18
__Sequelize version:__ 4.22.0
__Tested with latest release:__ Yes (v4.32.1)

**Comment by sushantdhiman** [comment] 2018-01-26 12:58
Duplicate of https://github.com/sequelize/sequelize/issues/8890

**Closed by sushantdhiman** 2018-01-26 12:58 UTC
