### ISSUE TITLE
FindOrCreate concurrent update error with Postgres

### ISSUE THREAD

**Issue by OlivierCuyp** [sequelize/sequelize#2400] opened 2014-10-07 12:43 UTC
Hi guys, I'm using the sequelize version 2.0.0-rc1 with postgres.
My project receive third party notifications on invoices and try to update or create the invoice if it doesn't exists.
Sometimes I receive simultaneous notifications about the same invoice (e.g.: for trial invoice, open + close) which sometime end up with this error : 

```
SequelizeDatabaseError: error: could not serialize access due to concurrent update
        at module.exports.Query.formatError (/var/www/my_project/node_modules/sequelize/lib/dialects/postgres/query.js:248:16)
        at null.<anonymous> (/var/www/my_project/node_modules/sequelize/lib/dialects/postgres/query.js:65:21)
        at EventEmitter.emit (events.js:95:17)
        at Query.handleError (/var/www/my_project/node_modules/pg/lib/query.js:101:8)
        at null.<anonymous> (/var/www/my_project/node_modules/pg/lib/client.js:167:26)
        at EventEmitter.emit (events.js:95:17)
        at Socket.<anonymous> (/var/www/my_project/node_modules/pg/lib/connection.js:109:12)
        at Socket.EventEmitter.emit (events.js:95:17)
        at Socket.<anonymous> (_stream_readable.js:746:14)
        at Socket.EventEmitter.emit (events.js:92:17)
```

I could bind this error on transaction thanks to this explanation : http://stackoverflow.com/questions/7705273/what-are-the-conditions-for-encountering-a-serialization-failure

But still not sure on how to fix this.

**Comment by OlivierCuyp** [comment] 2015-02-06 10:53
@janmeier Sorry for the delay. This bug was really a concurrency issue which was really difficult to reproduce. We are now using the rc8 and I don't see this error anymore in our logs.
So I guess this have been corrected somehow. Maybe someone else can confirm @rayshan can confirm.

**Comment by janmeier** [comment] 2015-02-06 11:00
@OlivierCuyp thanks for the feedback. Closing this, but feel free to comment if you encounter the issue again

**Closed by janmeier** 2015-02-06 11:00 UTC
Labels: bug

**Comment by chris-rock** [comment] 2015-02-06 11:32
@janmeier I upgraded to rc8 and the issue is gone. Thanks for the hard work.

**Comment by OlivierCuyp** [comment] 2015-02-24 09:51
@janmeier checking the log this morning,  I still see some : 

```
SequelizeDatabaseError: could not serialize access due to concurrent update
    at module.exports.Query.formatError (/var/www/node_modules/sequelize/lib/dialects/postgres/query.js:309:16)
    at null.<anonymous> (/var/www/node_modules/sequelize/lib/dialects/postgres/query.js:64:21)
    at emit (events.js:95:17)
    at Query.handleError (/var/www/node_modules/pg/lib/query.js:101:8)
    at null.<anonymous> (/var/www/node_modules/pg/lib/client.js:176:26)
    at emit (events.js:95:17)
    at Socket.<anonymous> (/var/www/node_modules/pg/lib/connection.js:109:12)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:764:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    at emitReadable (_stream_readable.js:422:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
    at TCP.onread (net.js:528:21)
```

But less, I assume that the queries build by RC8 are faster so this happens less but still happen.
Maybe @chris-rock can give some feedback too.

**Comment by janmeier** [comment] 2015-02-24 09:52
If you can give me a small-ish test case that can reproduce the problem I'd be happy to look more into it

**Comment by ronelliott** [comment] 2015-03-19 21:35
My team is having this issue as well, 2.0.0-rc8. Getting a reproducible test case will be difficult, still trying to figure out exactly what is causing the issue.

**Comment by janmeier** [comment] 2015-03-23 06:50
@ronelliott Do you experience the same issues on 2.0.5?

**Comment by apankov** [comment] 2016-03-31 08:45
Today I had same error running on 3.20.0 and Postgres. I was creating some item within transaction, but hook "beforeCreate" was doing some updates over same table without transaction. Passing same transaction reference into beforeCreate hook solved the issue.

**Comment by intiQuo** [comment] 2016-04-04 08:59
Today I had same error =)
I'm not sure, but I think, this error may happen when findOrCreate query returns more then one row.

**Comment by Amnacog** [comment] 2016-05-17 15:26
Multitple time, I had this error,
Running with sequelize v3.21.0
Without any transactions,
this line made me crash (not always):
```
db.Invoice.findOrCreate({ where: {id: owner, completed: false, status: 'ongoing', type: 'simple'}}).spread(function (result, created) { ... });
```

so +1 👍 :)

**Comment by janmeier** [comment] 2016-05-17 20:36
@Amnacog can you create a [SSCCE](HTTP://SSCCE.ORG/)?

**Comment by Amnacog** [comment] 2016-05-23 14:26
Sorry but my code is under the nda of my enterprise, but this is the sql raw output of the findOrCreate
http://pastebin.com/xkKyaH4j

**Comment by janmeier** [comment] 2016-05-23 14:29
@Amnacog You don't need to post the exact code, but you need to post some code that reproduces the error - Otherwise it is _impossible_ for us to fix anything :)

**Comment by aaronryden** [comment] 2017-04-07 22:03
i'm getting this error...

SequelizeDatabaseError: could not serialize access due to concurrent update
    at Query.formatError (/root/behance/node_modules/sequelize/lib/dialects/postgres/query.js:357:14)
    at Query.<anonymous> (/root/behance/node_modules/sequelize/lib/dialects/postgres/query.js:88:19)
    at emitOne (events.js:96:13)


...has to do with

sql: 'CREATE OR REPLACE FUNCTION pg_temp.testfunc(OUT response "TABLE", OUT sequelize_caught_exception text) RETURNS RECORD AS $func_043183608cd0444b9a22b6a28b36e733$ BEGIN INSERT INTO...

Seems to happen when i run multiple findOrCreate statements from different processes or nodes on the same db.

**Comment by mhuggins** [comment] 2017-08-21 01:00
Is there a solution for this?  I'm encountering this with 3.29.0.
