### ISSUE TITLE
Sequelize misbehaving with Node v14

### ISSUE THREAD

**Issue by kororos** [sequelize/sequelize#12158] opened 2020-04-23 12:17 UTC
Today I upgraded to Node v14. However, I run into some interesting issue, most probably with Sequelize. 

The problem that I run into is that in a normal execution of my app, sequelize will never return from the queries. However, if I run my program using VSCode debug, it goes through without problems. I have tried it with both v5.21.7 and v6.0.0.-beta.5 

Below is the package.json that I have. Note that CLS is not used for Sequelize. I was hoping to replace CLS with Node v14  AsyncLocalStorage. 

```
{
  "name": "backend",
  "version": "1.0.0",
  "main": "app.js",
  "author": "",
  "license": "MIT",
  "scripts": {
    "start": "babel-node src/app.js",
    "dev": "nodemon --watch src --exec BABEL_DISABLE_CACHE=1 babel-node src/app.js",
    "lint": "eslint --fix src",
    "clean": "rimraf dist",
    "build": "babel src -d dist --source-maps --copy-files",
    "build_prod": "babel src -d dist --copy-files",
    "clean-build": "yarn run clean && yarn run build"
  },
  "devDependencies": {
    "@babel/cli": "^7.8.4",
    "@babel/core": "^7.9.0",
    "@babel/node": "^7.8.7",
    "@babel/preset-env": "^7.9.5",
    "babel-polyfill": "^6.26.0",
    "eslint": "^6.8.0",
    "jsdoc": "^3.6.4",
    "rimraf": "^3.0.2"
  },
  "dependencies": {
    "babel-plugin-inline-dotenv": "^1.5.0",
    "bcrypt": "^4.0.1",
    "body-parser": "^1.19.0",
    "continuation-local-storage": "^3.2.1",
    "cors": "^2.8.5",
    "express": "^4.17.1",
    "express-session": "^1.17.0",
    "jsonwebtoken": "^8.5.1",
    "nodemon": "^2.0.3",
    "pg": "^8.0.2",
    "pg-hstore": "^2.3.3",
    "sequelize": "^5.21.7",
    "sequelize-cli": "^5.5.1"
  }
}
```

**Comment by Vardiak** [comment] 2020-04-23 13:02
I have the same problem, the `sequelize.authenticate()` method doesn't resolve, without any error.

**Comment by papb** [comment] 2020-04-23 16:27
Hmm... Can someone please create a minimal reproducible example for this?

**Comment by tevonsb** [comment] 2020-04-23 17:40
We are having the same issue. Will post a minimal example soon!

**Comment by tevonsb** [comment] 2020-04-23 17:51
I can confirm that the issue is node v14, when we downgrade to 13.x.x the issue goes away. We are using sequelize 5.21.7. 

The issue we experience is: any sequelize call (sync, findOne, etc) hangs indefinitely with no error messages. For us, this caused Heroku to time out our servers main process.

**Comment by papb** [comment] 2020-04-23 18:15
The first hypothesis that comes to my mind is that something is wrong with Bluebird in Node 14...

**Comment by dioslibre** [comment] 2020-04-23 19:48
The problem I think is in `pg` and not `sequelize`. `sequelize.authenticate()` doesn't resolve because `pg.client.connect()` does not resolve. sqlite on the other hand works fine.

**Comment by kororos** [comment] 2020-04-23 20:20
I have some findings. I tried with a very simple project and it worked. I examined the differences between the packages of this simple project and the project where I faced the issue that I reported and I noticed that in the working project, I had pg@8.0.3. When I installed version 8.0.2 of pg it failed with node v14 (silently) but worked with version 13.13.0. With this in mind I believe that upgrading pg@8.0.3 may resolve the problem.

**Comment by dioslibre** [comment] 2020-04-23 21:08
Yes @kororos, upgrading pg@8.0.3 did resolve the problem.

**Comment by papb** [comment] 2020-04-26 14:13
By the way there has been some unexpected breaking changes in Node 14 regarding streams as well, not sure if related: https://github.com/nodejs/node/issues/33050 and https://github.com/nodejs/node/issues/32954

**Comment by ryosua** [comment] 2020-05-09 20:49
Thanks @kororos ! Updating pg worked for me too.

**Comment by juberjj** [comment] 2020-05-12 22:18
Thanks a lot @kororos upgrading pg@8.0.3 worked as it should.

**Comment by kd-krishna** [comment] 2020-06-03 11:32
@tevonsb jeez thanks a lot , downgrading nodejs version did the trick. I was going mad as to what was going on.

**Comment by kororos** [comment] 2020-06-03 12:20
@kd-krishna check my earlier comment above

**Comment by kororos** [comment] 2020-06-03 12:22
I accidentally closed the issue. Reopened it now.

**Comment by serg1ua** [comment] 2020-06-12 04:01
Got the same issue on Node 14 and sequelize: 5.8.5. On Node v12.18.0 works perfectly

**Comment by alsohi24** [comment] 2020-10-11 07:40
Hello guys, WHY the latest version doesn't work (6.3.5)? . I had to go back to version 5.21.7.
node v14.5.0.
I was following this guide [Building a Serverless Application in AWS using React and Claudiajs](https://blog.kloud.com.au/2018/08/29/building-a-serverless-application-in-aws-using-react-and-claudiajs/)
My package.json:
````
{
  "name": "quryappgwaws",
  "version": "1.2.0",
  "description": "Backend for Serverless qury",
  "main": "app.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "claudia create --region us-east-1 --api-module app --profile claudia",
    "deploy": "claudia update --use-local-dependencies"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {},
  "dependencies": {
    "aws-sdk": "^2.771.0",
    "claudia": "^5.1.1",
    "claudia-api-builder": "^4.1.2",
    "mysql": "^2.18.1",
    "mysql2": "^2.2.5",
    "sequelize": "^5.21.7"
  }
}```

**Comment by arl-ray** [comment] 2020-10-15 18:20
Spent 2 days on this issue. Promises don't resolve or reject. Noticed my node version was 14 for "some reason" on the third day

went back to node 10 and it worked as expected

**Comment by MarouaneSH** [comment] 2020-10-22 14:28
upgrading to pg@8.0.3  resolve the problem with node v14

**Comment by sarifconrati** [comment] 2020-11-06 11:09
Upgrading the pg version solves the issue. It seems to be an issue with node version > 14.

**Comment by debuggy** [comment] 2020-11-17 05:54
Exactly the issue I met just now.
It is hard to find this issue from internet before realizing what the problem is, and it is easy to find this issue immediately after finding out the reason.
What a paradox 😹

**Comment by bbalban** [comment] 2020-11-21 19:59
exact same problem. resolved by updating pg from 7.x to 8.x latest: npm install pg@latest.

express js / nodejs hangs in node bin/www without printing Listening on port xxxx. It turned out the models.sequelize.sync() call never returns. This happened after upgrading node to 14.x and also upgrading the mac machine to big sur

**Comment by leobeosab** [comment] 2021-01-27 09:57
Upgrading PG did it for me as well, thanks everyone!

**Comment by christiansr85** [comment] 2021-02-08 15:18
Not working for me using the latest `pg` version. I'm using `v14.15.4` of `node`.

These are the most relevant dependencies for this case (actually, I was using `v6.3.5` of `sequelize` but I updated it to its latest version in order to test if it works, but it doesn't):
```
"pg": "^8.5.1",
"sequelize": "^6.5.0",
"sequelize-cli": "^6.2.0"
```
All my dependencies:
```
"dependencies": {
    "btoa": "^1.2.1",
    "config": "^3.3.3",
    "dotenv": "^8.2.0",
    "jsonschema": "^1.4.0",
    "jsonwebtoken": "^8.5.1",
    "node-fetch": "^2.6.1",
    "pg": "^8.5.1",
    "sequelize": "^6.5.0",
    "uuid": "^8.3.2"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/node": "^7.12.6",
    "@babel/plugin-proposal-private-methods": "^7.12.1",
    "@babel/preset-env": "^7.12.7",
    "@babel/register": "^7.12.1",
    "@sewan/eslint-config-sewan-base": "2.0.2",
    "@sewan/eslint-config-sewan-node": "2.0.2",
    "babel-loader": "^8.2.2",
    "clean-webpack-plugin": "^3.0.0",
    "eslint": "7.15.0",
    "eslint-config-airbnb-base": "14.2.1",
    "eslint-import-resolver-alias": "^1.1.2",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-jest": "^24.1.3",
    "eslint-plugin-json": "^2.1.2",
    "eslint-plugin-md": "^1.0.19",
    "eslint-plugin-node": "11.1.0",
    "jest": "^26.6.3",
    "nodemon": "^2.0.6",
    "nodemon-webpack-plugin": "^4.3.2",
    "npm-package-json-lint": "^5.1.0",
    "npm-run-all": "4.1.5",
    "remark-lint": "8.0.0",
    "remark-preset-lint-markdown-style-guide": "^4.0.0",
    "sequelize-cli": "^6.2.0",
    "webpack": "^4.44.2",
    "webpack-cli": "^4.2.0",
    "webpack-graphql-loader": "^1.0.2",
    "webpack-merge": "^5.4.1",
    "webpack-node-externals": "^2.5.2"
  }
```

**Comment by marcelomanchester** [comment] 2021-02-11 13:23
The upgrading works for me, thanks!!! @kororos

**Comment by gregbelyea71** [comment] 2021-02-18 17:18
upgrade gave me an error which i did not have time to troubleshoot probably something to do with my authenticate call, but setting node back to 13.x had me back up and running quickly, but that was a nail biter as i had no clue what was wrong before alot of drilling

**Comment by LucaProvencal** [comment] 2021-03-02 02:14
Upgrading `pg` worked here as well. So strange, does anyone know how it can crash without an error message? I even wrapped in try/catch and no error was caught🤔

**Comment by imnotdannorton** [comment] 2021-03-06 22:32
after far too long thinking something was just wrong with my Postgres install it would appear upgrading `pg` was the culprit. node 15.4. quite surprised to just get zero feedback at all as @LucaProvencal mentioned.

**Comment by bwoodlt** [comment] 2021-03-23 16:57
I've tried everything mentioned here, nothing works.

Tried different node version, `12.8.3`, `13.3.0`, with `pg: 8.0.3`& `pg: 8.5.2`. None worked. 

I can't debug. Its been two days... pretty frustrating...

I'm logging into my docker container and im certain of the node version installed.

If anyone has other pointers, please assist. Thanks.

**Comment by papb** [comment] 2021-03-23 23:10
Hello everyone, in particular @imnotdannorton and @LucaProvencal, does everyone confirm that the issue was caused by either `pg@8.0.0`, `pg@8.0.1` or `pg@8.0.2`?

**Comment by imnotdannorton** [comment] 2021-03-26 13:51
@papb upgrading from `^7.17.0` to `^8.5.1` did the trick for me.

**Comment by papb** [comment] 2021-03-26 15:26
@imnotdannorton Hmm, thanks, so `7.17.0` also causes the issue.

**Comment by IvanMtze** [comment] 2021-05-27 03:43
Upgrading to ^8.0.3 works. I think this issue can be closed.

**Comment by renecardozo** [comment] 2021-06-15 21:38
in my case I did confirm the issue are related with node v14, I was facing about 2 hours trying to understand what was happening in my project so downgrading my node to v12.22.1 my project works. I am using nvm.

**Comment by DiySane** [comment] 2021-06-21 21:19
Thank you so much @renecardozo !!! It saved me from many more days of fruitless investigation.

**Comment by boobo94** [comment] 2021-06-26 15:58
Updating pg library from `^7.18.2` to `^8.6.0` worked for me with sequelize `^5.22.4`

**Comment by papb** [comment] 2021-06-26 18:15
I will leave this issue open for now, PR welcome to add a warning for people using `pg` below version 8

**Comment by slavoroi** [comment] 2021-06-28 08:29
I can confirm that upgrading to pg 8+ worked.
```
    "pg": "8.6.0",
    "sequelize": "4.44.4"
```
Beforehand we had pg 6 + in one of our dependencies which caused a `connect` method to not resolve.

**Comment by nickzelei** [comment] 2021-08-11 20:48
> I can confirm that upgrading to pg 8+ worked (with node 14.17.1)
> 
> ```
>     "pg": "8.6.0",
>     "sequelize": "4.44.4"
> ```
> 
> Beforehand we had pg 6 + in one of our dependencies which caused a `connect` method to not resolve.

This worked for me as well. I'm upgrading a legacy system from node 12 to 14 and are almost on identical versions!

```
  "pg": "6.4.2",
  "sequelize": "4.44.0"
```

Bumping to `pg@8.7.1` rectified this.

**Comment by eliasfeijo** [comment] 2021-08-18 02:54
Same problem here, but bumping versions didn't work for me, I've tried node 14, 12 and 10, pg 8.7.1, sequelize 6.6.5... the program hangs on `await connection.authenticate()` and doesn't throw an error or timeout... in my case this bug started happening after I changed the database configuration of my application, but I've tested the connection running a script with pg only, and it works just fine with that same db config... I don't know what to do now, it's very frustrating that it only happens with sequelize and not with the pg script =/

**Comment by r0bynh00d** [comment] 2021-09-07 20:57
> I can confirm that the issue is node v14, when we downgrade to 13.x.x the issue goes away. We are using sequelize 5.21.7.
> 
> The issue we experience is: any sequelize call (sync, findOne, etc) hangs indefinitely with no error messages. For us, this caused Heroku to time out our servers main process.

You just saved me! I'd already spent 2+ days fighting with this issue in vain. Thank you.

**Comment by khaled** [comment] 2021-09-30 00:38
FWIW, I ran into this problem when I upgraded from `node:12.18.4-slim` to `node:12.22.6-bullseye-slim` as my base container, using sequelize 6.6.5 and pg 7.18.2.  I tried updating pg to 8.7.1 and it did not help.  I downgraded my base container back to `node:12.18.4-slim` and the problem went away.

**Comment by acharb** [comment] 2021-12-08 23:39
Looks like the issue is for other Node versions as well. I ran into this problem of `sequelize.authenticate()` getting stuck when I upgraded a project from Node v10 to v16 (but thankfully saw this thread 😄 ), and going from pg `^7.4.3` to `^8.7.0` fixed it for me

**Comment by ranierimazili** [comment] 2021-12-17 12:59
Same problem here, but with mysql...
I has having the problem with Node v12.22.1, so I updated to v14.18.2 and the problem persists.

"sequelize": "^6.11.0"
"mysql2": "^2.3.3"

**Comment by ranierimazili** [comment] 2021-12-17 13:14
Just found the reason for my problem...
First I was trying findOne with the following code:

`const organisationInfo: ITPSharedData = await ITPSharedData.findOne({ where: { organisation_id: "8292c33e-d95a-5fe7-8f27-dd7a95c68b55" } });`        

The code above was hanging without any error message... The I tried with code below:

```
ITPSharedData.findOne({ where: { organisation_id: "8292c33e-d95a-5fe7-8f27-dd7a95c68b55" } })
        .then(a => {
            console.log(a);
        })
        .finally(() => {
            sequelize.close();
        });
```

And it "worked", showing the error message and the error was that sequelize was adding in the query the columns createdAt and updatedAt, and I don't have these columns on my table, so to make sequelize work without add these coluns I had to define my sequelize instance as below:

```
const sequelize = new Sequelize("mysql://<user>:<pass>@<server>:<port>/<db>",
    {   
        define: {
            timestamps: false
        }
    }
);    
```

and now my code with await works

**Comment by PabloRosales** [comment] 2022-02-22 20:05
Had the same issue, no error or any message, updating the `pg` package worked for me while upgrading to Node 16.

Code had: 

```await database.authenticate();```

This is on a legacy app with Sequelize 4. A google search took me here.

**Comment by ephys** [comment] 2022-02-25 11:04
I'll close this issue as it's now documented that only pg 8 supports Node >= 14: https://sequelize.org/v6/manual/dialect-specific-things.html#postgresql

I would recommend upgrading to Sequelize 6, as Sequelize < 6 is not maintained anymore and we can't guarantee that they will continue working with more recent versions of node, or pg.

**Closed by ephys** 2022-02-25 11:04 UTC
Labels: dependency, dialect: postgres, status: understood, existing workaround, type: other, P4: nice to have

**Comment by amzbiz** [comment] 2022-07-25 09:02
Same issue for me, tried the error handling as recommended by others and still couldn't track down an error. Eventually identified that it was one of our internal packages node_modules that were the issue. I.e. they were old version of pg / sequelize etc. still. Once they were upgraded as well everything worked as expected.

**Comment by nitishsainani** [comment] 2022-08-30 13:03
Issue happening with me tried almost all combinations above

**Comment by amzbiz** [comment] 2022-08-30 22:55
Recently upgraded to Node 16 and had this issue again, was also further modules in one of our packages that needed to be upgraded to later versions, all postgres/database related.

**Comment by lualparedes** [comment] 2022-11-05 22:48
> My good silent errors are the worst at all for any developer after 2 days. Anyway thanks for your tips, I upgraded to : `"pg": "^8.7.3", "pg-hstore": "^2.3.4", "sequelize": "^6.20.1", "sequelize-cli": "^6.4.1",` and my node version is v18.2.0. After making the upgrade I can see typical errors and now works perfect.
> 
> Be careful devs and I hope this helps for some one else :)

Tried this and didn't work :disappointed:

**Comment by benjaminHarroch** [comment] 2023-04-02 12:31
i have the same issue , after  changing all package to :
"pg": "^8.7.3", "pg-hstore": "^2.3.4", "sequelize": "^6.20.1", "sequelize-cli": "^6.4.1"

my node version is v16.7

some one please can help me?

**Comment by amzbiz** [comment] 2023-04-02 20:14
Hi Benjamin, it's a matter of finding the right versions for your particular version of node, we were on 16.15 and using these versions which worked:    "pg": "8.3.0", "pg-hstore": "2.3.3", "pg-promise": "10.9.1", "sequelize": "6.3.3". We used exact versions rather than allowing upgrade to make sure that they stayed working together.

**Comment by UmerMIB** [comment] 2023-04-20 21:27
> My good silent errors are the worst at all for any developer after 2 days. Anyway thanks for your tips, I upgraded to : `"pg": "^8.7.3", "pg-hstore": "^2.3.4", "sequelize": "^6.20.1", "sequelize-cli": "^6.4.1",` and my node version is v18.2.0. After making the upgrade I can see typical errors and now works perfect.
> 
> Be careful devs and I hope this helps for some one else :)

Didn't worked for me on ubuntu  20.04

**Comment by windsome** [comment] 2023-04-28 14:48
hang at `new Sequelize("posgres://samplehost:5432",{database:"dbname"})`, when database not exist. 
versions:
sequelize: "6.31.0",
pg: "8.10.0",
pg-hstore:"2.3.4"
node: "16.15.1",

**Comment by ConstantinTuca** [comment] 2024-08-09 08:51
Upgrading the "pg" version also solved the problem for me
"pg": "8.11.3",
"sequelize": "6.37.3",
"node": "20.13.1"
