### ISSUE TITLE
Support for inet datatype?

### ISSUE THREAD

**Issue by ajmas** [sequelize/sequelize#5629] opened 2016-03-22 22:26 UTC
I did not see support for the [inet](http://www.postgresql.org/docs/9.3/static/datatype-net-types.html#DATATYPE-INET) data type. It would be useful to have support for this or if it exists already to include it in the documentation.

**Comment by janmeier** [comment] 2016-03-30 16:11
Duplicate of https://github.com/sequelize/sequelize/issues/5140

**Closed by janmeier** 2016-03-30 16:11 UTC
Labels: feature, postgres
