### ISSUE TITLE
underscored=true for timestamp not return snake_case

### ISSUE THREAD

**Issue by zainiazhr14** [sequelize/sequelize#13793] opened 2021-12-20 07:18 UTC
i use sequelize v6.11 and use underscore=true. if in database field timestamp is created_at and updated_at (snake_case) but when query it will return createdAt and updatedAt (CamelCase)

**Comment by ephys** [comment] 2021-12-23 10:19
Duplicate of https://github.com/sequelize/sequelize/issues/13784, let's continue there

**Closed by ephys** 2021-12-23 10:19 UTC
Labels: type: docs
