### ISSUE TITLE
Support for DB Cursor

### ISSUE THREAD

**Issue by ryanpager** [sequelize/sequelize#10550] opened 2019-03-14 15:29 UTC
## What are you doing?
Fetching a record set with > 10000 records runs a small EC2 server out of memory. Would like to do something like PHP has where you can grab a cursor, and do a while loop while theres rows so its not all stuff in an in-memory array.

Im fully aware of pagination -- but the use case in this *requires* me to grab all records at once so that I can iterate them and run other functions on it.

```typescript
Contact.findAll()
```

## What do you expect to happen?
Return a DB Cursor iterator, rather than an array.

## What is actually happening?
No matter what I do, it always stuffs it into an in-memory array which runs the server out of memory.

__Dialect:__ mysql
__Dialect version:__ 1.6.5
__Database version:__ ???
__Sequelize version:__ 4.42.0
__Tested with latest release:__ Yes

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by knoxcard** [comment] 2019-03-18 19:50
Doesn't the utilization of both `where `and `limit `solve this issue?

**Comment by ryanpager** [comment] 2019-03-18 22:24
@knoxcard Im aware of the where and limit clauses -- I stated that above (that I am aware of pagination). The point is that I **have** to grab a massive data set at once, and not page it.

**Comment by knoxcard** [comment] 2019-03-18 23:27
You also stated that you have to "grab everything at once".  To my knowledge, that will always use extensive memory.  Maybe someone else will chime in soon...

**Comment by ryanpager** [comment] 2019-03-18 23:50
@knoxcard You're completely missing the point and understanding of what a DB Cursor does. It specifically is used for limiting memory usage on large data sets rather than forcing it into an in-memory array. See PDOStatements in php for an example (http://php.net/manual/en/pdostatement.fetch.php). There are many other languages that support this as well.

The purpose of grabbing "everything at once" is not so that I can return it to a user, its used in a cron job to execute a specific business logic process in a chain. If I paginate this, it makes it exponentially more difficult.

See https://github.com/mysqljs/mysql/issues/1370 for a related solution. This solves the issue, however its a bandaid work around and requires hoops. My question is if there is something like this built in that Im missing in the documentation somewhere.

**Comment by sushantdhiman** [comment] 2019-03-20 04:55
Duplicate of https://github.com/sequelize/sequelize/issues/2454 & https://github.com/sequelize/sequelize/issues/10347

**Closed by sushantdhiman** 2019-03-20 04:55 UTC
